### ISSUE TITLE
logs regex stage fails to parse ONLY when config.expand-env is enabled

### ISSUE THREAD

**Issue by pheber** [grafana/agent#1001]
I am using the Grafana agent to push logfiles to Grafana Cloud. In my pipeline-stages, I have the following regex stage:

`        - regex:
            source: filename
            expression: '\\temp\\Logs\\(?P<log_app>.+?)\\'`

This stage works perfectly until I enable environment variable expansion via the --config.expand-env command line parameter. Once I do, the agent fails to start with the following error:

`ts=2021-10-18T23:33:40.4170414Z caller=main.go:68 level=error msg="error creating the agent server entrypoint" err="unable to apply config for backendlogs: unable to create logs instance: failed to make file target manager: invalid regex stage config: could not compile regular expression: error parsing regexp: invalid escape sequence: '\\L'"`

I have made no other changes to the yaml file - simply setting the command-line parameter causes the error.

Am I missing something here?

**Comment by rfratto** [comment]
Hi, can you share the scrape_configs for your agent's logging config? That will be useful here; there are some cases where enabling `-config.expand-env` will attempt to evaluate some regexes that look like environment variables which breaks things.
