### ISSUE TITLE
The `statsd_exporter` integration don't map timers (observers)

### ISSUE THREAD

**Issue by edinardo** [grafana/agent#1002]
I am using the Grafana Agent version 0.19.0 with the `statsd_exporter` integration `enabled`, which the timer (observer) metrics have been ignored. With debug enabled, it is possible to see that all other types are mapped/processed. The same behavior can be seen at [http://localhost:9090/integrations/statsd_exporter/metrics](http://localhost:9090/integrations/statsd_exporter/metrics).

The metrics are sent via UTP, and when using the Prometheus standalone StatsD exporter, the timers (observers) are automatically mapped to summaries.

For test purposes, the version used of the Prometheus standalone StatsD exporter was 0.22.2, and no extra parameters were used.  For the `statsd_exporter` integration only with:
```
statsd_exporter:
    enabled: true
    listen_udp: :9125
```

**Comment by edinardo** [comment]
Just as an update, I tested with the new agent version (0.20.0), and not only did this issue persist, but also a new fail appeared with the mapping configuration. The new issue is described at [#1052](https://github.com/grafana/agent/issues/1052).

**Comment by rfratto** [comment]
@gaantunes When you have time to look at this, it seems that the mapping problem is because [our mapper](https://github.com/grafana/agent/blob/017277cd034709d9fd2dfd16fde159d7f9b858a1/pkg/integrations/statsd_exporter/statsd_exporter.go#L128) isn't given the [Registerer](https://pkg.go.dev/github.com/prometheus/statsd_exporter/pkg/mapper#MetricMapper) it needs to expose the metrics that are mapped.

**Comment by gaantunes** [comment]
Hello guys,
I just opened https://github.com/grafana/agent/pull/1092 for fixing the mapping bug. 
I will need more time to test and fix this observer metrics bug, but will be OOO for tomorrow until the week after the next. If it can`t wait until then, maybe someone could take this?

**Comment by rfratto** [comment]
Hey @edinardo, sorry for the slow response on this. I'm trying to reproduce this; can you give me an example I could use? Something like the statsd metric name or what's being sent over UDP?

**Comment by rfratto** [comment]
In the meantime, I'm looking at the statsd_exporter code and can't find where it maps observers to summaries by default. Did you give the exporter a mapping config?

**Comment by rfratto** [comment]
@mattdurham found the issue and has a fix. Thanks for reporting!
