### ISSUE TITLE
[dev.scraping-service-scalability] Allow partial applying of configurations in ApplyConfigs

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#1005]
In [dev.scraping-service-scalability](https://github.com/grafana/agent/tree/dev.scraping-service-scalability), the batch is either all applied or rolled back. A partial apply would be nice so that new changes can propagate and not be held by a single problematic configuration.

Partial updates will require some feedback to the user and the ability to track/monitor failed configs.

**Comment by rfratto** [comment]
Closing this as the dev branch is stale. We can reopen if we return to this.
