### ISSUE TITLE
Add a Kubernetes Events integration

### ISSUE THREAD

**Issue by hjet** [grafana/agent#1013]
Add an [eventrouter](https://github.com/heptiolabs/eventrouter)-style integration to Agent that watches for [Events](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#event-v1-events-k8s-io) and potentially other objects of interest (Conditions?), and ships them to a Loki sink.

**Comment by rfratto** [comment]
This is currently being worked on, from what I understand.

**Comment by hjet** [comment]
> This is currently being worked on, from what I understand.

Yes, confirmed :)
