### ISSUE TITLE
unexpected files and directories in RPM package

### ISSUE THREAD

**Issue by simonc6372** [grafana/agent#1054]
Hi, 
The RPM package for the agent seems to contain some artefacts of the build process. 

```
~> rpm -qlp /tmp/grafana-agent-0.19.0-1.amd64.rpm
/etc/grafana-agent.yaml
/etc/sysconfig/grafana-agent
/usr/bin/grafana-agent
/usr/bin/grafana-agentctl
/usr/lib/.build-id
/usr/lib/.build-id/1e
/usr/lib/.build-id/1e/fe083e31c7378a89bbf813149e477cc705e7ee
/usr/lib/.build-id/a1
/usr/lib/.build-id/a1/000b82ed20d40e8f93ef338ca75cf92b4f5206
/usr/lib/systemd/system/grafana-agent.service
```

I would not expect to see the The /usr/lib/.build-id directory & files inside the RPM packages. (presumably they are in the DEB package too? )

**Comment by rfratto** [comment]
This seems to be [expected](https://unix.stackexchange.com/a/411736) in RPMs, and it doesn't seem like we're mounting anything along those lines to the created packages.

**Comment by rfratto** [comment]
Since those files are expected, I'm going to close this. Please feel free to reach out if you want to keep discussing.
