### ISSUE TITLE
[Traces] Improve Pod Association in the PromSDProcessor

### ISSUE THREAD

**Issue by joe-elliott** [grafana/agent#1095]
Currently we search for and use `ip` or `host.ip` on the resource to associate spans with kubernetes pods and enrich the data. It appears that the k8sattributeprocessor in otel contrib has slightly more robust logic for pod association:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/pod_association.go

Let's review this code and determine if there are improvements to be made in our processor. Additionally PR upstream any improvements we can contribute.

**Comment by james-callahan** [comment]
I thought you would be looking at the source IP for whatever sends you the message.
e.g. if you receive a connection to the jaeger TCP port from 10.1.2.3 then you'd be looking up the kubernetes pod by that.
