### ISSUE TITLE
Prometheus Vendor Update Tracking

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#112]
This issue is meant to track new versions of Prometheus and decide whether they introduce new functionality that the Agent would benefit from. We will note each version as:

- **vendored** in bold 
- _skipped update_ in italics.
- planned for vendoring in non-bold, not italicized text 

The current vendored version of Prometheus is **v2.21.0.**

- **v.2.17.1** 
- _v2.17.2_: Skipping, no fixes related to Agent 
- _v2.18.0_: Skipping, going directly to 2.18.1 
- **v2.18.1** (#58) 
- _v2.19.0_: Skipping, going directly to 2.20.1
- _v2.19.3_: Skipping, going directly to 2.20.1
- _v2.20.0_: Skipping, going directly to 2.20.1
- **v2.20.1** (#149, vendored in v0.6.0)
- **v2.21.0** (#203, vendored in v0.7.2)

**Comment by hardproblems** [comment]
@rfratto is a timeline for when the next release containing prometheus updates will land? We're trying to compare the resource usage for grafana-agent and prometheus and saw a ~30% memory usage reduction between Prometheus 2.18 -> 2.19.3. Would love to be able to pull this into grafana-agent soon if possible.

**Comment by rfratto** [comment]
@hardproblems The 0.5.0 release tomorrow won't have anything, but we should be able to update the Prometheus vendor to 2.20.1 for the 0.6.0 release. I had a quick chat with the team here and it seems like we'll be able to release 0.6.0 around the week of August 17th at the earliest or the week of August 24th at the latest.

**Comment by rfratto** [comment]
@hardproblems Sorry, the release got pushed back a week further than I had expected. We just released v0.6.0 that includes Prometheus 2.20.1.

**Comment by rfratto** [comment]
I'm going to lock this issue so it's purely for tracking; if anyone has a question about when we're going to update the vendor feel free to open a specific issue for the question or ask me on our public #agent slack channel at https://slack.grafana.com/.

**Comment by rfratto** [comment]
I'm closing and unpinning this. There's a lot of dependencies in the Agent that need tracking, and that number is just going to keep growing. 

There's now a GitHub action that runs every day and will check for updates against an allowlist of dependencies we explicitly want to track; Prometheus is one of them. You can see the results of this action in #267. All of the issues will have the label [outdated-dependency](https://github.com/grafana/agent/issues?q=is%3Aissue+label%3Aoutdated-dependency+). Closing them means that we intend to not update to that version, though if anyone needs a specific feature, please let us know and we can re-open.
