### ISSUE TITLE
Proposal: Remote Configuration

### ISSUE THREAD

**Issue by rlankfo** [grafana/agent#1121]
# Remote Configuration

This is a more detailed proposal to the original idea proposed in #869 

Currently the only way to provide configuration to the agent is to pass a local file. Ideally this feature would provide functionality for fetching remote files via several different sources including the following:

* ~~AWS Secrets Manager~~
* AWS S3
* Azure Blob Storage
* Google Cloud Storage
* ~~HashiCorp Vault~~
* HTTP/HTTPS
* Remote Git repos

Access to these remote sources should be made available through URLs. Using URLs for retrieving remote configuration will simplify passing parameters to the agent on the command line, and make it possible to retrieve other remote files which may be configured for use in the agent.

### Implementation Details
This proposal suggests adding the ability to fetch configurations from remote locations by utilizing [go-fsimpl](https://github.com/hairyhenderson/go-fsimpl). 
go-fsimpl enables access to these sources through [URL schemes](https://github.com/hairyhenderson/go-fsimpl/blob/main/url_schemes.md).

### Goals

* allowing instances of the agent to fetch configuration files from a remote location
* support several common remote sources (such as all of the URL schemes made available by go-fsimpl)
* reload remote configuration on requests to `/-/reload` endpoint

### Non-Goals

* polling remote sources for configuration changes
* merging configurations from different sources

###  Pros

* multiple sources supported resulting in more flexibility for end users
* the heavy-lifting is delegated to go-fsimpl
* easily source control agent configs by using git repository source

### Cons

* added complexity with more surface area to support
* different scheme types require different types of credentials
* each scheme type would need to be tested and well documented
* introduces several new dependencies

## Proposed Usage

The feature would be enabled by passing a valid URL to the `-config.file` command line parameter. See the go-fsimpl documentation for supported URL schemes. Default to a local file if no scheme is passed.

Several sources will require providing credentials; however, this should typically be done as documented by the source itself.  For example, when retrieving a config from S3, credentials would be provided in `~/.aws/credentials`. 

### Examples
```bash
./agent -config.file=s3://<bucket>/<path>/agent-config.yaml
```

<TODO: will provide more examples of how authorization would/could work>

**Comment by rfratto** [comment]
I know I initially opened #869 and lightly proposed this, but I do love this idea and I do have to give all the credit to @mattdurham for planting the seed here. 

I can imagine that we'd want to try taking the url-based-file concept beyond just the main config file (e.g., support for URLs in password_file?). One thing that concerns me is how we would configure the credentials for multiple URL based files. This likely isn't a problem for most of the providers, but I could see it becoming a challenge for HTTP/HTTPS. 

Should there be a restriction in the future where, if we were loading multiple things from URLs, you can only configure credentials globally? That would mean the recommendation is that you shouldn't mix retrieving files from multiple different instances of the same provider; ie only one unique HTTP/HTTPS server.

**Comment by rfratto** [comment]
> Should there be a restriction in the future where, if we were loading multiple things from URLs, you can only configure credentials globally? That would mean the recommendation is that you shouldn't mix retrieving files from multiple different instances of the same provider; ie only one unique HTTP/HTTPS server.

(If we did have this restriction, we would be prevented from supporting a scenario where a person mixes some files from a cloud provider, like Grafana Cloud, with an on-prem server.)

**Comment by mattdurham** [comment]
For most of these, the auth is baked into the URI itself. Does go-fsimpl support HTTPS/HTTP beyond basic auth?

**Comment by mattdurham** [comment]
Rereading them a fair amount of the auth is via environment vars. But I don't feel like that should change?

**Comment by rfratto** [comment]
> Rereading them a fair amount of the auth is via environment vars. But I don't feel like that should change?

I think it might make sense in this case, and I learned that the environment variables are expected from users using stuff like AWS tooling. When we donated our SigV4 code to Prometheus, there was a light discussion about the environment variables, since Prometheus prefers to only expose things via flags or the config file. 

I'm not sure which makes sense for us. We support exactly two environment variables (one for the HTTP proxy, inherited from OTel, and another for an integration to load DSNs). It might be useful if a consumer of go-fsimpl (cc @hairyhendereson) could opt out of the environment variable support, as it might help get the library broader adoption.

**Comment by rfratto** [comment]
One potential way of supporting multiple different auth methods per URL could be some kind of URL registry file passed to the agent:

```
http_configs:
- name: on-prem-server-a 
  base_url: http://server-a/base/path/ 
  basic_auth:
    username: foo
    password: bar 

s3_configs:
- name: storage-a 
  base_url: s3://bucket
  some_credentials: very secret 
```

which you could then refer to across the agent as `remote://on-prem-server-a/file.yaml` or `remote://storage-a/file.yaml`. I'm not very excited about this though, and it seems like it would be a pain to manage.

**Comment by rfratto** [comment]
One potential way of supporting multiple different auth methods per URL could be some kind of URL registry file passed to the agent:

```
http_configs:
- name: on-prem-server-a 
  base_url: http://server-a/base/path/ 
  basic_auth:
    username: foo
    password: bar 

s3_configs:
- name: storage-a 
  base_url: s3://bucket
  some_credentials: very secret 
```

which you could then refer to across the agent as `remote://on-prem-server-a/file.yaml` or `remote://storage-a/file.yaml`. I'm not very excited about this though, and it seems like it would be a pain to manage.

**Comment by rlankfo** [comment]
> It might be useful if a consumer of go-fsimpl (cc @hairyhendereson) could opt out of the environment variable support, as it might help get the library broader adoption.

We should be careful about forcing people to authenticate to services whose official documentation provides environment variables for doing so. If we're importing the aws sdk for example, and it allows users to authenticate with environment variables, we should not remove this ability.

**Comment by rfratto** [comment]
(cc @hairyhenderson for the broad conversation about go-fsimpl)

**Comment by hairyhenderson** [comment]
> Does go-fsimpl support HTTPS/HTTP beyond basic auth?

You can pass in any headers with https://pkg.go.dev/github.com/hairyhenderson/go-fsimpl#WithHeaderFS, or a whole custom HTTP client with https://pkg.go.dev/github.com/hairyhenderson/go-fsimpl#WithHTTPClientFS. That's available for `httpfs` and a few others.

> It might be useful if a consumer of go-fsimpl could opt out of the environment variable support, as it might help get the library broader adoption.

Does reading env vars hamper adoption? Or do you mean it should be possible to configure filesystems without using them?

**Comment by rfratto** [comment]
> Does reading env vars hamper adoption? Or do you mean it should be possible to configure filesystems without using them?

I think it should definitely be possible to configure filesystems without environment variables, but I am loosely concerned that some projects have a more firm stance on "everything must be done through our configuration file" for the sake of having exactly one way to configure something.

**Comment by hairyhenderson** [comment]
> but I am also loosely concerned that some projects have a more firm stance on "everything must be done through our configuration file" for the sake of having exactly one way to configure something.

is that the case for `agent`? 😉

The majority of env vars that are probably relevant are read by the AWS SDK, and I'm not sure how easy it'd be to prevent it from reading them...

**Comment by rfratto** [comment]
> The majority of env vars that are probably relevant are read by the AWS SDK, and I'm not sure how easy it'd be to prevent it from reading them...

Specifically for the AWS SDK, a consumer of go-fsimpl could provide a custom session.Config after validating that all of the fields used for connecting are manually configured and non-empty (since otherwise, if they're empty, it defaults to reading from environment variables).

**Comment by rfratto** [comment]
I think we're getting off track from the design. My concerns for the adoption of go-fsimpl and expanding how this is used can wait for another day. 

I will try to generally summarize why it impacts this feature specifically, and leave it at that: if we ever support more than one url-based files across the config, then it is likely that someone may want to use two distinct sets of credentials for different implementations of the same filesystem. If we get to that point, then we would need to explore a way of configuring credentials through another mechanism.

**Comment by hairyhenderson** [comment]
> a consumer of go-fsimpl could provide a custom session.Config

I _think_ that'd work for the `awssmfs` by using https://pkg.go.dev/github.com/hairyhenderson/go-fsimpl/awssmfs#WithSMClientFS, but for `blobfs` it's a bit more awkward... I'm not super happy with the hoops I had to jump through on that one, though I don't think any of it is insurmountable.

**Comment by peterbourgon** [comment]
Ideally go-fsimpl would be an implementation detail that supports a set of defined requirements, it shouldn't itself define the requirements as a side effect of it's current capabilities.

**Comment by rfratto** [comment]
I agree, and it's probably a good point to take a step back and talk about what the requirements are. 

@rlankfo aside from "we want to support URLs," do we have any other requirements we want to write down? Otherwise, if it's just support for URLs, then we're already past the point of requirement gathering and talking about go-fsimpl might be more appropriate.

**Comment by peterbourgon** [comment]
> take a step back and talk about what the requirements are . . . aside from "we want to support URLs," do we have any other requirements we want to write down?

And why is supporting URLs a requirement? I'm sure there's a reason :) but it should be written down, to make sure the proposed solution(s) address it directly.

**Comment by rlankfo** [comment]
> @rlankfo aside from "we want to support URLs," do we have any other requirements we want to write down? Otherwise, if it's just support for URLs, then we're already past the point of requirement gathering and talking about go-fsimpl might be more appropriate.

The main requirement is to "enable remote configuration sources". Support for URL's is likely an implementation detail.

**Comment by rfratto** [comment]
Could you:

1. Edit the proposal to remove references to go-fsimpl 
2. Reframe the approach in terms of remote sources we want to support (I'd strongly suggest at _least_ HTTP)
3. Give a specific proposal for how we will meet our requirements (URLs is definitely one, but if there's another more obvious approach, please do go with that)
4. Talk more about how users will interact with this functionality (including authentication) 

I'm sorry that I'm asking you to make these changes, and I know the state of the proposal now is because of my suggestions. The conversation here was helpful for making me realize I've been in the weeds too much after thinking about this for too long. 

For context, I initially started thinking about remote configuration as:

* a way to decouple some of the crufty bits of grafana/agent that have caused problems (i.e., config management API)  
* a path forward for remotely configuring agents through a Grafana plugin / some on-premises provisioner

**Comment by rfratto** [comment]
> For context, I initially started thinking about remote configuration as:
>
> * a way to decouple some of the crufty bits of grafana/agent that have caused problems (i.e., config management API)
> * a path forward for remotely configuring agents through a Grafana plugin / some on-premises provisioner

(The next thought was that the conf.d support @mattdurham is working on is also a good candidate for benefiting from remote configuration, but this also changes the implications of what we need to do in our solution to support entire filesystems and not just individual files)

**Comment by mattdurham** [comment]
I am also heavy in favor of supporting s3/s3 compatible systems. I think that one is to large of a win to easily pass up

**Comment by roidelapluie** [comment]
Additional cons are:
- the potential clash with service discovery (how would it work if you need aws credentials that can access the s3 buckets and run the aws service discovery?).
- Robustness, what happens if you don't have access to the configuration at startup?

**Comment by rlankfo** [comment]
> * the potential clash with service discovery (how would it work if you need aws credentials that can access the s3 buckets and run the aws service discovery?).

@roidelapluie I'm not sure I see how this would be different from trying to use any two AWS services using the same credentials. Can you elaborate here?

**Comment by roidelapluie** [comment]
You usually don't use two AWS services with the same credentials, because you need to scope them too large?

**Comment by rlankfo** [comment]
> You usually don't use two AWS services with the same credentials, because you need to scope them too large?

I agree that you want permissions to be as granular as possible. I don't think it is all that uncommon though to have more than a single action / policy / role assigned to an IAM account?

**Comment by rlankfo** [comment]
> I'm sorry that I'm asking you to make these changes, and I know the state of the proposal now is because of my suggestions. The conversation here was helpful for making me realize I've been in the weeds too much after thinking about this for too long.

@rfratto made a few minor changes to the proposal here and plan to start hacking away on a quick prototype for this. As I do, I'll update the usage examples to include what seems best for providing authentication details with different schemes we plan to support to get some feedback.

**Comment by jpkrohling** [comment]
About the HTTP/S provider, I believe there should only be HTTPS. Using a plain-text transport for the config would make it too easy for a man-in-the-middle to hijack an agent. For testing purposes, a Makefile (or alike) target can generate certs to be used by the local client.

**Comment by roidelapluie** [comment]
I plan to propose etcd as configuration backend for prometheus. Would it be an option for the agent as well?

**Comment by rlankfo** [comment]
> I plan to propose etcd as configuration backend for prometheus. Would it be an option for the agent as well?

@roidelapluie this sounds reasonable to me

**Comment by rfratto** [comment]
I'm going to close this issue. This has been superseded in part by #1308 and #1538/#1546/#1599.
