### ISSUE TITLE
[Question] Deploying Agent as a Service

### ISSUE THREAD

**Issue by WeiTangLau** [grafana/agent#1122]
Hi is it possible to deploy Agent as a service on linux?

this is because I am planning to use agent to scrap metrics on a raspberry pi.

**Comment by mattdurham** [comment]
We provide packages for our [releases](https://github.com/grafana/agent/releases/tag/v0.21.1) for installation as a service

**Comment by WeiTangLau** [comment]
Hi Matt,
Yes I see the packages.
but how can I run it as a service after downloading it. Sorry absolute beginner here

**Comment by mattdurham** [comment]
What linux distribution are you running?

**Comment by WeiTangLau** [comment]
Ubuntu. It is okay. Found the documentation here.
https://grafana.com/docs/grafana-cloud/agent/agent_as_service/

Thanks for your help! :)
