### ISSUE TITLE
MSSQL issues when running windows_exporter

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#1124]
When running MSSQL 2019 on Windows Server 2019 using windows_exporter mssql, it errors out with
<img width="1816" alt="Screen Shot 2021-11-22 at 10 55 48 AM" src="https://user-images.githubusercontent.com/3036838/142893403-90e4aed5-38e4-4d82-b305-c175d70ee130.png">

**Comment by rfratto** [comment]
Closing in favor of #1164 which has more detail.
