### ISSUE TITLE
Update to Loki v2.4.1

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1127]
We're currently using a non-release commit of Loki (for Promtail) between v2.3.x and v2.4.1. We should update to the latest release (v2.4.1) to bring in new Promtail features like grafana/loki#4495. 

This change may be non-trivial due to the change Loki's migration over to grafana/dskit. 

cc @rlankfo

**Comment by rlankfo** [comment]
@rfratto any reason we want to go specifically to v2.4.0 and not v2.4.1? 

This PR https://github.com/grafana/agent/pull/1102 has most of the work done but need to rebase and do some thorough testing, especially around the ring changes.

**Comment by mattdurham** [comment]
Closing in lieu of #1394
