### ISSUE TITLE
Windows Service start timeout if WAL takes to long to load

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#1128]
While replaying the WAL the service does not respond to Windows Service commands, which means if it takes over 30s then the service fails to start and is stopped.

The most likely change is to have the service start handling service commands immediately.

**Comment by menukagurung** [comment]
@mattdurham HI Matt, any updates on this? There is no status on this issue, are we able to provide an ETA for this currently?

**Comment by mattdurham** [comment]
There is no ETA, did the registry change not work?

**Comment by mattdurham** [comment]
Note to self and others: I have not been able to reproduce this accurately. I changed the ServicesPipeTimeout to a lower number to help simulate a slow start and then put a 1GB WAL on a USB 2.0 stick and was unable to recreate the problem.
