### ISSUE TITLE
Explore supporting additional tracing exporters

### ISSUE THREAD

**Issue by mapno** [grafana/agent#1135]
Currently, the Agent is only capable of exporting traces via OTLP (gRPC and HTTP). The main reasoning is that the Agent is built with the intention of sending telemetry data to the opinionated Grafana observability stack. While Tempo can ingest jaeger and other formats, with OTLP this goal is already achieved.

Exporting has a custom config block in the Agent (`remote_write`), which is translated to OTLP's exporter config. This translation is ad-hoc for this exporter. Adding new exporter would require changing or adding fields to the config, to suit the new different options. This would increase complexity in the configuration, in a way that is not beneficial to working with Tempo.

Outside OTLP, 4 of the 5 available exporters that Tempo could ingest from are built on top of gRPC or HTTP ([jaeger](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/jaegerexporter), [jaeger thrift](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/jaegerthrifthttpexporter), [opencensus](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/opencensusexporter) and [zipkin](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/zipkinexporter)). It's possible that `remote_write` is compatible with these exporters, but this requires further inspection to verify.

**Comment by nicoche** [comment]
Hey!

This is something that we would really like to use. I've hacked around and got something running. The config looks like this:

```yaml
traces:
  configs:
    - name: default
      receivers:
        zipkin:
      remote_write:
        - endpoint: localhost:14250
          format: jaeger
          insecure: true
          retry_on_failure:
            enabled: false
```

With `docker run --rm --name jaeger -p 14250:14250 -p 9412:9411 -p 16686:16686 jaegertracing/all-in-one:latest`, spans are correctly forwarded:

```shell
curl --verbose -X POST 127.0.0.1:9411/v1/traces -H 'Content-Type: application/json' -d '[{ "id": "f5402e865c61400e", "traceId": "0123456789abcdef", "timestamp": 1639437423899795, "duration": 1000030, "name": "span from bash!", "tags": { "http.method": "GET", "http.path": "/api" }, "localEndpoint": { "serviceName": "shell script" } }]'
```

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/78445450/145911567-464d56f8-4d9c-40fd-8bea-b91c2962104c.png">

_____________

If this is something you would want to integrate in the agent, I'd glady help. First step would be to settle down on a config format?

**Comment by rfratto** [comment]
This has fallen a bit behind, and we've decided to close this in our most recent bug scrub. We're still willing to support this functionality, but just don't want our list of issues to grow forever.

If anyone is interested in working on this, please feel free to submit a PR, or if more people are actively interested in this functionality, please let us know and we can re-open.
