### ISSUE TITLE
grafana-agent couldn't pull docker containers logs

### ISSUE THREAD

**Issue by ramimohammad** [grafana/agent#1146]
Hi Support team , quick question please , is there any permanent trick like [sudo usermod -a -G adm grafana-agent] for /var/log , but here the case for /var/lib/docker/containers/*/*.log because seems grafana-agent couldn't send any logs to grafana cloud

Best regards

**Comment by rlankfo** [comment]
Does the user the agent is running as have permission to read the logs in /var/lib/docker/containers? The usermod command you reference adds the grafana-agent user to the adm group so I would assume the adm group has permission to read logs in /var/log.

If could assign similar file permissions to log files in /var/lib/docker/containers by making them readable by the adm group, something like `chown -R :adm /var/log/containers/*.log; chmod ug=rw /var/log/containers/*.log` might work.
