### ISSUE TITLE
GPU metrics support

### ISSUE THREAD

**Issue by dhogan-io** [grafana/agent#1160]
Support for metrics from Nvidia GPUs would be useful for monitoring GPU nodes. Nvidia provides [NVML](https://developer.nvidia.com/nvidia-management-library-nvml), a library intended for monitoring GPUs, with officially-supported, Apache-licenced [Go bindings](https://github.com/NVIDIA/go-nvml).

**Comment by rfratto** [comment]
Hey! I looked into this a little bit, and it seems like it might be a bit of effort to get going. There are two main things to consider here:

* The Go bindings you linked to have external prerequisites, which might not fit very cleanly into our existing build tooling. 
* Historically, we have yet to include an integration for something that isn't an existing Prometheus exporter like this one for [postgres](https://github.com/prometheus-community/postgres_exporter). There's no hard rule against building an exporter directly in Grafana Agent, but I do believe having it exist as a separate project helps it gain more traction in the wider Prometheus ecosystem. 

I'm not against this, but it's not likely something that the core maintainers are going to have time to build. I am willing to guide anyone who is interested in taking this on, though.

**Comment by rfratto** [comment]
Have you looked at [dcgm-exporter](https://github.com/NVIDIA/dcgm-exporter)? It's unlikely we'd add it as an integration because it would complicate our build setup, but it might solve your needs to get metrics.
