### ISSUE TITLE
Grafana Agent Operator documentation

### ISSUE THREAD

**Issue by pvlltvk** [grafana/agent#1161]
Hi everyone!

I've found some inaccuracies in the [Grafana Agent Operator documentation](https://github.com/grafana/agent/blob/main/docs/operator/custom-resource-quickstart.md) which prevent the Kubernetes Integration activation in Grafana Cloud:
1. `relabeling` for the `job` label  should be added in the `ServiceMonitor` configs - see #1149. Without it an `up` metric for `kubelet` and `cadvisor` jobs doesn't have the right label for the Kubernetes Integration dashboards.
2.  Also there is nothing written about the` kube-state-metrics` installation but without kube-state-metrics in a cluster an agent can't scrape metrics which are needed for the Kubernetes Integration dashboards.

If you find these remarks reasonable, i can prepare a PR.

**Comment by TGuimbert** [comment]
Some notes about what I changed to make everything work that could be added to this PR:

* cadvisor's interval need to be lower (`30s` for example) for the network panels to work
* I added `machine_memory_bytes|container_fs_reads_total|container_fs_writes_total|container_fs_reads_bytes_total|container_fs_writes_bytes_total` to the cadvisor regex

**Comment by rfratto** [comment]
Hi, thanks for opening the issue! I'm going to loop in @rgeyer and @hjet who should know more about this.

@rgeyer @hjet: is our operator quickstart being used for the Grafana Cloud integration?

**Comment by rgeyer** [comment]
> Hi, thanks for opening the issue! I'm going to loop in @rgeyer and @hjet who should know more about this.
> 
> @rgeyer @hjet: is our operator quickstart being used for the Grafana Cloud integration?

We have not yet updated the integration instructions to use the operator.

Right now, the integration instructs you to deploy the agent using the [bare yaml production file](https://github.com/grafana/agent/blob/main/production/kubernetes/agent-bare.yaml), and install kube-state-metrics seperately.

The proposed changes will be necessary for when we instruct users to install with the agent operator for the integration tho. I agree that these changes are required for compatibility with the k8s integration/mixin.

**Comment by hjet** [comment]
Yeah I think I'm partly responsible for the confusion here.

The Agent Operator quickstart is currently _not_ used for the K8s integration at all, and neither is Agent Operator. We are working on "official" Operator support for the K8s integration at the moment and expect to deliver it in the next couple of months. Right now support is on a "best effort" basis.

However, I added some default config (basically just `job` label replacement and allowlists) to the quickstart to sort of make it work "out of the box" with the K8s integration, but we are not syncing this with what's live in prod, so there will be some drift and things may break.

These changes are welcome IMO. 

Specifically:
-  Moving the `job` label replacement to the `relabelings` stanza so that it actually works (I have to look into why this solves the issue when I get some time later today) - this is a bug
- Adding a short note to install KSM and linking to the [relevant step](https://grafana.com/docs/grafana-cloud/kubernetes/integration-kubernetes/#deploy-kube-state-metrics-helm-chart) in the integration docs if users need support with this
- Updating the allowlists to bring the metrics needed in sync with the prod dashboards and alerts

Will be happy to review this PR, thanks for flagging this.

> cadvisor's interval need to be lower (30s for example) for the network panels to work

This would be a K8s integration bug as all the panels should work with a 60s interval cc @rgeyer

**Comment by rgeyer** [comment]
> > cadvisor's interval need to be lower (30s for example) for the network panels to work
> 
> This would be a K8s integration bug as all the panels should work with a 60s interval cc @rgeyer

I'm not able to reproduce this. The latest version of the integration, and the k8s mixin from which it's based, uses `$__rate_interval` for those queries. My test environment has a 60s scrape interval, and the network graphs are working as expected. @pvlltvk can you elaborate on which panels aren't working with a higher scrape interval?

![image](https://user-images.githubusercontent.com/428415/145867033-19a7d05d-5fc7-4ef8-809a-06904319e218.png)

**Comment by TGuimbert** [comment]
@rgeyer Those panels are not working with the `60s` interval but are working with `30s` :
![Screenshot from 2021-12-13 21-02-58](https://user-images.githubusercontent.com/33598842/145880597-e8b85ee1-52e7-46f7-ae5c-567f61aa943f.png)

There are others, I can give a full list if needed. 

Also, I don't know if it's linked but the scrape interval configured for the Prometheus datasource in Grafana Cloud is `15s`. I read somewhere that `$__rate_interval` can be up to 4 times the scrape interval, so I thought it could be the cause.

**Comment by rgeyer** [comment]
> @rgeyer Those panels are not working with the `60s` interval but are working with `30s` : ![Screenshot from 2021-12-13 21-02-58](https://user-images.githubusercontent.com/33598842/145880597-e8b85ee1-52e7-46f7-ae5c-567f61aa943f.png)
> 
> There are others, I can give a full list if needed.
> 
> Also, I don't know if it's linked but the scrape interval configured for the Prometheus datasource in Grafana Cloud is `15s`. I read somewhere that `$__rate_interval` can be up to 4 times the scrape interval, so I thought it could be the cause.

Ahh of course @TGuimbert, I neglected that detail. If you're using Grafana Cloud, the scrape interval set on your prometheus data source needs to be updated to 60s. If you were an existing user of the K8s integration, you should have actually received an email with details on this.

You're right that `$__rate_interval` is effectively 4x the scrape interval defined in the data source being queried in Grafana. The default is 15s scrape interval, meaning 15 * 4 = 60s. At anything longer than 30s scrape interval there will only be (at best) one data point, which is insufficient to calculate a rate.

Unfortunately, you can not change that value, but support staff (or I) can do that.

What is the slug/name of your Grafana Cloud instance?

**Comment by rgeyer** [comment]
> Edit: The name of my Grafana Cloud instance is `tguimbert`.

You should be updated to 60s scrape interval on your instance now. Let me know if those panels are producing appropriate output now :)

**Comment by pvlltvk** [comment]
@rgeyer @hjet @rfratto Thanks for quick replies! I agree that using Agent Operator is not a default option for the Kubernetes Integration in Grafana Cloud. But with all these fixes it works pretty good and I personally think that installing an agent with Operator is much more convenient way than using that yaml file with kubernetes manifests :)
So, I'm planning to prepare a small PR when i have more time.

**Comment by TGuimbert** [comment]
> You should be updated to 60s scrape interval on your instance now. Let me know if those panels are producing appropriate output now :)

I can confirm that with the 60s scrape interval, the panels are working. Thanks again !
