### ISSUE TITLE
jsonnet v2: /etc/machine-id cannot be mounted as is

### ISSUE THREAD

**Issue by 56quarters** [grafana/agent#1178]
Hello agent team,

I'm attempting to use the [v2 Agent jsonnet](https://github.com/grafana/agent/tree/main/production/tanka/grafana-agent/v2) to scrape logs. I'm running into the following issues:

* `/etc/machine-id` can't be mounted since it isn't a directory. Instead `/etc` has to be mounted and `machine-id` specifified as a `subPath`
* However, `/etc` can't be mounted read-only because the agent configuration file needs to be mounted to `/etc/agent/agent.yml`

The Jsonnet I'm using can be found at https://github.com/grafana/tns/compare/grafana:5d8f820...grafana:c9baaaa

Given the following jsonnet:

```
  daemonset_agent:
    gragent.new(name='grafana-agent', namespace='default') +
    gragent.withDaemonSetController() +
    gragent.withLogVolumeMounts(config={}) +
    gragent.withAgentConfig({ /* config goes here */ })
```

Kubernetes (using k3d and tanka) fails to start the pod with the following error:

```
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/etc/machine-id" to rootfs at "/etc/machine-id" caused: mount through procfd: not a directory: unknown
      Exit Code:    128
```

Modifying the above jsonnet to the following fixes that particular error:

```
  daemonset_agent:
    gragent.new(name='grafana-agent', namespace='default') +
    gragent.withDaemonSetController() +
    gragent.withAgentConfig({ /* config goes here */ })
     {
        controller+:
          // For reading docker containers. /var/log is used for the positions file
          // and shouldn't be set to readonly.
          $.util.hostVolumeMount('varlog', '/var/log', '/var/log') +
          $.util.hostVolumeMount('varlibdockercontainers', '/var/lib/docker/containers', '/var/lib/docker/containers', readOnly=true) +

          // For reading journald
          $.util.hostVolumeMount('etc', '/etc', '/etc', readOnly=true, volumeMountMixin={subPath: 'machine-id'}),
      }
```

But results in the following problem due to `/etc` being read-only

```
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/var/lib/kubelet/pods/ac8604e0-bed1-4803-8885-679d1293fb72/volumes/kubernetes.io~configmap/grafana-agent" to rootfs at "/etc/agent" caused: mkdir /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/2edde74176985e31843f8e2b302f2d09270b13fcf72f9c2cab3f63758bb5725b/rootfs/etc/agent: read-only file system: unknown
      Exit Code:    128
```

I'm not sure what the correct solution to this is. Moving the agent config outside of `/etc`? Maybe something else I'm missing (I'm admittedly not very familiar with Kubernetes volume mounts)

**Comment by rfratto** [comment]
I'm thinking that error might actually be a red herring. Promtail has successfully used that mount for a while for it to read from journald.  

I'm looking into what options we have here. We really only want to mount it _if_ it exists on the host.

**Comment by rfratto** [comment]
What do you think about this:

1. Change the hostPath volume so that [`type`](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) is set to `File`
2. Look for a config field in `withVolumeMounts` to explicitly enable journald:

```jsonnet 
// journald adds a /etc/machine-id mount. Defaults to false.
gragent.withLogVolumeMounts({ journald: true })
```

**Comment by 56quarters** [comment]
> What do you think about this:
> 
>     1. Change the hostPath volume so that [`type`](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) is set to `File`

Ah, good call. That makes sense to me.

>     2. Look for a config field in `withVolumeMounts` to explicitly enable journald using that mount:
> 
> 
> ```jsonnet
> // journald adds a /etc/machine-id mount. Defaults to false.
> gragent.withLogVolumeMounts({ journald: true })
> ```
> 
> That would make it required, but I think you'd want to enforce it if you're trying to use journald anyway.

That seems reasonable.

Thanks for your help!
