### ISSUE TITLE
Add promtail command line flag -dry-run

### ISSUE THREAD

**Issue by renannprado** [grafana/agent#1180]
`promtail` has a flag `-dry-run` which lets you run and see how the logs are being parsed, etc. It's very useful for debugging.

With the grafana agent, though, that's not possible.

It would be really handy to have that in the agent too.

**Comment by rfratto** [comment]
Hey, thanks for the suggestion! 

I'm definitely not opposed to this, but I think given our increased scope it makes a general `-dry-run` flag harder to pull off (i.e., people might find it surprising if `-dry-run` is only used for logs).

What would you think about a `agentctl test-logs -config.file=<agent config>` command? That would help make it explicit that it will let you use the agent config file but only for testing logs (through the dry run functionality).

**Comment by renannprado** [comment]
@rfratto I'm by far attached to the name of the flag. What's important IMHO is that we have the feature and I think your suggestion is a good one.

**Comment by rfratto** [comment]
I'm going to keep this one alive. This came up a few times and I think it'd be useful to have for equivalent testing that people do with promtail.

**Comment by xiejian06033218** [comment]
@rfratto I understood this tool is called grafana-agentctl test-logs, it seems it doesn't support to add flags like "--inspect" and "--stdin" for piping a test log, as promtail does. is that possible to add these flags/features in  this tool. thanks
