### ISSUE TITLE
kubelet service: add /metrics/probes, /metrics/resource to ServiceMonitor and ClusterRole

### ISSUE THREAD

**Issue by flokli** [grafana/agent#1186]
While debugging some missing metrics in default grafana dashboards, I realized we probably want to also add the following two paths to the ClusterRole (`nonResourceURLs`), and add it to the scraping rules in `agent-example-config.yaml` and (`docs/operator/custom-resource-quickstart.md`):

`/metrics/probes`, `/metrics/resource`

The former exposes the `prober_probe_total` (for `probe_type` `Startup`, `Liveness` and `Readiness`), the latter      - exposes the `{container,pod}_{cpu_usage_seconds_total,memory_working_set_bytes}` metrics.

**Comment by rfratto** [comment]
cc @hjet 

Which dashboards were you looking at that were expecting these metrics? IIRC we omitted those endpoints to try to cut down on the number of metrics being sent and (at the time) weren't using anything they had for visualization.

**Comment by flokli** [comment]
`Kubernetes / StatefulSets` uses `container_cpu_usage_seconds_total` (and some others uses the aggregated `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate` - see https://github.com/prometheus-operator/kube-prometheus/blob/6d013d4e4f980ba99cfdafa9432819d484e2f829/manifests/kubernetesControlPlane-prometheusRule.yaml#L1223).

In the list of dashboards I had, I couldn't immediately find something using `prober_probe_total`.

**Comment by hjet** [comment]
Since the CR quickstart has an allowlist in the default config, I am cool with adding those two paths to the `ClusterRole` to open up permissions.

I don't think it'll increase cardinality unless the relevant monitors or scrape targets are configured. I also don't think you need it for `container_cpu_usage_seconds_total`? IIRC that's a cadvisor metric

**Comment by hjet** [comment]
Could see the probe use case being useful though. Again, won't add the path as a default scrape target in the quickstart, but permission-wise it'll be open in case anyone would want to scrape that
