### ISSUE TITLE
Support more config store like configdb or s3 

### ISSUE THREAD

**Issue by AllenzhLi** [grafana/agent#1199]
Now grafana agent support etcd and consul store configs which require a more etcd or consul to deploy.

Support more ways such as configdb or s3 to share existing components.

reopen #488

**Comment by AllenzhLi** [comment]
Is there any plan working on this?

**Comment by mattdurham** [comment]
It has been discussed internally, but the work is not planned for the immediate future.

**Comment by AllenzhLi** [comment]
> It has been discussed internally, but the work is not planned for the immediate future.

If a configdb like cortex is implementd, will it be received?

If the answer is yes, then I will trying to work on this.

**Comment by rfratto** [comment]
Hi @AllenzhLi, sorry for the response delay, most of us have been on holiday. 

Just to make sure I'm clear on the proposal, this is for the config store used by the scraping service to support configdb / s3 and _not_ the [new experimental functionality](https://github.com/grafana/agent/blob/main/docs/configuration/_index.md#remote-configuration-beta) to load files from remote locations? 

I wouldn't be opposed to adding s3 support to the config-from-URL feature, but adding it to the scraping service config store might be pretty challenging. The scraping service config stores need to implement [this interface](https://github.com/grafana/agent/blob/c526607a6bca1fe5ea348c78a47ee8f6b7f7613e/pkg/metrics/instance/configstore/store.go#L11-L42), which includes a method for receiving change events. I'm not sure if S3 has a watch API, or it might be prohibitively expensive. 

FWIW: I've been itching to revamp the config store. As one of the original components of the agent, it has severe limitations and currently doesn't scale very well. We'll probably continue to support it in some capacity, but it might be a new dedicated service external from the agent.

**Comment by AllenzhLi** [comment]
Thank you for your reply.

> Just to make sure I'm clear on the proposal, this is for the config store used by the scraping service to support configdb / s3 and not the new experimental functionality to load files from remote locations?

This is for the config store used by the scraping service, I want to update the `Configs` regularly.
https://github.com/grafana/agent/blob/5bf8cf452fa76c75387e30b6373630923679221c/pkg/metrics/agent.go#L44

> I wouldn't be opposed to adding s3 support to the config-from-URL feature, but adding it to the scraping service config store might be pretty challenging. The scraping service config stores need to implement this interface, which includes a method for receiving change events. I'm not sure if S3 has a watch API, or it might be prohibitively expensive.

It's really harder than I expected. 

> We'll probably continue to support it in some capacity, but it might be a new dedicated service external from the agent.

I use agent in k8s multi-cluster which have main-cluster and some sub-cluster. The main- cluster is always exist and deploy cortex, while the sub-cluster is dynamic create and only deploy agent. When a new sub-cluster created, it will bootstrap using a default config from configmap, and watch a etcd which in main-cluster.

The problem is that main-cluster may not know what sub-cluster is created or deleted and share etcd is also a weak point. I expect the agent can pull scrape configs from a  remote locations with cluster name arguments. 

I was wondering whether a external service can slove the problem.

**Comment by AllenzhLi** [comment]
>It does sound like the direction we're heading in with remote configs might be better for your use case.
Expect this can support  remotely retrieve scrape configs.

I have implement a service sync scrape config to sub-cluster agent regularly and it worked.

> Do you need to use the scraping service for any reason other than how it can remotely retrieve configs?
Don't understand what you mean. I try to answer this question.
I have use the agent scraping service in my cluster and it worked well, except  remotely retrieve scraping configs.
