### ISSUE TITLE
Windows Grafana Agent is Vulnerable for Unquoted Path vulnerability

### ISSUE THREAD

**Issue by mich4e1** [grafana/agent#1213]
The windows agent is vulnerable for Unquoted path and could be used for Privilege escalation to get SYSTEM permissions.
By default it is installed in C:\Program Files\Grafana Agent\ directory (this also could be used for escalation from Admin to SYSTEM), but also is possible to use another different subdirectories (in the example was used C:\Program Files\My Custom Path\Grafana Agent\ directiry).

To verify the unquoted path was used wmic tool:
![image](https://user-images.githubusercontent.com/50629340/147549669-197bbda5-4fa1-428e-8113-024b4714f395.png)

Was tested the latest version of the agent - v0.21.2.

**Comment by mattdurham** [comment]
Thanks for the heads up! Will go out with our next release.
