### ISSUE TITLE
document installation with brew

### ISSUE THREAD

**Issue by rlankfo** [grafana/agent#1236]
The grafana-agent can now be installed from homebrew-grafana or homebrew-core. Creating this issue to track creation of brew install docs. 

See https://github.com/grafana/agent/issues/193

**Comment by rfratto** [comment]
cc @rlankfo @brendamuir can you work together on this?

**Comment by karengermond** [comment]
@rfratto  To document this, would we update this topic on [installing Grafana Agent on macOS](https://grafana.com/docs/agent/latest/set-up/install-agent-macos/)?

**Comment by rfratto** [comment]
Actually, it looks like that document (introduced in #1717) covers what we're talking about here. 

I'll close this; implemented by #1717.
