### ISSUE TITLE
Grafana Cloud - NGINX parse error

### ISSUE THREAD

**Issue by arantesxyz** [grafana/agent#1237]
I'm currently having this error on Grafana Cloud NGINX dashboard:

```
parse error : queries require at least one regexp or equality matcher that does not have an empty-compatible value. For instance, app=~".*" does not meet this requirement, but app=~".+" will
```

Linux Server dashboard works fine. Not sure why does this error mean.

Btw, I had some other problems i figured out on my own, couldn't find much about any grafana errors online.

**Comment by rfratto** [comment]
Hey @arantesxyz! I'm sorry you're having problems, but this repository is dedicated for issues relating specifically to the Grafana Agent as an OSS project. We won't be very useful assisting with Grafana Cloud-specific problems, such as with the NGINX integration. 

Instead, can you open this as a support ticket? You can do that from the grafana.com portal under Support -> Open a Ticket. The support engineers should be able to give you the help you deserve there.

**Comment by rfratto** [comment]
I’m sorry, but we don’t maintain the dashboard you’re using or have any knowledge about it. I still recommend opening up a support ticket.
