### ISSUE TITLE
Can't configure migrated node_exporter fields

### ISSUE THREAD

**Issue by pkoenig10** [grafana/agent#1240]
I think there's a bug in the migration field logic introduced in https://github.com/grafana/agent/pull/1228.

I'm trying to configure the `collector.filesystem.mount-points-exclude` node_exporter option. But after upgrading the a versiom with https://github.com/grafana/agent/pull/1228, I am unable to get any value but the default value.

| Input | Expected | Actual |
| --- | --- | --- |
| Old unset, New unset | Default value | Default value |
| Old set, New unset | Old value, with unmarshall warning | Default value, no unmarshall warning |
| Old unset, New set | New value | Default value |
| Old set, New set | Error | Error |

When setting either the old or new value, I see the following logs when starting Grafana Agent:
```
caller=filesystem_common.go:111 level=info integration=node_exporter collector=filesystem msg="Parsed flag --collector.filesystem.mount-points-exclude" flag=^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+)($|/)
```

Because the default value is the same in Grafana Agent and node_exporter, it's not clear whether were passing the default value or passing an empty string.

I also tried to reproduce this in a playground, but was unable to. So I'm not sure what's going wrong here.
https://go.dev/play/p/oNxDvMSHVr2

@rfratto

**Comment by pkoenig10** [comment]
I have confirmed using the official Grafana Agent docker image the config works as expected on the commit before https://github.com/grafana/agent/pull/1228 (5bf8cf452fa76c75387e30b6373630923679221c) but does not work on the commit with https://github.com/grafana/agent/pull/1228 (50f8e6657bbd05c9a32bf0dc40b341506448302f).

**Comment by pkoenig10** [comment]
Here's a reproduction:
```yaml
// agent.yaml

integrations:
  node_exporter:
    enabled: true
    filesystem_ignored_mount_points: oldValue
```

```
$ docker run --rm -v $PWD/agent.yaml:/etc/agent/agent.yaml:ro grafana/agent:main-50f8e66
```

In the output, I see:
```
caller=filesystem_common.go:111 level=info integration=node_exporter collector=filesystem msg="Parsed flag --collector.filesystem.mount-points-exclude" flag=^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+)($|/)
```

**Comment by rfratto** [comment]
Thanks for reporting! First off, let me thank you for running the main build of the agent. It's great that we were able to catch this before we did a release, and although I added a test to make catch specifically this, mistakes happen :) 

I'll look into this this morning and see what's going on.

**Comment by pkoenig10** [comment]
Thanks for the quick fix!
