### ISSUE TITLE
Feature Request: Oauth2 extension OTEL / Grafana agent tracing

### ISSUE THREAD

**Issue by Whyeasy** [grafana/agent#1250]
**Is your feature request related to a problem? Please describe.**

Currently the tracing part of the Grafana Agent is missing Oauth2 authentication capabilities. These are available for the metrics and logs part. As the tracing part is using the opentelemetry collector, there is an extension that enables this: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oauth2clientauthextension

**Describe the solution you'd like**

Would be great if it would be possible to use Oauth2 authentication for all 3 data streams within the Agent. By implementing this extension or make it possible to configure extensions we can achieve this goal.

**Comment by Canuteson** [comment]
PR for this one @Whyeasy 
Appreciate any feedback.

**Comment by rfratto** [comment]
Closed by #1386.
