### ISSUE TITLE
Invert condition used to exempt network tests

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1251]
Today, we have tests which only execute when `-tags has_network` is provided: https://github.com/grafana/agent/blob/727f9089b3c67dea416353b9e24062a85c6f3c3f/pkg/operator/kubelet_test.go#L3

This is useful for running tests in a sandbox environment where things like the network aren't available. We initially started doing this after @flokli's #333, which needs to skip over tests for NixOS. 

However, adding the extra tag makes it more difficult to write the tests, as it is excluded from build by default, and therefore excluded from gopls by default. 

I'd suggest that we invert the condition instead:

```
//go:build !nonetwork
```

```
//go:build !nodocker 
```

(etc)

This makes it easier to add to the tests, and ensures that the default testing behavior is to run everything.

**Comment by flokli** [comment]
Both works - whenever I bump to a version containing these changes, I should realize the tests start failing ;-)

Thanks for the heads-up!
