### ISSUE TITLE
Add ability to receive traces via http and pass along the org id

### ISSUE THREAD

**Issue by bputt-e** [grafana/agent#1285]
We'd like the ability to process data from multiple tenants (each tenant has a separate orgId). This is to request the ability for the OTLP receiver to accept the header X-Org-Id and have the loki/prometheus/tempo writers pass along that orgId.

Our current setup:
OTEL collector -> Kafka -> Grafana agent

We'd add an otel collector after kafka to effectively send spans to the grafana agent via otlp protocol. We understand that this would be preferred to be done at the kafka receiver, but figured using the otlp receiever where we can extract http headers into internal vars would be more achievable and possibly setup the future for kafka

**Comment by mapno** [comment]
Hi @bputt-e, thanks for opening the issue.

The Grafana Agent can run any number of tracing pipelines, each with a different `remote_write`. You could run a pipeline per tenant. If you're able to route traces to their tenant's pipeline (you mention running an additional OTel collector), it should work as intended in your description.

However, I think this brings up a broader conversation regarding multi-tenancy support for traces in the Grafana Agent. Not too long ago, OTel added support for multi-tenancy via the [routing processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor) ([feature issue](https://github.com/open-telemetry/opentelemetry-collector/issues/1260)). This processor is able to route traces to specific exporters based on HTTP headers or attributes. After giving it a quick look, I think this is something that could be incorporated into the Agent. Would that meet your needs?

**Comment by bputt-e** [comment]
Hello @mapno the routing processor might be feasible considering how we can specify a remote url to pull the config from. My main concern with grafana-agent current is being able to generate service graphs per tenant. We're aware of cortex-tenant which will be able to use a dimension as the ```x-scope-orgid``` and we planned on using the ```spansmetricprocessor``` in otel to add the auth as a dimension so that we can configure a remote promtheus for all of our tenants.

**Comment by mapno** [comment]
> My main concern with grafana-agent current is being able to generate service graphs per tenant.

Right, the way this feature was built does not open the possibility to support multiple tenant in single Agent. It could be achieved by running an Agent per tenant, but that is less than ideal.

> We're aware of cortex-tenant which will be able to use a dimension as the x-scope-orgid and we planned on using the spansmetricprocessor in otel to add the auth as a dimension so that we can configure a remote promtheus for all of our tenants.

This should work. Let me know if you need any help with running this set-up.

As for actual multi-tenancy support, we're currently working on [server-side metrics](https://github.com/grafana/tempo/pull/1206) for Tempo. With this project, we will add service graphs support in Tempo. It's being built for multi-tenancy support out-of-the-box.

**Comment by mapno** [comment]
Yes, not a lot has changed regarding multi-tenancy since. If you want to use a single layer of pipelines, configuring a pipeline per tenant I still believe it's the best option. The main problem I find with this approach is that it gets propagated to the instrumentation itself, since it'll need to know to which pipeline to send the traces.

A simpler solution for the instrumentation, but that's only supported in the OTel collector is the [routingprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor).
