### ISSUE TITLE
Investigate deleting *.tmp WAL files on startup

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#1321]
There are cases where due to various cleanup issues the files in the wal directory grow until they consume all the disk space available on the instance.

Determine 
- is it safe to delete these  *.tmp files
- under what circumstances, always or only if orphaned

**Comment by tpaschalis** [comment]
After our discussion, it seems like it's safe to delete those checkpoint .tmp directories.

As a matter of fact, Prometheus [already deletes blocks tmp dirs](
https://github.com/prometheus/prometheus/blob/0df3489275ed4357b12d98e737290992e19915ce/tsdb/db.go#L54-L58) on TSDB startup, and have considered also deleting other types of tmp dirs to save space. 

Furthermore, checkpoint .tmp dirs are supposed to be cleaned [in a defer](https://github.com/prometheus/prometheus/blob/cda025b5b50328ccd129c141e09dd77b3b1b034e/tsdb/wal/checkpoint.go#L140-L144) statement if the checkpoint itself errored out, but I suppose this doesn't get executed when we're OOMed.

IMHO we've got a couple of options:
a) Open an issue upstream, see if they're okay with deleting checkpoint.*.dirs on startup like they do for blocks dir
b) Implement this check ourselves to "be a good citizen" and cleanup after our own mess (supposedly no one's going to be running other Prometheus/Agents in parallel, the same WAL dir)

Any thoughts? /cc @rfratto @rlankfo

**Comment by tpaschalis** [comment]
Opened prometheus/prometheus#10245 just to get some feedback.

Looking back at the original conversation I suppose it's also important to understand _how_ the cleanup isn't getting called (a panic, oom, something else?) but let me know if you think this is something should handle anyway.

**Comment by mattdurham** [comment]
Going with B and seeing where A leads seems reasonable =)

**Comment by tpaschalis** [comment]
To be honest I didn't have the time to look into this, but we just got word from upstream that they'd be into cleaning them up on startup.

https://github.com/prometheus/prometheus/issues/10245#issuecomment-1033755396

**Comment by rfratto** [comment]
It looks like someone might contribute the fix upstream based on that issue. Let's wait a little bit and let them have a shot at implementing it.

**Comment by rfratto** [comment]
Bump; there's still upstream movement on this.

**Comment by tpaschalis** [comment]
The upstream proposal was accepted and the fix was merged. I think it's safe to close this issue. (Wouldn't hurt to verify that ourselves as well)

**Comment by rfratto** [comment]
Can we cherry-pick the fix into our grafana-specific release branch and import it into the agent before closing this?
