### ISSUE TITLE
Proposal: Operator: Add additionalIntegrations to LogsInstance/MetricsInstance

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1335]
#1330 introduces our first non-exporter integration in the form of Kubernetes events logging. This works by watching Kubernetes for events and sending received events to an existing logging instance. 

The effort to support integrations in the operator (#1224) is mainly focused around metrics-based integrations, where integrations are deployed as separate pods, with no knowledge of existing metrics/logging instances. This is fine for these integrations, since the metrics they generate are scraped externally where a WAL is available. 

However, this means that #1330 wouldn't have access to the logging instance, and can't function properly. The long term solution for this is to move everything into a single DaemonSet, but we're not ready for that yet (see #1140). 

I propose a short term solution: add `additionalIntegrations` to LogsInstance and MetricsInstance, in the same style of `additionalScrapeConfigs`. This would allow you to specify a Secret holding raw integration settings to inject alongside logging- and metrics-related pods. 

Note that this short term solution would work for integrations that only interact with either metrics or logging, but not both. An integration that needs both metrics and logging instances couldn't run inside of the operator until the unified DaemonSet is available. 

cc @hjet

**Comment by hjet** [comment]
I worry about how this would work with the forthcoming cloud integrations API changes. I am not super familiar with the operator/integrations design, but could we create a new "temporary" CR for this type of integration, or extend the existing spec (in a similar way that's proposed here, but "reversed," where the integration allows a logs instance config)?

**Comment by hjet** [comment]
Since those changes haven't even been designed yet, we could also probably incorporate this and figure out a solution, fwiw

**Comment by rfratto** [comment]
The need for this is superseded by the current revision of #1224.
