### ISSUE TITLE
Operator: main build fails to reconcile secrets

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1339]
@stevo-f3 [reported][original-report] in #1271 that the operator is failing to reconcile on secrets:

> 
```
level=info ts=2022-02-01T18:57:31.693552638Z component=controller.grafanaagent msg="Starting workers" workercount=1
level=info ts=2022-02-01T18:57:31.693623302Z component=controller.grafanaagent name=foo namespace=bar msg="reconciling grafana-agent"
level=error ts=2022-02-01T18:57:31.694405371Z component=controller.grafanaagent name=foo namespace=bar msg="unable to build hierarchy" err="failed to discover secrets: failed to find \"/v1, Kind=SecretList\" resource: list failed: Index with name field:metadata.name does not exist"
```

This is likely caused by the ongoing refactoring to help test and maintain the code more easily. 

[original-report]: https://github.com/grafana/agent/issues/1271#issuecomment-1027214694_

**Comment by stevo-f3** [comment]
Maybe this applies https://github.com/kubernetes-sigs/kubebuilder/issues/547#issuecomment-450772300

**Comment by rfratto** [comment]
Thanks @stevo-f3, that was definitely helpful! And thanks for reporting too, sorry we had missed this initially.
