### ISSUE TITLE
Different Pod resources definitions for metrics and log agents

### ISSUE THREAD

**Issue by jimgus** [grafana/agent#1348]
If you wan't to configure Agent Pod resources (requests/limits) when using the grafana-agent-operator, you do that in the `GrafanaAgent` resource. This will apply both to the Grafana Agent StatefulSet created from the `MetricsInstance` resource and the Grafana Agent DaemonSet created from the  `LogsInstance` resource. I would however be great if it was possible to configure different resources definitions for those two since the CPU/Memory need may differ.

**Comment by rfratto** [comment]
Hi! At the moment, the fact that a GrafanaAgent generates multiple resources (StatefulSet + DaemonSet) is a bit of an implementation detail. Long term, I'd like for it to generate a single DaemonSet for all your telemetry.

Given that, I'm hesitant to support a temporary resource field for the resources it generates now. The current workaround would be to have a dedicated GrafanaAgent for logs, and another for metrics, and to give both their own set of resources.

**Comment by jimgus** [comment]
Hi! Ok, I see. Sounds like a good idea to make a single DeamonSet. Just curios, when is that change planned to happen?

**Comment by rfratto** [comment]
Eventually™ 🙃 

Unfortunately I don't really have a timeline for when that might happen. Within the next year seems like a safe bet, but there's a lot we need to do on the agent side to make a DaemonSet approach possible for Kubernetes.
