### ISSUE TITLE
Integrations: replace `agent_hostname` label with `instance` label

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#135]
#134 pointed out issues with the `agent_hostname` label. Integrations would work more nicely with existing Grafana Dashboards if integrations instead replaced the value of the `instance` label with the machine hostname. 

This is harder than it sounds; we don't want to do this manually with metric_relabeling_rules, because we'd either have to deal with an added `exported_instance` or force all integrations to not respect labels on behalf of the users. The proper way to implement this is to intercept the label at the WAL layer or replace in the remote_write configs.

**Comment by nikoalch** [comment]
+1

**Comment by eamonryan** [comment]
+1

**Comment by suitupalex** [comment]
![image](https://user-images.githubusercontent.com/5080493/88228789-4ae3d680-cc35-11ea-9807-fef971d5e661.png)
