### ISSUE TITLE
Docs feedback: /getting-started/install-agent-on-windows.md

### ISSUE THREAD

**Issue by als-graf-git** [grafana/agent#1366]
This doc does not currently contain a link to the Windows Agent from https://github.com/grafana/agent/releases.

**Comment by rfratto** [comment]
Thanks for the feedback! I've opened a PR to add a link. In the future, feel free to open PRs! We'd be more than happy to review and give guidance if you're interested in contributing. If not - no big deal, providing feedback like this is also a super valuable type of contribution.
