### ISSUE TITLE
Script exporter integration

### ISSUE THREAD

**Issue by carlosabalde** [grafana/agent#1371]
I think integrating something similar to the [script exporter](https://github.com/ricoberger/script_exporter) would be a nice addition to Grafana Agent, specially when used to monitor the same host where the agent is running. That would allow scrapping of ad-hoc metrics when a specific-purpose exporter is not available.

Although some far-from-ideal alternatives exist (e.g. node exporter's textfile collector + cron jobs; see [this](https://utcc.utoronto.ca/~cks/space/blog/sysadmin/PrometheusScriptExporterWhy) for a nice explanation), in spite of being an old school monitoring strategy, and keeping in mind that forking processes with unbound execution times could be risky (but I think fixable using timeouts), having something like a script exporter integrated in Grafana Agent would IMHO offer a lot of flexibility when properly used.

Is this something that would be opened to consider? Any opinions?

**Comment by rfratto** [comment]
Hey! I don't speak for all the maintainers, but I think this is a pretty interesting idea and I'm not immediately opposed to exploring it. 

At the surface, this seems kind of similar to [pushgateway](https://github.com/prometheus/pushgateway); do you have a use case for where script_exporter is preferable over a pushgatway?

**Comment by carlosabalde** [comment]
Thanks for the feedback @rfratto! I think the pushgateway is the right tool for other uses cases. For example, pushing some summary metrics once a backup script completes its hourly job. Execution of that script could be triggered by cron or any other tool; definitely **not** by Grafana Agent.

What I'm suggesting here is different and the reason why things like https://github.com/ricoberger/script_exporter exist. It's about offering a simple way of monitoring a component -probably running in the same host where the Grafana Agent is running- (1) not requiring that component to expose a scrapping end-point; and (2) not requiring the implementation, installation and execution of a specific-purpose exporter. Even if both options are possible, and even knowing that those options usually are the most performant approaches, sometimes they are simply too much effort or noise.

A simple Bash, Python, etc. script dumping properly formatted Prometheus metrics to the stdout + a generic exporter embedded in Grafana Agent executing the script on every scrapping event, collecting the metrics and adding a few more (e.g. exit status, execution time, etc.), would offer a lot of flexibility. I think the pushgateway is not really designed to cover something like this.

**Comment by rfratto** [comment]
Thanks for the explanation! It sounds like this would be a useful addition. I don't think any of the current maintainers are going to have the bandwidth to implement this in the near term. If you or anyone else is interested on working on a PR to support this, I'd be more than willing to give guidance and help it get merged.
