### ISSUE TITLE
WAL: Minimum series staleness time before deletion

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#138]
Using `queue_highest_sent_timestamp_seconds` doesn't guarantee that all samples prior to that time have been successfully sent and as such, it shouldn't be used as the only indicator for deleting stale series. 

A new config option should be added to delete stale series if they haven't received a write since the `queue_highest_sent_timestamp_seconds` _and_ their last write was over _X_ seconds ago. This will help guarantee that samples get sent if remote_write is sending them in a different order.

One thing to note: it's not clear how significant of a problem this is. Since we only consider samples for deletion after ~2 GC cycles and the GC cycle interval has to be greater or equal to the scrape interval, it might be exceedingly difficult for this to align in a way where we GC unsent samples. 

/cc @cstyan

**Comment by rfratto** [comment]
I could implement this now but I'd like to wait until #137 is merged at least.

**Comment by cstyan** [comment]
Can you clarify what you mean by:
> they haven't received a write since the `queue_highest_sent_timestamp_seconds`

Maybe I'm just not up to date on how the agent works but it's not clear what "received a write" means here.

> One thing to note: it's not clear how significant of a problem this is.

Agreed, would be good to get some kind of baseline #'s about how often we might be prematurely truncating the WAL.

**Comment by rfratto** [comment]
> Maybe I'm just not up to date on how the agent works but it's not clear what "received a write" means here.


Every [1 minute](https://github.com/grafana/agent/blob/55e9697c948f7d68fc7c1a2a85a7becced08eba3/pkg/prom/instance/instance.go#L451-L464) we'll poll the value of `queue_highest_sent_timestamp_seconds` and use that as the truncation timestamp. Any series whose timestamp is before that value will be scheduled for deletion. If the last received (i.e., scraped) timestamp for the series is still lower than `queue_highest_sent_timestamp_seconds` on the next iteration, it'll be deleted. Otherwise, if we got a sample that's newer than `queue_highest_sent_timestamp_seconds`, we'll unschedule that series for deletion and keep it in memory/in the WAL.

**Comment by cstyan** [comment]
> If the last received (i.e., scraped) timestamp for the series is still lower than queue_highest_sent_timestamp_seconds on the next iteration, it'll be deleted. 

okay so we keep track of the last time we got a sample for each series, I wasn't aware of that

:+1: sounds like a good improvement to me
