### ISSUE TITLE
add feature flag section in documentation

### ISSUE THREAD

**Issue by rlankfo** [grafana/agent#1383]
Currently there is not much visibility into feature flags users can toggle in the agent. I'm proposing that we create a dedicated page in our docs to enumerate the available feature flags. See https://prometheus.io/docs/prometheus/latest/feature_flags/ for inspiration.

**Comment by rlankfo** [comment]
> @rlankfo We kind of have this now on a [command line flags page](https://grafana.com/docs/agent/latest/configuration/flags/#command-line-flags)
> 
> WDYT? Should we still have a dedicated page for feature flags?

hey @rfratto, sorry, this fell off my radar. I think the page we have now is fine, my intention was just to get these grouped together and it seems like we've accomplished that.  Do you see the need for additional section in the docs? If not, let's close this. Thanks!

**Comment by rfratto** [comment]
I think it's probably good enough as-is for now, closing :)
