### ISSUE TITLE
Proposal: add "next" milestone

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1392]
I propose we have a release milestone called "next" to help us track issues we would like to resolve before the next minor release. 

This milestone would not be a guarantee of what features will be made available in the next release, but rather as a way to help maintainers not lose track of issues. 

The description for the milestone will be: 

> Issues or PRs planned to be included in the next release. This is not an official roadmap or guarantee of when changes may be delivered; the next release may not include all changes listed here, or may include changes that are not listed.

**Comment by mattdurham** [comment]
I wholeheartedly approve, thoughts on where this would live?

**Comment by rfratto** [comment]
In this repo, I'd say: https://github.com/grafana/agent/milestones

**Comment by mattdurham** [comment]
We can prune the closed issues since they would be reflected in the changelog.

**Comment by rfratto** [comment]
Hmm, maybe play it by ear for now? We can also create a milestone per release so we don't have to do too much maintenance after a release.

**Comment by rfratto** [comment]
On second thought, I think I'd like to try a milestone per release since it might help with searching historical issues / PRs to see what release they were a part of.

**Comment by mattdurham** [comment]
Fine with that. We can always adjust as we go along.

**Comment by rfratto** [comment]
See the v0.24.0 milestone here: https://github.com/grafana/agent/milestone/1
