### ISSUE TITLE
Docs feedback: /operator/custom-resource-quickstart.md

### ISSUE THREAD

**Issue by Skeen** [grafana/agent#1395]
cAdvsior -> cAdvisor

![image](https://user-images.githubusercontent.com/225151/154534853-75c1c295-fd3a-47a4-947c-234f92c3acf2.png)

**Comment by rfratto** [comment]
The diffs you posted seem reasonable, I'd accept a PR with those changes. In any case, if you make a suggestion in a PR and get a detail wrong I'm always happy to help nudge things in the right direction :)
