### ISSUE TITLE
Elasticsearch exporter self-signed certs documentation

### ISSUE THREAD

**Issue by michaelvanderbeek** [grafana/agent#1398]
Hi All,

I'm requesting for more detailed config for the elasticsearch exporter via grafana-agent. Using the latest v0.23.0 
The documentation shows:
integrations:
 elasticsearch_exporter:
    enabled: true
    address: http://elasticsearch:9200

My cluster has a self-signed cert for the port 9200. So I need to know how to 
a) tell it to ignore the ssl verification (like curl -k)
or 
b) configure the self sign key and cert.

I'm currently getting
Feb 18 04:02:34 elk3 grafana-agent[27561]: ts=2022-02-18T04:02:34.616818434Z caller=nodes.go:1871 level=warn integration=elasticsearch_exporter msg="failed to fetch and decode node stats" err="failed to get cluster health from https://elk3:9200_nodes/_local/stats: Get \"https://elastic:***@elk3:9200/_nodes/_local/stats\": x509: certificate signed by unknown authority"
Feb 18 04:02:34 elk3 grafana-agent[27561]: ts=2022-02-18T04:02:34.61787996Z caller=cluster_health.go:290 level=warn integration=elasticsearch_exporter msg="failed to fetch and decode cluster health" err="failed to get cluster health from https://elk3:9200/_cluster/health: Get \"https://elastic:***@elk3:9200/_cluster/health\": x509: certificate signed by unknown authority"

Thanks a lot!

Regards,

Michael

**Comment by rlankfo** [comment]
The error indicates the ssl certificate can't be verified. You could either get a certificate signed by a trusted certificate authority, or if you are using a self-signed certificate you could skip verification. 

Adding the following field to your exporter config should allow you to skip certificate verification if that's what you wish to do:
```
ssl_skip_verify: true
```
