### ISSUE TITLE
metrics: instanceNamespaceSelector: {} missing from docs page. 

### ISSUE THREAD

**Issue by simonc6372** [grafana/agent#1400]
It was reported. that 
this document <https://grafana.com/docs/agent/latest/operator/custom-resource-quickstart/>

is missing

metrics: instanceNamespaceSelector: {}

Found it in spec, but not in docs
https://github.com/grafana/agent/blob/main/production/operator/crds/monitoring.grafana.com_grafanaagents.yaml

**Comment by rfratto** [comment]
Hmm, `instanceNamespaceSelector: {}` is optional. If you don't provide it, only instances in the current namespace will be checked. 

I'm not sure if we should configure it to search all namespaces by default or just document what namespaces would be searched as-is.

wdyt @hjet?

**Comment by hjet** [comment]
i think current default behavior is reasonable, but perhaps best to document and include a note about `instanceNamespaceSelector: {}` in that doc. i'll take care of that today
