### ISSUE TITLE
Operator : Logs common relabeling / change default

### ISSUE THREAD

**Issue by tesharp** [grafana/agent#1406]
Is there any way to add or change the default labels added by operator on logs for all scapes? For instance I would like to remove the default `filename` label on all jobs, and add a couple of pod labels. Can do this on the PodLogs manifest using relabelings, but I would like to do it for all jobs and not having to define it for every single resource.

**Comment by rfratto** [comment]
Hi! Sorry for the delay in responding. 

We don't have a way of having default relabelings for all pod logs today, but I'm not against the idea. @captncraig WDYT?
