### ISSUE TITLE
"context deadline exceeded" during agent install - Cause found

### ISSUE THREAD

**Issue by h4ckninja** [grafana/agent#1410]
I was attempting to install the agent for communicating with my cloud account. I got the install to run and kept getting "Failed to retrieve config". I found the function in the shell script that called `grafana-agentctl cloud-config` and invoking that manually with my stack ID and API key, I got a little more verbose of an error message:

```
could not retrieve agent cloud config: failed to make request: Get "https://integrations-api-us-central.grafana.net/stacks/<my ID>/agent_config": context deadline exceeded
```

However, invoking this through curl worked:

```
curl -H "Authorization: Bearer eyJ<my API key>" https://integrations-api-us-central.grafana.net/stacks/<my ID>/agent_config
```

Response:

```
{"status":"success","data":{"integrations":{"node_exporter":{"enabled":true},"prometheus_remote_write":[{"basic_auth":{"password":"eyJ<removed>},"server":{"http_listen_port":12345}}}
```

On a hunch, I checked my `/etc/resolv.conf` and the first DNS server was a (currently) down DNS resolver. I commented that out and `grafana-agentctl` worked, despite having a second working resolver.

**Bug:**

Make `grafana-agentctl` more resilient in DNS lookups.

**Comment by rfratto** [comment]
Thanks for reporting! It looks like our timeout is set lower than the timeout for establishing the TCP connection, which might be obscuring the underlying error here. 

We'll have to see if tweaking the timeouts helps make the error more obvious, and if it's possible to have it fall back to another DNS resolver if the first one isn't responding fast enough.

**Comment by marctc** [comment]
> We'll have to see if tweaking the timeouts helps make the error more obvious

Setting up a timeout in the HTTP Client besides the Context timeout shows this message when it is exceed:
```
context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Not sure if this is a more helpful message. Wdyt?

**Comment by rfratto** [comment]
Ah, I don't think that's much better in this case. There's a few timeouts in play here:

1. Timeout for the command as a whole in `cmd/agentctl/main.go`

2. HTTP client timeout (defaults to no timeout)

3. HTTP client transport timeout (defaults to 30 seconds)

It seems like the values for these should be `command timeout` > `client timeout` > `transport timeout`. 

If my understanding of the code is right, that would return:

```
dial tcp: context deadline exceeded
```

as an error, which honestly still might not be very useful here. I don't know if there's really anything we can do about this.

**Comment by rfratto** [comment]
Ah, actually, looking through the code again it might be more detailed:

```
dial tcp: lookup integrations-api-us-central.grafana.net: context deadline exceeded
```

That would probably be slightly more helpful :)

**Comment by marctc** [comment]
The transport timeout shows `dial tcp: i/o timeout`. If that message is good enough, would that mean that we can get rid of the command timeout?

**Comment by rfratto** [comment]
Yeah, I think for now we can get rid of the command timeout.
