### ISSUE TITLE
windows_exporter: any metric for sorting out physical hosts from virtual ones?

### ISSUE THREAD

**Issue by jagbarcelo** [grafana/agent#1418]
Just as simple as that: is there  any way for guessing which of my agents are running on a physical hardware and which ones are virtual machines? I've been googling around, looking at the provided metrics and documentation and and I cannot find a single thing about this.

Thanks.

**Comment by mattdurham** [comment]
I took a quick look and didn't see anything. You could use a mixture of relabeling rules and/or environment variables to add/set a label if a host was running in a virtual environment or not.

**Comment by mattdurham** [comment]
Creating the variables is what I was suggesting, aside from that I don't think there is an easy way. The best route would be to open an issue in the windows_exporter repo and then we could pull those changes if/when they are made.
