### ISSUE TITLE
Evaluate consulagent_sd_config for Metrics and Traces

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1419]
The newest version of Promtail introduced consulagent_sd_config which only looks for targets on the local machine. Once we update our Promtail dependency, we should evaluate whether this SD mechanism can be added to metrics and traces as well for consistency. It would only work for metrics and traces if it emits enough labels to find a target's address and port. 

Depends on #1394.

**Comment by chuckyz** [comment]
@rfratto 

I wrote this patch against b027e7c62b0d92d55faf3a59229682f806dc2d60

```
diff --git a/cmd/agent/main.go b/cmd/agent/main.go
index eb78fda8..ae110105 100644
--- a/cmd/agent/main.go
+++ b/cmd/agent/main.go
@@ -19,6 +19,7 @@ import (

        // Register Prometheus SD components
        _ "github.com/prometheus/prometheus/discovery/install"
+       _ "github.com/grafana/loki/clients/pkg/promtail/discovery/consulagent"

        // Register integrations
        _ "github.com/grafana/agent/pkg/integrations/install"
diff --git a/pkg/metrics/cluster/validation.go b/pkg/metrics/cluster/validation.go
index 04bab6f1..185cd0d8 100644
--- a/pkg/metrics/cluster/validation.go
+++ b/pkg/metrics/cluster/validation.go
@@ -22,6 +22,7 @@ import (
        "github.com/prometheus/prometheus/discovery/scaleway"
        "github.com/prometheus/prometheus/discovery/triton"
        "github.com/prometheus/prometheus/discovery/zookeeper"
+       "github.com/grafana/loki/clients/pkg/promtail/discovery/consulagent"
 )

 func validateNofiles(c *instance.Config) error {
@@ -76,6 +77,10 @@ func validateDiscoveryNoFiles(disc discovery.Config) error {
                if err := validateHTTPNoFiles(&config.HTTPClientConfig{TLSConfig: d.HTTPClientConfig.TLSConfig}); err != nil {
                        return err
                }
+       case *consulagent.SDConfig:
+               if err := validateHTTPNoFiles(&config.TLSConfig); err != nil {
+                       return err
+               }
        case *digitalocean.SDConfig:
                if err := validateHTTPNoFiles(&d.HTTPClientConfig); err != nil {
                        return err
```

Does this look like vaguely the right path?

**Comment by rfratto** [comment]
That looks right to me :) Adding new SDs is generally straightfoward, making sure it's in the import path is all you need to do for metrics (aside from our gnarly `validateDiscoveryNoFiles` hack)

**Comment by chuckyz** [comment]
What tests would you like for this?  I'll get a PR open ASAP.

**Comment by rfratto** [comment]
IMO we don't really need unit tests or anything, just manual tests to verify that:

* Does consulagent_sd_configs generate an `__address__` label so metrics can be collected out of the box?
* Are are all other SD labels prefixed with `__` by default so users don't have to drop those labels they don't want from the final metrics? 

If that's the case, I'd say it's likely fully compatible with metrics and traces and we could accept the proposed diff as-is
