### ISSUE TITLE
Add support for triggering NRPE checks through Grafana Agent

### ISSUE THREAD

**Issue by simskij** [grafana/agent#1469]
At Canonical, we really like Grafana Agent, and we'd like to use it as **the** agent to monitor cloud-native solutions. We do see a functional gap, however: We would like to be able to run scripts similarly to how one does with NRPE and the `exec`-input plugin of Telegraf and have the results materialized as time series in Prometheus.

We are not suggesting that we create an emulator for NRPE or the input plugin, however, we'd like something that is functionally comparable.

We would love to collaborate on the design of such a feature and, of course, on the implementation as well.

**Comment by mattdurham** [comment]
Sounds like a good candidate for an integration, which means we could import it and it would get all the advantages that come with it being an integration. Are there any narrower needs/circumstances we could start with?

**Comment by rfratto** [comment]
I'm interested in learning more about what's being suggested here. Do you have any links that explain some of the use cases with NPRE or Telegraf's exec-input plugin?

**Comment by mmanciop** [comment]
Our use-case is bundling monitoring logic with [Juju charmed operator](https://charmhub.io). Depending on which integrations those operators support (called "relations" in Juju's lingo), Juju charms are capable to integrating Prometheus and Loki alert rules (see e.g. the [Spring Music charm](https://github.com/mmanciop/spring-music/tree/juju_charm)), and/or NRPE checks and/or "exec" checks in Telegraf (although this is less common).

**Comment by rfratto** [comment]
Thanks for clarifying :) This seems similar to #1371; would that cover exec-like checks or are you looking for something more specific?

**Comment by mmanciop** [comment]
#1371 might indeed scratch our itch. Script exporter is not something we had on our radar, but a cursory look at it seems very promising indeed.

**Comment by mmanciop** [comment]
We are going to experiment with the Script exporter a bit (e.g., try to port a few Nagios checks to it) and then report our findings.
