### ISSUE TITLE
Support Prometheus /-/reload endpoint

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#147]
When running in non-scraping-service mode, currently the Agent has to be completely restarted to apply updates made to the config file. A `/-/reload` endpoint that functions like Prometheus' should be added.

Related: #140

**Comment by amckinley** [comment]
+1 for this feature!

**Comment by rfratto** [comment]
I'm starting to work on this this week. I suspect it'll be available in the 0.13.0 release.
