### ISSUE TITLE
OpenBSD release?

### ISSUE THREAD

**Issue by mrusme** [grafana/agent#1487]
According to [this documentation](https://gist.github.com/josiahg/5c1405120d9bfc619bc84909a1714b53) it's possible to build the agent on OpenBSD. Since there's already a FreeBSD binary, maybe it makes sense to add OpenBSD as well?

**Comment by rfratto** [comment]
Hey! I'm not opposed to it, but it might be non-trivial depending on how much work it takes getting our current C cross-compiler to support OpenBSD. 

We currently use [rfratto/seego](https://github.com/rfratto/seego) for cross-compiling the binaries. As long as we can update it to bundle a sysroot to use with clang like we do for [FreeBSD](https://github.com/rfratto/seego/blob/7257eaba401374ce0a6aa53a63317475aff3905c/rootfs/go_wrapper.sh#L123-L141), official OpenBSD releases should be possible.
