### ISSUE TITLE
Grafana Agent Logs deployment manifest does not match with the Grafana Agent configuration in the docs.

### ISSUE THREAD

**Issue by Condla** [grafana/agent#1511]
When I follow the official docs, currently I'll get a CrashLoopBackOff for my daemonset.
The logs show the following:
```
flag provided but not defined: -server.http.address
Usage of /bin/agent:
  -config.enable-read-api
    	Enables the /-/config and /agent/api/v1/configs/{name} APIs. Be aware that secrets could be exposed by enabling these endpoints!
  -config.expand-env
    	Expands ${var} in config according to the values of the environment variables.
  -config.file string
.... 
```

The -server.http.address of the manifest does not match with the agent version.

The ask here is to make sure the docs point to the manifest that matches the current agent version.

**Comment by aengusrooneygrafana** [comment]
For reference, the doc that Stefan refers to is as follows:  
https://grafana.com/docs/grafana-cloud/kubernetes/agent-k8s/k8s_agent_logs/

**Comment by rfratto** [comment]
cc @hjet can you take a look at scanning through all the docs and make sure nothing is pointing at the main branches?

**Comment by aengusrooneygrafana** [comment]
for info..  
this.. 
https://grafana.com/docs/grafana-cloud/kubernetes/agent-k8s/k8s_agent_logs/#step-1-deploy-grafana-agent-daemonset
is referring to this.. 
https://github.com/grafana/agent/blob/main/production/kubernetes/agent-loki.yaml

**Comment by hjet** [comment]
Should be fixed per https://github.com/grafana/cloud-docs/pull/142, please let me know if any issues!
