### ISSUE TITLE
Remove older Tanka libraries

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1522]
The ["v0"](https://github.com/grafana/agent/tree/main/production/tanka/grafana-agent) and [v1](https://github.com/grafana/agent/tree/main/production/tanka/grafana-agent/v1) libs have been deprecated for a while, and I think the [v2](https://github.com/grafana/agent/tree/main/production/tanka/grafana-agent/v2) configs landed on a good design. 

Note that the [smoke](https://github.com/grafana/agent/tree/main/production/tanka/grafana-agent/smoke) folder currently sits alongside the v0 libs, but is _not_ deprecated and should not be removed.

We should remove all the deprecated stuff and replace it with:

```
production/tanka/grafana-agent/ 
  testbed/       # previously smoke/
  internal/      # previously v2/internal/
  main.libsonnet # previously v2/main.libsonnet 
  README.md      # previously v2/README.md 
```

cc @rlankfo for your opinion on me renaming smoke to testbed, since I'm not sure "smoke test" is really an accurate name for what that environment is.

Alternatively, `production/tanka/grafana-agent/smoke` can be moved to a higher folder, such as `production/tanka/grafana-agent-testbed` or `production/tanka/grafana-agent-smoke`.

**Comment by rlankfo** [comment]
> cc @rlankfo for your opinion on me renaming smoke to testbed, since I'm not sure "smoke test" is really an accurate name for what that environment is.

+1 for renaming smoke to something like testbed, testkit, or testenv.

**Comment by rfratto** [comment]
This was done a few months ago. Closing as complete.
