### ISSUE TITLE
grafana-agent-operator volumes issue with logs daemonset

### ISSUE THREAD

**Issue by jimgus** [grafana/agent#1524]
A continuation of my setup in https://github.com/grafana/agent/issues/1523. Tried to add volumes and volume mounts to the Grafana Agent config. It do however look like only the volume mounts are forwarded to the DS configuration. When checking the operator logs it looks like the volumes are not found:

```
level=error ts=2022-03-21T14:34:10.718098671Z component=controller.grafanaagent name=grafana-agent-platform namespace=grafana-agent msg="error during reconciling" err="failed to reconcile statefulset governing service: failed to create daemonset: DaemonSet.apps \"grafana-agent-platform-logs\" is invalid: [spec.template.spec.containers[0].volumeMounts[6].name: Not found: \"secrets-store\", spec.template.spec.containers[0].volumeMounts[7].name: Not found: \"tls\", spec.template.spec.containers[1].volumeMounts[6].name: Not found: \"secrets-store\", spec.template.spec.containers[1].volumeMounts[7].name: Not found: \"tls\"]"
```

Peeking into the code (https://github.com/grafana/agent/blob/main/pkg/operator/resources_logs.go) I see no part where the volumes in the Grafana Agent config are considered as for metrics: https://github.com/grafana/agent/blob/2da56c0a24778fc6c48bf0600f7ab3e558c6b0ff/pkg/operator/resources_metrics.go#L216

**Comment by mar-pan** [comment]
Was it really fixed? I'm trying to add volumes and I'm getting failed to create 
`daemonset: DaemonSet.apps \"grafana-agent-logs\" is invalid: [spec.template.spec.containers[0].volumeMounts[6].name: Not found: \"grafana-secret-two\", spec.template.spec.containers[1].volumeMounts[6].name: Not found: \"grafana-secret-two\"]`
