### ISSUE TITLE
windows_exporter config bug when installed using the grafana-agent-installer.exe

### ISSUE THREAD

**Issue by adeverteuil** [grafana/agent#1530]
When I install the Grafana Agent v0.23.0 using `grafana-agent-installer.exe`, I cannot configure a windows_exporter.

![Screenshot 2022-03-24 14-51-57 windows integration](https://user-images.githubusercontent.com/3270755/159990506-ac62f39c-a137-4b38-bbdd-e52d057100b0.png)

When I download and uncompress the single binary from `agent-windows-amd64.exe.zip` using the same config, it runs fine and I can see the `windows_exporter` metrics in Prometheus.

**Comment by mattdurham** [comment]
I am unable to reproduce this, with either the installer or downloaded binary version. Can you ensure your loading the correct file by passing in the absolute path to the agent.yml? Did you use a non standard install for the installer version? Normally it places agent/config into `c:\program files\grafana agent`?

**Comment by adeverteuil** [comment]
I tried to install on a system that already had a previous version of the agent and my environment wasn't clean. I reinstalled from scratch and this time it worked as expected. Sorry for the noise, you can close this issue!
