### ISSUE TITLE
question: prometheus agent mode vs. grafana agent

### ISSUE THREAD

**Issue by m-yosefpor** [grafana/agent#1543]
The functionality of grafana agent has now implemented in prometheus in agent mode. So what is the status of grafana agent project right now? is it going to be deprecated in favor of prometheus? are there still any benefits to use grafana-agent instead of prometheus agent mode or vice versa? I couldn't find any documentations about the comparison between the two.

Also there is no comparison between grafana agent logs and promtail.

**Comment by rfratto** [comment]
Hey! Grafana Agent and Prometheus Agent will continue to exist side-by-side, and we'll continue contributing as much metrics-specific code as we can to Prometheus. 

Grafana Agent covers more ground than Prometheus Agent does:

* It supports other types of telemetry (logs, traces). It's fairly unlikely that Prometheus Agent will do this. 
* It supports integrations to collect metrics from common systems. It's also fairly unlikely that Prometheus Agent will do this. 
* We explore new use cases in Grafana Agent, such as scaling metrics collection through clustering. These are things we would be happy to contribute upstream, but some use cases we explore (like the clustering) aren't currently of interest to the Prometheus team. 

I wrote a little bit about our relationship with Prometheus Agent on the [Grafana Labs blog](https://grafana.com/blog/2021/11/16/why-we-created-a-prometheus-agent-mode-from-the-grafana-agent/) recently which might help give extra detail on the above.

I hope this helps! 

> Also there is no comparison between grafana agent logs and promtail.

At the moment, Grafana Agent's log support is a thin wrapper around Promtail; the only difference is Promtail has a GUI (the agent doesn't) and Grafana Agent can instantiate any number of independent log collection pipelines whereas Promtail only has one.

**Comment by rfratto** [comment]
> are there still any benefits to use grafana-agent instead of prometheus agent mode or vice versa?

We try to provide an all-in-one experience, but the trade-off here is that we're slightly behind upstream.

I'd be completely reasonable to avoid Grafana Agent if:

* You're not interested in the all-in-one experience
* Any of the new use cases we might explore (e.g., scalability via clustering) wouldn't apply to you 
* You want to be closer to upstream to receive new features faster 
* Our custom integrations (that aren't based on existing exporters) don't apply to you (i.e., [eventhandler](https://grafana.com/docs/agent/latest/configuration/integrations/integrations-next/eventhandler-config/))
