### ISSUE TITLE
Listen for PrometheusRule resources and configure in Grafana Mimir/Cortex

### ISSUE THREAD

**Issue by flokli** [grafana/agent#1544]
It'd be really awesome if GrafanaAgent could listen for `PrometheusRule` resources, and create remote Mimir/Cortex configuration.

While it seems it's possible to configure these manually via Grafana, a lot of applications ship `PrometheusRule` resources to describe aggregations or alerts.

Using this would mean there's no need to deploy alertmanager in a downstream cluster, and do aggregation there, but it could all live in the monitoring system.

**Comment by rfratto** [comment]
I'd love this! This is somewhat similar to #523, which we'd probably add first before supporting PrometheusRule resources.

**Comment by TarekAS** [comment]
This would be great to have if we want to use Mimir as drop-in replacement for kube-prometheus-stack

**Comment by jhohertz** [comment]
#1986 seems to cover the same subject, appears to have some attention.
