### ISSUE TITLE
Questions: Grafana-agent-operator created component resource limit

### ISSUE THREAD

**Issue by kovaxur** [grafana/agent#1548]
Hi,
I would like to set a resource limit for all grafana-agent-operator created components, like the metrics and log collectors. If I'm right, resource limits/requests can be set via the GrafanaAgent custom resource object, however it seems, that it can only set the same limits for each object created by the operator:
https://doc.crds.dev/github.com/grafana/agent/monitoring.grafana.com/GrafanaAgent/v1alpha1@v0.22.0#spec-resources

Is it possible somehow to specify different limits/requests for different types of resources? Like settings different limits for log collector pods and metrics collector pods?

**Comment by rfratto** [comment]
Hi, at the moment the only way to specify custom requests/limits per created pod is to have multiple GrafanaAgent resources which discover a subset of all CRDs. For example, a GrafanaAgent which only discovers MetricsInstances and its related CRDs, and another which only discovers LogsInstances and its related CRDs. Then you could give each GrafanaAgent specific resources. 

The reasoning behind this limitation has been discussed briefly in #1348 and #1495.
