### ISSUE TITLE
[traces] Add support for experimental persistent queue feature from OpenTelemetry Collector

### ISSUE THREAD

**Issue by annanay25** [grafana/agent#1552]
The OpenTelemetry Collector project has implemented a (currently experimental) feature to allow buffering traces on disk in case the outbound connection to the backend dies out. I think this is super interesting -- it increases stability of the agent (no OOMs) and prevents loss of data (in memory buffer can only hold on to so much data) in case of network disruption to the backend.

This is a feature request to add support for the same to the Grafana Agent.

Reference: Persistent queue documentation https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md#persistent-queue

**Comment by yeya24** [comment]
I am interested in working on this issue

**Comment by mapno** [comment]
Hi @yeya24! That's great, it'll be interesting to see how it performs. Let us know if you need any help from our side.

**Comment by rfratto** [comment]
I'll remove keepalive from this, but if anyone is actively working on this let us know and we can re-add the keepalive label.
