### ISSUE TITLE
Update Loki dependency

### ISSUE THREAD

**Issue by splitt3r** [grafana/agent#1558]
It looks like https://github.com/grafana/loki/issues/1361 still exists in this project. The used Loki version (https://github.com/grafana/agent/blob/main/go.mod#L26) looks pretty old.

**Comment by rfratto** [comment]
Hi, the version string is misleading thanks to how Go handles non-semantically versioned projects.

We're using Loki SHA `295dc4ee3ae5` which is from 2022-03-09.
