### ISSUE TITLE
Upstream duplicate exemplar filtering

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1570]
#1316 introduced an enhancement to filter out duplicate exemplars when writing them to the WAL.

This change needs to be upstreamed to the Prometheus Agent codebase.

cc @tpaschalis @marctc

**Comment by tpaschalis** [comment]
In Grafana Agent, we opted to use a `stripeSeries` to store exemplars and deduplicate exemplars for each refID.

In contrast, Prometheus' TSDB, is using a [circular buffer](https://github.com/prometheus/prometheus/blob/1c1b174a8e98f5a97ba782b50f4eb9a09d3f9a8e/tsdb/exemplar.go#L118) for the storing exemplars in-memory. Just a point to keep in mind when upstreaming this, in case someone asks why keep two different ways of storing the exemplars. We didn't want to pre-allocate storage for the entire buffer, plus we don't need the extra functionality it contains (eg. querying for exemplars).

**Comment by rfratto** [comment]
@tpaschalis I'm going to assign to you since you did the original PR, but this isn't extremely urgent and can wait for you to have some free time :)

**Comment by tpaschalis** [comment]
The upstream PR is open at https://github.com/prometheus/prometheus/pull/10595.

I'll get into the habit of thinking how to keep us more closely aligned with Prometheus Agent. :)

**Comment by rfratto** [comment]
Closed by prometheus/prometheus#10595.
