### ISSUE TITLE
Out of date "Getting Started" instructions for tanka

### ISSUE THREAD

**Issue by amckinley** [grafana/agent#158]
I'm glad https://github.com/grafana/agent/pull/143 got merged, but it breaks the normal tanka workflow of `tk init && jb install <blah>`. Instead you have to follow [these](https://github.com/jsonnet-libs/k8s-alpha#usage) instructions, which I only stumbled across by reviewing this project's git history looking for things that might have introduced recent breakage 😛 

Since the install process is non-standard, maybe change the `README` to either include the `k8s-alpha` install process, or just link to it?

To make this issue more searchable for the next person, here's the exception I was getting before I figured out I needed to use `k8s-alpha`:
```
$ tk eval environments/default/
evaluating jsonnet: RUNTIME ERROR: Field does not exist: envVar
	/Users/austin.mckinley/robinhood/kubernetes-manifests/internal-tools/grafana-agent/vendor/grafana-agent/grafana-agent.libsonnet:37:7-23
	During manifestation
```

**Comment by amckinley** [comment]
(Oh, and you might want to add that the `jb install` command you need is `jb install github.com/grafana/agent/production/tanka/grafana-agent`, since I was stuck for a while assuming that `jb install github.com/grafana/agent` would work).

**Comment by rfratto** [comment]
Thanks for reporting this! You're more than welcome to contribute the docs change yourself, but I'll be able to spend some time updating the docs early next week.

**Comment by amckinley** [comment]
Sure, I'll put up a PR for that since I'm in the middle of messing with this anyway.
