### ISSUE TITLE
 "Edit this page" links from grafana.com/docs/agent are broken

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1587]
The "Edit this page" link from any document on the hosted Grafana Agent docs (such as the [upgrade guide](https://grafana.com/docs/agent/latest/upgrade-guide/)) produces a broken link. It links to `docs/` when it should link to `docs/user/`.

cc @brendamuir

**Comment by osg-grafana** [comment]
Please move the source files up a directory rather than change the website.

**Comment by osg-grafana** [comment]
cc @jdbaldry and @robbymilo

**Comment by robbymilo** [comment]
This is configurable on the website end. https://github.com/grafana/website/blob/master/content/docs/agent/_index.md?plain=1#L15 can be updated from `/docs` -> `/docs/user`.

I agree on point to standardize, however.

**Comment by rfratto** [comment]
@osg-grafana please don't edit the title of the issue when we're still discussing the solution.

**Comment by brendamuir** [comment]
Created PR as a workaround for this issue and fixed on the website repo: https://github.com/grafana/website/pull/8438. Now we have some time to discuss a solution for the wider issue of consistent source directories for agent docs.

**Comment by brendamuir** [comment]
Closing this issue as the immediate issue has been fixed and the larger issue is being tracked by Jack as per above.
