### ISSUE TITLE
Using latest agent image throws yaml syntax error

### ISSUE THREAD

**Issue by anwarchk** [grafana/agent#1625]
Based on the Grafana docs, I am trying to run the agent using this chart https://github.com/DandyDeveloper/charts/tree/master/charts/grafana-agent and it is referencing the latest image from grafana/grafana-agent. However, I am getting this error and the Daemonset fails to start:

`2022-04-18 19:08:22.868271 I | error loading config file /etc/agent/agent.yml: yaml: line 13: did not find expected alphabetic or numeric character`

**Comment by rfratto** [comment]
👋 that chart is maintained by the community and not by us, so we're enable to guarantee that it works between releases. 

What is the config file it generates that has an error?

**Comment by anwarchk** [comment]
That error is coming from the image `grafana/agent:latest`, which I assume is published by Grafana. The chart just references it. At the end the resulting command is `/bin/agent -config.file=/etc/agent/agent.yaml`. As you can see from the error above, the agent binary fails while trying to load the agent config file that is at /etc/agent

**Comment by anwarchk** [comment]
Turns out, based on this bug https://github.com/helm/helm/issues/9917, having a "*" instead of "" causes this issue with Helm. Sorry for the trouble and thank you for looking into this, even if it was not a issue related to this project.
