### ISSUE TITLE
Implement push model in grafana agent 

### ISSUE THREAD

**Issue by Ultrafenrir** [grafana/agent#1627]
Hi guys ! Grafana agent looks great as metric shipping agent , but it looks like as it stick to prometheus implementation there’re is a lack of protocols that grafana agent can accept. I just wondering how great will be if you will implement influxdb/graphite protocol receivers for pushing metrics  as vmagent did https://docs.victoriametrics.com/vmagent.html

**Comment by mattdurham** [comment]
Different protocols is something that we have talked about. It’s something we would like to investigate but it’s not something we plan on doing in the next few months.

**Comment by rfratto** [comment]
👋 Hey there! We do support pushing metrics in a few ways:

* v0.24.0 added support for [pushing Prometheus metrics](https://grafana.com/docs/agent/latest/api/#accept-remote_write-requests)
* We have a [statsd integration](https://grafana.com/docs/agent/latest/configuration/integrations/statsd-exporter-config/) for receiving statsd metrics over the network. 

Our primary focus is on the open source LGTM stack (Loki, Grafana, Tempo, Mimir). We're not opposed to supporting other protocols, but it's not something we've prioritized yet. We'd definitely be open to RFCs and helping out contributors to add new ingest formats. 

However, I do want to be careful when adding a new format. We should probably only consider formats that can be converted to Prometheus metrics without information loss: losing information in the conversion process might be seen as a subpar user experience.

**Comment by Ultrafenrir** [comment]
Thanks for the fast response. The main point for me is to have some agent with reliable state aka wal that can accept metrics from various subsystems by simple protocol. Remote write is really an good option , but for me it doesn’t  work. I think when u add influxdb protocol it will be outstanding feature that attract more users to the grafana agent and the whole stack as well ;)

**Comment by Ultrafenrir** [comment]
Actually , I find this exporter https://github.com/prometheus/influxdb_exporter So basically u can add it  as  integration instead of writing something embedded into the agent . It also solves the problem with UX as u just provide ability to integrate , not the new agent feature.

**Comment by rfratto** [comment]
We'd definitely be open to contributions for embedding the influxdb_exporter as an integration!  If you or anyone is looking into contributing that and needs guidance, please feel to reach out to us and we can assist.
