### ISSUE TITLE
Update windows_exporter with latest

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#1631]
Update windows_exporter with latest version of the community windows exporter

**Comment by mattdurham** [comment]
We use a forked version of the windows_exporter that is pretty different so merging is more involved.

**Comment by mattdurham** [comment]
It is currently at the back of the queue. I have no idea when it will be resolved. As far as merging the upstream when we do this we can take a look to see how far they diverged and if upstream is willing to take the changes.

**Comment by jkroepke** [comment]
I will also look into this, since I'm also interested into a updated windows exporter dependency. But I agree we with mattdurham that upstream changes are requires that can take a well and no one knows if they want to accept them.
