### ISSUE TITLE
grafana-agent-operator: support taints for DaemonSet-based scraping workloads

### ISSUE THREAD

**Issue by flokli** [grafana/agent#1636]
Assume you have a bunch of specialized kubernetes worker nodes, which don't run general-purpose workloads.

The canonical way to accomplish this is add a taint to the node, and let your special workloads tolerate the taint (and normally provide a node selector to select only these nodes).

This will prevent general-purpose workloads from getting scheduled on these nodes.

However, this will also cause grafana-agent pods from DaemonSets (Logs) to not get scheduled on these pods either, so you miss logs.

In the operator and its CRDs, there seems to be no way to express the fact that you want pods in the logs daemonset to tolerate such taints.

This might become unnecessary with https://github.com/grafana/agent/pull/1565 and https://github.com/grafana/agent/pull/1546, if the taints for the workload could be described in the helm chart that's deploying it.

**Comment by rfratto** [comment]
This might not be too difficult to add, depending on how we do it. 

If we allow tolerations to be specified for all managed controller objects (DaemonSet/Deployments/StatefulSets), it should be simple. 

However, if the idea is to specify tolerations that only apply to some of the controllers, it might need some more thought. #1495 discusses how the original intent was to leave the controllers being deployed as a hidden implementation detail, to allow for consolidating to a single controller once it's possible. Controller-specific tolerations should mark a deliberate deperature from that original intent, with a general plan for how controller-specific settings could tolerate #1495 being implemented.

**Comment by rfratto** [comment]
But like you said, given #1565 and #1546 this isn't likely something the core maintainers will spend time on until we know more what the future of the agent and operator looks like, though contributions are definitely welcome.

**Comment by flokli** [comment]
This is actually supported already - `GrafanaAgent` CRD already has a `nodeSelector` and `tolerations` field, and it'll correctly propagate through to the pod spec.

**Comment by noyoshi** [comment]
Hi, I have a similar situation as described by @flokli . I resolved it by using the tolerations field in the GrafanaAgent CR, but the issue is that by adding the toleration, it not only adds the toleration to the pods created to scrape logs, but the general GrafanaAgent itself. This is an issue since it blocks scaling down on specialized nodes that get the GrafanaAgent pod running on them (the daemonset obv doesn't prevent scaling down). This is essentially a hard blocker on us using the GrafanaAgent since we cannot guarentee that our specialized (and expensive) nodes will scale down properly.

**Comment by flokli** [comment]
That's indeed right. But looking at https://github.com/grafana/agent/issues/1636#issuecomment-1105448484, I doubt the existing CRDs will be extended to allow specifying different taints for the log collection daemonset pods and grafana-agent metrics scraping deployment pod.
