### ISSUE TITLE
pushing traces to kafka

### ISSUE THREAD

**Issue by Ultrafenrir** [grafana/agent#1648]
Hi folks! Guys that’s support tempo told me that it’s possible to push traces into the Kafka with grafana agent  and pull it with tempo on other side (https://github.com/grafana/tempo/issues/1412)  But I can’t find anything about that in grafana agent docs, could you clarify a bit more about this. (I found section about Kafka receiver , but it looks like it’s only for receiving spans  from Kafka, not for pushing).

**Comment by mapno** [comment]
Hey! The Grafana Agent support exporting otlp and jaeger only. Kafka is not supported. What it can do is consume from Kafka.

If you want to push to Kafka, you will need to use the opentelemetry receiver

```
otel collector -> kafka -> (otel collector | grafana agent | tempo ) -> tempo
```

**Comment by titaneric** [comment]
Do tempo developers have any plans to support this feature? We would like to send tracing data to kafka as well.
