### ISSUE TITLE
support for ssl_exporter

### ISSUE THREAD

**Issue by jamesalbert** [grafana/agent#1670]
Hi there 👋🏻  

In an effort to keep it short 😄  I would find it useful for grafana-agent to support [ssl_exporter](https://github.com/ribbybibby/ssl_exporter). Following contributing.md, I'm posting here to see if that's something the maintainers are okay with and if that's the case to claim that contribution. Let me know!

**Comment by mattdurham** [comment]
Absolutely go for it. The snmp_exporter would be the best place to start, we are switching to a new way of handling exporters and if I was in your shoes I would target that one [first](https://github.com/grafana/agent/tree/main/pkg/integrations/v2/snmp_exporter). Feel free to jump into the community channel `https://slack.grafana.com/ #agent `, I am `@mattd` there

**Comment by jamesalbert** [comment]
Awesome y'all, sounds good 👍🏻  will see what I can get cooked up

**Comment by marctc** [comment]
Closing as the PR also got closed due inactivy. @jamesalbert feel free to reopen once you work on this again, thanks!
