### ISSUE TITLE
instance default does not exist when enable Integrations Revamp

### ISSUE THREAD

**Issue by cngdkxw** [grafana/agent#1674]
integrations config
`integrations:
  agent: {}
`

startup command
`./agent-darwin-amd64 -config.file agent-config.yaml -enable-features=integrations-next`

running logs
`ts=2022-05-04T16:12:52Z level=info caller=traces/traces.go:135 msg="Traces Logger Initialized" component=traces
ts=2022-05-04T16:12:52.280081Z caller=integrations.go:138 level=warn msg="integrations-next is enabled. integrations-next is subject to change"
ts=2022-05-04T16:12:52.280746Z caller=autoscrape.go:122 level=error component=autoscraper msg="cannot autoscrape integration" name=agent/MBP.lan:12345 err="instance default does not exist"
ts=2022-05-04T16:12:52.280822Z caller=main.go:57 level=error msg="error creating the agent server entrypoint" err="configuring autoscraper failed: instance default does not exist"
`

**Comment by zlepper** [comment]
@cngdkxw I'm also getting this with another integration, what did you do to fix it?
