### ISSUE TITLE
Flow component for mutating targets

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1683]
This is the counterpart to #1680; there should be a component in Flow which can mutate discovered targets, dropping specific targets or changing their labels. 

Like #1680, for the initial implementation, it is recommended that the configuration for this component matches Prometheus relabeling rules, where you can provide multiple relabel configs in the component's config block.

The name of this component also needs some thought, as an exercise to the implementor.

**Comment by tpaschalis** [comment]
Reopening the issue. Might be able to close it after documentation on the new component has been added.
