### ISSUE TITLE
Flow component for windows_exporter

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1685]
In addition to #1684, it would be beneficial to have a windows_exporter component so that we make sure Flow works on Windows. 

It is not yet obvious how these components will expose metrics. The prototype had an [integration.github](https://github.com/grafana/agent/blob/agent-flow/expressions/component/integration/github/github.go) component which exported an integration-specific metrics endpoint as its state.

The implementation of this component may do something similar, or it may push scraped metrics directly to a receiver. It is up to the discretion of the implementor to weigh the trade offs and pick a path forward, though it should be noted that the chose made will likely influence how other exporter components are implemented.

It is recommended to re-use the existing windows_exporter integration code as much as possible for building this component.

**Comment by marctc** [comment]
Fixed in #3547
