### ISSUE TITLE
Window agent failed to start up after window update.

### ISSUE THREAD

**Issue by habitappaing** [grafana/agent#1690]
Version : v0.24.2

Error:
panic: ReqQueryValueEx failed: The system cannot find the file specified. errno 2                                                                                                                                                                   goroutine 1 [running]:                                                                                                    github.com/leoluk/perflib_exporter/perflib.QueryNameTable({0x4701c2d, 0xb})                                                       /go/pkg/mod/github.com/grafana/perflib_exporter@v0.1.1-0.20211013152516-e37e14fb8b0a/perflib/nametable.go:43 +0x257                                                                                                                         github.com/leoluk/perflib_exporter/perflib.init.0()                                                                               /go/pkg/mod/github.com/grafana/perflib_exporter@v0.1.1-0.20211013152516-e37e14fb8b0a/perflib/perflib.go:266 +0x29  
![image](https://user-images.githubusercontent.com/98567767/166861755-e7781c7b-659b-4808-8daa-67166b7f5d57.png)

**Comment by nick-wvu** [comment]
What was done to get it working? I'm receiving the same error.
