### ISSUE TITLE
Enhance agent with NATS exporter

### ISSUE THREAD

**Issue by nikakis** [grafana/agent#1704]
Would you consider a PR for enhance [NATS-exporter](https://github.com/nats-io/prometheus-nats-exporter)?

**Comment by nikakis** [comment]
Great! I will start it asap. Thanks!

**Comment by mytototo** [comment]
Any news regarding support for NATS on the agent?

**Comment by mytototo** [comment]
Awesome! Thank you very much.

**Comment by garethparris** [comment]
Any news on this?

**Comment by nikakis** [comment]
I will try to  work on this during the next days
