### ISSUE TITLE
Flow: support for reading file contents

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1725]
Grafana Agent Flow should allow users to read files from disk. This can be used for any string, but most commonly will be used to read passwords or API keys. 

There are two ways this can be implemented: as a component, or as a function. 

### Component approach 

The `local.file` component will read & watch a file from disk, updating its exports whenever the file changes. 

It is crucial that the `local.file` component can be marked as sensitive so that its value does not appear at the `/-/config` endpoint.  

```hcl 
local "file" "some-api-key" {
  path      = "./some-api-key.txt"
  sensitive = true 
}
```

### Function approach 

The `file` function will return the latest contents of a file. The file will be watched for changes, and cause components using it to have their arguments re-evaluated. 

```hcl 
file("./some-api-key.txt") 
```

### Pros / Cons 

Pros for component: 

* Easily implementable as a component 
* Fits in well with the `remote.*` components

Pros for a function: 

* Way less tedious for users to load many secrets from many files, which is likely a common use case. 
* Because the function isn't a separate component, you wouldn't need to mark it as sensitive, and its value will be hidden by default if being assigned to a secret field. 

## Proposed path 

Whatever we pick can be changed down the line. 

I think functions make more sense than components if the user is going to define many of them for one-off use cases. Components should be re-usable; functions should be more limited. I think we're bound to eventually have component-like functions: they encapsulate some logic and can change their resulting value over time.

However, since we are going to have `remote.*` components, it probably makes the most sense to have `local.file` exist as a component too. 

Function-like components can remain as a potential solution for some other problem, like a function for checking ownership of a key within a cluster which is re-evaluated when the cluster changes.

**Comment by mattdurham** [comment]
I like components for this, I think of `functions` as transformations. Components also give us far more configuration knobs, instead of using a bunch of arguments. 

I assume components are easier/cheaper to "cache" the result if it is an expensive operation. Functions could do that but that moves that responsibility to the control plane/language which feels harder to upkeep.

**Comment by tpaschalis** [comment]
Not opposed to any of the options here, here's my 2c. 

Initially a function sounded clearer to me at first (similar use-cases to how we have a function that loads environment variables), but after reading your opinions and thinking about it, I'm also inclined towards a component. 

In my mind, a component would also tie better to the 'graph'-like configuration that we ultimately want to achieve.
