### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by scriptcoded** [grafana/agent#1726]
Hey!

As a result of #1715 a few links to the old production/README.md have broken. These are the two places I've stumbled upon broken links, but I'm sure there might be more:

- The link to the _"full instructions"_ here: https://grafana.com/docs/grafana-cloud/agent#installing-the-binary-directly-without-our-script-for-all-other-use-cases
- The readme of this very repository, _"Other installation methods can be found in our [Production](https://github.com/grafana/agent/blob/main/production/README.md) documentation."_: https://github.com/grafana/agent#getting-started

I assume these links should go to this page instead: https://grafana.com/docs/agent/latest/set-up

**Comment by tpaschalis** [comment]
Thanks for letting us know Malcolm! cc @brendamuir
