### ISSUE TITLE
metrics with colons in the __name__ stop working after applying write_relabel_configs

### ISSUE THREAD

**Issue by IT-Luka** [grafana/agent#1730]
I'm trying to cut down on the number of active metrics, so I followed [this guide](https://grafana.com/docs/grafana-cloud/metrics-control-usage/control-prometheus-metrics-usage/usage-analysis-mimirtool/).

I've tried allowlisting used metrics, and denylisting unused ones, but in both cases metrics with colons in their names like node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate stop working (no data), while metrics without colons in their name work as expected.

Steps to reproduce:
- Set up the Kubernetes integration
- Metrics with colons in their name work as expected
- Generate a list of used metrics with mimirtool by following [this guide](https://grafana.com/docs/grafana-cloud/metrics-control-usage/control-prometheus-metrics-usage/usage-analysis-mimirtool/) :
`

          write_relabel_configs:
            - source_labels: [__name__]
              regex: container_fs_reads_bytes_total|container_fs_reads_total|container_fs_writes_bytes_total|container_fs_writes_total|container_memory_rss|container_network_receive_bytes_total|container_network_receive_packets_dropped_total|container_network_receive_packets_total|container_network_transmit_bytes_total|container_network_transmit_packets_dropped_total|container_network_transmit_packets_total|kube_node_status_allocatable|kube_pod_owner|machine_memory_bytes|namespace_cpu:kube_pod_container_resource_limits:sum|namespace_cpu:kube_pod_container_resource_requests:sum|namespace_memory:kube_pod_container_resource_limits:sum|namespace_memory:kube_pod_container_resource_requests:sum|namespace_workload_pod:kube_pod_owner:relabel|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|node_namespace_pod_container:container_memory_rss|up
              action: keep

`
- Apply, rollout restart grafana-agent
- Metrics with colons in their name stop working, others work as expected
- Use mimirtool to create a list of unused metrics, and create a denylist
- Apply, rollout restart grafana-agent
- Same result as when using an allowlist

I've also tried using less precise regex for those metrics, but no luck.

**Comment by rfratto** [comment]
Hey there! Sorry for the delay in responding to you. 

`node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate` looks like it's referring to a recording rule, which wouldn't be generated by Grafana Agent, and instead generated by Mimir itself. 

You might be excluding metrics which the recording rule uses to create `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate`, which could be why it disappears after applying your write_relabel_configs here.
