### ISSUE TITLE
Operator Helm Chart Test Resources

### ISSUE THREAD

**Issue by allir** [grafana/agent#1786]
When installing the Grafana Agent Operator via Helm Chart one of the test resources doesn't have the helm hook to mark it as a test resource and therefore ends up being a part of the installation.

I've put in a PR that highlights where the issue is and fixes it: https://github.com/grafana/helm-charts/pull/1470

**Comment by tpaschalis** [comment]
Thanks you for the report! cc @captncraig @hjet who may have more insight around the helm charts here.

**Comment by rfratto** [comment]
It looks like this is a dupe of #1650; I'm going to close this in favor of that one and mention your PR there. Thank you!
