### ISSUE TITLE
Document configuring command line flags for operator managed agent

### ISSUE THREAD

**Issue by stevo-f3** [grafana/agent#1798]
Please cover in https://grafana.com/docs/agent/latest/operator/custom-resource-quickstart/ or related document an example configuring agent flags https://grafana.com/docs/agent/latest/configuration/flags/

If configuring agent flags is not supported at the moment, please add the support.

**Comment by stevo-f3** [comment]
Depends on https://github.com/grafana/helm-charts/issues/1495 ?

**Comment by marctc** [comment]
Hey @stevo-f3, I'm currently looking into this. Just to confirm, are you asking that all configurable flags that agent has could be also set to an agent deployed using the operator?

**Comment by marctc** [comment]
I'm closing the ticket due inactivity, we can reopen if the issue is still relevant.
