### ISSUE TITLE
Add integration usage to telemetry

### ISSUE THREAD

**Issue by RutgerKe** [grafana/agent#1830]
Recently, in https://github.com/grafana/agent/issues/1488, some telemetry data was introduced.

I propose to leverage this feature to get a better grip on the usage of integrations in the agent. Which integrations are configured? How many metrics do they collect, how many logs? This could for example be an average over the currently used reporting-interval.

**Comment by RutgerKe** [comment]
>I don't like the idea that more information could start being collected by the agent simply because someone at Grafana might find it useful.

Could you elaborate on your concerns?

>Do we document what information is collected anywhere? Is there any process or approval required to add something besides getting code merged?
 
Fair points, I don't know of any process right now, but agree that would be good. As part of this feature I think there should at least be clear documentation on what is collected. I'll let the agent maintainers comment further on this.

>This seems to be an increase in scope from the original intent of this feature:

Why do you think this increases the scope? The integrations are part of the agent, and using them would be an indication that users find them 'helpful'.

**Comment by rfratto** [comment]
Personally, I'm comfortable adding more usage information as long as we:

* Continue to document what we collect
* Continue to document how to disable collection clearly in an obvious location 
* Clearly document when the things we collect changes between releases 
* Continue to only collect anonymous information 

I do agree that integration usage info could be helpful in the same way that experimental feature usage info is helpful, and I think it's ok to broaden the scope as long as we're extremely transparent about doing it and why we're doing it.
