### ISSUE TITLE
Corrupt WAL Removal

### ISSUE THREAD

**Issue by rlankfo** [grafana/agent#1838]
## Problem

WAL Corruption can occur when the agent is terminated while latest segments are being flushed to disk, such as when an OOM kill occurs, or the host running the agent is hard shutdown. 

Upon restarting with a corrupt WAL, the Agent will attempt to repair the WAL by removing the corrupt segments and any records created since.  In some cases, corruption repair may be unsuccessful.  When this occurs, the Agent may continuously attempt to repair the WAL unsuccessfully, which will result in data loss. Recovery from this state is a manual process.

### Manual Recovery Steps

1. Stop the Agent
2. Delete the WAL from disk
3. Restart the Agent

## Proposal

For some users, when these cases occur, the preferred behavior would be to have the Agent automatically delete the WAL to avoid manual intervention. I’m proposing that we add this functionality behind a feature flag. 

The following feature could be passed if a user wishes to opt in to this behavior:
`-enable-features=corrupt-wal-removal` 

When this feature is enabled, the Agent should remove the corrupt WAL after a failed attempt to repair.

**Comment by mattdurham** [comment]
Thoughts on making it the default? Is their a remedy for a corrupt WAL aside from deletion?

**Comment by marctc** [comment]
> The only remedy I'm aware of is deletion

We could just add this behavior by default and no need to specify any flags
