### ISSUE TITLE
Possible deadlock while truncating the WAL and adding a new series at the same time

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#184]
It is possible for a deadlock to happen when a truncation is running at the same time as a new series being added. 

The WAL gc process works as such:

1. Iterate over each series stripe, obtaining a lock on the shared mutex stripe. 
2. Lookup the hash stripe, obtaining a lock on the shared mutex stripe if it is on a different stripe than is currently locked. 
3. Delete the series and hash.
4. Release the lock on the hash stripe, if obtained. 
5. Release the lock on the series stripe. 

When a new series is added, we check to see if a series with that hash already exists:

1. Obtain a lock on the hash stripe. 
2. Lookup the series stripe, obtaining a lock on the shared mutex stripe if it is on a different stripe than is currently locked. 
3. Return the series if it exists. 
4. Release the lock on the series stripe, if obtained. 
5. Release the lock on the hash stripe. 

Fundamentally, the problem is that the WAL can not have two concurrent goroutines that can both lock the same mutex more than once. It is OK for the gc process to lock two different stripes, but no other goroutine must do the same. 

Prometheus does not have this problem because their series hashmap points to a series rather than a ref ID. To fix the problem in the Agent, the `seriesHashmap` should point to a `memSeries` and each `memSeries` should store their labels. 

Credit to @amckinley for discovering this issue.

**Comment by amckinley** [comment]
Followup note: upgrading to v0.6.0 doesn't fix this issue.
