### ISSUE TITLE
Publish docker image for Windows architecture

### ISSUE THREAD

**Issue by basvdl** [grafana/agent#1847]
For sending logs from Kubernetes nodes running Windows to the Grafana Cloud, I had to create a Docker image with the Grafana agent binary for Windows.

Would it be possible for Grafana to host a Windows docker image with the Grafana Agent Windows executable?

```
FROM mcr.microsoft.com/windows/servercore:ltsc2019
RUN mkdir C:\agent
WORKDIR "C:\agent"
COPY agent-windows-amd64.exe C:\agent\
ENTRYPOINT ["agent-windows-amd64.exe"]
CMD ["--config.file=C:\agent\agent.yaml" "--metrics.wal-directory=C:\agent\data"]
```

**Comment by rfratto** [comment]
Closing this in favor of #646 which is tracking the same thing.
