### ISSUE TITLE
Flow: consider removing singleton component concept

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1861]
The initial implementation of the Flow controller allows components to register themselves as "singletons," meaning only one of that component may be instantiated:

https://github.com/grafana/agent/blob/80ae7af17ad8ca772cef0f36b3e51c0e3919ad54/component/registry.go#L85-L106

This was introduced because some integrations only support existing once per process:

* agent 
* cAdvisor 
* eventhandler
* node_exporter
* process_exporter
* snmp_exporter
* statsd_exporter
* windows_exporter

I think the singleton component will cause long-term problems, especially around if we ever wanted to support modules, which seems inevitable: two modules that both launch node_exporter with different settings will conflict, and one will be rejected based on load order. 

I think we should slowly invest effort in:

1. Determining which of these integrations breaks if more than one exists per process (I know node_exporter and cAdvisor do due to using global flags to function)
2. Ensuring that the Flow components of these integrations do not function as singletons 
3. Removing the singleton flag from component registration

This is probably a blocker for Flow leaving experimental. Alternative suggestions are welcome for how we can potentially avoid conflict for modules (which although unplanned at the moment, feel inevitable for Flow).

Integrations which need updates to support multiple instances:

- [ ] cAdvisor  
- [ ] node_exporter 

List of integrations which could support multiple instances today: 

* agent 
* eventhandler

List of integrations which need investigation:

* process_exporter
* snmp_exporter
* statsd_exporter
* windows_exporter

**Comment by tpaschalis** [comment]
cc @rfratto @captncraig while looking at #2095, I realised that when we moved from HCL to using River throughout the controller in #1954, we lost the handling around `Singleton` field.

Right now, it's not being utilised anywhere and for example, you can have two instances of `prometheus.integrations.node_exporter` at the same time. Does this make it any more pressing to figure out a solution?

**Comment by rfratto** [comment]
Singleton components aren't allowed in the context of modules, which would prevent remove configuration of components like `prometheus.exporter.unix`. That's all the more reason, IMO, to replace all singleton components with non-singletons and remove the flag.

**Comment by marctc** [comment]
After merging cadvisor and unix flow components removing Singleton, I think we can close this issue. I didn't see any references of Singleton in main.
