### ISSUE TITLE
Grafana Agent Windows - cant disable built in http server neither grpc

### ISSUE THREAD

**Issue by dvaguirre** [grafana/agent#1902]
To scrap from windows_exporter until can run without SYSTEM (administrative privileges)

**Comment by mattdurham** [comment]
Can you elaborate on what you're indicating here?

**Comment by dvaguirre** [comment]
I cant disable the built in exporter from startup parameters or yaml file, to scrap from another exporter installed on the same machine.

![image](https://user-images.githubusercontent.com/78813891/178822370-d4efd470-20f7-4656-9bf0-fa319917cac8.png)

**Comment by mattdurham** [comment]
By default that only listens to localhost, there is no way to disable.

**Comment by tpaschalis** [comment]
You can enable and disable the exporter from your YAML config file, as described [here](https://grafana.com/docs/agent/latest/configuration/integrations/windows-exporter-config/). The Agent can either be configured to autoscrape its own integration, or scrape an external exporter installed on the same machine.

The address you're highlighting here is the Agent's own HTTP API endpoint. As Matt said, it only listens on localhost and you can read more about it [here](https://grafana.com/docs/agent/latest/api/#agent-api).

**Comment by dvaguirre** [comment]
tks, ll close this issue
