### ISSUE TITLE
Version v0.26.0 Broken on CentOS Linux release 7.9.2009 (Core)

### ISSUE THREAD

**Issue by kmf** [grafana/agent#1923]
# download the binary
```
curl -O -L "https://github.com/grafana/agent/releases/download/v0.26.0/agent-linux-amd64.zip"
```

# extract the binary
```
unzip "agent-linux-amd64.zip"
```

# make sure it is executable
```
chmod a+x "agent-linux-amd64"
```

```
 ./agent-linux-amd64
./agent-linux-amd64: error while loading shared libraries: libbcc.so.0: cannot open shared object file: No such file or directory
```

**Comment by tpaschalis** [comment]
Hey Karl, thanks for the heads-up.

This might have to do with the way we're packing the eBFP exporter (we should be including the bcc tooling in the build stage). Let me check it out.

**Comment by stephan-vollmer** [comment]
Same issue with `grafana-agent-0.26.0-1.amd64.deb` on Ubuntu 18.04.6 LTS. 

**Output of `uname -a`:**
```
Linux obcs690 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
**Version of binutils:** `2.30-21ubuntu1~18.04.7`

**Comment by tpaschalis** [comment]
Apologies, we'll be working for a fix as soon as possible.

I know it isn't exactly the same but if it's an emergency, you could either use the v0.26 Docker image (which doesn't have the same issue) or build the Agent from source while providing the `-tags=noebpf` flag.

For reference, this affects binaries running on AMD64 systems, which don't have the libbpfcc bindings installed.

**Comment by tpaschalis** [comment]
We'll soon be pushing out a new v0.26.1 patch release, with new binaries that do not require the bcc toolkit to be installed.
