### ISSUE TITLE
Publish on homebrew for macs

### ISSUE THREAD

**Issue by tomwilkie** [grafana/agent#193]
Please :-)

**Comment by inf0rmer** [comment]
Homebrew/homebrew-core#66723

**Comment by inf0rmer** [comment]
We ended up publishing to our [own cask](https://github.com/grafana/homebrew-grafana/pull/9).

**Comment by rfratto** [comment]
This needs some docs in this repo for installing the formula before we can close this IMO

**Comment by bboles** [comment]
FYI this showed up in `homebrew-core` a few days ago:
https://github.com/Homebrew/homebrew-core/commits/master/Formula/grafana-agent.rb

**Comment by rfratto** [comment]
Oh interesting! Thanks for the heads up, lovely to see it in core.

**Comment by bboles** [comment]
@rfratto can you comment on the recommended Homebrew formula to use?  There are formulas for both the agent and server in https://github.com/grafana/homebrew-grafana and https://github.com/Homebrew/homebrew-core and both have recent commits.

**Comment by rlankfo** [comment]
Here's the homebrew-core PR for posterity: https://github.com/Homebrew/homebrew-core/pull/92578

Once this gets merged🤞, I'll sync this to homebrew-grafana.

**Comment by bboles** [comment]
Nice, thanks for the quick response @rlankfo !
