### ISSUE TITLE
Update Prometheus and Loki dependencies to latest releases

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1930]
Prior art: #1870 , #1895 

The latest Loki release requires updating Prometheus, so updating both will need to be done in a single PR.

**Comment by rfratto** [comment]
For #1820, we should update Loki to a weekly release which contains https://github.com/grafana/loki/pull/6135, since it's not in the latest tagged release and tagged releases are uncommon.

**Comment by jmherbst** [comment]
Any estimation on when a Loki update will be pulled in?  I'm interested in using the agent for the [heroku_drain](https://github.com/grafana/loki/blob/main/docs/sources/clients/promtail/configuration.md#heroku_drain)

**Comment by rfratto** [comment]
The Loki update happened in v0.28; the Prometheus update will be released in v0.29.0. Closing as done.
