### ISSUE TITLE
Use -config.expand-env when running grafana agent by default

### ISSUE THREAD

**Issue by mshahzeb** [grafana/agent#1943]
We have a number of integrations where we would like to have the hostname of the machine automatically populated in the agent config file using `${HOSTNAME}` with `-config.expand-env`.

For example as reported internally here:
https://github.com/grafana/cloud-onboarding/issues/1979

It is suggested to use `-config.expand-env` by default in the deb/rpm/windows packages of the agent.

Looking at the documentation it doesent seem that enabling it by default will have any negative consequences.
https://github.com/grafana/agent/blob/8d090877f2bd6bb47052ee420cc2e8720b25dde6/example/docker-compose/agent/config/agent.yaml#L12

However if it is not enabled then we would need to ask users using the integration to edit their service files which defeats the purpose of giving the customers easy to setup integrations.

**Comment by mshahzeb** [comment]
Corresponding files that would need changing:

For deb & rpm
https://github.com/grafana/agent/blob/1fda90adc917c8d107e2e2a0207611adc43222b4/packaging/environment-file#L13

For windows
https://github.com/grafana/agent/blob/1fda90adc917c8d107e2e2a0207611adc43222b4/packaging/environment-file#L13

**Comment by rfratto** [comment]
I'm not against enabling them by default, but would it be possible for the installation scripts used by Grafana Cloud to enable them instead?

**Comment by mshahzeb** [comment]
I think through the install scripts we would have to update the environment file and add -config.expand-env (in case of linux) using sed or something similar.

Any other thoughts or ideas on how to do it with the install script here?

The sed step to modify the environment default file can be added here after this step before enabling the service:
https://github.com/grafana/agent/blob/0a3d59ce45ec2cb5d6cda0267c62e2e8099a37de/production/grafanacloud-install.sh#L78

**Comment by mshahzeb** [comment]
Opening up for conversation again to mark it as not stale.

**Comment by ToonTijtgat2** [comment]
+1.
It would be nice if it's possible to run the windows installer of the grafana agent with a parameter to create the windows service with the -config.expand-env parameter
