### ISSUE TITLE
Allow settings for keep alives and idle connection timeouts for scrape configs

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#1953]
Allow the usage of custom keep alive duration for scrape configs (both normal and scraping service). This hopefully can be done via the custom DialerFunc

**Comment by mattdurham** [comment]
Ideally should be able to pass to the `instance.go:newScrapeManager`

**Comment by rfratto** [comment]
We can't use the custom DialerFunc, but we can use `config.WithKeepAlivesDisabled` and `config.WithIdleConnTimeout` from prometheus/common/config.

**Comment by jnyi** [comment]
Is there any process on this one, we are seeing `404 not found` issue with kubernetes API for kubelet proxy: https://stackoverflow.com/questions/49275380/node-proxy-404-page-not-found, if we could disable keep alives for the connection and idle conn timeout, hopefully this could be mitigated.
