### ISSUE TITLE
OTLP trace receiver not working

### ISSUE THREAD

**Issue by giuliohome** [grafana/agent#1977]
My code to send an OTLP trace is [on github](https://github.com/giuliohome/pytest-otel-jaeger-kubernetes/blob/grafana-cloud/myinstr.py) .

Tried to feed the agent and send to Tempo local or in Cloud but it doesn't work (I also [texted about this](https://grafana.slack.com/archives/C01050C3D8F/p1659118485880999) on Slack).

I resolved the issue by using an standard OTEL collector instead of the Agent, as per the very helpful @mdisibio [blog post in Grafana Labs ](https://grafana.com/blog/2021/04/13/how-to-send-traces-to-grafana-clouds-tempo-service-with-opentelemetry-collector/). I'm happy with this solution. If it's by design, please close this issue but notice and consider that in your Agent documentation (see [here](https://grafana.com/docs/tempo/latest/getting-started/?pg=oss-tempo&plcmt=resources#2-pipeline-grafana-agent) and [this](https://grafana.com/blog/2020/11/17/tracing-with-the-grafana-cloud-agent-and-grafana-tempo/) blog) they say it can receive OTLP traces using grpc or http protocol.

**Comment by giuliohome** [comment]
I don't know why @cfstras closed his [similar issue](https://github.com/grafana/agent/issues/1643) but my understanding is that Grafana Agent only accepts Prometheus emitted Histograms with [examplars](https://grafana.com/blog/2022/02/23/introducing-exemplar-support-in-grafana-cloud-tightly-coupling-traces-to-your-metrics/#how-to-get-started-with-exemplars):

> Your applications need to include those trace IDs in their calls to emit metrics

The point is that my simple app only emits traces and does not include the trace id in any metrics, I guess this is why the Agent doesn't receive such traces, that are standard opentelemetry traces though. Indeed they can be received (and sent wherever, including Grafana Coud) thanks to an opentelemetry collector, instead of the agent, as already explained above.

**Comment by cfstras** [comment]
My main error was trying to test the gRPC endpoint with curl -- which won't work. So as long as your OTLP receiver config has the gRPC port enabled, and the `insecure` flag active, it should work without certificates.
Exemplars should not be necessary, my apps certainly don't generate any.

It might be helpful if you post the config you use for grafana agent, and the exact URL you set your trace exporter to.

**Comment by giuliohome** [comment]
Hello sir, thanks for your help, I'm surprised you say the Agent works without exemplars. I resorted to the standard OTEL collector and I'm happy with it but surely I want to learn what I did wrong and I really appreciate your help if you can (no worries otherwise). I published all my kubernetes files (well, I started with docker-compose, then I moved to kubernetes to double check, it's more or less the same thing, we can easily switch from one to another. The only think I obscured is my grafana key (lol, actually published it, but then rewrited git history, last commit). Ok so they are in the [grafana-cloud branch](https://github.com/giuliohome/pytest-otel-jaeger-kubernetes/tree/grafana-cloud) of my last public repo. In particulare you ask about the OTLP receiver port (I assume you are speaking about the grafana agent, correct? because with the pure otel collector I said it's ok), so that files in k8s is this [configmap](https://github.com/giuliohome/pytest-otel-jaeger-kubernetes/blob/grafana-cloud/otel-collector-config-yaml-configmap.yaml). Ehm, actually there is no insecure flag active, ops! Now, to save money, I destroyed the kuberenetes cluster, so I will copy the docker agent config of your issue and I will proceed with docker-compose. I will add that insecure flag there (in your initial comment you didn't include it indeed). I will comment again when done. Hopefully this should be the solution, in any case thank you very mucha gain for your help!!! very much appreciated!!!

**Comment by giuliohome** [comment]
Ehm, I am running your exact cmd:
```
docker run -it --rm -p 4317:4317 -p 4318:4318 -p 12345:12345 -v $(pwd):/cfg:ro grafana/agent:v0.24.1 -config.file=/cfg/config.yaml
```
with the only change in your config.yaml being adding an `insecure` flag

```
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
              insecure: true
            http:
              endpoint: 0.0.0.0:4318
```
but docker-compose complains:
```
ts=2022-08-01T09:37:19.394972941Z caller=main.go:57 level=error msg="error creating the agent server entrypoint" err="failed to create tracing instance integrations: failed to create pipeline: failed to load otelConfig from agent traces config: failed to load OTel config: error reading receivers configuration for \"otlp\": 1 error(s) decoding:\n\n* 'protocols.grpc' has invalid keys: insecure"
giuliohome@DESKTOP-5Q65LFI:~/grafana/
```
**Notice also that in my working otel collector, there is no insecure flag activated in the receiver part.**

**Comment by giuliohome** [comment]
> It might be helpful if you post the config you use for grafana agent, and the exact URL you set your trace exporter to.

It would be the same I'm using in the otel collector, so I would use the following in the agent to send to Grafana Cloud

```
traces:
  configs:
  - name: default
    remote_write:
      - endpoint: tempo-eu-west-0.grafana.net:443
        basic_auth:
          username: <MyUser>
          password: <MyKey>
```
or I would put insecure for an internal destination, but neither is working for me.

**Comment by giuliohome** [comment]
In conclusion - AFAICS - I would still claim that the Agent remote write would not work without Prometheus metric exemplars, as opposite to the standard opentelemetry collector.

**Comment by rfratto** [comment]
Could you paste your entire agent config which doesn't work, scrubbing out credentials?

The tracing parts of Grafana Agent use OpenTelemetry Collector internally, and it should work for forwarding OTLP trace data to an OTLP endpoint.

**Comment by giuliohome** [comment]
**Hello @rfratto , very pleased to meet you!** 
(minor note, I understand that Grafana Agent uses Otel Collector internally, but in the pure Otel Collector I have the exporters section, in Grafan Agent I have the remote_write, they seem to do different things... anyway, I reply to your question).

Assumning a docker-compose situation, the agent.yaml (or config.yaml) is this

```
server:
  http_listen_port: 12345
  log_level: debug
traces:
  configs:
    - name: integrations
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      remote_write:
        - endpoint: tempo-eu-west-0.grafana.net:443
          basic_auth:
            username: 201581
            password: <my API key>

```
then I run 
docker run -it --rm -p 4317:4317 -p 4318:4318 -p 12345:12345 -v $(pwd):/cfg:ro grafana/agent:v0.24.1 -config.file=/cfg/config.yaml
on an ubuntu window 

```
docker run -it --rm -p 4317:4317 -p 4318:4318 -p 12345:12345 -v $(pwd):/cfg:ro grafana/agent:v0.24.1 -config.file=/cfg/config.yaml
```
and on another I call my [myinstr.py](https://github.com/giuliohome/pytest-otel-jaeger-kubernetes/blob/grafana-cloud/myinstr.py) python like that
```
python3 myinstr.py  http://localhost/v1/traces go-cloud
```

**Comment by rfratto** [comment]
Thanks! Can you also post the OpenTelemetry Collector config which did work for you?

> but in the pure Otel Collector I have the exporters section, in Grafana Agent I have the remote_write, they seem to do different things... anyway, I reply to your question

That's true, at the time we called the section `remote_write` because we wanted to be consistent with how metrics is configured, but the remote_write section for traces gets transformed into a config for an OTLP exporter.

**Comment by giuliohome** [comment]
The  OpenTelemetry Collector config which did work for me.

```
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
  otlp:
   endpoint: tempo-eu-west-0.grafana.net:443
   headers:
     authorization: Basic MyToken

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
```

MyToken is obtained following the instructions of the mentioned blog:

```
$ echo -n "<your user id>:<your api key>" | base64
```

The command to run docker 

```
docker run -it --rm -p 4317:4317 -p 4318:4318 -p 12345:12345 -v $(pwd):/cfg:ro otel/opentelemetry-collector-contrib-dev:latest --config=/cfg/otel-config.yaml
```

The command to run myinstr.py is the same as above.

Full output of docker until I break it

```
docker run -it --rm -p 4317:4317 -p 4318:4318 -p 12345:12345 -v $(pwd):/cfg:ro otel/opentelemetry-collector-contrib-dev:latest --config=/cfg/otel-config.yaml
2022/08/01 16:23:16 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/08/01 16:23:16 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
2022-08-01T16:23:16.125Z        info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "otlp"}
2022-08-01T16:23:16.125Z        info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "logging"}
2022-08-01T16:23:16.126Z        info    builder/pipelines_builder.go:224        Pipeline was built.     {"kind": "pipeline", "name": "traces"}
2022-08-01T16:23:16.126Z        info    builder/receivers_builder.go:226        Receiver was built.     {"kind": "receiver", "name": "otlp", "datatype": "traces"}
2022-08-01T16:23:16.126Z        info    service/telemetry.go:109        Setting up own telemetry...
2022-08-01T16:23:16.127Z        info    service/telemetry.go:129        Serving Prometheus metrics      {"address": ":8888", "level": "basic", "service.instance.id": "4fb5c53c-db2d-4a77-9868-825863a6c190", "service.version": "latest"}
2022-08-01T16:23:16.127Z        info    service/service.go:76   Starting extensions...
2022-08-01T16:23:16.127Z        info    service/service.go:81   Starting exporters...
2022-08-01T16:23:16.127Z        info    builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "otlp"}
2022-08-01T16:23:16.128Z        info    builder/exporters_builder.go:48 Exporter started.       {"kind": "exporter", "name": "otlp"}
2022-08-01T16:23:16.128Z        info    builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "logging"}
2022-08-01T16:23:16.128Z        info    builder/exporters_builder.go:48 Exporter started.       {"kind": "exporter", "name": "logging"}
2022-08-01T16:23:16.128Z        info    service/service.go:86   Starting processors...
2022-08-01T16:23:16.128Z        info    builder/pipelines_builder.go:54 Pipeline is starting... {"kind": "pipeline", "name": "traces"}
2022-08-01T16:23:16.128Z        info    builder/pipelines_builder.go:65 Pipeline is started.    {"kind": "pipeline", "name": "traces"}
2022-08-01T16:23:16.128Z        info    service/service.go:91   Starting receivers...
2022-08-01T16:23:16.129Z        info    builder/receivers_builder.go:68 Receiver is starting... {"kind": "receiver", "name": "otlp"}
2022-08-01T16:23:16.129Z        info    otlpreceiver/otlp.go:70 Starting GRPC server on endpoint 0.0.0.0:4317   {"kind": "receiver", "name": "otlp"}
2022-08-01T16:23:16.129Z        info    builder/receivers_builder.go:73 Receiver started.       {"kind": "receiver", "name": "otlp"}
2022-08-01T16:23:16.129Z        info    service/collector.go:251        Starting otelcontribcol...      {"Version": "40d055d", "NumCPU": 2}
2022-08-01T16:23:16.129Z        info    service/collector.go:146        Everything is ready. Begin running and processing data.
2022-08-01T16:24:39.099Z        INFO    loggingexporter/logging_exporter.go:42  TracesExporter  {"#spans": 2}
2022-08-01T16:24:39.099Z        DEBUG   loggingexporter/logging_exporter.go:51  ResourceSpans #0
Resource SchemaURL:
Resource labels:
     -> service.name: STRING(service-pyshell)
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope pyshell
Span #0
    Trace ID       : d6c53e27f97f5c4faa9670601cc509ac
    Parent ID      : efd153c34f6f8da9
    ID             : 70ca7bf3e7252d57
    Name           : test_step_123_go-cloud
    Kind           : SPAN_KIND_INTERNAL
    Start time     : 2022-08-01 16:24:38.957808982 +0000 UTC
    End time       : 2022-08-01 16:24:38.957878534 +0000 UTC
    Status code    : STATUS_CODE_OK
    Status message :
Events:
SpanEvent #0
     -> Name: log
     -> Timestamp: 2022-08-01 16:24:38.957846674 +0000 UTC
     -> DroppedAttributesCount: 0
     -> Attributes:
         -> roll.sides: INT(10)
         -> roll.result: INT(8)
SpanEvent #1
     -> Name: log
     -> Timestamp: 2022-08-01 16:24:38.957861762 +0000 UTC
     -> DroppedAttributesCount: 0
     -> Attributes:
         -> roll.sides: INT(10)
         -> roll.result: INT(2)
Span #1
    Trace ID       : d6c53e27f97f5c4faa9670601cc509ac
    Parent ID      :
    ID             : efd153c34f6f8da9
    Name           : test_case_ABC_go-cloud
    Kind           : SPAN_KIND_SERVER
    Start time     : 2022-08-01 16:24:38.957572621 +0000 UTC
    End time       : 2022-08-01 16:24:38.95790237 +0000 UTC
    Status code    : STATUS_CODE_OK
    Status message :
Attributes:
     -> url: STRING(myurl1)


^C2022-08-01T16:26:40.016Z      info    service/collector.go:177        Received signal from OS {"signal": "interrupt"}
2022-08-01T16:26:40.016Z        info    service/collector.go:267        Starting shutdown...
2022-08-01T16:26:40.016Z        info    service/service.go:111  Stopping receivers...
2022-08-01T16:26:40.017Z        info    service/service.go:116  Stopping processors...
2022-08-01T16:26:40.017Z        info    builder/pipelines_builder.go:73 Pipeline is shutting down...    {"kind": "pipeline", "name": "traces"}
2022-08-01T16:26:40.017Z        info    builder/pipelines_builder.go:77 Pipeline is shutdown.   {"kind": "pipeline", "name": "traces"}
2022-08-01T16:26:40.017Z        info    service/service.go:121  Stopping exporters...
2022-08-01T16:26:40.018Z        info    service/service.go:126  Stopping extensions...
2022-08-01T16:26:40.018Z        info    service/collector.go:281        Shutdown complete.
```

And finally my aesome trace of Grafana Could! 😄 🎆 

![image](https://user-images.githubusercontent.com/3272563/182198572-3936e9b3-e9ec-443e-9ef8-71d1d9ec2f09.png)

**Comment by rfratto** [comment]
Thanks! 

That's interesting, I wonder if it's because you don't have the batch processor defined on the agent equivalent, though I don't understand why that would matter. 

```yaml
server:
  http_listen_port: 12345
  log_level: debug
traces:
  configs:
    - name: integrations
      # Configure batch processor 
      batch: 
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      remote_write:
        - endpoint: tempo-eu-west-0.grafana.net:443
          basic_auth:
            username: 201581
            password: <my API key>
```

@mapno would you expect traces to not show up in tempo if the batch processor isn't declared?

**Comment by rfratto** [comment]
FWIW, if you're happy with using OpenTelemetry Collector, you should by all means continue using it :) But I appreciate you helping take the time for us to get to the bottom of why the Grafana Agent config wasn't working for you so we can help other people that might run into the same issue.

**Comment by giuliohome** [comment]
My wild guess at this point is that this was a bug in an older release of the opentelemetry collector that has been fixed in a release maybe newer than the one used to produce the Agent image. But I don't know if this makes really sense.

Yes, as you said I'm happy with the Collector, but I think it would be also great to have the Agent working in this situation. Not strictly needed though. Yes I confirm that on my side this is resolved with the Collector.
Thanks for your help again.

**Comment by giuliohome** [comment]
> That's interesting, I wonder if it's because you don't have the batch processor defined on the agent equivalent, though I don't understand why that would matter.

I commented that part and indeed it doesn't matter, sorry for adding it in the minimal repro.

> My wild guess at this point is that this was a bug in an older release of the opentelemetry collector that has been fixed in a release maybe newer than the one used to produce the Agent image. 

Well, you recently upgraded from v0.46.0 to v0.55.0 and the former version of the colletor  (namely otel/opentelemetry-collector-contrib:0.46.0) does not work.
So I think we have arrived at the bottom line, let me know if you agree and feel free to close this as you prefer.

**Comment by giuliohome** [comment]
Wait a moment, why is the latest version of the core collector not working?
Because [docker latest tag](https://github.com/open-telemetry/opentelemetry-collector-releases/issues/73) is not updated!
Actually `otel/opentelemetry-collector:0.56.0` **does work!**
**Also the version 55 but not the 46** - this is confirmed (after the latest tag introduced some confusion) and it's maybe the only valid explanation why the Agent is not working (and will work soon, I thin)

**Comment by giuliohome** [comment]
Yeah, `grafana/agent:main-53e8cf3` is working!

docker run -it --rm -p 4317:4317 -p 4318:4318 -p 12345:12345 -v $(pwd):/cfg:ro  grafana/agent:main-53e8cf3  -config.file=/cfg/config.yaml

**Comment by giuliohome** [comment]
### Reference to otel collector core issue and changelog

-  Spans are not being exported by OTEL Collector when using API/SDK version 1.11.0 [#2624 ](https://github.com/open-telemetry/opentelemetry-python/issues/2624)

-  [receiver/otlp] data not processed when using the old instrumentation library fields [#5188](https://github.com/open-telemetry/opentelemetry-collector/issues/5188)

- in the ChangeLog see BugFixed of [v0.49.0 Beta](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md#v0490-beta): The codepath through the OTLP receiver for gRPC was not translating the InstrumentationLibrary* to Scope* (#5189) - Fixes #5188

### Docker tags

NOTICE that your latest tag on docker grafana/agent is "Last pushed 9 days ago" hence is **still not working**.

**Comment by daper** [comment]
Hello, I also faced the same issue here, and it looks like it's fixed on `main`. Could you make an agent release? Not feeling very comfortable running `main` :sweat_smile: . Thanks!

**Comment by giuliohome** [comment]
I agree with @daper: better to consider the issue "_open_" until it's fixed on `latest`.

**Comment by giuliohome** [comment]
@daper I've tested that now - with the new [**version 1.12** of python opentelemetry sdk](https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.12.0) - even the `latest` tag of grafana agent (though not yet updated) is working!

[Same solution](https://github.com/grafana/tempo/issues/1698#issuecomment-1229481556) as for this tempo _straight_ ingestion issue.
