### ISSUE TITLE
Flow: Discussion on scraper success/error

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#2035]
Preamble, this discussion likely has ramifications for synchronous vs asynchronous paths for the agent. 

In the current flow scraper setup appending is almost always a success, even if a downstream endpoint fails. This can lead to possible issues, notably with exemplars and reporting errors.  

The current static scraper follows a synchronous writing path to a WAL and can expect a single success or failure.  There is already existing handling of mixed mode failures via the fanout appender. If there is any error, then return the error. This does set a precedent for the scraper handling mixed mode operations. 

With flow we can have deeply nested branching paths to any number of endpoints; having synchronous paths can lead to performance bottlenecks, see [experiment](https://github.com/grafana/agent/pull/2034) with workers.

**Comment by rfratto** [comment]
I'm going to close this as the semantics of handling errors in the fan-out mechanism haven't come up again. If we want to revisit this discussion we can reopen later.
