### ISSUE TITLE
add agent deb to the grafana apt repository

### ISSUE THREAD

**Issue by abstiger** [grafana/agent#2100]
is there any plan to add grafana agent and the others of LGTM stack(loki,tempo,mimir) debian package to the grafana apt repository: https://packages.grafana.com/oss/deb  ? 

so we can get started LGTM stack on ubuntu with one command  like : `sudo apt-get install grafana loki tempo mimir agent` ?

**Comment by marctc** [comment]
@abstiger that's is a good idea. I believe this issue is relevant what are you saying: #844

**Comment by abstiger** [comment]
@marctc yes exactly, sorry for the duplicated question!

**Comment by abstiger** [comment]
WOW, Great Job! 👍   

Looking forward to the other Grafana apps (loki and mimir) coming soon too! 👀 

BTW: It will be helpful if the default systemd configuration of the LGTM and the Agent can works well together.

**Comment by Flygsand** [comment]
@tpaschalis What's the relationship between `apt.grafana.com`/`rpm.grafana.com` and `packages.grafana.com`?

**Comment by marctc** [comment]
> @tpaschalis What's the relationship between `apt.grafana.com`/`rpm.grafana.com` and `packages.grafana.com`?

`packages.grafana.com` on has Grafana and Grafana Enterprise and it will be deprecated soon
