### ISSUE TITLE
Failure to build 0.27.0 (issues with gobpf/bcc)

### ISSUE THREAD

**Issue by daurnimator** [grafana/agent#2113]
```
# github.com/iovisor/gobpf/bcc
/build/go/pkg/mod/github.com/iovisor/gobpf@v0.2.0/bcc/module.go:230:132: not enough arguments in call to (_C2func_bcc_func_load)
	have (unsafe.Pointer, _Ctype_int, *_Ctype_char, *_Ctype_struct_bpf_insn, _Ctype_int, *_Ctype_char, _Ctype_uint, _Ctype_int, *_Ctype_char, _Ctype_uint, nil)
	want (unsafe.Pointer, _Ctype_int, *_Ctype_char, *_Ctype_struct_bpf_insn, _Ctype_int, *_Ctype_char, _Ctype_uint, _Ctype_int, *_Ctype_char, _Ctype_uint, *_Ctype_char, _Ctype_int)
```

```
$ pacman -Q libbcc
bcc 0.25.0-1
```

Upstream issue: https://github.com/iovisor/gobpf/issues/314

**Comment by tpaschalis** [comment]
Hey there, thanks for the report. This seems to be another case of `gobpf` not yet being updated to match a recent bcc version; these new arguments were introduced in [1](https://github.com/iovisor/bcc/commit/25438d3863a0d5fc61af2d861a9e7c7a60a1cfbe
) and [2](https://github.com/iovisor/bcc/commit/ffff0edc00ad249cffbf44d855b15020cc968536
) which were part of v0.25. We'll be keeping an eye out on the upstream issue.

For the time being, you could either use the `-tags noebpf` flag to opt-out of building the ebpf_exporter on your system, or (if possible) downgrade to an older bcc version. Our build pipeline just installs libbpfcc-dev using apt and it seems to be working; are you installing bcc from source using a more recent version?

**Comment by daurnimator** [comment]
> For the time being, you could either use the `-tags noebpf` flag to opt-out of building the ebpf_exporter on your system, or (if possible) downgrade to an older bcc version. Our build pipeline just installs libbpfcc-dev using apt and it seems to be working; are you installing bcc from source using a more recent version?

I am packaging grafana-agent for ArchLinux. We *could* disable ebpf, but anyone using that would suddenly either get errors, or have missing metrics.
We would not downgrade libbpfcc for all ArchLinux users for this issue.

**Comment by martinetd** [comment]
@tpaschalis the patch suggested in https://github.com/iovisor/gobpf/pull/311 will keep working with older version as well, just keep using the latest gobpf.
For this case it's really just the new bcc release that changed its API without much warning, so the rest of the ecosystem needs a bit of time to catch up...

**Comment by tpaschalis** [comment]
I'm closing this as `wontfix`. For now we have removed the problematic bundled ebpf_exporter that was using gobpf/bcc. 

If we bring this back, we should look into either using cloudflare/ebpf_exporter's release v2.0 which moves away from BCC or something based on cilium's go-ebpf to avoid such issues with static linking.
