### ISSUE TITLE
usagestats can hammer DNS servers if DNS requests are blocked

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2114]
See original comment: https://github.com/grafana/agent/issues/1856#issuecomment-1235928718

It seems that DNS servers can be hammered by requests if the DNS requests are being blocked. 

This likely could happen to _any_ of our HTTP clients where DNS requests are blocked, but the issue was first discovered for usagestats.

**Comment by rfratto** [comment]
It looks like the backoff is configured properly. This might be something Go is doing by default; I see that [http.Transport will retry requests](https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/net/http/transport.go;l=685) if it receives specific errors.

It seems like the only way to prevent this from going on forever is to cancel the context to the request, but http.Transport doesn't have any kind of backoff mechanism if it gets stuck in this retry loop, so it would still hammer DNS requests for the duration of the context. 

There's probably a few things we could do, but we would probably have to replicate the DNS filter to be able to figure out where exactly things are looping and what the specific error Go sees is.

**Comment by rfratto** [comment]
It's starting to seem like this is coming from the standard library and may not be simple to fix. It might be worthwhile prioritizing adding the flag to disable usagestats from the operator over this, since that would be much easier to deliver.

**Comment by rfratto** [comment]
I'm going to close this as won't do in favor of #2116. This seems like behavior of the standard library, and the workaround of disabling usagestats is more than reasonable.

**Comment by lightistor** [comment]
Where is the feature flag information or the issue to disable this at the operator level?
