### ISSUE TITLE
Proposal: Flow local.exec component 

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2118]
I propose a `local.exec` component which can execute a command on a specified interval:

```river 
local.exec "kubernetes_creds" {
  command = "doctl"
  args    = [
    "kubernetes",
    "cluster",
    "kubeconfig",
    "show",
    env("KUBERNETES_CLUSTER_ID"),
  ]
  
  // How often to rerun the command. The default (0s) means to only rerun 
  // when the component is created or updated. 
  refresh = "8h" 
}

// Use local.exec.kubernetes_creds.stdout in components that need 
// a kubeconfig to authenticate against Kubernetes.
```

As demonstrated above, this is particularly useful for credentials helpers. However, credentials helpers are typically only found outside of Docker environments, so I don't anticipate this being very useful inside Docker, unless a custom image was built. 

The obvious concern here would be about security: would a local.exec component be dangerous to allow? I'm not sure if it introduces any _new_ potential attack vectors that local.file + prometheus.remote_write doesn't already introduce (since a malicious user could craft a config using those two components to send the contents of any file Grafana Agent can read to an arbitrary endpoint through basic auth headers).

**Comment by ptodev** [comment]
If the Agent runs with elevated privileges (e.g. using a Windows Service with a special account), a malicious user would also be able to start any malicious executable this way and take advantage of the extra privileges.

**Comment by mattdurham** [comment]
Closing per May community call conversation

**Comment by mattdurham** [comment]
Updated reason
