### ISSUE TITLE
Cluster Management API Cannot accept urlencoded config names

### ISSUE THREAD

**Issue by nlowe** [grafana/agent#215]
The [`PUT /agent/api/v1/config/{name}`](https://github.com/grafana/agent/blob/master/docs/api.md#update-config) API cannot accept url-encoded `{name}`s for configuration documents. This makes it hard to migrate away from something like the prometheus operator, which encodes ServiceMonitor scrape job names with this format: `<namespace>/<name>/<endpoint index>` (for example, `foo/myapp/0`):

https://github.com/prometheus-operator/prometheus-operator/blob/d97ba662bc94d64e254e116f3cbf573068ac2d87/pkg/prometheus/promcfg.go#L868-L871

I can work around this by updating my configuration fragments to something like `foo.myapp.0` instead, but it'd be nice if the agent could accept these config fragments natively.

I believe this boils down to calling [`(*Router).UseEncodedPath()`](https://pkg.go.dev/github.com/gorilla/mux#Router.UseEncodedPath) on the router, although I don't know if this will require the agent to attempt to url-decode the config name or if the router will do it for you.

**Comment by rfratto** [comment]
Thanks for reporting! I'll try to have a fix for this in the next few days and include it as part of the planned release on Friday.
