### ISSUE TITLE
discrepancy between otel-collector and grafana-agent tail_sampling configuration options

### ISSUE THREAD

**Issue by vbichov** [grafana/agent#2176]
it seems that grafana-agent is missing a bunch of configuration options that otel-collector has. 

In my usecase I would like to increase `num_traces` value but it's missing from grafana config.

In otel-collector `num_traces`  is loaded into [this struct](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b2327211df976e0a57ef0425493448988772a16b/processor/tailsamplingprocessor/config.go#L125:L138)
while in grafna agent configs are represented by [this struct](https://github.com/grafana/agent/blob/main/pkg/traces/config.go#L302:L308) which has only a subset for the properties the otel-collector has.

an attempt to add the said property resutlts in :
```
2022-09-19 11:10:46.806018 I | error loading config file /configs/agent.yaml: yaml: unmarshal errors:
  line 52: field num_traces not found in type traces.tailSamplingConfig
```

I'm using the following docker image `grafana/agent:v0.26.1`

**Comment by tpaschalis** [comment]
Hey there Vitaly, thanks for the report!

In most cases, we're directly embedding the upstream configuration structs to be 1:1 compatible with the OpenTelemetry collector, but I don't have the context around why this isn't the case here. I think that we could go ahead and change the Agent struct to bring them closer together.

**Comment by Alexul** [comment]
@rfratto hey, any chance to build it from some branch to get that fix before December? Its kind of a blocker for us. Thank you

**Comment by rfratto** [comment]
PRs are more than welcome to get this going sooner, but we're not planning on working on this ourselves until after v0.29 at the moment. We also don't really manage alternative branches at the moment, though every main branch commit gets pushed as a Docker image.
