### ISSUE TITLE
Agent keeps restarting with Checkpoint error

### ISSUE THREAD

**Issue by Dileep-Dora** [grafana/agent#219]
Hi,

We're using agent to remote write metrics, we're running the agent as a part of k8's cluster,
however in some cases the agent is getting restarted with the following error, CPU and memory looks fine.

```
msg="Error process checkpoint" err="readCheckpoint: getSegmentSize: stat /data/68f636f5f69a242dbee28a0080f37c36/wal/checkpoint.00000046/00000001: no such file or directory"
```

This error is there in both **0.50** and **0.6.1** versions.

**Comment by rfratto** [comment]
Hi, sorry you're running into this. How are you storing the WAL? i.e., what is `/data/68f636f5f69a242dbee28a0080f37c36`?

**Comment by motyla** [comment]
I'm also getting this. `msg="Error process checkpoint" err="readCheckpoint: getSegmentSize: stat /opt/prometheus-data/agent/2116dcc766b260bb15843b7cbf4416a7/wal/checkpoint.00000024/00000009: no such file or directory"` I'm running with `wal_directory: /opt/prometheus-data/agent`

**Comment by rfratto** [comment]
The error message isn't fatal. Every five seconds `remote_write` will check for a new checkpoint. If reading the new checkpoint fails, a warning-level log will be emitted but `remote_write` will try to read the checkpoint again five seconds later. 

I'd like to confirm with `kubectl describe po` that the Agent process is actually crashing and not being killed by k8s. If it is crashing, you might have to enable debug-level logs to find out more information about why it's exiting. 

A few reasons you might run into this log line: 
- Checkpointing failed (check for a `could not truncate WAL` log line)
- Slow storage. Backing a storage by a PVC mounted on the host is ideal. Network PVCs might cause problems. 
- Underlying storage error 

 Some users may prefer to run the WAL in a `tmpfs` even if it'll be lost when the host goes down. I'd recommend trying this at least to see if you don't see the error anymore. 

If the WAL gets corrupted and the Agent starts crash looping, you may have to delete your WAL.

**Comment by Dileep-Dora** [comment]
Hi @rfratto Sorry for replying late,

We're running on AWS, and using 1.2TB of GP2 storage for the host machine, on this we're running the k8s container with 2GB storage provided, however the overall IOPS on this volume looks fine.

**Comment by motyla** [comment]
After looking better into it , my grafana agent does not restart itself but still give these error messages.
Although not restarting utself it is not writing to my remote write endpoint (thanos receive) ending up with lot's of server errors on thanos receive side.

Unlike @Dileep-Dora I'm using physical machine with fast and reliable NVME disk with xfs on it.
