### ISSUE TITLE
Flow API: empty exports not returned from the API

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2205]
If a component has a zero value for everything in its exports, the entire exports section is omitted from the API result. 

This might mislead users, since it makes it seem like those components don't have any exported fields.

**Comment by tpaschalis** [comment]
This might be a bit harder to encounter now that many components export capsules (like a Receiver or RelabelRules); a simple way to check this is make `local.file` point to an empty file.

**Comment by rfratto** [comment]
This is closely related to #2206, where a fix for that will also probably resolve this.
