### ISSUE TITLE
Flow API: empty values hidden from attributes 

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2206]
If a component has a zero value for any attribute, that attribute is omitted from the API result.

This might mislead or confuse users, since it makes it seem like that attribute isn't set (or potentially doesn't exist).

I think all required attributes should always show up in the UI, even if they're the zero value.

**Comment by ptodev** [comment]
Do you mean that all attributes should show up in the UI, or all attributes who are not "optional"?

**Comment by mattdurham** [comment]
My thought is anything with a "real" value should show, either entered or set as default. Nil values should not.

**Comment by rfratto** [comment]
I'm not sure I agree. I think these should be the rules:

* If a field is marked required (i.e., not optional), then always return it in the API result regardless of value (including nil/zero values). 
* If a field is marked optional, only return it in the API result if its value is not nil/zero. 

This would help explicitly inform a user that something in their file is evaluating to the zero value, such as `targets = []`, which today would just not show up at all. This would also then apply to exports, making it explicitly clear that a component has no exported targets (because the targets field in DebugInfo is listed as required).
