### ISSUE TITLE
Flow: add OpenTelemetry Collector components

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2213]
This issue proposes a set of `otelcol` components to add first-class OpenTelemetry Collector support in Grafana Agent Flow. 

Adding first-class OpenTelemetry Collector support enables Grafana Agent to embrace Grafana's big tent philosophy, allowing the agent to support multiple vendors outside of the LGTM stack. 

## Proposal 

We will create a set of OpenTelemetry Collector components across three namespaces:

* `otelcol.receiver`: A list of OpenTelemetry Collector receivers 
* `otelcol.processor`: A list of OpenTelemetry Collector processors 
* `otelcol.exporter`: A list of OpenTelemetry Collector exporters 

A description of how to handle extensions is out of scope for this proposal. However, extensions for at least authentication will be included. 

> **NOTE**: Throughout this proposal, I use the term "consumer" in the same sense as OpenTelemetry Collector; a consumer is a component which can consume OpenTelemetry data sent from other components.  

### Pipeline construction

Grafana Agent Flow creates a pipeline by having each component reference other components where data will be sent. This contrasts OpenTelemetry Collector, where components are defined separately from the pipeline. 

For consistency with other Flow components, the set of `otelcol` components will form a pipeline the same way: by having each component reference other components where data will be sent. 
 
### Arguments 

All `otelcol` Flow components which send data to a consumer will support the following arguments: 

* `output.traces`: A list of consumers where traces should be forwarded. Only available if the configured component supports traces.  
* `output.metrics`: A list of consumers where metrics should be forwarded. Only available if the configured component supports metrics.
* `output.logs`: A list of consumers where logs should be forwarded. Only available if the configured component supports logs.

### Exported fields 

`otelcol` Flow components which act as consumers will support the following exported fields:

* `input`: A consumer for telemetry data. Any telemetry type supported by the OTel component can be sent to this consumer. 

Note that there is only one exported field for input for all telemetry types. This simplifies the config, and there doesn't seem to be much value in separating the fields. 

### Example config 

```river
otelcol.receiver.jaeger "default" {
  // Define the server settings where applications 
  // may push Jaeger-formatted traces to. 
  server {
    // Create a gRPC server with the default settings. 
    grpc {} 
  }

  output {  
    traces = [otelcol.processor.batch.default.input] 
  } 
}

otelcol.processor.batch "default" {
  output {
    traces = [otelcol.exporter.logging.default.input]
  }
}

otelcol.exporter.logging "default" {
  log_level = "debug"

  // Exporters cannot forward data to a consumer, 
  // so the "output" field does not exist here. 
}
```

## Flow component list

We will cherry-pick specific OpenTelemetry Collector components from both the otelcol and otelcol-contrib distributions to include in Grafana Agent Flow. 
 
Our initial set of components is minimal, but will grow over time. While we should consider supporting most existing OTel components, we should initially avoid supporting any OTel components whose functionality is covered by an existing Flow component. This will be the case for `otelcol-contrib` receivers which collide with functionality of `prometheus.integration` Flow components. 

We will start with the following components: 

`otelcol` distribution components:
* `otelcol.receiver.otlp`: Receives OTLP data over the network.
* `otelcol.processor.batch`: Batches telemetry data before sending to another consumer.
* `otelcol.processor.memory_limiter`: Drops telemetry data if memory usage is getting too high.
* `otelcol.exporter.otlp`: Sends telemetry data via gRPC using OTLP.
* `otelcol.exporter.otlphttp`: Sends telemetry data via HTTP using OTLP.

`otelcol-contrib`: distribution components:
* `otelcol.receiver.jaeger`: Receives telemetry data from Jaeger applications.
* `otelcol.receiver.kafka`: Receives telemetry data from Kafka. 
* `otelcol.receiver.opencensus`: Receives telemetry data from OpenCensus. 
* `otelcol.receiver.zipkin`: Receives telemetry data from Zipkin.
* `otelcol.processor.attributes`: Processes span attributes. 
* `otelcol.processor.spanmetrics`: Creates metrics from spans.
* `otelcol.processor.tail_sampling`: Performs tail sampling against tracing data.
* `otelcol.exporter.jaeger`: Writes telemetry data to a Jaeger server. 

This list of components is based solely on the current exposed functionality of the tracing subsystem within Grafana Agent. As the intent is to embrace the big tent philosophy, we should continue to add more exporters for other vendors over time. 

Additionally, we will create Grafana Agent-specific custom components:
* `otelcol.exporter.logging`: Logs telemetry data in-process. 
* `otelcol.processor.discovery`: Associates incoming spans with a Prometheus discovery target.
* `otelcol.processor.servicegraph`: Generates a service graph from incoming spans. 
* `otelcol.receiver.prometheus`: Receives Prometheus metrics from a `prometheus.scrape` Flow component.
* `otelcol.exporter.prometheus`: Sends Prometheus metrics to a `prometheus.remote_write` Flow component. 

The last two components, `otelcol.receiver.prometheus` and `otelcol.exporter.prometheus`, enable interoperability between the Prometheus-specific and OpenTelemetry-specific components, allowing users to freely switch between both as needed.

## Implementation 

Flow `otelcol.*` components should work by wrapping around upstream components from OpenTelemetry Collector, using River for configuration. We should not reimplement components that already exist, with the except for the Grafana Agent-specific custom components. 

An initial prototype for this was done in #1843. The prototype can serve as a base for the final implementation.

## Tasks 

This is the list of components to implement for the initial set of components: 

- [x] #2286
- [x] #2285
- [x] #2287
- [x] #2288
- [x] #2289
- [x] #2290
- [x] #2291
- [x] #2292
- [x] #2293
- [x] #2294
- [x] #2295
- [x] #2296
- [x] #2297
- [x] #2298
- [x] #2299
- [x] #2300
- [x] #2301
- [x] #2302
- [x] #4068
- [x] #4261
- [x] #2612

These components will be gradually introduced across a few releases.

**Comment by rfratto** [comment]
I've updated the proposal to descope extensions but list them as needed. See #2352 for the first package to encapsulate authentication extensions.

**Comment by ptodev** [comment]
The tracing subsystem in Static mode also supports "load_balancing" and "automatic_logging". Are we going to offer feature parity on those?

The Static mode uses the Collector's [loadbalancing](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/loadbalancingexporter) exporter directly. Should we add it ot the list of components which we need to port over?

For automatic logging I cannot find an equivalent Collector process so we might have to port our own.

**Comment by cyrille-leclerc** [comment]
I faced the same `\n` as @sylvainOL to verify few OTel logs, it forced me to copy paste the message in a text editor to replace it by real line breaks. 
I wish the console output I use for debugging honored line breaks

**Comment by ptodev** [comment]
Hi @sylvainOL and @cyrille-leclerc, thank you for your feedback. I opened another issue for this: #4261
If you have further comments, please feel free to write them in the dedicated issue.

**Comment by sylvainOL** [comment]
Hi @ptodev, thanks for the comment, I'll follow it :)

**Comment by kago-dk** [comment]
@rfratto Any plans to add the https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor into Grafana Agent Flow so that we can filter spans from traces https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/filterprocessor/README.md#filter-spans-from-traces

**Comment by rfratto** [comment]
@kago-dk We're open to it, but this issue is just to track the initial set of OpenTelemetry Collector components which are already available in static mode; for anything net-new we'd want to track it in a separate issue. Would you mind opening a new issue requesting filter processor to be added to flow mode?
