### ISSUE TITLE
Flow: `prometheus` components still partially function after removal

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2216]
`prometheus` components which export receivers don't reject metrics after the component is removed. This can have some unintended side effects. 

To demonstrate the issue, start with this config file:

```river 
prometheus.scrape "default" {
  targets    = [{ __address__ = "localhost:12345" }]
  forward_to = [prometheus.relabel.default.receiver]
}

prometheus.relabel "default" {
  forward_to = [prometheus.remote_write.default.receiver] 

  // (no rules defined) 
}

prometheus.remote_write "default" {
  // (no endpoints defined) 
}
```

Initially, all components work as intended. Now, modify the config file to remove  `prometheus.relabel.default`, and reload the config by POSTing to `/-/reload`:

```river
prometheus.scrape "default" {
  targets    = [{ __address__ = "localhost:12345" }]
  forward_to = [prometheus.relabel.default.receiver]
}

prometheus.remote_write "default" {
  // (no endpoints defined) 
}
```

This causes `prometheus.scrape.default` to go unhealthy because the evaluation will fail. However, the component remains in its last valid state, and still holds a pointer to the now-removed `prometheus.relabel.default.receiver`, which was last configured to send to `prometheus.remote_write.default`. 

Because the prometheus components don't check to see if they were terminated, metrics will still be sent to `prometheus.remote_write` unexpectedly, even though there is no running component that would enable that to happen.

To avoid this issue, `prometheus` components which export a receiver should reject or ignore samples if they have been shut down.

**Comment by ptodev** [comment]
I've been thinking more about this, and I cannot think of a good reason why we would want to allow an update with an invalid graph? And I cannot think of any reason why a user would want to knowingly send us an invalid one. The only reason I can think of is if it got sent by accident. Then, if we accept it, this could potentially lead to a loss of data. Would it not be better to just abort the whole update, like [this](https://github.com/grafana/agent/commit/fb4c8533049795aa7ac7218dac15cacbba7ca004)?

**Comment by rfratto** [comment]
> I've been thinking more about this, and I cannot think of a good reason why we would want to allow an update with an invalid graph? 

One of the original goals of the Flow controller was that we'll try to apply as much as we can to reduce the blast radius of an invalid config. We can discuss changing that decision, but I feel it's separate from this issue still: it is invalid for the `prometheus` components to still accept metrics after they've been shut down.
