### ISSUE TITLE
Flow: otelcol.processor.spanmetrics component

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2295]
Expose the OpenTelemtry Collector `spanmetrics` processor as a Flow component called `otelcol.processor.spanmetrics`. This component is from the `otelcol-contrib` distribution.

**Comment by rfratto** [comment]
We should probably _not_ port this over from static mode, as a span2metrics connector component is being planned upstream for OpenTelemetry Collector, and we should probably use that instead.

**Comment by mar4uk** [comment]
@ptodev Was `spanmetrics` component added to Agent Flow components? I can't find it in https://github.com/grafana/agent/tree/main/component/otelcol/processor

**Comment by ptodev** [comment]
Hi @mar4uk 👋  It's not added yet, but it's the next one on my list, after #4261 and #2300
I'm sorry for closing this issue - not sure why this is, it must have been a mistake. Probably got mixed up with #2612
