### ISSUE TITLE
Flow: otelcol.exporter.logging component

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2298]
Create an OpenTelemetry Collector exporter component called `logging` and expose it as a Flow component called `otelcol.exporter.logging`. This is named similarly to the upstream `logging` exporter, but instead would use Grafana Agent Flow-specific loggers.

**Comment by rfratto** [comment]
This can _probably_ supersede the [automaticloggingprocessor](https://github.com/grafana/agent/tree/v0.28.0/pkg/traces/automaticloggingprocessor) currently used in the static mode tracing subsystem. 

@mapno would have to confirm, but I think the only reason the current tracing subsystem uses a processor for logging is because there's no other supported exporters other than otlp and otlphttp. This could be an opportunity to turn it into an exporter, which might make more sense given its functionality.

**Comment by rfratto** [comment]
We have to consider if this component is necessary anymore, or if it could be replaced with otelcol.exporter.loki and loki.stdout (#2736). (For context, this issue exists to reproduce behavior possible in the static mode).

The main difference between otelcol.exporter.logging and loki.stdout is that logs would be sent to the internal logger instead of directly to /dev/stdout (if I understand correctly).

cc @tpaschalis

**Comment by tpaschalis** [comment]
The reason why I'm on the fence is that the logging exporter also works for metrics and traces and might be useful for local development and debugging; not sure if this warrants keeping it around as a separate component.
