### ISSUE TITLE
Flow: Add app_agent_receiver integration component(s)

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2320]
Add one or more components for the `integrations-next` [app_agent_receiver integration](https://grafana.com/docs/agent/next/configuration/integrations/integrations-next/app-agent-receiver-config/).

**Comment by husseinraoouf** [comment]
Hello
will this be completed soon ?, I think since you are pushing the flow mode and faro, this should be high priority,

currently i am using the agent in flow mode in a kubernetes cluster and i had to deploy another grafana agent in static mode just for app_agent_receiver integration

**Comment by megumish** [comment]
I'm working on implementation right now.
I will eventually issue a PR.

I am working on the following forks

https://github.com/megumish/agent

We are also considering splitting the commits and separating the PRs for review, as the differences are likely to be significant ;)

**Comment by tpaschalis** [comment]
Hey @megumish thanks for working on this. Let us know if you need any pointers, we'd like to help this land!

**Comment by rfratto** [comment]
@megumish Thanks for your work on an implementation for this. We're trying to get all issues labeled `flow/feature-parity` completed within the next 17 days. 

I don't want you to feel like your work has gone to waste; would you be willing to open a PR with the current state of your work, and I can add commits to it to help finish? That way you can receive credit for what you have done so far. 

If not, I will start working on creating a component for this from scratch tomorrow.

**Comment by megumish** [comment]
@rfratto 
I have been busy with my day job lately and have not made much progress.
At any rate, I have committed and PR'd all the implementations I have just completed!
https://github.com/grafana/agent/pull/5243

**Comment by rfratto** [comment]
@megumish Thank you! We'll help get it finished and make sure you receive credit.

**Comment by megumish** [comment]
@rfratto Thank you!
