### ISSUE TITLE
Operator metrics-related remote_write blocks do not support bearerToken authorization

### ISSUE THREAD

**Issue by selverob** [grafana/agent#2332]
According to the documentation `remote_write` in `MetricsInstance` and `GrafanaAgent.spec.metrics` support a `bearerToken` field which enables bearer token authorization.

However, from my experiments and from looking at the code (`pkg/operator/config/templates/component/metrics/remote_write.libsonnet`), it seems like the bearer token is actually never templated into the `remote_write` block or, rather more generally, the `authorization` block in `remoteWrite` is never templated by the operator.

**Comment by marctc** [comment]
Thanks for reporting @selverob! We'll look into it as soon as we can.
