### ISSUE TITLE
Include JMX exporter for Grafana Cloud Agent

### ISSUE THREAD

**Issue by te4336** [grafana/agent#235]
Would be great to have the JMX Exporter included in the agent for those that aren't using an APM such as New Relic or App Dynamics.

**Comment by jeschkies** [comment]
The exporter https://github.com/prometheus/jmx_exporter is written in Java.

**Comment by rfratto** [comment]
@te4336 I'm looking into this this week. It seems like `jmx_exporter` is intended to run as a Java Agent alongside your main JAR. While we could add it as an integration within the Agent, the level of metrics collected wouldn't be as detailed (eg, no memory or CPU metrics). Is there a reason running it as a Java Agent doesn't work for you? Would you still be interested in a JMX integration in the Agent, even with the understanding that it can't collect CPU/memory metrics?

**Comment by te4336** [comment]
@rfratto Using the java agent alongside the main jar is fine however it comes down to restarting the java app so that everything is picked up and in working order. In a Healthcare production environment that is heavily regulated like ours it could be 14-21 days before that restart can take place unless it's an emergency. The Java apps in Tomcat and other platforms already have the built-in JMX endpoints exposed, would be great to have a way to just pull the metrics from what is already exposed and bypass the hurdles that would come with a restart or having to install an agent alongside the jars.

**Comment by te4336** [comment]
CPU and Memory metrics wouldn't be that big of a deal as we already gather CPU and memory metrics via the node agent that will suffice.

**Comment by rfratto** [comment]
@te4336 Thanks for explaining your use case! That makes a ton of sense, and I'll continue on with my prototype to include the JMX exporter as an integration. 

The first approach I'm prototyping is a system to download the JMX JAR at runtime and launch it as an integration. I'll tag you on the PR when I have something more substantial and we can discuss if the approach will work for your environment. 

> The Java apps in Tomcat and other platforms already have the built-in JMX endpoints exposed

It sounds like this means you could configure a normal `scrape_config` job to pull from these specific endpoints. Am I understanding correctly?

**Comment by te4336** [comment]
@rfratto That would be correct, if we could scrape it like an endpoint and gather the metrics from the exposed java beans, etc that would be fantastic.

**Comment by rfratto** [comment]
I'm removing keepalive on this. I would like to see this eventually, but it's not on the near term roadmap at least for the Agent team.
