### ISSUE TITLE
Flow: add OpenTelemetry Collector extension components

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2353]
This issue extends #2213 and proposes a set of `otelcol` components which wrap around OpenTelemetry Collector extensions. 

## Background 

#2343 added the `otelcol.exporter.otlp` component, wrapping around the OpenTelemetry Collector `otlp` exporter. The upstream exporter can be configured with a reference to an ID of an extension component to use for authentication. The instance of the component is then retrieved from the `component.Host` instance.

Authentication was descoped from the initial PR while an approach to handle extensions was undetermined. 

There were two approaches that could be taken:

1. Bake in support for authentication into components, similar to what is done for the `prometheus.remote_write` component.
2. Introduce new components which handle authentication extensions and allow the user to wire them together.  

To remain close to how upstream handles it, this issue proposes the latter approach. 

## Proposal 

We will create a set of OpenTelemetry Collector extension components in an `otelcol.auth` namespace. The namespace will be composed of OpenTelemetry Collector extensions which are intended for authentication and implement one or more of the interfaces from the OpenTelemetry Collector [configauth][] package. 

Other extensions are considered out of scope for this proposal. [Storage extensions][storage-ext] are likely to be included eventually, but are out of scope due to being experimental. Extensions that aren't authentication extensions or storage extensions may be added in the future, but would likely belong in a dedicated namespace rather than being scoped to `otelcol`. 

[configauth]: https://pkg.go.dev/go.opentelemetry.io/collector@v0.61.0/config/configauth
[storage-ext]: https://pkg.go.dev/go.opentelemetry.io/collector@v0.61.0/extension/experimental/storage

### Exported fields 

`otelcol.auth` namespace will support the following exported fields:

* `handler`: The raw OpenTelemetry Collector extension instance which other components can use. 

## Example config 

```river 
otelcol.exporter.otlp "default" {
  // Configure this component to use otelcol.auth.basic.default 
  // for authentication. 
  auth = otelcol.auth.basic.default.handler 

  ...
}

otelcol.auth.basic "default" {
  username = ...
  password = ... 
}
```

## Flow component list

We will cherry-pick specific OpenTelemetry Collector extensions from both the otelcol and otelcol-contrib distributions to include in Grafana Agent Flow. Our initial set of extensions is minimal, but will grow over time. 

We will start with the following extensions:

`otelcol-contrib` distribution components: 

* `otelcol.auth.basic`: Performs Basic authentication (from `basicauthextension`). 
* `otelcol.auth.bearer`: Performs Bearer token authentication (from `bearertokenauthextension`). 
* `otelcol.auth.headers`: Adds custom headers for authentication (from `headerssetterextension`).
* `otelcol.auth.oauth2`: Performs OAuth2 authentication (from `oauth2clientauthextension`). 
* `otelcol.auth.sigv4`: Performs SigV4 authentication (from `sigv4authextension`).

## Tasks 

This is the list of components to implement for the initial set of extensions:

- [x] #2354
- [x] #2355
- [x] #2356
- [x] #2357
- [x] #2358

**Comment by fawadasaurus** [comment]
I can't wait for `headerssetterextension` support.  I switched to Otel collector because of it.  It will be nice to have the choice to switch back to Grafana Agent once that is available.

**Comment by rfratto** [comment]
This is completed; all tracking tasks are done.
