### ISSUE TITLE
Flow: expose telemetry from otelcol components

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2372]
Currently, none of our otelcol components expose metrics to help users debug or introspect their status. 

Metrics from OpenTelemetry Collector components work primarily by using [obsreport](https://pkg.go.dev/go.opentelemetry.io/collector@v0.62.1/obsreport). `obsreport` provides helper methods for components to use to instrument operations for collecting traces, metrics, and logs. 

Internally, these helper methods [use OpenCensus](https://github.com/open-telemetry/opentelemetry-collector/blob/b45d0ed7f3c7f897fa59071a36371592c5f6d6a9/obsreport/obsreport_exporter.go#L110-L115) to record individual measurements for each component. The metrics exposed are defined as globals in an [internal package](https://github.com/open-telemetry/opentelemetry-collector/blob/b45d0ed7f3c7f897fa59071a36371592c5f6d6a9/internal/obsreportconfig/obsmetrics/obs_exporter.go#L50-L78). 

Our component wrappers should find a way to expose metrics from running OpenTelemetry Collector endpoints as Prometheus metrics. 

The biggest challenge is that Flow components are ephemeral, but OpenTelemetry Collector components are (currently) scoped to the process lifetime. This means that we should remove metrics for components which are no longer running in Grafana Agent Flow. 

There are two approaches we could take, in descending preference order:

1. Find a way to have our wrappers expose OpenCensus metrics as Prometheus metrics for _only_ the components being wrapped. This would automatically remove them once the component is removed. 
2. Globally register OpenCensus metrics from OpenTelemetry Collector, and figure out a way to remove metrics for components that have been terminated. 

cc @tpaschalis @jpkrohling

**Comment by rfratto** [comment]
I can't really see a good path forward here right now. 

Until there's a public API for collecting component level metrics from OpenTelemetry Collector components, maybe we should create our own based on the data being passed to consumers?

It wouldn't be as detailed as the information OpenTelemetry Collector has (i.e., no information on dropped or rejected data), but it would be better than nothing.

**Comment by jpkrohling** [comment]
> but OpenTelemetry Collector components are (currently) scoped to the process lifetime

We have config reloads, and components might be started/stopped during the process's lifecycle. Even if this is not true at the moment, this is something we always aim for, so this use-case is undoubtedly relevant for the collector.

**Comment by rfratto** [comment]
This is blocked until go.opentelemetry.io/collector/obsreport is fully instrumented using the OpenTelemetry SDK (for example, using `metric.MeterProvider` for internal metrics). This is already done for [exporters][] and [receivers][] behind a [feature gate][], but isn't yet done for processors. We can wait a few more weeks for it to be available or contribute ourselves if we're feeling confident enough to be able to make the changes easily without putting too much review burden on the maintainers. 

We'll have to wait even longer if we want it to leave feature gate status, but we can force the feature gate to be enabled from our end for now.

[exporters]: https://github.com/open-telemetry/opentelemetry-collector/blob/6b27644724d821cf6b876b32d2718705dd488d0c/obsreport/obsreport_exporter.go#L113
[receivers]: https://github.com/open-telemetry/opentelemetry-collector/blob/6b27644724d821cf6b876b32d2718705dd488d0c/obsreport/obsreport_receiver.go#L127
[feature gate]: https://github.com/open-telemetry/opentelemetry-collector/blob/6b27644724d821cf6b876b32d2718705dd488d0c/internal/obsreportconfig/obsreportconfig.go#L30

**Comment by rfratto** [comment]
Looks like support for the `MeterProvider` is available for processors now too. It's not available in a release yet, but it looks like once v0.67 is available we'll be able to upgrade and expose metrics from all the wrapped components.

**Comment by rfratto** [comment]
I'd say this is probably ready for work now then, and it'll hopefully just work(tm) for all the components once we upgrade to v0.67. I'm removing the blocked label.
