### ISSUE TITLE
[otelcollector] grafana agent export to otel collector

### ISSUE THREAD

**Issue by Dongqi-Guo** [grafana/agent#2396]
Since otel collector should be a better centralized logs filter and dispatch app. But seems grafana agent could not support this feature now, is there any plan to support this?

**Comment by ToMMy86** [comment]
That would be awesome,  i'm also trying to find a solution to ship logs from  "Grafana Agent" on servers ( one configuration language to mantain  )  - metrics to prometheus out of the box..  .. AND ... centralize  filtering and log routing to different destinations using OTEL as a central service .. ( filtering, routing and other logs BE such us SIEM.. in one place & config to mantain. ) 

As of now i'haven't find a good solution to do so.

In my case would be awesome to be able to put  OTEL Collector  "Before"  LOKI  destination in the flow and be able to route logs to other destinations also without touching agent confs....   so this would be a really really good feature indeed.

Please make this happen.

**Comment by rfratto** [comment]
Hi, this is something that might be possible in the future with upcoming features like #2213 which supports all the telemetry signals (metrics/logs/traces), but it'll take some time for everything to fall into place here.

**Comment by tpaschalis** [comment]
I'm closing this as our Flow components around the OpenTelemetry Collector have matured enough. Let us know how they work for you!
