### ISSUE TITLE
FreeBSD assets missing from v0.28.0 release

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2415]
It looks like the FreeBSD release assets were accidentally removed from the v0.28.0 release.

**Comment by krolingo** [comment]
please bring back support for FreeBSD

**Comment by tpaschalis** [comment]
@krolingo the FreeBSD assets will be back starting from next release.

If you need the FreeBSD assets for v0.28, you can build them by setting the appropriate GOOS/GOARCH environment variables. Thanks!

**Comment by BasixKOR** [comment]
Hi team, it seems like `grafana-agent-freebsd-amd64.zip` is missing again. Could you open this issue back?
