### ISSUE TITLE
Feature Request: Include service name in trace/tempo metrics

### ISSUE THREAD

**Issue by linjmeyer** [grafana/agent#242]
When using Grafana Agent to forward traces there are several helpful metrics like:

```
tempo_exporter_send_failed_spans
tempo_exporter_sent_spans
tempo_receiver_accepted_spans
tempo_receiver_refused_spans
```

It would be great if these were broken down by service to show which services are sending the most traces. 

Jaeger collectors have similar metrics and provide a `svc="my-service"` label for example.  It has been very helpful to understand if one service is using more than it's "fair share" of the backend storage.  I think this is especially important with Tempo as you don't have access to an indexed storage to find this information otherwise For example, you could find this in Kibana if using Elastic stack and Jaeger but this isn't be possible with Tempo's unindexed storage.

**Comment by joe-elliott** [comment]
We are unable to control these metrics.  They are produced by the [OTel Collector](https://github.com/open-telemetry/opentelemetry-collector).

If you'd like to see this feature in Grafana Agent please file an issue in that repo.  Thanks!

**Comment by linjmeyer** [comment]
Opened an issue there: https://github.com/open-telemetry/opentelemetry-collector/issues/2070
