### ISSUE TITLE
Grafana Agent Flow doesn't support Prometheus exemplars

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2420]
Grafana Agent Flow currently doesn't support Prometheus exemplars. 

It looks like `prometheus.remote_write` will properly send exemplars if they were written to the WAL, but the current FlowMetric abstraction means that no exemplars get written to the WAL. 

See #2037 for one proposal which can fix this issue.

**Comment by aknuds1** [comment]
This is a regression, right? From which Agent version?
