### ISSUE TITLE
Flow: What labels should `prometheus.exporter.unix` export? 

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2424]
Currently, the `prometheus.exporter.unix` component exports a target with a minimal set of labels:

https://github.com/grafana/agent/blob/18eeffa4bda2371ecd658f3ce1cbe427947434f2/component/prometheus/integration/node_exporter/node_exporter.go#L53-L58

The v1 integrations subsystem appends three labels:

* `instance`: Set to an integration-specific ID 
* `job`: Set to `integrations/INTEGRATION_NAME` 
* `agent_hostname`: Set to `$HOSTNAME` (if set) or to `os.Hostname()` otherwise. 

In addition to the labels listed above, the v2 integrations subsystem includes meta labels which can be useful for relabeling: 

* `__meta_agent_integration_name`: alias to `job`  
* `__meta_agent_integration_instance`: set to the name of the integration
* `__meta_agent_integration_autoscrape`: `"true"` when autoscrape is enabled for this integration

The only non-required label the Flow component sets is `name`, which is similar to `__meta_agent_integration_name` from the v2 integration subsystem. 

Not all of v1/v2 integration labels may be relevant to the Flow component equivalent, but I think we should determine of the current minimal list of labels was deliberate, and if not, which labels should be added to it. 

cc @captncraig

**Comment by captncraig** [comment]
Great points. I think the most relevant ones are definitely the job and name labels if you want to manipulate them later.

hostname, I kinda feel like should come from relabels or external labels later in the pipeline, but I could be convinced otherwise if you have strong feelings. Autoscrape does not have an equivalent in flow right now.

So my new proposed set for #2916 is:

```
jobName := fmt.Sprintf("integrations/%s", name)

model.AddressLabel:                  opts.HTTPListenAddr,
model.SchemeLabel:                   "http",
model.MetricsPathLabel:              path.Join(opts.HTTPPath, "metrics"),
"instance":                          opts.ID,
"job":                               jobName,
"__meta_agent_integration_name":     jobName,
"__meta_agent_integration_instance": opts.ID,
```

**Comment by rfratto** [comment]
> hostname, I kinda feel like should come from relabels or external labels later in the pipeline, but I could be convinced otherwise if you have strong feelings.

Removing hostname is fine with me, provided none of our integration dashboards rely on it being set. 

> So my new proposed set for https://github.com/grafana/agent/pull/2916 is:

LGTM 👍

**Comment by captncraig** [comment]
Going to drop back in here. We've had some feeback that the instance label is not useful. Do we want to make an additional change there?

**Comment by rfratto** [comment]
IMO it should probably be an integration-specific ID like before (the agent hostname:port, or the address of the MySQL server being monitored, etc).

**Comment by tpaschalis** [comment]
cc @captncraig @rfratto I'd like to try and reach consensus here and see what code changes we need to make. 

I've looked at the [mixin](https://github.com/prometheus/node_exporter/tree/master/docs/node-mixin) present on the node_exporter repo, to help us make informed decisions.

> Removing hostname is fine with me, provided none of our integration dashboards rely on it being set.

Yes, I can't see a `hostname` label being used on the upstream mixin or our dashboards. I think we're fine to remove it.

> We've had some feeback that the instance label is not useful

Looking at the node_exporter mixin, they _do_ make heavy use of the `$instance` label in their queries. We should keep it and also probably standardize it among other integrations. As Robert said, it's gonna be helpful when receiving metrics from multiple integration components of the same type.

Also, the upstream mixin makes use of a `cluster` label if the "showMultiCluster" option is enabled, but it's off by default and something that shouldn't be added to the base set of labels.

So IMHO we should go with a slight change to the last proposal for the default set of labels

```
jobName := fmt.Sprintf("integrations/%s", name)
hostname, _ := os.Hostname()

model.AddressLabel:                  opts.HTTPListenAddr,
model.SchemeLabel:                   "http",
model.MetricsPathLabel:              path.Join(opts.HTTPPath, "metrics"),
"instance":                          hostname,
"job":                               jobName,
"__meta_agent_integration_name":     jobName,
"__meta_agent_integration_instance": opts.ID,
```

**Comment by rfratto** [comment]
Personally, I would step away from the `__meta_agent_integration_` labels, since they're a holdover from static mode, and they could be reintroduced with some clever relabeling rules. Going forward, `__meta_component_name` and `__meta_component_id` would be more future-proof. 

In this case `__meta_component_name` would not have the same value as `__meta_agent_integration_name` did. For example, `__meta_agent_integration_name` would be `unix` while `__meta_component_name` would be `prometheus.exporter.unix`.

**Comment by rfratto** [comment]
I'm also noticing that the `instance` label does _not_ match up with its behavior in static mode. The `instance` label used to be integration-specific, but now it's always the hostname of the agent. 

For example, when running a MySQL exporter, the `instance` label used to be the address of the MySQL server. That was something we did explicitly in static mode because we felt it was more useful information, especially when looking at dashboards and selecting between agents.  

Do we want to bring that behavior back?

**Comment by tpaschalis** [comment]
The `__meta_component_name` and `__meta_component_id` sound useful, indeed.

> The instance label used to be integration-specific, but now it's always the hostname of the agent.
> Do we want to bring that behavior back?

I didn't express it correctly before. I _do_ think that `instance` should be standardized among all integration components, but each component type should decide what that value is.

In the case of `prometheus.exporter.unix export`, it makes sense to be the hostname of the machine collecting data for. WDYT?
