### ISSUE TITLE
Does the grafana-agent output the OS version?

### ISSUE THREAD

**Issue by nick-wvu** [grafana/agent#2442]
Does the agent output the OS type/version. For example RHEL 8.

**Comment by marctc** [comment]
AFAIK it displays the OS (linux, windows, etc) but not the distribution.
```
./agent -version
agent, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.18.3
  platform:         linux/amd64
```
What's the use case?

**Comment by tpaschalis** [comment]
Hey Nick! I suppose you mean the OS type and version of the host system that's running the Agent, right? The Agent's internal metrics do not include this information about the host system by default. 

If your hosts are some flavor of Linux, you can use the [node_exporter integration](https://grafana.com/docs/agent/latest/configuration/integrations/node-exporter-config/) with the `os` collector which parses `/etc/os-release` or `/usr/lib/os-release` to retrieve this information. Take some time to read through the documentation to see the available list of collectors, as well as advice on how to set up the exporter correctly if you plan on running it on Docker or Kubernetes.

For macOS, the `os` collector is not implemented yet, but is tracked on [this](https://github.com/prometheus/node_exporter/issues/2271) upstream ticket. For Windows machines you can use the equivalent [windows_exporter](https://grafana.com/docs/agent/latest/configuration/integrations/windows-exporter-config/) which _does_ have an `os` equivalent collector.

**Comment by nick-wvu** [comment]
Does the grafana-agnet use the `os` collector from the `node_exporter`?

**Comment by tpaschalis** [comment]
Yes, the `os` collector is enabled by default when using node_exporter.

You can use the `set_collectors` key to run _only_ this collector, if you don't need the other ones from the default set.

**Comment by nick-wvu** [comment]
OK, thank you. Any chance you happen to have the metric handy? 
I don't see anything like `node_os_info` like there is for windows

```
integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
```
