### ISSUE TITLE
Update Docker image to prevent OpenSSL v3 critical issue

### ISSUE THREAD

**Issue by alexrocco** [grafana/agent#2458]
Hi,

I just would like to create awareness about the [OpenSSL v3 critical issue ](https://snyk.io/blog/new-openssl-critical-vulnerability/)as the Docker image uses the 3.0.2 version.

Most likely the base image from https://github.com/rfratto/viceroy/blob/main/Dockerfile#L22 has to be updated.

Thanks,
Alexandre

**Comment by tpaschalis** [comment]
Thanks for the heads-up Alexandre, we'll take a look to mitigate this issue.

**Comment by rfratto** [comment]
To clarify, `rfratto/viceroy` is only used for building and should probably be updated anyway, but our base image (at runtime) is `ubuntu:jammy`.

**Comment by suryaval** [comment]
Hi @rfratto Are we going to have a patched version of grafana agent released sometime at the earliest?

**Comment by robinsmidsrod** [comment]
Will you rebuild the image tagged as `0.28.0` (latest tagged version) on Docker hub automatically, or will someone have to do something for this to happen?

**Comment by rfratto** [comment]
It looks like `ubuntu:jammy` isn't vulnerable anymore; I've just tagged v0.28.1 to build containers against an updated base image. Just waiting for CI now; I'll close this issue once the patch release is available.

**Comment by rfratto** [comment]
`grafana/agent:v0.28.1` is now available with a patched version of OpenSSL. Thanks for reporting!
