### ISSUE TITLE
Docs feedback: /operator/_index.md

### ISSUE THREAD

**Issue by gloriasc** [grafana/agent#2471]
The abbreviation "SD" is being used without being written out in clear text. 
CC @karengermond

**Comment by karengermond** [comment]
@captncraig and @rfratto, could you take a look at https://grafana.com/docs/agent/latest/operator/ and let me know if SD means "Service Discovery"?  If not, what does it refer to?

**Comment by rfratto** [comment]
@karengermond Yes, SD refers to service discovery.

**Comment by marctc** [comment]
Seems to be fixed now. I'll close the issue.
