### ISSUE TITLE
Feature Request:  Expose Prometheus RemoteWrite to other subsystems

### ISSUE THREAD

**Issue by joe-elliott** [grafana/agent#249]
**What I want to do:**

In the Tempo tracing pipeline I would like to generate histograms of operation duration.   Then push them through Prometheus remote write to the metrics backend.  Unfortunately, I can't find a way to easily expose remote write to the tempo/tracing pipeline.  

Is this possible?  I feel like it should be done in a generic way that it could be plugged into logging or any other module.

Credit to @genebean for sharing this idea in an offline discussion.

**Comment by rfratto** [comment]
I think the primary question is how we want this data to be collected. If it's via scraping, this could be an integration. If we're pushing it directly into the WAL arbitrarily, I think there's more work to be done here (i.e., we need a global Prometheus remote_write config section that is shared throughout the Agent).

**Comment by joe-elliott** [comment]
Right, my instincts tell me this could turn into a lot of data very fast which is why I was thinking remote write might make more sense.

Instead of scraping itself I wonder if the agent could just read its own Prometheus registry and send that.

**Comment by rfratto** [comment]
My concern is that there's already a system in place for the Agent to scrape metrics from its own registries and building something to turn that into a pure push model seems like a bit of work (and might lean towards being an implementation detail).

Is there a reason we'd specifically want it to push data directly rather than self-scraping a registry?

**Comment by joe-elliott** [comment]
I think volume would be the only one?  Does the agent initiate an http connection, pull the page and parse everything?

For high volume metrics it might be better to just push them directly.

**Comment by rfratto** [comment]
Yeah, it'd be treated as a real scrape target. What are you thinking the push frequency would be?

**Comment by rfratto** [comment]
We do this now, right? Can this be closed?

**Comment by mapno** [comment]
Yes! Closing
