### ISSUE TITLE
Add support for Prometheus native histograms

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#2492]
Prometheus [v2.40](https://github.com/prometheus/prometheus/releases/tag/v2.40.0) was just released with experimental support for native histograms.

The new histogram representation is currently only available in the protobuf exposition format, and is not readily supported by all clients (although client_golang also just released [v1.14](https://github.com/prometheus/client_golang/releases/tag/v1.14.0) to add it), but contains some pretty interesting technical advantages over the current histogram implementation.

For more information you might want to look at
https://docs.google.com/document/d/1cLNv3aufPZb3fNfaJgdaRBZsInZKKIHo9E6HinJVbpM
https://www.youtube.com/watch?v=T2GvcYNth9U

This is a tracking issue for making the Agent aware of and enable handling of native histograms if exposed by a scraped target.

https://github.com/grafana/agent/issues/2492#tasklist-block-fc85b971-bda8-4c46-af46-60a076f1f592

https://github.com/grafana/agent/issues/2492#tasklist-block-03a5c081-07e9-4fd7-a968-18d85828cfcc

**Comment by rfratto** [comment]
We need to update Loki before we can update our dependency. Updating Loki is currently blocked by weaveworks/common#262.
