### ISSUE TITLE
Flow: extend logging support in OpenTelemetry Collector components

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#2501]
Issue #2213 is tracking the addition of OTel Collector components to Grafana Agent Flow.

While the current set of `otelcol.*` components supports pipelines for all three telemetry signals, this new issue proposes and outlines some logs-specific functionality and improvements.

## Proposal
We propose to create a set of OpenTelemetry components across the existing otelcol namespaces that improve the usefulness of logs handling in Flow, as well as allow users to switch between using OTel and Loki for logs.

- [x] #2665
- [x] #2666

One thing to keep in mind is that logging support in the OTel Collector is not yet as polished as support for metrics and traces, and is marked as `alpha`. We should keep an eye out for the possibility of more frequent breaking changes.

## Implementation
One improvement that could be made to the current usage of the ConsumerExports interface, is to constrain the signals that can be passed to the `input` of an otelcol component.
Some components like otelcol.processor.batch make sense to be able to receive all three signals, while others like the upstream [cumulativetodeltaprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/cumulativetodeltaprocessor) or the [logstransformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/logstransformprocessor) only make sense for a subset of them.

As a first step for more flexible handling, we propose that the component which do not act on all three signals expose some debug info when non-supported telemetry signals pass through to provide visibility to the user.

**Comment by rfratto** [comment]
Personally, I think `otelcol.receiver.loki` and `otelcol.exporter.loki` are a must, but I'm not as confident about the other components since we'll already have similar components in the loki namespace.

**Comment by tpaschalis** [comment]
Since we've trimmed down the list of OTel-specific logging components to avoid having two things that do the same thing, one in the Loki and one in the OTel ecosystem, the issue can now be closed as done.

What we still may consider doing in the future is smarter handling around the ConsumerExports interface, and specifically OTel components that can only act on one or two signals input, but not all three of them.
