### ISSUE TITLE
grafana-agent-traces DaemonSet creation fails on OpenShift 4.5

### ISSUE THREAD

**Issue by mstyne** [grafana/agent#251]
OpenShift appears to have a 15 character limit on `container.ports.name`; per the documentation:

> If specified, the value must be no more than 15 characters, have at least one letter [a-z] and contain only [a-z0-9-]. Hyphens cannot be leading or trailing characters, or adjacent to each other.

Unfortunately, this leads to the failure of the `grafana-agent-traces` DaemonSet.

```
The DaemonSet "grafana-agent-traces" is invalid: 
* spec.template.spec.containers[0].ports[1].name: Invalid value: "tempo-jaeger-thrift-compact": must be no more than 15 characters
* spec.template.spec.containers[0].ports[2].name: Invalid value: "tempo-jaeger-thrift-binary": must be no more than 15 characters
* spec.template.spec.containers[0].ports[3].name: Invalid value: "tempo-jaeger-thrift-http": must be no more than 15 characters
* spec.template.spec.containers[0].ports[4].name: Invalid value: "tempo-jaeger-grpc": must be no more than 15 characters
* spec.template.spec.containers[0].ports[7].name: Invalid value: "tempo-opencensus": must be no more than 15 characters
```

Would manually modifying the port names in the `agent-tempo.yaml` definition be a reasonable solution to this issue?

**Comment by rfratto** [comment]
Hi 👋, I saw this earlier today myself and opened up #250 to fix this. In the meantime, manually modifying the port names is definitely a reasonable workaround.

**Comment by mstyne** [comment]
Thank you @rfratto ! I promise I searched before opening this issue!

**Comment by mstyne** [comment]
For any poor soul that wanders into this issue, here are my (awful) shortened names:

```
          name: tmpo-jgr-thr-z
          name: tmpo-jgr-thr-b
          name: tmpo-jgr-thr-80
          name: tmpo-jgr-grpc
          name: tmpo-zipkin
          name: tmpo-otlp
          name: tmpo-opencensus
```
