### ISSUE TITLE
Flow: investigate fanout approach for logging components.

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#2518]
Investigate different approaches for efficient and reliable fanning out of log entries from one to one or more components.

We can start by reusing Promtail's `api.Entry` struct to move log entries and their labels between components, as we sketch up new ideas.

**Comment by rfratto** [comment]
@tpaschalis Does this still need work or is it completed as of loki.write and loki.source.file?

**Comment by tpaschalis** [comment]
Sorry for the delayed response. Yes, I think that for now we can go ahead with the current approach for the LogsReceiver capsule. If in the future we see the opportunity for any changes or improvements, I think they may not even be user-impacting.

I'm closing this as resolved.
