### ISSUE TITLE
v0.29.0: Invalid CRD monitoring.grafana.com_metricsinstances.yaml

### ISSUE THREAD

**Issue by daper** [grafana/agent#2534]
The yaml containing the CRD for _metricsinstances.monitoring.grafana.com_ on the release `v0.29.0` is invalid. It contains a duplicated _oauth2_ key on the same yaml level. The first key appears at `/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/remoteWrite/oauth2`.

- https://github.com/grafana/agent/blob/v0.29.0/production/operator/crds/monitoring.grafana.com_metricsinstances.yaml#L269
- https://github.com/grafana/agent/blob/v0.29.0/production/operator/crds/monitoring.grafana.com_metricsinstances.yaml#L429

**Comment by marctc** [comment]
This issue is fixed. It wasn't properly closed when this was merged: https://github.com/grafana/agent/pull/2535
