### ISSUE TITLE
Add option to disable reporting in the config file

### ISSUE THREAD

**Issue by DeadNews** [grafana/agent#2540]
### Discussed in https://github.com/grafana/agent/discussions/2539

<div type='discussions-op-text'>

<sup>Originally posted by **DeadNews** November 15, 2022</sup>
https://github.com/grafana/agent/discussions/1777

> This is release `v0.25.0` of the Grafana Agent.
>     * As of this release, the Grafana Agent will send anonymous, but uniquely-identifiable information around enabled feature flags to `stats.grafana.org`.  Statistics help us better understand how Grafana Agent is used. This helps us prioritize features and documentation. If you would like to disable the reporting, Grafana Agent provides the flag `-disable-reporting`
>       to stop the reporting.

How to disable telemetry via `--config.file`, in `/etc/grafana-agent/grafana-agent.yml`?</div>

<div type='discussions-op-text'>

<sup>Originally posted by **rfratto** November 16, 2022</sup>
https://github.com/grafana/agent/discussions/2539#discussioncomment-4154124

 Hi, there is currently no way to disable reporting in the config file and it must be done via the `-disable-reporting` command line flag mentioned above.</div>

    

https://github.com/grafana/agent/issues/2540#tasklist-block-092a3036-8dee-4831-be2d-f87556dc2256

**Comment by marctc** [comment]
Hi @DeadNews. It sounds that it could be a good addition. Could you describe the use case? Thanks!

**Comment by DeadNews** [comment]
@marctc
Like [loki](https://github.com/grafana/loki/blob/0f139e2cb35daa9e56f8e0bbdaca472dbf802201/cmd/loki/loki-local-config.yaml#L48-L50), [mimir](https://grafana.com/docs/mimir/latest/operators-guide/configure/about-anonymous-usage-statistics-reporting/#disable-the-anonymous-usage-statistics-reporting) or [grafana](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#analytics).

**Comment by marctc** [comment]
Hi @DeadNews, I'm inclined to close this issue. In order to make config options suitable for the agent they should work in case you reload the config. This is not how it works currently and it would require further refactors. Furthermore, the initial use case for this was to report usage of feature flags, which now, can only be specified via command line flags.
