### ISSUE TITLE
[River config] http://localhost:12345 returns a 404 with the v0.29.0 Homebrew darwin/arm64 binaries

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/agent#2550]
When using the river config with the v0.29.0 Homebrew darwin/arm64 binaries, http://localhost:12345 returns a 404

**Comment by tpaschalis** [comment]
Thanks for the report!

It looks like when we're building other binaries (eg. for [linux/amd64](https://github.com/grafana/agent/blob/c3283babedc425cc2c4892289dc99379e8d641b5/tools/make/packaging.mk#L33-L37)) we call `make generate-ui` before the build, but we haven't updated the [homebrew formula](https://github.com/grafana/homebrew-grafana/blob/master/grafana-agent.rb) to do the same.

Also, the default configuration file that is created contains http_listen_port/grpc_listen_port which are no longer part of the configuration but are only configurable via command-line flags.

**Comment by rfratto** [comment]
The UI is now available when using the official Homebrew formula.
