### ISSUE TITLE
Proposal: Don't use quotation marks in block names

### ISSUE THREAD

**Issue by ptodev** [grafana/agent#2584]
When naming components, we currently use quotation marks like this:
```
prometheus.remote_write "default" { ... }
```
This may be confusing for users who then learn that to reference this component they need to use the dot notation, e.g.:
```
prometheus.remote_write.default.receiver
```
The quotation marks imply that the name is a string, but in reality it feels more like what would be a struct or a variable in some programming languages. Hence, it may be more intuitive to not use the quotation marks.

An alternative would be to keep the quotation marks but use bracket notation to refer to components:
```
prometheus.remote_write["default"].receiver 
```
However, @rfratto has advised that the bracket notation may not always work. Hence, if we are to keep the dot notation one would argue that the quotation marks make the dot notation a bit unintuitive.

**Comment by rfratto** [comment]
`prometheus.remote_write default` is less to type, and it's less work for users, but my immediate concern is if it's more confusing what the different between 

```river 
remote.write default {

}
```

and 

```river 
remote.write.default {

}
```

is.

**Comment by ptodev** [comment]
I've been brainstorming on alternative ways to do this, and came up with another potential issue. If the names of each component are unique, is it not unusual that we use the type of the component when we refer to it? E.g. in Go if we have an int `c`, we refer to it as `c` and not `int.c`.

If we don't use the component type when referring to it, then there would never be a situation where we write `remote.write.default`, so this would not be a problem.

**Comment by rfratto** [comment]
>  If the names of each component are unique, is it not unusual that we use the type of the component when we refer to it? E.g. in Go if we have an int c, we refer to it as c and not int.c.

The labels aren't unique, just the combination of component name + component label (which forms the unique ID)

**Comment by ptodev** [comment]
Yes, but there'd still have to be a uniqueness check to make sure there isn't more than one component of a given type with the same label. So I was wondering why not just make the label globally unique, and use only the label name to refer to the component. Then the syntax would be more in line with other programming languages, which would possibly make it more intuitive.

**Comment by ptodev** [comment]
Personally I'm ok with just ignoring the inconsistency between declaring components with quotations marks and referencing them with a dot. I'm quite used to the status quo by this point, and don't feel strongly against it 😄 

The only problem is I remember how weird it felt to me at the beginning, and I feel it might cause some head scratching to people new to Flow.

These are my preferences at the moment:
* I don't like how the quotation marks make the component names look like ordinary strings
* I like the dot notation for referencing components
* I would not want to use the map notation to reference components
* I like that if we use quotation marks when declaring component names, it makes the component name pop out in the text a little more. If we get rid of those quotation marks, it might make the config harder to read.

For those reasons, I'm personally ok with just closing this and potentially revisiting it in a few months/years when we have more real world feedback on Flow. 

If we do get rid of the quotation marks, maybe it'd be nice to invent another way to make the component name pop out in the config. Maybe something like this:

```
remote.write :: default { ... }
remote.write < default > { ... }
remote.write ~ default { ... }
remote.write | default { ... }
```
