### ISSUE TITLE
blackbox metric is collected when blackbox integration is disabled

### ISSUE THREAD

**Issue by v-zhuravlev** [grafana/agent#2627]
`blackbox_exporter_config_last_reload_successful: 0` metric returned by grafana agent 0.29 even if  blackbox_exporter integration is not enabled.

I think there could be two issues with this:
- We try to collect only metrics that are useful for users so, so users don’t pay too much if they use Grafana Cloud. Of course it just one metrics but…
- Also, since it has 0, it could trigger some blackbox exporter related alerts , as 0 actually means there is an issue with reloading config

**Comment by tpaschalis** [comment]
Adding a note; the issue should be around the blackbox_exporter using [init functions](https://github.com/search?q=repo%3Aprometheus%2Fblackbox_exporter%20init()&type=code) to register various metrics. Maybe we can work with upstream to move the registering logic and allow passing a custom registerer instead.

**Comment by rfratto** [comment]
IMO this should definitely be an upstream fix.
