### ISSUE TITLE
Syntax error when manually installing CRDs

### ISSUE THREAD

**Issue by jamunam** [grafana/agent#2693]
Hi

We are trying to manually install Grafana Agent and related CRDs with the command in our dedicated AKS cluster

`kubectl apply -f https://github.com/grafana/agent/tree/main/production/operator/crds`

We are getting this error -
`error: error parsing https://github.com/grafana/agent/tree/main/production/operator/crds: error converting YAML to JSON: yaml: line 165: mapping values are not allowed in this context
`
Please let us know how to proceed

**Comment by jamunam** [comment]
any updates?

**Comment by rfratto** [comment]
Hi @jamunam, where did you get those instructions from? I believe it's failing because the URL returns HTML, and kubectl is trying to parse the HTML content.

**Comment by rfratto** [comment]
If you download that folder to disk, or use raw.githubusercontent.com for each file (e.g., https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.coreos.com_podmonitors.yaml), then `kubectl apply -f URL` works as expected.

**Comment by karengermond** [comment]
I can see the confusion and it's resolved already in the "next" version of the docs.  

Here's the [current text](https://grafana.com/docs/agent/latest/operator/getting-started/#step-1-deploy-customresourcedefinitions):

The current set of CustomResourceDefinitions can be found in [production/operator/crds](https://github.com/grafana/agent/tree/main/production/operator/crds). Apply them from the root of this repository using:

`kubectl apply -f production/operator/crds`

Here's the [new text](https://grafana.com/docs/agent/next/operator/getting-started/#deploy-the-agent-operator-custom-resource-definitions-crds):

To deploy the CRDs:

1. Clone the agent repo and then apply the CRDs from the root of the agent repository:

    `kubectl apply -f production/operator/crds`

**Comment by jamunam** [comment]
@karengermond your solution worked! thanks
