### ISSUE TITLE
flow: Allow the `logging` block to send the Agent's own logs to`loki.*` components

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#2700]
Since we've implemented #2214, and introduced an initial set of Loki components, we can now consider allowing the logging block to forward the Agent's own logging to one or more `loki.*` components.

This would require adding a new `write_to` optional field, that treats logged entries as `loki.Entry` values and propagates them to the given list of `LogsReceiver` capsule values.

```
logging {
  level    = "debug"
  format   = "logfmt"
  write_to = [loki.write.local.receiver, loki.process.redact.receiver]
}
```

### Comments/Open Questions
- Should logs continue to be written in `stderr`? My gut feeling is that yes, the `write_to` field should not otherwise interfere with the Agent's logging.
- As with other places in the codebase where we fan out Loki entries, this happens over Go channels in sequence; this means that a blocked pipeline might delay other log lines from being sent. Should this be best-effort and use a timeout?
- Users will be able to use the OTel <-> Loki converters in #2501 to send them to an OTel logging pipeline. I don't think that it's particularly useful to have write_to support _two_ kinds of receivers at the same time.

**Comment by ptodev** [comment]
I personally agree that `write_to` should not interfere with the Agent's logging, and that it doesn't need to support Otel components.

However, what if there is a part of the Agent, e.g. a third party library, which logs to stderr/stdout but not through the Agent's logger? Would we still be able to capture this?

Also, just out of curiosity, do you know why we use stderr? I'd have thought that we would use stdout for non-errors and stderr for error logs only.
