### ISSUE TITLE
Flow: add utility to dump the WAL 

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2708]
It would be useful if Flow had agentctl-like utilities to dump the WAL to verify the final result of metrics post relabeling.

**Comment by tpaschalis** [comment]
Alternatively, could a similar thing be achieved via a metrics passthrough component that exposes metrics as DebugInfo? 

The component could either filter metrics with a selector, or use a sampling percentage.

**Comment by rfratto** [comment]
Maybe, but I'm worried that would be _way_ too much information for some agents. Our internal agents have a few million active series, which would be too much to show in the browser as DebugInfo. 

I'm also not sure how much confidence that would give me: the only way to be absolutely sure of what metrics are being remote_written is to look at the WAL (i.e., what if the prometheus.remote_write appendable has a bug which modifies the labels incorrectly?)

**Comment by rfratto** [comment]
I can see UI support being useful though. Instead of DebugInfo, maybe in the future a component API endpoint could be added to stream back the metrics? 

But I think that would be a supplement to a command-line tool which would allow you to do it offline without an agent running.
