### ISSUE TITLE
flow: Better trouleshooting for `loki` pipelines

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#2736]
To troubleshoot a Loki pipeline, it might be useful to mimic Promtail's dry-run mode. 

One way to go about it would be to have a `loki.stdout` component that other components could forward entries to and allow the users to inspect the logs flowing in real time.

This has one crucial difference to Promtail's dry-run mode, where the positions file is _not_ updated, so when Promtail runs in its normal mode again, the entries will be re-read and passed through the pipeline. If we wanted to also add support for this, it would need to be at the tailers level, eg. with a new Argument on the `loki.source.file` component.

**Comment by rfratto** [comment]
I like the idea of a `loki.stdout` component for debugging.

Should we try to introduce a `sink` namespace (`loki.sink.stdout`) or leave it as `loki.stdout`? 

> If we wanted to also add support for this, it would need to be at the tailers level, eg. with a new Argument on the loki.source.file component.

SGTM. Maybe we can call it `cache_target_positions` or something and default it to true?
