### ISSUE TITLE
/bin/grafana-agent: no such file or directory

### ISSUE THREAD

**Issue by lehuyv** [grafana/agent#2760]
Hi,

I'm getting the following error:

`Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/grafana-agent": stat /bin/grafana-agent: no such file or directory: unknown`

when I try the https://github.com/grafana/agent/blob/main/production/kubernetes/agent-bare.yaml

STEP to reproduce:
Under MicroK8s for Windows
or
Under K3s in WSL2

Apply the following configmap [Replacing value in square bracket]:

`kind: ConfigMap`
`metadata:`
`  name: grafana-agent`
`apiVersion: v1`
`data:`
`  agent.yaml: |`
`    metrics:`
`      wal_directory: /var/lib/agent/wal`
`      global:`
`        scrape_interval: 60s`
`        external_labels:`
`          cluster: [Name of your Cluster]`
`      configs:`
`      - name: integrations`
`        remote_write:`
`        - url: [URL to push]`
`          send_exemplars: true`
`          basic_auth:`
`            username: [User Name]`
`            password: [Pass Word]`
`        scrape_configs:`
`        - job_name: agent`
`          static_configs:`
`            - targets: ['A.PC.NAME:5050']`

Then apply the latest agent-bare.yaml for the v0.30.2 release.

**Comment by tpaschalis** [comment]
Hey there 👋 The binary names are being renamed to add the `grafana-` prefix, but this is a change in the upcoming v0.31 release.

Which image tag are you running your manifest with? Is there any chance you're importing a newer image than `v0.30.2` manually on your cluster's registry?

**Comment by lehuyv** [comment]
Thanks,

In the current [agent-bare.yaml](https://github.com/grafana/agent/blob/main/production/kubernetes/agent-bare.yaml)
Line 82: /bin/grafana-agent
Line 88: grafana-agent:v0.30.2

Changing line 82 to /bin/agent will fix the problem.

**Comment by tpaschalis** [comment]
Oh, I see.

Feel free to use the `agent-bare.yaml` manifest from the v0.30.2 tag or the `release-v0.30` branch, so that it goes hand-in-hand with the Agent image version until v0.31 is out.

**Comment by rfratto** [comment]
Fixed by #2747. 

Going forward, I'd recommend using the manifests from the release branch instead of main: https://github.com/grafana/agent/blob/release/production/kubernetes/agent-bare.yaml
