### ISSUE TITLE
Support Windows.

### ISSUE THREAD

**Issue by jeschkies** [grafana/agent#277]
It would be create to have a Windows build so that we could monitor Windows machines as well.

**Comment by rfratto** [comment]
We [do provide Windows builds](https://github.com/grafana/agent/releases/tag/v0.8.0) as release assets. Are you talking about a specific feature in particular?

**Comment by jeschkies** [comment]
No, then it's perfect and we can add the Windows exporter eventually. I thought there was no Windows build :slightly_smiling_face:
