### ISSUE TITLE
Proposal: add Flow `debug.variables` component 

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2772]
(Originally discussed in [#2766](https://github.com/grafana/agent/issues/2766#issuecomment-1385983680))

I propose a new component called `debug.variables`, which defines a set of variables that can be changed by invoking an API endpoint: 

```river 
logging {
  level = debug.variables.default.loglevel 
}

debug.variables "default" {
  variable "loglevel" {
    default = "info"
  }
}
```

Then, one could change the values of variables using the API:

```
curl -XPOST -d '"debug"' https://localhost:12345/components/debug.variables.default/loglevel
```

I think a component like this provides some basic level of remote configuration that would be helpful specifically for debugging without having to update the config file. This would also integrate well with conditionals (#2638) to allow dynamically switching between where data get sent: 

```river 
debug.variables "default" {
  variable "uselocalprom" {
    default = false 
  }
}

prometheus.remote_write "default" {
  client {
    // Syntax for conditionals not final; see #2638 for more details.
    url = (
      if debug.variables.default.uselocalprom 
      then env("LOCAL_PROMETHEUS") 
      else env("CLOUD_PROMETHEUS")
    )
  }
}
```

### Details 

The `variable` block is a labeled block which defines an individual variable whose value can change. The label of the block defines the name of the variable. The `default` attribute provides the original value for the variable. The `default` attribute is ignored if a user has provided an explicit value via the API. 

Variable values must be a type which can be represented in JSON:

* Boolean
* Number 
* String 
* Object 
* Array 

Arrays can only have elements matching any of the above types, and Objects can only have values matching any of the above types. 

For the initial implementation, it will not be possible to use River expressions from the API, so no capsule values can be used. 

### UI integration

The UI could show a special view for `debug.variables` which would allow changing the values for variables within the UI itself (and showing the current values).

**Comment by mattdurham** [comment]
I like this,  the only part I am a bit hesitant about is the UI integration.

**Comment by rfratto** [comment]
As discussed during the proposal review in the community call, we think that this encourages bad behavior, where debug hooks are left in the config file permanently. We think that changing the config file when you need to test out another value is a healthier approach, so we decided to reject this for now.
