### ISSUE TITLE
Grafana-agent-operator metrics shard: secret "grafana-agent-metrics-shard-1-config" not found

### ISSUE THREAD

**Issue by kovaxur** [grafana/agent#2779]
Hi,
We are using grafana-agent-operator with sharded metrics instances, currently 3 shard is running, two of the shards are unable to start, because they can't find their configs as secrets:

![image](https://user-images.githubusercontent.com/9846259/213478999-4367a8de-e399-4da7-87a4-35a886541891.png)

Error message: 
```
MountVolume.SetUp failed for volume "config" : secret "grafana-agent-metrics-shard-1-config" not found
```
Operator was installed via helm, version: 0.2.3
CRD versions: v0.9.2

The same setup works with helm version 0.2.0 and CRD version v0.9.2 without any issues. The operator either not generating the secrets or it uses a wrong name.

**Comment by jcreixell** [comment]
@kovaxur could you please test v0.33 and let us know if you still have this issue?

**Comment by rfratto** [comment]
Hi, this issue seems abandoned and we weren't able to reproduce, so I'm going to close this for now. If people are experiencing this issue and can help us reproduce, please open a new issue for tracking; we won't see any further comments on this issue.
