### ISSUE TITLE
Flow: allow receiving remote_write metrics over HTTP

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2780]
The static mode [supports sending metrics over HTTP](https://grafana.com/docs/agent/latest/api/#accept-remote_write-requests) to a metrics instance, but there is no Flow equivalent for this yet. 

I see two paths:

1. Add an API endpoint for `prometheus.remote_write` that allows external processes to send metrics to it over the network (i.e., `/components/prometheus.remote_write.default/remote_write`) 
2. Create a new component dedicated to receiving metrics over the network, which would allow it to be chained into other components for processing. 

Option 2 is probably immediately preferable for its increased flexibility.

**Comment by thampiotr** [comment]
Proposing to take path 2 and the component to be called `prometheus.source.api`.
