### ISSUE TITLE
Forward Windows NPS Logs

### ISSUE THREAD

**Issue by LSNIGHTSHOT** [grafana/agent#2782]
Would anyone be willing to help me make a configuration file to forward Windows NPS logs to Grafana using the agent?

Thanks.

**Comment by tpaschalis** [comment]
Hey, thanks for reaching out!

Feel free to check out our documentation pages. We have examples of a [full](https://grafana.com/docs/agent/latest/configuration/create-config-file/#full-config-example) configuration file, you can only keep the logs part if you're not interested in metrics or traces. Then, check out our [logs config](https://grafana.com/docs/agent/latest/configuration/logs-config/) page, which borrows Promtail's configuration. I suspect you might need a `windows_events` block under your `scrape_configs` key to configure getting logs.

Also, feel free to check out out [Community Slack](https://slack.grafana.com/) for such discussions as well!

**Comment by tpaschalis** [comment]
I'm closing this as our docs should cover this. If you still need any help feel free to reach out on our community Slack or start a new discussion.
