### ISSUE TITLE
grafana-agent-xxx                      0/1     ProviderFailed   0          6m51s

### ISSUE THREAD

**Issue by arkachat** [grafana/agent#279]
Events:
  Type     Reason                Age                   From                                   Message
  ----     ------                ----                  ----                                   -------
  Normal   Scheduled             2m14s                 default-scheduler                      Successfully assigned observability/grafana-agent-78ggz to virtual-node-aci-linux
  Warning  ProviderCreateFailed  51s (x14 over 2m14s)  virtual-node-aci-linux/pod-controller  ACI does not support providing args without specifying the command. Please supply both command and args to the pod spec.

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"37c06f456fdb4d25e402b5fbcb72cd6a77a021a9", GitTreeState:"clean", BuildDate:"2020-09-18T21:59:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rfratto** [comment]
Hi, have you tried adding the `command` to the Kubernetes manifest? `[/bin/agent]` should work. I haven't run into this before, it seems to be an Azure-specific problem.

**Comment by arkachat** [comment]
Thanks for the tip @rfratto  , lemme try it
