### ISSUE TITLE
Grafana agent failed to start as a windows service

### ISSUE THREAD

**Issue by gvillalta99** [grafana/agent#282]
Hi everyone, first of all, I'd like to thanks you all for this project, it is amazing!

So, to give you some context about what I'm trying to do, I'm setting up a monitoring infrastructure on some windows servers, to do so I'm trying to use [prometheus/windows_exporter](https://github.com/prometheus-community/windows_exporter) with grafana agent to send the metrics to our grafana cloud account.

I've already tested running the executable manually and it works like a charm, sending all the metrics to our grafana cloud. But I'd like to setup the windows service, so I don't have to manage it manually.

I'm trying to do so with the following PowerShell script:
```powershell
$params = @{
  Name = "grafana_agent"
  BinaryPathName = "C:\apps\grafana-cloud-agent\agent.exe -config.file=C:\apps\grafana-cloud-agent\agent.conf"
  DisplayName = "Grafana Agent"
  StartupType = "Automatic"
  Description = "Grafana Cloud Agent"
}
New-Service @params
#Start-Service -Name "grafana_agent"
```

Unfortunately, when I try to start the service it fails with the following error:
`Error 1053: The service did not respond to the start or control request in a timely fashion`

Am I missing something?

**Comment by rfratto** [comment]
Hi! 

Unfortunately I have no knowledge about Windows services. I'm asking around my team to see if anyone can chime in here, but until then I'll do the best I can. 

So, to make sure I understand: you can run that command normally but when you run it as a service, it doesn't start? I take it there's no logs anywhere, either? (Guessing they'd go to the Windows Event Log if there were any, but I'm not sure how this works).

I took a look at the docs for [`New-Service`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service?view=powershell-7.1) and one thing that sticks out is how `BinaryPathName` in their examples are quoted twice:

```
New-Service -Name "TestService" -BinaryPathName '"C:\WINDOWS\System32\svchost.exe -k netsvcs"'
```

Perhaps you need to do the same?

```powershell
$params = @{
  Name = "grafana_agent"
  BinaryPathName = '"C:\apps\grafana-cloud-agent\agent.exe -config.file=C:\apps\grafana-cloud-agent\agent.conf"'
  DisplayName = "Grafana Agent"
  StartupType = "Automatic"
  Description = "Grafana Cloud Agent"
}
New-Service @params
#Start-Service -Name "grafana_agent"
```

**Comment by gvillalta99** [comment]
When I try wrapping the `BynaryPathName` with an extra `'` it gets even weirder:

<img width="439" alt="Screen Shot 2020-12-09 at 15 26 59" src="https://user-images.githubusercontent.com/396968/101671331-2006ed00-3a33-11eb-86d0-2ab776f21ff2.png">

Without the extra `'` it sends some metrics to grafana cloud and after a while Windows kills it with error 1053.

**Comment by rfratto** [comment]
Gotcha, I'm able to see that same behavior. It looks like you can't just [run any executable as a Windows service](https://stackoverflow.com/questions/3582108/create-windows-service-from-executable), and the Grafana Cloud Agent doesn't implement the methods needed to operate as a Windows service.

As an alternative, you can try [NSSM](http://nssm.cc/) which I read people have used before to run the Agent as a service. A quick google search for "running Prometheus as a service" turned up [this article](https://www.coretechnologies.com/products/AlwaysUp/Apps/InstallPrometheusAsAWindowsService.html), though I'd probably recommend trying NSSM first since I know people have successfully used that.

**Comment by gvillalta99** [comment]
Thanks @rfratto, I'l try it.
