### ISSUE TITLE
add support for modules into flow

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#2834]
Add support for "modules," a way to encapsulate entire Flow configuration files as components. Modules should support being given arguments and having exports like any other component would.

Modules allow for reusing and sharing complex, common configs.  

Design doc RFC incoming.

<TBD>

Relates to https://github.com/grafana/agent/issues/2560

**Comment by erikbaranowski** [comment]
Closing with the introduction of modules in v0.33.0
