### ISSUE TITLE
Support running as a Windows Service

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#287]
Add an optional `-windows-svc` flag that starts the Agent in Windows service mode. The flag is needed to maintain backwards compatbility with users using tools like NSSM to run the Agent as a service; it seems like NSSM may break if Windows service mode is blindly entered. 

Note that if this service is used, logs should be sent to the Windows Event Log. A shim to map go-kit logs to the Windows Event Log will need to be included.

The [`golang.org/x/sys/windows/svc`](https://pkg.go.dev/golang.org/x/sys/windows/svc) package can be used to run as a service. The Go team has an [example application that uses this package](https://github.com/golang/sys/blob/master/windows/svc/example/main.go).

**Comment by rfratto** [comment]
I'm labeling this as help wanted for now. While we do want to improve Windows support, we have other things prioritized at the moment, so a community PR to get this sooner rather than later would be great.

**Comment by te4336** [comment]
@rfratto Would it be possible for someone to add Windows config info to the documentation on the production docs? There is a Windows package to install the agent but there is zero documentation about it. We have about 11,000 Windows based servers, if not more, and this would be a huge assistance in gaining adoption. I know that Windows might not be a primary focus but not having the service portion or even documentation in order is a huge barrier for large enterprises that still have a large Windows footprint even  if they are migrating to the Cloud or to Linux and need to have a deployment strategy.

**Comment by rfratto** [comment]
> Would it be possible for someone to add Windows config info to the documentation on the production docs? There is a Windows package to install the agent but there is zero documentation about it.

Absolutely, and I'm sorry that the Windows experience hasn't been great to date. This (and #285) are going to be huge for this, and documentation will follow shortly afterwards. Stay tuned for this, we might have someone putting their effort into the Windows experience sometime in January. 

From the documentation perspective, the good news is there shouldn't be much to add for Windows users. Unless I'm mistaken, I'm pretty sure the only thing that would differ between Unix and Windows users are the file paths (ie WAL directory).

**Comment by te4336** [comment]
@rfratto We are currently using the 0.9.1 release and when trying to run the .exe for the agent from the command prompt it return the error that it's not a recognizable service or program in windows. Is this something that is known for that particular release? I believe we were hitting a roadblock like this with the other releases as well so not sure if something else needs to be included with the .exe or if there is a particular way we need to run it, that is why I mentioned the documentation as there is nothing anywhere regarding the Windows version of the agent.

**Comment by te4336** [comment]
The actual error for the issue I just mentioned is that the .exe is not recognized as an internal or external command, operable program or batch file.

**Comment by rfratto** [comment]
Can you share the command you're running? It sounds you need to give the absolute path to the Agent as part of the command or put the Agent .exe in one of the folders of your `%PATH%`.

**Comment by te4336** [comment]
Well that is the thing, since there isn't any documentation for that version we tried double clicking on the .exe as well as running it inside the folder via command line by running agent-windows-amd64.exe

**Comment by rfratto** [comment]
I understand you're waiting for the documentation, but I don't have an update for when it will be available yet. 

I want to keep this issue locked down to just talking about the Windows Service feature. If you create a [discussion](https://github.com/grafana/agent/discussions) with the exact command you've tried inside the command prompt I'll be more than happy to help get you up and running.

**Comment by te4336** [comment]
@rfratto Sure thing I can definitely do that. Thanks for the assistance!

**Comment by rfratto** [comment]
@mattdurham Did #449 close this?

**Comment by mattdurham** [comment]
#449 solves half of this. It does NOT currently write to the windows event log anything beyond service status messages.

**Comment by mattdurham** [comment]
Checked and the service changes are backwards compatible with NSSM
