### ISSUE TITLE
Release asset name change problems

### ISSUE THREAD

**Issue by splitt3r** [grafana/agent#2884]
The binary install commands at https://github.com/grafana/agent/releases/tag/v0.31.0 are still using `agent` as the binary name.

The Windows binaries were zipped before e.g. `grafana-agent-windows-amd64.exe` was `grafana-agent-windows-amd64.exe.zip`. Now they are attached as plain exe. Is that change of behaviour intended? If so the braking changes should note that.

https://github.com/grafana/agent/releases/tag/v0.31.0 vs https://github.com/grafana/agent/releases/tag/v0.30.2

**Comment by marctc** [comment]
Good catch! Fixing now

**Comment by marctc** [comment]
> The Windows binaries were zipped before e.g. `grafana-agent-windows-amd64.exe` was `grafana-agent-windows-amd64.exe.zip`. Now they are attached as plain exe. Is that change of behaviour intended? If so the braking changes should note that.
> 
> https://github.com/grafana/agent/releases/tag/v0.31.0 vs https://github.com/grafana/agent/releases/tag/v0.30.2

I'm not sure about this, @erikbaranowski do you know?

**Comment by erikbaranowski** [comment]
I'm continuing the conversation in #2887 for this issue
