### ISSUE TITLE
The Windows binaries were zipped before rename

### ISSUE THREAD

**Issue by splitt3r** [grafana/agent#2887]
> The Windows binaries were zipped before e.g. `grafana-agent-windows-amd64.exe` was `grafana-agent-windows-amd64.exe.zip`. Now they are attached as plain exe. Is that change of behaviour intended? If so the braking changes should note that.
> 
> https://github.com/grafana/agent/releases/tag/v0.31.0 vs https://github.com/grafana/agent/releases/tag/v0.30.2

I'm not sure about this, @erikbaranowski do you know?

_Originally posted by @marctc in https://github.com/grafana/agent/issues/2884#issuecomment-1411805235_

**Comment by erikbaranowski** [comment]
I'm looking at it now

**Comment by erikbaranowski** [comment]
@rfratto it looks like this was intentional from the comment added so maybe we need to document as @splitt3r mentioned?

https://github.com/grafana/agent/commit/6f9bae516fd109234f48d1891612e6f019ef857a

**Comment by rfratto** [comment]
I got the logic wrong, the `.exe` installer was never zipped, so I excluded all exe (I didn't notice there were other zipped exes). 

Whatever we pick, we should be consistent and document it accordingly.
