### ISSUE TITLE
River: permit unmarshaling blocks to maps 

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2903]
I'd like to be able to unmarshal a River block into a `map[string]T`. This will allow for using the block syntax for unmarshaling blocks where the schema isn't known fully at parse time. This ability was mentioned as a possible future enhancement in a code comment: 

https://github.com/grafana/agent/blob/d7dd485c52af68cec8faad0247233d794a5eef58/pkg/river/vm/vm.go#L105-L109

Allowing `map[string]interface{}` would be especially useful for #2898, where 

```river
module.single "mysql" {
  content   = local.file.mysql.content
  arguments = {
    "password" = PASSWORD,
    "username" = USERNAME,
  }
}
```

can become:

```river 
module.single "mysql" {
  content = local.file.mysql.content
  arguments {
    password = PASSWORD
    username = USERNAME
  }
}
```

which would be much easier on users who are using a lot of modules.

I can also see maps being useful for [headers in phlare.write's endpoint block](https://grafana.com/docs/agent/latest/flow/reference/components/phlare.write/#endpoint-block) or [match_labels in mimir.rules.kubernetes](https://grafana.com/docs/agent/latest/flow/reference/components/mimir.rules.kubernetes/#label_selector-block).

The downside to enabling this would be making blocks inconsistent, where there's not always a fixed schema which is checked by the River evaluator. 

cc @mattdurham @tpaschalis for thoughts.

**Comment by mattdurham** [comment]
This feels like a good quality of life enhancement for modules.

**Comment by rfratto** [comment]
@erikbaranowski What do you think about us scoping this in for v0.33 since it would be a breaking change to module loaders? I can help out with it; it shouldn't be too much effort to implement.

**Comment by rfratto** [comment]
also cc @tpaschalis for thoughts on shifting it to v0.33.

**Comment by rfratto** [comment]
I decided to throw together a PR just in case we want it: #3232
