### ISSUE TITLE
OTEL: transformprocessor

### ISSUE THREAD

**Issue by gouthamve** [grafana/agent#2910]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor is a powerful processor to modify OTLP data.

**Comment by gouthamve** [comment]
This processor is set to replace the `resource` and `attributes` processors, and hence would be a good addition instead of those: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18643

**Comment by LittleLadySunshine** [comment]
Is this being worked on, actively? If so, can we please update the status to reflect current events.

**Comment by ptodev** [comment]
> Is this being worked on, actively? If so, can we please update the status to reflect current events.

The PR for this component was raised just now - #5337. I am confident that it will be included in the next Agent release.
