### ISSUE TITLE
how to change listen port 9090,9091

### ISSUE THREAD

**Issue by lovesharepc** [grafana/agent#2946]
hello 
I see grafana-agent will listen 
127.0.0.1:9090
127.0.0.1:9091 

how can I change listen port ?

**Comment by tpaschalis** [comment]
Hello there! The Agent's listen address for HTTP and gRPC connections are defined with the `-server.http.address` and `-server.grpc.address` command-line flags.

I guess you're running the Agent as a systemd service right? Then you'll need to change the Agent's service definition eg. using `systemctl edit`.

**Comment by tpaschalis** [comment]
I'm closing this issue as completed. Let us know if you need any more help by opening a new issue or in [Grafana's Community Slack](https://slack.grafana.com/)!

**Comment by durcon** [comment]
@tpaschalis 

Could you show an example?  Do I have to write 

```
-server.http.address 127.0.0.1:9999
```

or do I have to change `$CUSTOM_ARGS` with 

```
CUSTOM_ARGS="-server.http.address 127.0.0.1:9999"
```

What are the default values of  `$CUSTOM_ARGS` and do I have to repeat it in the override file?

**Comment by lovesharepc** [comment]
if you use deb install grafana-agent 

the systemd unit file will use env file

systemctl cat grafana-agent.service
```
EnvironmentFile=/etc/default/grafana-agent
```

the `$CUSTOM_ARGS` setting is in the this env file 

edit  /etc/default/grafana-agent to disable listen port
```
# CUSTOM_ARGS="-server.http.address=127.0.0.1:9090 -server.grpc.address=127.0.0.1:9091"
CUSTOM_ARGS=""
```
