### ISSUE TITLE
About git tags `external-v0.63.0-attempt3`, `external-v0.63.0-attempt4`

### ISSUE THREAD

**Issue by chenrui333** [grafana/agent#2961]
👋 It looks like the repo contains two seemingly test tags, namely `external-v0.63.0-attempt3` and `external-v0.63.0-attempt4`, not sure what they are for. Maybe we can delete it if not in use? Thanks!
<img width="417" alt="image" src="https://user-images.githubusercontent.com/1580956/217901910-79829d53-ce47-497c-98bb-266dd74391f8.png">

**Comment by rfratto** [comment]
It sounds like were pushed by a maintainer by mistake and went unnoticed. We just deleted them. Thanks for reporting!
