### ISSUE TITLE
Wrong asset url since v 0.31.0

### ISSUE THREAD

**Issue by suikast42** [grafana/agent#2963]
The docu shloud be https://github.com/grafana/agent/releases/download/v0.31.2/grafana-agent-linux-arm64.zip

![image](https://user-images.githubusercontent.com/5046525/217943253-64dde9a5-237d-41f9-9012-b6eb83e9f396.png)

**Comment by rfratto** [comment]
Thanks, this was originally fixed in #2885 but it looks like that change didn't make it into the release for v0.31.2. I updated the release description directly.
