### ISSUE TITLE
Spelling mistake in docs

### ISSUE THREAD

**Issue by Saideepak01** [grafana/agent#2969]
Spotted a spelling mistake in the grafana agent create confign file docs
<img width="519" alt="image" src="https://user-images.githubusercontent.com/68103212/218286971-c0b5abac-3e61-4910-8861-51128467ba7e.png">

**Comment by Saideepak01** [comment]
https://github.com/grafana/agent/pull/2968 PR for the same changes include the corrected work

**Comment by rfratto** [comment]
Closed by #2968
