### ISSUE TITLE
Flow: synchronize block names in remote.s3 and remote.http? 

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#3001]
`remote.s3` has a block called `client_options`, while `remote.http` has a block called `client`. 

Should they be synchronized to use a common name?

**Comment by polyrain** [comment]
It would be useful to sync these up with the other remote options as well; for example, `prometheus.remote_write` and `phlare.write` both call their configuration `http_client_config`, which would imply these should be named something like `client_config` to be in sync with the rest of the component ecosystem. Of course, the squashing that's been happening lately might render this point moot.

**Comment by rfratto** [comment]
After offline discussion, we agreed to rename both blocks to `client`. As pointed out, `http_client_config` doesn't need to change, as it's currently being squashed. 

One concern is that people might assume that all `client` blocks mean the same thing.
