### ISSUE TITLE
Grafana Agent Failing on PI  and Atom Processors

### ISSUE THREAD

**Issue by jimthedj65** [grafana/agent#3012]
Hi All,

I am installing the grafana agent for various boxes and seem tpo have an issue with edge boxes

**Raspberry pi Armv7** on install of agent I get ```5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux```
(Reading database ... 47458 files and directories currently installed.)
Preparing to unpack /tmp/grafana-agent.deb ...
Unpacking grafana-agent (0.31.2-1) over (0.31.2-1) ...
Setting up grafana-agent (0.31.2-1) ...
--- Retrieving config and placing in /etc/grafana-agent.yaml
Failed to retrieve config

**Second system different architecture.**

**On the Atom 3000** using sudo ARCH="amd64" Installs ok but fails to start systemd unit file, it starts ok and fails after a few seconds.

```5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```

````grafana-agent.service - Monitoring system and forwarder
     Loaded: loaded (/lib/systemd/system/grafana-agent.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-02-16 14:06:38 UTC; 42min ago
       Docs: https://grafana.com/docs/agent/latest/
    Process: 799187 ExecStart=/usr/bin/grafana-agent --config.file $CONFIG_FILE $CUSTOM_ARGS (code=exited, status=1/FAILURE)
   Main PID: 799187 (code=exited, status=1/FAILURE)
        CPU: 264ms

Feb 16 14:06:38 myhostname systemd[1]: grafana-agent.service: Scheduled restart job, restart counter is at 5.
Feb 16 14:06:38 myhostname systemd[1]: Stopped Monitoring system and forwarder.
Feb 16 14:06:38 myhostname systemd[1]: grafana-agent.service: Start request repeated too quickly.
Feb 16 14:06:38 myhostname systemd[1]: grafana-agent.service: Failed with result 'exit-code'.
Feb 16 14:06:38 myhostname systemd[1]: Failed to start Monitoring system and forwarder.
```

```Feb 16 14:06:38 myhostname systemd[1]: grafana-agent.service: Start request repeated too quickly.
Feb 16 14:06:38 myhostname systemd[1]: grafana-agent.service: Failed with result 'exit-code'.
```

**Comment by jimthedj65** [comment]
FYI I am on the trial version of Grafana Cloud evaluating the agent.

**Comment by jimthedj65** [comment]
I manually copied the grafana-agent on a working system to the pi and that resolved the issue for the pi armv7. The atom C3000 refuses to start the agent

Thanks in advance for any assistance

**Comment by jimthedj65** [comment]
Ok thanks for the guidance, I wasn't sure if it was the build or the script.

**Comment by marctc** [comment]
Closingm @jimthedj65 feel free to reopen if you think issue you should exist here
