### ISSUE TITLE
Support starting log tailers at the end of files

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#3102]
Some Grafana Agent users may try to use Grafana Agent to collect historical log files which have tons of data on them. This can lead to increased resource consumption for logs which will never be stored (because they're outside of the acceptable time range), but still need to be read line-by-line since files get tailed starting at the beginning. 

Ideally, Flow components support a parameter for a maximum log age (such as only tailing Kubernetes logs which are newer than 4 hours old), but this isn't possible for files, where byte offsets in the file are used instead.

I would like to see an option added to `loki.source.file` which supports starting a log tailer at the end of files when a cached position is not found.

**Comment by rfratto** [comment]
This isn't as easy as it looks; just seeking to the end of the file may cause partial log lines to be sent. There needs to be some kind of consideration for either skipping a partial line or seeking backwards to the first newline character.

**Comment by wildum** [comment]
> Ideally, Flow components support a parameter for a maximum log age (such as only tailing Kubernetes logs which are newer than 4 hours old), but this isn't possible for files, where byte offsets in the file are used instead.

Assuming that the entries of a log file are sorted by timestamp, can't we just do a lower-bound binary search to find the offset that corresponds to the first log that matches the maximum log age? To do the search we would start at the middle (file_size/2) and then read a bunch of bytes starting at that offset (enough to get at least a full line), parse the first timestamp that we find, and then depending on this value we go higher or lower and continue the search till the lower bound is found. Once the offset is found, we can tail the file as we would have done with a cached position

**Comment by rfratto** [comment]
That may work, but the timestamps may not always be in a predictable format. There also may be files being tailed without traditional timestamps, including Linux kernel messages where the timestamps are relative to the boot time of the server. 

The final edge case is a user tailing a file that has no timestamp at all, but this would usually only be the case for something fully custom, as most software include some kind of timestamp with their log lines.

**Comment by wildum** [comment]
I see, we could define this option to work only we a specific set of formats.

Another simple but less fancy solution to avoid this constraint would be to offer the user to decide at which % of the file we should start reading. The user might know roughly that only the last 5% bytes of the file are relevant to him.

Because if we just read the file backward, when would we stop? Although we would start with the most relevant lines, we would read the whole file, no?

**Comment by rfratto** [comment]
> I see, we could define this option to work only we a specific set of formats.

Yes, that's possible. You would need to weigh the trade-offs between a max age field which uses a subset of formats and a offset field which uses position, and make a judgment call for which we should invest in. 

> Another simple but less fancy solution to avoid this constraint would be to offer the user to decide at which % of the file we should start reading. The user might know roughly that only the last 5% bytes of the file are relevant to him.

Can you expand on this scenario a little more? Since the size of the file constantly changes and there may be log spikes, I'm not sure how a user would know whether the most recent 5% is useful to them. 

> Because if we just read the file backward, when would we stop? Although we would start with the most relevant lines, we would read the whole file, no?

Generally speaking, the tailer cuts a log entry at every newline character, so you would do the same in reverse: stop seeking backwards at one of the newlines (depending on the logic you use), indicating the end of an entry. All subsequent entries after that one would then be sent to Loki.

**Comment by wildum** [comment]
> Can you expand on this scenario a little more? Since the size of the file constantly changes and there may be log spikes, I'm not sure how a user would know whether the most recent 5% is useful to them.

That's indeed not very practical, it would only work if the user has a rough idea of the logs distribution in the file. Depending on how much the user knows about it, he can take a safe guess and still filter out a big part of the file. But if he misses the relevant area then it's a problem which makes this solution not very good. But still worth mentioning because it requires very little effort on our side and still could skip some parts of the file.

>Generally speaking, the tailer cuts a log entry at every newline character, so you would do the same in reverse: stop seeking backward at one of the newlines (depending on the logic you use), indicating the end of an entry. All subsequent entries after that one would then be sent to Loki.

Sorry I was not clear, I meant, after how many entries do we stop? Do we continue reading backward line after line till we reach the beginning of the file? And what about new entries added at the end of the file while we are iterating backward?

**Comment by rfratto** [comment]
> Sorry I was not clear, I meant, after how many entries do we stop? Do we continue reading backward line after line till we reach the beginning of the file? And what about new entries added at the end of the file while we are iterating backward?

One potential implementation is:

1. When the tailer starts with "start at end of file" mode, seek to the end of the file in its current state.
2. Seek backwards until you find the first `\n` character. 
3. The tailer then starts on the first byte after the `\n` character. 

This would mean that the definition of "end of the file" is when the tailer started so it doesn't have to concern itself with writes made to the file after the tailer started.

**Comment by wildum** [comment]
> it doesn't have to concern itself with writes made to the file after the tailer started.

This is fine only if the log file is not used anymore. If there are still logs being written in the file then we should not ignore those.

Also, if the agent does not stop early then it will read line-by-line (backward) till it reaches the beginning of the file. That would not answer the problem of "increased resource consumption for logs which will never be stored (because they're outside of the acceptable time range)". That means we would recommend the user to manually stop the agent from reading the file once it has consumed "the relevant part of the logs"?

**Comment by wildum** [comment]
I experimented with the binary search:
- use the search to jump at different bytes in the file
- at every jump:
  - backtrack to the beginning of the line
  - read the full line and search for keywords "timestamp, t, ts, date"
  - if a keyword is found, extract and parse its value
  - if no keyword is found, parse the first bytes
  - when parsing, try all formats supported by the time package (https://go.dev/src/time/format.go)
  - check whether the time is before or after the maximum log age and continue the search accordingly
- when hitting twice the same log line, stop the binary search
- finish with a linear search forward or backward depending on the timestamp to find the exact point that matches the maximum log age
- return the position of this log and start tailing the file from there

Drawbacks of this approach:
- expects to have one timestamp per line (does not work with multiline logs)
- expects the file to be sorted per timestamp
- does not support all available formats

Support for multiline logs while trying to keep the flexibility in the formats would make things complicated and I'm not sure that this would be worth it.

**Comment by rfratto** [comment]
> This is fine only if the log file is not used anymore. If there are still logs being written in the file then we should not ignore those.

Sorry, I think you've misunderstood what I was saying. I was saying the initial seek to the "end" only needs to account for the size of the file at the time the tailer was started. New lines past that determined "end" would still be tailed once the tailer is running. 

> Also, if the agent does not stop early then it will read line-by-line (backward) till it reaches the beginning of the file. That would not answer the problem of "increased resource consumption for logs which will never be stored (because they're outside of the acceptable time range)". That means we would recommend the user to manually stop the agent from reading the file once it has consumed "the relevant part of the logs"?

I'm sorry, I'm not sure what this is talking about. I have two questions from your comment here: 

* Why would we never _not_ stop early? 
* Why would we recommend the user to manually stop the agent?

**Comment by wildum** [comment]
Aaaaah I get it now sorry. I thought that you wanted to read the log file in reverse, but I understand that now you mean that the agent should seek to the end and then start reading the new logs which will be added from this point on.
That means that if the agent starts in this mode, all existing logs in the file will be ignored and only the new incoming one will be added, right?

**Comment by rfratto** [comment]
> That means that if the agent starts in this mode, all existing logs in the file will be ignored and only the new incoming one will be added, right?

Right, but you do have to seek backwards slightly to the most recent newline so you don't end up sending a partial log if you seek to the end in the middle of a write.
