### ISSUE TITLE
Flow Modules: Add Unit Tests and Benchmarks 

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#3104]
Flow modules need more unit tests and benchmarks, ideally we should know the cost of spinning up thousands of subgraphs.

```[tasklist]
### Tasks
- [x] Add unit tests
- [ ] Add benchmarks
```

**Comment by erikbaranowski** [comment]
There's a lot of scenarios with modules. I'm not sure how much we can get/want automated testing for, but we should consider the overall picture to regression test module functionality as part of this issue or another.

To name a few
- Loading modules
- Reloading modules (invalid or valid)
- Multiple arguments
- Multiple exports
- Invalid module content
- Module loading another module

**Comment by mattdurham** [comment]
Closing since we havent seen performance issues and tests exist.
