### ISSUE TITLE
 otelcol.exporter.prometheus: add support for native Prometheus histograms

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#3120]
Add support for Prometheus native histograms (also called exponential histograms, sparse histograms) into `otelcol.exporter.prometheus`.

**Comment by wildum** [comment]
Opentelemetry forgot to expose the ZeroThreshold field. This threshold defines the interval of the ZeroBucket, without it we don't know which exemplars belong to this bucket. I made a PR to fix it: https://github.com/open-telemetry/opentelemetry-collector/pull/8769.
In the meantime we have several options to carry on with the ticket:
- not support the exemplars
- assign only the exemplars with the value 0 to the zerobucket
- not assign any exemplars to the zerobucket

Once Opentelemetry publishes a release containing the fix, we will need to update our dependency and update the code accordingly.

More context on exponential histogram: https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exponentialhistogram
