### ISSUE TITLE
hostPort not available in chart

### ISSUE THREAD

**Issue by pnathan** [grafana/agent#3129]
Hi,

When running the agent in a daemonset mode, it can be useful to attach the daemonset to a hostPort for UDP transmission of traces.

I would suggest patching to have hostPort be an optional parameter in the ExtraPorts area around here - 
https://github.com/grafana/agent/blob/main/operations/helm/charts/grafana-agent/templates/containers/_agent.yaml#L39

thanks!

**Comment by rfratto** [comment]
Hi, would you be interested in opening a PR to contribute `hostPort` support?
