### ISSUE TITLE
Grafana agent Windows .exe not running on Windows

### ISSUE THREAD

**Issue by te4336** [grafana/agent#315]
When trying to run the Grafana Agent on windows we receive an error that "the .exe is not recognized as an internal or external command, operable program or batch file." Normally a .exe can be ran from the command prompt simply by typing in the name of the .exe or by double-clicking on it in the GUI. This is for the 0.9.1 version however we have tried earlier versions as well with the same issue. We have also tried using the absolute path to no avail. This is also on Windows Server 2012 R2.

**Comment by rfratto** [comment]
Hi. I'm able to run the Agent successfully on my Windows machine. Please provide the following:

1. Share the exact line you are running in a command prompt 
2. Confirm that you are trying to run the agent on an AMD64 machine and not a 32-bit machine or an ARM machine. 
3. Confirm that you are running the command in the folder containing `agent-windows-amd64.exe`

**Comment by te4336** [comment]
I think I figured it out, it has to be located in the root path so it has to be in a folder on the c:\ directory and it can't be in a users folder when ran. I tried that and it tells me that it needs a config file which wasn't passed with the command for the agent to start.
