### ISSUE TITLE
Flow: Allow the ability to handle thousands of log files on a single machine 

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#3175]
Currently agent->promtail->fsnotify cannot handle 10s of thousands files on a single instance. The overhead of os.Stat being called every 250s along with opening hundreds of thousands of goroutines causes a ton of context switching. 

Since flow is taking the opportunity to import more of promtail this is a great time to see if we can make flow work well with thousands of instances. Traditionally depending on polling was done because we found filesystem events flakey.

**Comment by rfratto** [comment]
This has been addressed with #3560.
