### ISSUE TITLE
Agent installation on Kubernetes Envirnment

### ISSUE THREAD

**Issue by ChinmayMishra** [grafana/agent#319]
When installing Grafana cloud agent to our Kubernetes cluster I faced issues where no metrices are flowing to cortex. I fixed it and finally it is up and running. I am not sure if it is a issue with the configuration file provided. Please check and update if required.

Step 1: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/grafana/agent/release/production/kubernetes/install.sh)" | kubectl -ndefault apply -f -

Please note we are using a different namespace, so we change the -n to a new namespace.

Step 2: None of the metrics are flowing to Cortex.

Issue: For ClusterRoleBinding, ServiceAcount is still tagged to the default namespace. 

Fix: After changing the namespace all metrices start flowing to cortex.

**Comment by rfratto** [comment]
Thanks for reporting this! This is definitely an issue with the install script; we'll probably need to add the namespace as an option that can be added to the script.
