### ISSUE TITLE
River: Parts of expression are ignored

### ISSUE THREAD

**Issue by ptodev** [grafana/agent#3222]
When parsing the `{ a = 15 }.7` expression, it gets formatted as `map[string]interface {}` with one element - the string key of "a" and an int value of 15. The `.7` part is seemingly ignored. Instead, I'd have expected an error to be thrown that there is no element `7`. 

Similarly, the result of the expression `7.8.5` is a float64 value of 7.8 and the `.5` part is ignored. I'd have expected to see an error for the `.5` part here too.

**Comment by rfratto** [comment]
This is only true when calling ParseExpression, so you could only hit this when calling that function (which is never called from Flow)
