### ISSUE TITLE
Feature request: Configuration validation

### ISSUE THREAD

**Issue by exFalso** [grafana/agent#329]
Hi, it would be great if the agent could load and validate its configuration without actually starting. This would enable a static check of the configuration before deployment.

**Comment by rfratto** [comment]
Hey! I agree this would be nice, but it could be pretty difficult to implement generally. For example, there's not a standard remote_write URL that can be used to validate credentials. Other validations might only be possible to check at runtime, such as if your `relabel_rules` are valid. 

What types of validations are you interested in specifically?

**Comment by exFalso** [comment]
(Wow fast response!)

The reason I thought of this is that I got an "unmarshall" error for my yaml (I think it was the server http_listen_port setting) because I used a `=` instead of a `:`. I added a yamllint pass but that doesn't catch this error, it's specific to grafana agent.
So I think perhaps a good tradeoff for validation is to simply deserialize the config to make sure the types align.

**Comment by rfratto** [comment]
Ahh, I see now. We can totally do this! Would you care if it's a part of `agentctl` as a `check-config` command? Or would you prefer it to be some kind of a flag on the main Agent binary?

(FWIW, today, `agentctl` isn't included in the main `agent` image, but we can change this too)

**Comment by exFalso** [comment]
Both would make sense. We actually build/package the agent from source and include the `agentctl` binary, so either works for us.
