### ISSUE TITLE
Non-obvious Flow map(string) syntax when special characters are used in a label.

### ISSUE THREAD

**Issue by jacobstr** [grafana/agent#3304]
Looking to configure a prometheus rule that matches rules with a label that may contain `/` or `.` - both are legal characters in a typical [kubernetes label](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set).

E.g. The agent itself using chart defaults has this k8s label:

```
labels:
    app.kubernetes.io/instance: grafana-agent
```

The docs indicated `map(string)` as the type when using `match_labels` in the mimir rule forwarding component. I've tried the following:

YOLO:

```
mimir.rules.kubernetes "default" {
        match_labels {
          grafana.example.com/forward = "true"
        }
}
```

Double quote the key? This is my principle-of-least-surprise favorite given experience in jsonnet and yaml.
```
mimir.rules.kubernetes "default" {
        match_labels {
          "grafana.example.com/forward" = "true"
        }
}
```

Single-quotes?

```
mimir.rules.kubernetes "default" {
        match_labels {
          'grafana.example.com/forward' = "true"
        }
}
```

Escape a special character?

```
mimir.rules.kubernetes "default" {
        match_labels {
          grafana\/forward = "true"
        }
}
```

---

Random thoughts that I hope convey my confusion:

* Vaguely, I'd expect something in the [documentation here](https://grafana.com/docs/agent/latest/flow/config-language/expressions/types_and_values/#objects) specific to map types. It's really left up to guesswork like I did above to determine what the syntax is - if any.
* If the language can't support this - well that's a bit of a conundrum because kubernetes labels _do_ allow characters that might not typically comprise a valid `identifier` or `block label`. 
* Examples in [loki](https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.podlogs/#usage) and [mimir](https://grafana.com/docs/agent/latest/flow/reference/components/mimir.rules.kubernetes/) would benefit from using non-trivial examples for these label selectors.
* The "BNF"-looking spec for the language suggests https://grafana.com/docs/agent/latest/flow/config-language/syntax/#identifiers  that `grafana.example.com/forward` is an identifier and claims that any UTF-8 ~character~ letter is valid.
  * Which would be somewhat difficult since the identifier obviously can't have spaces or an equal sign if it wants to get lexed.
  * `UTF-8 letters, digits or underscores, but doesn’t start with a digit` stated in the docs. I don't actually know what a UTF-8 letter is , I suppose.

**Comment by jacobstr** [comment]
Aight. Here it is:

```
mimir.rules.kubernetes "default" {
	rule_selector {
		match_labels = {
			"grafana.example.com/forward" = "true",
		}
        }
}
``

**Comment by rfratto** [comment]
Sorry for the confusion here, we'll try to clear up some of the documentation to make this easier to follow.

**Comment by jacobstr** [comment]
So... if I had just copypasta'd the example I would have been fine 😅. I think the confusion was largely the result of the `fmt` not catching the wonky invalid `block`. The `match_labels {` without the `=` sign was not caught during fmt. At runtime, I would get an error message that also left me pursing the dead end of quoting / escaping the label `keys`.
