### ISSUE TITLE
Can we have a service setup in the default k8s install, so I can use it for traces?

### ISSUE THREAD

**Issue by tomwilkie** [grafana/agent#331]

**Comment by rfratto** [comment]
We do have a trace specific install, would that be good enough for you?

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/grafana/agent/release/production/kubernetes/install-tempo.sh)" | kubectl -ndefault apply -f -
```

I can add a service to the default K8s install but it would need to be edited along with the configmap to add the ports that are being used for listening to spans. Would that be fine for your use case?

**Comment by rfratto** [comment]
I think I'm partial to just doing an all-in-one install that has some reasonable defaults for everything so it can be used out of the box. I'll work on putting one together.
