### ISSUE TITLE
Integration test fails inside Nix sandbox

### ISSUE THREAD

**Issue by flokli** [grafana/agent#333]
I tried packaging `grafana/agent` for NixOS, and ran into an issue while running the tests:

```
=== RUN   TestIntegrationRegistration
--- PASS: TestIntegrationRegistration (0.00s)
PASS
ok      github.com/grafana/agent/pkg/integrations       2.548s
=== RUN   TestNodeExporter
    node_exporter_test.go:43:
                Error Trace:    node_exporter_test.go:43
                Error:          Received unexpected error:
                                failed to create node_exporter: failed to open sysfs: could not read /sys: stat /sys: no such file or directory
                Test:           TestNodeExporter
                Messages:       failed to setup node_exporter
--- FAIL: TestNodeExporter (0.00s)
=== RUN   TestNodeExporter_IgnoredFlags
```

Apparently the node exporter integration test tries to access `/sys`, which doesn't quite work in that sandboxed environment. Could the test be skipped in such cases?

**Comment by rfratto** [comment]
I'd be happy to add a build flag to make tests for that package skippable. I won't be able to work on this for a few more days, but if you want to take a shot at it, you're more than welcome to!

**Comment by flokli** [comment]
For now, [while packaging this in nixpkgs](https://github.com/NixOS/nixpkgs/pull/109573) I simply removed `pkg/integrations/node_exporter/node_exporter_test.go` before running the tests.

Inside Nix sandboxed builds, `/sys` simply doesn't exist. Maybe that test can skip if it detects `/sys` not being present.

**Comment by flokli** [comment]
still relevant.

**Comment by rfratto** [comment]
Hey @flokli, is this still a problem? Are there any other tests that are failing inside Nix that we can filter out?

**Comment by flokli** [comment]
I tried to re-roll this, but stumbled over https://github.com/grafana/agent/pull/773#pullrequestreview-734182163.

I think if we can get build flags to work, we should probably also add a flag for these, that needs to be enabled.

**Comment by flokli** [comment]
Okay, build flags seem to be the way to add conditional tests.

We could add a `integration` flag, filter these out, and set it in the drone config and Makefile.

But I'm not about the naming. I don't want to disable all these tests. Some integrations tests seem to work, even inside the sandbox. Should we skip them too, or call this flag `with_node_exporter_integration_tests`?

Why does the redis integration test not fail? I do see `time="2021-08-19T17:05:03Z" level=error msg="Couldn't connect to redis instance"` in the logs, but it still seem to initialize…

**Comment by rfratto** [comment]
Sorry for taking so long to get back to you @flokli, things have been busy and I lost track of some of these issues. 

This is a really interesting problem to have, and I'm not sure how to break this down. What are the limitations of the sandbox? No network, no access to host folders like /sys or /dev that something like node_exporter might use? 

It's starting to sound more and more like we might just need a `sandbox` tag, but I'm starting to question whether it's worthwhile running these tests in a restricted environment anyway. It'd ensure some base behavior of the Agent is functional, but could miss out on other things being broken. What do you think?

**Comment by rfratto** [comment]
> Yeah, certainly no network access, only private networking. I assume the sandbox also prevents access to some of these folders, to rule out hardware-specific impurities leaking into builds. /dev and /proc are also very minimal, not sure about /sys.
>
> It's not super well documented, but https://github.com/NixOS/nix/blob/bedd12ec14062bb23bbd87dd892219b84abbcce9/src/libstore/build/local-derivation-goal.cc#L1580 should get you an idea if you want to know exactly.

Thanks, this is helpful!

> More generally: What are the tests supposed to test? Why do the redis ones succeed, even though there's obviously no redis database started, and why does the node-exporter one fail even though it might only not be able to get some metrics?

I don't think we've been very consistent in testing these, but for integrations in particular, I'd say there's a few things we'd be interested in looking at:

1. Testing the translation from the agent's integration to the exporter's config (if a translation exists, sometimes the exporter's config is sufficient). 
2. A test where where we test the entire integration (including the exporter)

The first case can _probably_ just be performed as a unit test safely within a sandbox. The second case almost always requires network access (or root FS access for node_exporter), and it sounds like that's where we'd want to start using the sandbox flag.

**Comment by rfratto** [comment]
I'd like to close this as part of our normal bug cleanup process. If we run into similar issues again, we can open a new issue for tracking.
