### ISSUE TITLE
[helm] The helm chart has inconsistent indentation

### ISSUE THREAD

**Issue by carlosjgp** [grafana/agent#3341]
After raising a couple of PRs I've noticed that the Helm chart contains inconsistent indentation.

Would it be ok to raise a PR using [`yamllint`](https://github.com/adrienverge/yamllint), [used by Helm chart testing](https://github.com/helm/chart-testing#prerequisites) to detect this after generating the tests?

Alternatively, the whole project could use [`pre-commit`](https://pre-commit.com)

**Comment by carlosjgp** [comment]
I'm not sure chart-testing would highlight this because the project is not using the ["official" `ci` folder for `ct lint`](https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md)
> Charts may have multiple custom values files matching the glob pattern '*-values.yaml' in a directory named 'ci' in the root of the chart's directory. The chart is linted for each of these files. If no custom values file is present, the chart is linted with defaults.

My projects use this folder and render the tests (I called them examples) with the following script
```
#!/bin/bash

set -ex

helm repo up

# Find `ci` directories
for chart_file in $(find * -name Chart.yaml -print | sort); do
  # Find `.template` files
  dir=$(dirname ${chart_file})

  if [ -d "${dir}/ci" ]; then
    examples_dir="${dir}/examples"
    rm -rf ${examples_dir}
    mkdir -p ${examples_dir}
    for file in $(find ${dir}/ci -name "*-values.yaml" -type f); do
      # Render chart
      example_filename=$(basename ${file})
      helm dep build ${dir} --skip-refresh
      helm template ${dir} --values ${file} > "${examples_dir}/${example_filename}"
    done
  fi
done
```

**Comment by rfratto** [comment]
Ah, that's unfortunate. I wouldn't mind changing to use that folder structure / naming convention so we can take advantage of the linting rules.

**Comment by carlosjgp** [comment]
I'll raise a PR tomorrow
