### ISSUE TITLE
Agent Operator Helm charts

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#339]
The `kubernetes_sd_config` rules used by default tend to confuse people:

1. Pods must have a label named name
2. Pods must not have an annotation of "prometheus.io/scrape": "false"
3. Pods must have a named port to scrape metrics from, where the named port ends in "-metrics".

Specifically, the "label named name" is the most confusing. 

These rules were inherited from [prometheus-ksonnet](https://github.com/grafana/jsonnet-libs/tree/master/prometheus-ksonnet) but it would be nice to come up with a saner set of defaults, or perhaps find out what the default rules used by the Prometheus Helm chart is and use those instead.

**Comment by rfratto** [comment]
This will be handled by the Helm charts that install the Operator.

**Comment by jtyr** [comment]
I just would like to make a note here that apart of the [`agent-operator`](https://github.com/grafana/helm-charts/pull/599) Helm chart, I have also created [`agent`](https://github.com/grafana/helm-charts/pull/604) Helm chart.
