### ISSUE TITLE
Docs: Align scrape_interval in docs to 60s

### ISSUE THREAD

**Issue by digitalemil** [grafana/agent#3411]
When setting the scrape_interval to e.g. 15s and you are using Grafana Cloud please make sure the scrape interval is also reflected in your corresponding datasource settings. Otherwise the agent will scrape at an 15s interval but Grafana will still show just one data point per minute.

**Comment by mattdurham** [comment]
Example is https://github.com/grafana/agent/blob/5ad7c9abbbb69851760e82559fd23d75dcf28224/docs/sources/static/configuration/integrations/node-exporter-config.md?plain=1#L45
