### ISSUE TITLE
Flow:  loki.source.journal only one label (job)

### ISSUE THREAD

**Issue by emidevops** [grafana/agent#3460]
The documentation explains that other labels "are stripped unless a rule is created to retain the labels",  but give no clue of where and how this rule should be created.

**Comment by rfratto** [comment]
Thanks, we'll work on improving the docs here. In the meantime, you're expected to do something like this:

```river 
discovery.relabel "example" {
  targets = [] // Leave empty since you're using a different export. 

  rule { ... } 
  rule { ... } 
  ... 
}

loki.source.journal "example" {
  relabel_rules = discovery.relabel.example.rules 
}
```

cc @tpaschalis I think we should remove the required flag from `targets` in discovery.relabel since it doesn't really make sense when you're using the rules export.
