### ISSUE TITLE
Deprecate Flow component otelcol.exporter.jaeger

### ISSUE THREAD

**Issue by erikbaranowski** [grafana/agent#3495]
Jaeger gRPC Exporter is being deprecated in otel in favor of direct jaeger OTLP support.

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/jaegerexporter

**Comment by ptodev** [comment]
`otelcol.exporter.jaeger` has been labeled as deprecated as of v0.35
