### ISSUE TITLE
Synchronize Promtail stages with loki.process component

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#3519]
In the last couple of months, a few new Loki pipeline stages were introduced (`geoip`, `eventlogmessage`, `decolorize`, `sampling`.

The initial set of stages was based on grafana/loki@16761723f4f2dbdeece4697377239b99d25368fe which was our dependency version at the time; let's update for these stages and find a way to keep up with any new changes in the future.

**Comment by rfratto** [comment]
Is this a dupe of #3376?

**Comment by rfratto** [comment]
> I don't know if it makes any difference but please also update the classic configurtion to include the new changes. Not only Flow.

We don't have to do anything for static mode; we've already updated the Loki dependency to a recent version and that will automatically expose the new stages with the upcoming release. We have to do manual work with Flow mode, so we need a dedicated tracking ticket for that.

**Comment by tpaschalis** [comment]
Whoops, yes it is. I'm closing this Issue in favor of #3376
