### ISSUE TITLE
otelcol.exporter.prometheus doesn't include custom resource attributes for the metrics

### ISSUE THREAD

**Issue by paul-lysak** [grafana/agent#3520]
What's happening:
--------------------------

When using OpenTelemetry Java SDK for collecting the metrics  I've specified attributes `service.name`, `service.instance.id` and `some.other.attr` for the resource.
The `service.name` and `service.instance.id` attributes get converted to `job` and `instance` labels (which is expected) of the metrics, 
but `some.other.attr` simply disappears (which is not expected). I've tried the camel-case attribute name `someOtherAttr` as well, it also disappears.

I've tried to send metrics directly to Mimir over OTLP/HTTP and intercept the communication with WireShark, and I've seen all the three attributes included in the message as Resouce attributes (Mimir doesn't save custom attributes either, but that's another story) - so, I'm pretty sure that OpenTelemetry SDK is actually sending custom attributes as well as standard.

I'm running Grafana Agent in flow mode, here's the River configuration file for it:
```
logging {
  level  = "debug"
  format = "logfmt"
}

otelcol.receiver.otlp "default" {
  grpc {
    endpoint = "0.0.0.0:8317"
    include_metadata = true
  }
  http {
    endpoint = "0.0.0.0:8318"
  }

  output {
    metrics = [otelcol.exporter.prometheus.default.input]
    //traces = [otelcol.exporter.otlp.default.input]
  }
}

otelcol.exporter.prometheus "default" {
  include_target_info = true
  include_scope_info = true
  forward_to = [prometheus.remote_write.default.receiver]
}


prometheus.remote_write "default" {
  external_labels = {"grafana_agent_host" = "sample_host_1"}
  endpoint {
    url = "http://mimir:9009/api/v1/push"
  }
}


otelcol.exporter.otlp "default" {
  client {
    endpoint = "tempo:4317"
    tls {
      insecure = true
    }
  }
}

```

Observed behavior:
----------------------------
Custom attribute `some.other.attr` of the resource is dropped by `otelcol.exporter.prometheus`

Expected behavior:
----------------------------
Custom attribute `some.other.attr` should be forwarded as `some_other_attr` label by `otelcol.exporter.prometheus`

**Comment by rfratto** [comment]
Thanks, behavior you've noticed is from the [OpenTelemetry Specification for Prometheus and OpenMetrics Compatibility](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md), and I agree we should find a way to link to it from the component documentation (but I'm not sure we should try to mirror the documentation).
