### ISSUE TITLE
Docs feedback: /docs/sources/_index.md - A few suggestions

### ISSUE THREAD

**Issue by ethirolle** [grafana/agent#3526]
I am reviewing this doc page, and have a few suggestions:

* there is some awkward grammar & phrasing throughout the page, this doc might benefit from an overall review/edit by one of the G docs writers

* I am not sure why the word "on-call" is present in this sentence:
> Grafana Agent is for engineers, operators, or administrators who want to collect and forward telemetry data for analysis and on-call alerting.

* afaiu, the support for Grafana Agent Operator in Beta, and may be getting replaced, so would it make sense to remove this bullet?:
> * Provides the Grafana Agent Operator, which enables individual teams to manage their configurations through PodMonitors, ServiceMonitors, and Probes.

* and remove mention here?:
> Starting with the v0.28 release, a new minor release is planned for every 6 weeks. This includes a release for Grafana Agent, **Grafana Agent Operator**, and the agentctl binary.

* this "Scraping Service mode" link should probably go to the anchor on the same page (https://grafana.com/docs/agent/latest/#scraping-service), not to the separate page: https://github.com/grafana/agent/blob/3.2/docs/sources/_index.md?plain=1#L44

* check if we have already added support for OpenTelemetry HTTP format:
> The Grafana Agent is also capable of exporting to any OpenTelemetry GRPC compatible system.

Thanks!!

**Comment by rfratto** [comment]
Hi @ethirolle, we've recently (this morning) revamped the page you're talking about here; take a look at https://grafana.com/docs/agent/next/ to see what will be published with the next release on April 25.

**Comment by ethirolle** [comment]
Robert, thanks! The new docs look good, and I think they either directly resolve the issues I raised, or make them irrelevant, so I will go ahead and close this issue now 👍
