### ISSUE TITLE
tools/riverfmt: add riverfmt and riverval binaries to release

### ISSUE THREAD

**Issue by dosmanak** [grafana/agent#3549]
Could you build riverfmt and rivereval as part of release?

**Comment by rfratto** [comment]
Things in tools/ aren't considered to be official assets and can be removed at any time. Can you share more details on what you want these tools for?

**Comment by dosmanak** [comment]
Hi, your own vim plugin uses the tool It would be nice to download binary and not have to build my own.
https://github.com/rfratto/vim-river/commit/7a6c5d9480136f70178cdc6886b8baa36e285013

**Comment by rfratto** [comment]
River is being moved to a dedicated repo so other projects can make use of it. The new repo includes publishing riverfmt as part of it. 

You can download riverfmt from here: https://github.com/grafana/river/releases/tag/v0.1.0

(rivereval will probably get removed, since we don't use it)
