### ISSUE TITLE
Add support for metrics from traces

### ISSUE THREAD

**Issue by joe-elliott** [grafana/agent#357]
There is an incoming PR to the opentelemetry-collector-contrib repo that will allow the generation of metrics from traces:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2012

Once this is merged let's vendor and expose this config to our users.

**Comment by yeya24** [comment]
I am interested in working on this. Can I take it?

**Comment by rfratto** [comment]
@yeya24 sure, go for it! When you have a PR, @mapno will be able to review :)

**Comment by yeya24** [comment]
Hi, @joe-elliott @mapno. For the `spanmetricsprocessor`, how do you want to consume the generated metrics?

Do we want to use `prometheus` exporter or the `prometheusremotewrite` exporter (I guess not this one) or this is something configurable by users?

**Comment by mapno** [comment]
> Hi, @joe-elliott @mapno. For the `spanmetricsprocessor`, how do you want to consume the generated metrics?
> 
> Do we want to have one default exporter for the generated metrics or something else configurable by users?

Hi! I think a default Prometheus exporter is fine for a first pass. Ideally, the exporter will hook the metrics to the prometheus registry the Agent is already using.
