### ISSUE TITLE
flow: component/loki network based components should allow more configuration fields

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#3571]
The network-based targets we inherited from Loki make use of a `weaveworks.Server` implementation to accept requests.

In Loki/Promtail, the [YAML-based](https://grafana.com/docs/loki/next/clients/promtail/configuration/#server) configuration contains a more detailed server configuration, that also allows to accept gRPC connections. When we first introduced the components, the intermediate River configuration layer only accepted two options (listen address and port), and the rest of the fields were never wired up.

We should do two things:
- [ ] Make sure all the network-based components use the same underlying structs for unmarshaling and starting their server implementation
- [ ] Make sure that we support all the same configuration options that Promtail does

**Comment by rfratto** [comment]
There's a shared server now, which closes this issue.
