### ISSUE TITLE
Docs feedback: /docs/sources/configuration/integrations/cadvisor-config.md

### ISSUE THREAD

**Issue by ju4nmg** [grafana/agent#3585]
https://grafana.com/docs/agent/latest/configuration/integrations/cadvisor-config/

Actually add how to initialize cadvisor integration, this is overlooked but is not understandable for somebody who never used integrations

```
integrations:
  #Initilizes the cadvisor integration
   cadvisor:
        # Enables the cadvisor integration, allowing the Agent to automatically
        # collect metrics for the specified github objects.
        [enabled: <boolean> | default = false]
```

**Comment by marctc** [comment]
Hey @ju4nmg, is it actually explained [here](https://grafana.com/docs/agent/v0.33/static/configuration/integrations/cadvisor-config/). What other information do you think it's missing?

**Comment by marctc** [comment]
Closing due inactivity. Feel free to reopen with specific feedback.
