### ISSUE TITLE
agentctl: Show HTTP response on error from agentctl cloud-config

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#360]
`agentctl cloud-config` is the command used during the install script to retrieve the Grafana Cloud-generated config. If an invalid stack ID is passed to the install script, the error is just reported as a generic 404. However, the response body contains more information:

```{"status":"error","error":"stack '1' not found"}```

The error in the response body should be reported back to the user.

**Comment by ealmonte32** [comment]
Also, maybe the script should `break` when this happens, because when incorrect stack ID is passed, the script continues like enabling the agent service for example..:
```
--- Retrieving config and placing in /etc/grafana-agent.yaml
could not retrieve agent cloud config: unexpected status code 404
Failed to retrieve config
--- Enabling and starting grafana-agent.service
```

**Comment by rfratto** [comment]
Thanks! That's a good point, the script should definitely stop if that command fails. Seems like a bug in the script.

**Comment by ealmonte32** [comment]
Yeah I've been trying to fix it, but the problem as of now is that when the retrieve_config function is called, the fatal error and exit code of 1 happens inside that function only, thus when that function finishes, the script simply continues to the next set of commands.
What could be done is something like rewriting these functions in a way that if one step fails, the script terminates.
