### ISSUE TITLE
Flow: replace discovery_target_decode with components

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#3607]
discovery_target_decode was introduced as a way to act as a substitute for the functionality of Prometheus' HTTP and file discovery with `local.file` and `remote.http`. 

However, this approach was flawed: 

* Prometheus file discovery supports YAML files, which cannot be done with local.file/discovery_target_decode. 
* I think it was a mistake to introduce component-specific functions. 

I would like to replace `discovery_target_decode` with two components:

* `discovery.file_targets` for Prometheus' file SD. 
  * `discovery.file` is already in-use for file globbing, unless we renamed that component.  
* `discovery.http` for Prometheus' HTTP SD. 

And going forward, I'd like to change the guidelines around the stdlib to _not_ include any component-specific functions, and keep the stdlib generic. 

I'm looking for feedback on this proposal.

**Comment by zackman0010** [comment]
Hi! What's the priority on this kind of functionality? We recently moved to using file-based discovery for our own services, where on startup each service creates its own file in a specified folder. Our Static configuration uses file globbing to find all the files in that folder to dynamically locate the targets. We can't hardcode the files due to their usage of random ports, so the inability to dynamically read multiple files is unfortunately a hard blocker on us moving to use Flow.

**Comment by zackman0010** [comment]
@rfratto Just to share my own opinion, I like the second choice for one reason: the current existing `discovery.file` doesn't actually return the files themselves, it instead returns the file _paths_. So maybe the old could be renamed `discovery.filepath`?

**Comment by mattdurham** [comment]
Some random thoughts:
* A new and maybe not needed `local.files` should return a `map(string)` where the key is the filename and the value is the content. This aligns with `local.file`
* `discovery.file` stays as is
* `discovery.file_targets` handles a more label based Prometheus approach.

**Comment by mattdurham** [comment]
I should add that `local.files` likely is not immediately useful without adding some additional exports and functions.

**Comment by tpaschalis** [comment]
My 2c is to name the new component `discovery.file_targets`.

The thing is, keeping the current `discovery.file` name isn't doing us any favors, and might continue being confusing. Maybe we can _also_ rename the existing component to `discovery.fileglob` and have a clearer distinction of what each is doing?

> `local.files` should return a map(string) where the key is the filename and the value is the content
This could also be a module once/if #2783 is implemented, right?

**Comment by rfratto** [comment]
I'm comfortable with both components being renamed to not be ambiguous, especially if there's going to be two file-based discovery components. 

Though I don't know about `discovery.file_targets` being the right name, since both `discovery.fileglob` and `discovery.file_targets` emit a set of targets.

**Comment by rfratto** [comment]
It sounds like there's a few topics at hand to immediately discuss: 

1. Should `discovery_target_decode` be replaced with discovery components which map directly to Prometheus' file_sd_configs and http_sd_configs?
      1. If yes: What should they be called?  
2. Should `discovery.file` be renamed? 
      1. If yes: What should it be called?

Do we have rough consensus that 1 (the primary premise of this proposal) is a yes?

**Comment by mattdurham** [comment]
Yes to number one

**Comment by rfratto** [comment]
> Yes to number one, to make it easy to transition discovery.target.decode?

I'm not sure if making the transition easier is a goal we need to have (especially since the export would be called `discovery.target.decode.LABEL.targets` which is weirdly repetitive). 

> 1. Should discovery_target_decode be replaced with discovery components which map directly to Prometheus' file_sd_configs and http_sd_configs?
>     i. If yes: What should they be called?

Unless someone disagrees, it sounds like the equivalent component to http_sd_configs should be given the obvious name (`discovery.http`). 

For the file_sd_configs equivalent, we've heard two name suggestions so far:

1. `discovery.file` (requires renaming the current `discovery.file` component)
2. `discovery.file_targets`

I am currently not in favor of `file_targets` because I would like to avoid the repetition with the export name (`discovery.file_targets.LABEL.targets`).  

A third path could be to introduce a new component namespace inside `discovery`, either a namespace for components which map to Prometheus SD (`discovery.source.kubernetes`, `discovery.source.file`) or a namespace for components which do transformations (`discovery.transform.filepath`, `discovery.transform.relabel`).

If we don't introduce new namespaces, I think the current `discovery.file` component should be renamed regardless to make the distinction clearer between this new component (which returns a set of targets read from a file) and the existing component (which expands a set of targets based on files located on disk).

**Comment by rfratto** [comment]
> A new and maybe not needed `local.files` should return a `map(string)` where the key is the filename and the value is the content. This aligns with `local.file`

I'm not sure I understand how this relates to removing discovery_target_decode to align more closely to the functionality supported by file_sd_configs, can you explain?

**Comment by mattdurham** [comment]
@rfratto `local.files` is more of a tangent on future functionality and can be ignored for the moment.

**Comment by mattdurham** [comment]
I am pro new namespace. Reusing `discovery.file` into something different feels like a bad change.

**Comment by rfratto** [comment]
After having a chat with @mattdurham, @captncraig, @erikbaranowski, we wanted to find a way to unblock the removal of discovery_target_decode without getting consensus on what to do with discovery.file, since finding an appropriate name for that is challenging. 

Here is what we identified:

* Create a new component in the style of `module.string` called `discovery.string`, which behaves the same as discovery_target_decode, except with the ability to specify the format of the string (JSON or YAML).
* Remove `discovery_target_decode` in favor of the `discovery.string` component.
* Add a warning to the documentation of discovery.file to note that it is _not_ an equivalent to file_sd_configs, and to use discovery.string with local.file instead. 
* Revisit the name of discovery.file later. 

Part of the issue with coming up with a name for discovery.file is whether or not it is a transformation-style component in the same vein as discovery.relabel; we don't have consensus on how to categorize it. Components which do transformations typically are named with verbs to make it clearer that it's processing its attributes. Once we get consensus on how to categorize discovery.file, we should be able to finalize its name more easily.

**Comment by rfratto** [comment]
We just discovered that the proposal above wouldn't be equivalent to file_sd_configs, since file_sd_configs _also_ supports file globbing. 

We're back to needing to have components which match up with file_sd_configs and http_sd_configs (though we could still have discovery.string) and getting consensus on if the name for discovery.file should change, and what it should change to.

**Comment by mattdurham** [comment]
IMO and this is contentious, I think the the  prometheus sd file does to much in a flow world and should be broken down to something like this.
``
discovery.file "sd" {
    path_targets = [{"__path__"} = "/var/sd/*.json"]
}

# new component that exports [{"__path__"="/var/sd/targets.json","__content__"="JSON_HERE"}, plus other attributes]
local.files "sd" {
    targets = discovery.file.targets
}

discovery.string "sd" {
    // list(map(string)) where there is a label named "__content__" holds content
    targets = local.files.sd.content
}
```

**Comment by rfratto** [comment]
After discussing offline, we've gotten consensus on doing the following:

1. (Breaking change) Remove discovery_target_decode for the reasons mentioned in this proposal. 
2. (Breaking change) Rename discovery.file to local.file_match to make it more clear that it operates on the local filesystem.
3. To focus on compatibility with static mode and Prometheus, introduce components based directly on Prometheus' file_sd and http_sd called discovery.file and discovery.http. 

More powerful Flow-like flexibility that Matt describes above is being delayed to the future where we have more Flow-level primitives for dynamic components, such as the ability to dynamically generate prometheus.exporter.mysql components based on discovered MySQL pods.
