### ISSUE TITLE
Horizontal scaling configuration using operator

### ISSUE THREAD

**Issue by yurii-kryvosheia** [grafana/agent#3633]
We have a working setup of _GrafanaAgent_ and _MetricsInstance_ and would like utilize horizontal scaling. 

I've spent hours searching documentations on how to insert [host_filter](https://grafana.com/docs/agent/latest/configuration/metrics-config/#metrics_instance_config) parameter into grafana-agent instance.
Is it possible using agent-operator or this is only available with static [yaml file](https://grafana.com/docs/agent/latest/configuration/create-config-file/)?

**Comment by captncraig** [comment]
So the host_filter is not really relevant to a kubernetes deployment. Even if you were running as a daemonset on every node, you would generally use relabel rules to drop targets that don't match the current host.

The recommended way to scale horizontally with the operator is to increase the number of shards and use [hashmod sharding](https://grafana.com/docs/agent/latest/static/operation-guide/#hashmod-sharding-stable) to distribute the load between the agents. The operator will manage this for you if you increase the number of shards in your GrafanaAgent crd.
