### ISSUE TITLE
Version Output of 0.33.0 is broken (No Version number and branch name)

### ISSUE THREAD

**Issue by ResuBaka** [grafana/agent#3645]
After Upgrading to version 0.33.0 I noticed that the output of the version command is missing the version and branch name.

Here is the output I get from downloading [linux amd64](https://github.com/grafana/agent/releases/download/v0.33.0/grafana-agentctl-linux-amd64.zip)  version 0.33.0
```
$ grafana-agent --version

agentctl, version  (branch: , revision: d25614ee52578ac5a0dc0c6d31c45ee97263843a)
  build user:       
  build date:       
  go version:       go1.20.3
  platform:         linux/amd64
  tags:             netgo
```

Here is the output I get from downloading [linux amd64](https://github.com/grafana/agent/releases/download/v0.32.0/grafana-agentctl-linux-amd64.zip)  version 0.33.0
```
$ grafana-agent --version

agentctl, version v0.32.0 (branch: HEAD, revision: 4cb09454)
  build user:       root@b6fac91b1532
  build date:       2023-02-28T17:28:30Z
  go version:       go1.20
  platform:         linux/amd64
```

**Comment by mattdurham** [comment]
Thanks for the heads up, we are looking into it.
