### ISSUE TITLE
Flow: loki.source.journal docs give incorrect example

### ISSUE THREAD

**Issue by Chewie** [grafana/agent#3656]
The [docs](https://grafana.com/docs/agent/v0.33/flow/reference/components/loki.source.journal/#example) give the following example code:

```
loki.relabel "journal" {
  rule {
    source_labels = ["__journal__systemd_unit"]
    target_label  = "unit"
  }
}

loki.source.journal "read"  {
  forward_to    = [loki.write.endpoint.receiver]
  relabel_rules = loki.relabel.journal.rules
}

loki.write "endpoint" {
  endpoint {
    url ="loki:3100/api/v1/push"
  }
} 
```

This fails because the loki.relabel component expects a `forward_to` attribute.

In general, the relabel_rules makes it confusing as to how relabeling should proceed: should the source forward to the `loki.relabel` component, which will in turn forward to `loki.write`, or should the source be responsible for forwarding to the write endpoint, leaving the ` loki.relabel` as a dumb bag of rules?

**Comment by rfratto** [comment]
@tpaschalis Should the example be using discovery.relabel here instead?
