### ISSUE TITLE
Flow: component docs mention types not present in language reference

### ISSUE THREAD

**Issue by Chewie** [grafana/agent#3657]
At various points, the component docs mention types such as `map(string)` and ` list(string)` (see [loki.write](https://grafana.com/docs/agent/v0.33/flow/reference/components/loki.write/#arguments)). However, the [language reference](https://grafana.com/docs/agent/v0.33/flow/config-language/expressions/types_and_values/) does not mention these types.

In particular, the map type was a head scratcher to write a literal for. I was able to find an example in the [phlare.write](https://grafana.com/docs/agent/v0.33/flow/reference/components/phlare.write/#example) after grepping the repo, but it would be good to have a central example showing how to fill such attributes.

**Comment by rfratto** [comment]
Thanks for the feedback; this is the second time this has come up, and I definitely agree we need to document this somewhere.

We'll add the convention for type names to [Types and values](https://grafana.com/docs/agent/latest/flow/config-language/expressions/types_and_values/).
