### ISSUE TITLE
Missing promtail multiline stage

### ISSUE THREAD

**Issue by Galarzaa90** [grafana/agent#366]
I tried migrating my standalone promtail into the agent, but the agent is using an old loki or promtail version that doesn't support the `multiline` stage

```
agent_1  | level=error ts=2021-01-29T17:33:54.15079771Z caller=main.go:74 msg="failed to create loki log collection instance" err="failed to make file target manager: invalid match stage config: match stage failed to create pipeline from config: map[selector:{job=\"nabbot\"} stages:[map[multiline:map[firstline:^\\x{200B}\\[ max_wait_time:3s]] map[regex:map[expression:^\\x{200B}\\[(?P<time>[^]]+)\\]\\[(?P<level>\\w+)\\](?:\\[(?P<tag>\\w+)\\])?\\s?(?P<content>.*)]] map[labels:map[level:<nil> tag:<nil>]] map[replace:map[expression:(,) replace:. source:time]] map[timestamp:map[format:2006-01-02 15:04:05.999 location:America/Hermosillo source:time]] map[output:map[source:content]]]]: invalid multiline stage config: Unknown stage type: multiline"
```

Docs: https://grafana.com/docs/loki/latest/clients/promtail/stages/multiline/

**Comment by rfratto** [comment]
Hey! That's right, the v0.11.0 release of the Agent is using Promtail v2.1.0 which doesn't have the multiline stage in it. The v0.12.0 release next week updates the Promtail dependency and should have it included.

**Comment by Galarzaa90** [comment]
I see that v0.12.0 was released 5 days ago and included this 👍🏼
