### ISSUE TITLE
Integrations won't work when using HTTPS and client-side cert validation

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#367]
The Agent communications with itself over the network when using integrations. Currently, there's no way to provide a client cert when configuring integrations. If you turn on TLS for the HTTP listener and require a client cert, the Agent will be unable to scrape itself. 

The most straightforward solution here is to add providing client settings to integrations. However, it feels a little awkward: should the Agent have a special communication channel just for integrations? Since we plan to eventually launch some integrations as child processes (#295), we couldn't do all of this in-memory.

**Comment by mattdurham** [comment]
This was resolved in #418
