### ISSUE TITLE
[flow] `prometheus.scrape` should better validate its config and report health

### ISSUE THREAD

**Issue by thampiotr** [grafana/agent#3696]
### Steps to reproduce:
1. Start agent flow mode using the following river config
```
prometheus.scrape "agent_self" {
  targets = [
    {"__address__" = "localhost:1234", "job" = "agent"},
  ]
  forward_to = []
  scrape_interval = "5s"
}
```
2. Observe there are no configuration errors and the components evaluation appears successful:
```
ts=2023-04-27T16:58:24.089453Z level=info trace_id=036c06881ab01e171d08a0de3de6ae71 msg="finished complete graph evaluation" duration=8.905708ms
ts=2023-04-27T16:58:24.089476Z level=info msg="scheduling loaded components"
```
3. Observe the component health is reported as healthy.
4. See this log line appear when scraping is attempted, indicating the config is invalid and component is not healthy:
```
ts=2023-04-27T16:58:29.090893Z component=prometheus.scrape.agent_self level=error scrape_pool=prometheus.scrape.agent_self msg="Creating target failed" err="instance 0 in group prometheus.scrape.agent_self: scrape timeout cannot be greater than scrape interval (\"10s\" > \"5s\")"
```

### Expected behaviour
The misconfiguration should be caught early with a relevant error clearly visible to the user. We could interrupt the agent startup, or we could make sure that the health of the component is reported as unhealthy. Other solutions are also welcome, as long as we can observe the issue with clarity.

**Comment by tpaschalis** [comment]
The `prometheus.scrape` component's `UnmarshalRiver` method only validates the HTTPClientConfig struct but does not check the other parameters [unlike Prometheus](https://github.com/prometheus/prometheus/blob/24d7e5bd49dd26a45c2123a897c6cac5ac7c47f0/config/config.go#L549-L569) which is where the error is caught.

We should make sure the UnmarshalRiver method also returns an error so it gets caught early; this is the way we also re-implement validation logic from other upstream pieces of code (either OTel or Promtail).
