### ISSUE TITLE
Grafana agent sends data only for 5 mins for oracle integration

### ISSUE THREAD

**Issue by shubhamnyaik** [grafana/agent#3756]
Hi All, 
With grafana agent 32.1, we have onboarded one of the oracleDB hosts. 
The data for oracle is only being reported for 5 mins and stops. 
The service continuous to show active (running) state. 

Error in journalctl: 
msg="failed to report usage" err="5 errors: Post \"[https://stats.grafana.org/agent-usage-report\":](https://stats.grafana.org/agent-usage-report/%22:) dial tcp 34.96.126.106:443: i/o timeout (Client.Timeout exceeded while awaiting headers); Post \"[https://stats.grafana.org/agent-usage-report\":](https://stats.grafana.org/agent-usage-report/%22:) context deadline exceeded.

We also added command line arguments to the ExecStart command in service file. 
--disable-reporting 
--disable-support-bundle 

Regards 
Shubham Nyaik

**Comment by marctc** [comment]
@shubhamnyaik The problem seems unrelated to oracledb integration. Are you running the agent in a node without internet?

**Comment by marctc** [comment]
I'm going to close the ticket as the fact that usage statns can't be sent is realted to oracledb integration. Feel free to reopen providing more debug information if the problem persists.
