### ISSUE TITLE
Integrated Blackbox exporter metrics not showing target label

### ISSUE THREAD

**Issue by ishantanu** [grafana/agent#3835]
### What's wrong?

Hello,

I am trying to use the integrated blackbox exporter with grafana agent flow config for monitoring some URLs.

However, I noticed that the pushed metrics didn't have the `target` label. 

Is grafana agent automatically removing any label before relabelling is done?

Example metric generated:
```
probe_success{instance="prometheus.exporter.blackbox.demo",job="integrations/blackbox/url1"}
```

What I want is another label `host` with the value `http://url1.com`.

### Steps to reproduce

Run the grafana agent binary in flow mode and provide the river config file.

### System information

Linux

### Software version

Grafana Agent Flow mode v0.33.1

### Configuration

```text
prometheus.exporter.blackbox "demo" {
  config = "{ modules: { http_2xx: { prober: http, timeout: 5s } } }"

  target "url1" {
    address = "http://url1.com"
    module  = "http_2xx"
  }

  target "url2" {
    address = "http://url2.com"
    module = "http_2xx"
  }
}

prometheus.relabel "blackbox_relabel" {
  forward_to      = [ prometheus.remote_write.agent_metrics.receiver ]

  rule {
    source_labels = ["__param_target"]
    action = "replace"
    target_label = "host"
  }

}

// Scrape agent metric endpoint(*required)
prometheus.scrape "blackbox_metrics_scraper" {
  targets = prometheus.exporter.blackbox.demo.targets
  job_name        = "blackbox_metrics_job"
  scrape_interval = "60s"
  metrics_path = "/probe"
  forward_to      = [ prometheus.relabel.blackbox_relabel.receiver ]
}

// Remote write metrics to Grafana Metrics back-end
prometheus.remote_write "agent_metrics" {
  endpoint {
    url = "http://xxxxxx/api/v1/push"
    headers = { "xxx" = "yyy" }
 }
}
```
```


### Logs

_No response_

**Comment by ishantanu** [comment]
Update:

I was able to achieve this by using `discovery.label` to relabel before forwarding it to `prometheus.scrape` since `discovery.relabel` had `output` which can be used as targets in `prometheus.scrape`. I thought scrape was removing the `__param_target` label internally and that was why relabeling wasn't working. I was referring to [this ](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.scrape/)doc which mentions 

> Labels coming from targets, that start with a double underscore __ are treated as internal, and are removed prior to scraping.

Here's the working code (not sure if this is the correct way to do it):
```
prometheus.exporter.blackbox "demo" {
  config = "{ modules: { http_2xx: { prober: http, timeout: 5s } } }"

  target "url1" {
    address = "http://url1.com"
    module  = "http_2xx"
  }

  target "url2" {
    address = "http://url2.com"
    module = "http_2xx"
  }
}

discovery.relabel "blackbox_example" {
  targets = prometheus.exporter.blackbox.demo.targets

  rule {
    source_labels = ["job"]
    regex         = "integrations/blackbox/(.+)$"
    target_label  = "job"
  }

  rule {
    source_labels = ["__meta_agent_integration_instance"]
    target_label  = "component"
  }

  rule {
    source_labels = ["__param_target"]
    separator     = "|"
    target_label  = "instance"
  }

  rule {
    source_labels = ["__param_module"]
    target_label  = "module"
  }
}


// Scrape agent metric endpoint(*required)
prometheus.scrape "blackbox_metrics_scraper" {
  targets = discovery.relabel.blackbox_example.output
  job_name        = "blackbox_metrics_job"
  scrape_interval = "10s"
  forward_to      = [ prometheus.remote_write.agent_metrics.receiver ]
}

// Remote write metrics to Grafana Metrics back-end
prometheus.remote_write "agent_metrics" {
  endpoint {
    url = "http://xxxxxx/api/v1/push"
    headers = { "xxx" = "yyy" }
 }
}

```

**Comment by tpaschalis** [comment]
Hey there, apologies for the belated response! Yes, the way you went about it is right; Prometheus' code will remove all labels starting with a double underscore `__` just before scraping, so the way to keep them is via relabeling, much like you did here.

Does the upstream blackbox_exporter do something different (eg. pre-populates this label?), and is there something to fix, or should we close this issue?

**Comment by ishantanu** [comment]
It is correct that labels starting with `__` are removed by Prometheus. The only thing I would like to add is that it wasn't clear which one of `prometheus.relabel` or `discovery.relabel` should be used for this use case. I think it would've been better if the blackbox exporter's example included the relabeling config as well.

I will close this issue as it is working as expected.
