### ISSUE TITLE
Flow UI: Padding of table incorrect

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#3870]
### What's wrong?

The padding on rows in the component list table no longer looks incorrect. It looks like this started with #3101. 

Before: 

![](https://grafana.com/docs/agent/latest/assets/ui_home_page.png)

After:

<img width="1450" alt="image" src="https://github.com/grafana/agent/assets/630212/25287202-d993-42c4-ad6b-f637e8ce9563">

The height of the rows have changed, and there's inconsistent padding around the "view" buttons.

### Steps to reproduce

1. Open the UI.

### Software version

Grafana Agent Flow v0.33.2

**Comment by rfratto** [comment]
cc @xiyu95

**Comment by xiyu95** [comment]
Thanks for letting me know. I would be happy to review it at my earliest convenience!

**Comment by xiyu95** [comment]
@rfratto Let me know if this satisfies the layout 

https://github.com/grafana/agent/assets/112968312/42b597e8-864b-4a82-b0cc-74a30387a7f8

Changes in the video:
1. Vertically aligned the `View` button
2. Fixed the padding of first and second column of table

Checks in the other page:
4. Double checked with the detail page to see the changes does not affect the table in there
5. Double checked to see if the component work properly with `flex` while window shrink

**Comment by rfratto** [comment]
@xiyu95 That's perfect, thanks! 👏
