### ISSUE TITLE
docker compose example needs updating

### ISSUE THREAD

**Issue by beanow-at-crabnebula** [grafana/agent#3890]
### What's wrong?

The [docker-compose example](https://github.com/grafana/agent/tree/main/example/docker-compose) has gone stale on some front and needs an update.

- [omnition/synthetic-load-generator](https://github.com/Omnition/synthetic-load-generator) was deprecated years ago and the docker hub image has been removed.
- The `grafana/agent:latest` usage actually fails.
  Because the binary renamed from `/bin/agent` to `/bin/grafana-agent`
- You might want to use the Mimir backend instead of Cortex.

I've found https://github.com/grafana/opentelemetry-demo but it has similar issues.
It's the "grafana way" fork of an opentel demo, but uses very little of the grafana stack actually.

### Steps to reproduce

1. `docker compose --profile agent up` in the example directory

This should fail at least on the synthetic load container and agent container.

### System information

Linux 6.2.6 AMD64 | Docker Compose version v2.17.3

### Software version

Example git cloned from `main`.
Latest commit in that directory, https://github.com/grafana/agent/tree/99aba52da1b64250c992c7eb176a4d6d24919fb9

### Configuration

```text
N/A
```

**Comment by clayton-cornell** [comment]
The points raised here have been fixed in other PRs. Closing this issue.
