### ISSUE TITLE
Flow: Display metrics from Collector components in the Agent's metrics endpoint

### ISSUE THREAD

**Issue by ptodev** [grafana/agent#3923]
### Request

In static mode, if we use the Otel batch processor we can see metrics such as the `traces_processor_batch_batch_send_size` histogram. This metric comes from within the Collector's codebase and it is not visible on the Agent's `/metrics` endpoint when the Agent runs in Flow mode.  

According to @rfratto that's because the version of Otel we embed doesn't support using the Otel SDK for processors, and only uses OpenCensus. 

We need to make such metrics visible in Flow mode and this should ideally work out of the box when we add new Otel components into Flow without extra work just to get metrics integrated.

### Use case

Feature parity between Static and Flow mode.

**Comment by rfratto** [comment]
👍 

I'd like to note that this will happen automatically once we upgrade the OpenTelemetry Collector SDK, since newer versions support using the OpenTelemetry SDK for processor telemetry (but not the version we currently import).

**Comment by ptodev** [comment]
I suspect that even after we upgrade to the latest Collector version we will still not see a lot of new metrics. 

I believe most components in the Contrib codebase use OpenCensus for metrics. For example, the Kafka receiver which we added to Flow recently also [uses](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kafkareceiver/metrics.go) OpenCensus.

**Comment by rfratto** [comment]
That's pretty unfortunate, but I think there's plans for the OTel SDK to be adopted throughout the collector, which would address that issue. 

In the meantime, it looks like it may be possible for us to create a shim to get OpenCensus metrics per component without exposing more information than we'd want. However, it also looks like that would require manual work so it'd be something we'd opt each component into.

**Comment by rfratto** [comment]
@ptodev Is this a blocker for feature parity? Can we remove the feature-parity label?

**Comment by ptodev** [comment]
I think we can close the whole issue, since we no longer use the OpenCensus metrics in static mode. In theory, the Otel metrics in static mode should be the same as the Otel metrics in flow mode.

**Comment by rfratto** [comment]
Closing because OpenCensus metrics are not being used in static mode.
