### ISSUE TITLE
Document and verify Otlp -> Loki label translation

### ISSUE THREAD

**Issue by ptodev** [grafana/agent#3928]
### Request

The Collector's Loki exporter documents its translation rules [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter) and [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheus/README.md#Labels). At the moment [otelcol.exporter.loki](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.exporter.loki/) does not have such a documentation. We need to add it.

In addition, we need to:
* Document the importance of hints such `loki.attribute.labels`
* Unit test the translation to make sure it works. I'm not 100% sure it works at the moment, because when I added a unit test just now it didn't pass in the way I thought it should do.

### Use case

The expected behaviour of the component will be more clear to the users.

**Comment by Eve832** [comment]
Tagging @clayton-cornell since I'm really not sure who would own the docs for this.
