### ISSUE TITLE
Add registry to helm chart

### ISSUE THREAD

**Issue by edwintye** [grafana/agent#3929]
### Request

I want to have the ability to use a different registry from the default `docker.io`, say a private cache of the image in JFrog or Nexus. Seems like an easy enough change without breaking the default behaviour on [_agent.yaml#3](https://github.com/grafana/agent/blob/main/operations/helm/charts/grafana-agent/templates/containers/_agent.yaml#L3) to

```yaml
image: {{ .Values.image.registry}}/{{ .Values.image.repository }}:{{ include "grafana-agent.imageTag" . }}
```

### Use case

Fetching images from dockerhub has some well known issues these days and will increasingly be more challenging.  We just want to decrease the amount of traffic across the public internet when this problem can be resolved easily.

**Comment by rfratto** [comment]
I don't think a dedicated registry field is necessary; to use a different registry you can add it to the repository: 

```yaml 
image:
  repository: quay.io/REPO/IMAGE_NAME:TAG # (or another registry)
```

**Comment by edwintye** [comment]
Is that the preferred solution? Then you are forcing everyone to treat `repository` as `registry/repository` here which is perfectly fine by me.   Can someone changing the existing value from `grafana/agent` to `docker.io/grafana/agent` to help future readers to see that it is not a missing feature but intended behaviour?

**Comment by rfratto** [comment]
> Is that the preferred solution?

In general I'd prefer not to add new fields if an existing field can be made to work, yeah. 

> Can someone change the existing value from grafana/agent to docker.io/grafana/agent to help future readers see that it is not a missing feature but intended behaviour (since the silent docker.io prepend is unique to docker)?

I'm ok with either making the default explicit to note that it's using docker.io or by documenting it to note that a different registry can be used.

(I think image.repository is a bad name, but that's the default name Helm generates so I'm not sure how common it is to change it to something else like image.name)

**Comment by QuentinBisson** [comment]
`image.registry` and more specifically global.image.registry or `global.imageRegistry` is something that is commonly present in a lot of community helm charts as a default for a lot of different use cases like umbrella charts (using a global property https://github.com/prometheus-community/helm-charts/blob/30ab923a49d7c7b9434e2eabaac03baf6c226b1e/charts/kube-prometheus-stack/values.yaml#L187)

For what it's worth, even the loki or vertical pod autoscaler charts supports it https://github.com/grafana/helm-charts/blob/c756b95494544056e43098b9e8b695a8010c21f2/charts/loki-distributed/values.yaml#L4

We internally use the global fields as a general config across all our clusters so we can define the same property across a set of helm charts in one place. Not having this means the registry change must be done on all deployments of the app and this makes no sense.

I'm happy to create the PR if needed

**Comment by rfratto** [comment]
> We internally use the global fields as a general config across all our clusters so we can define the same property across a set of helm charts in one place. Not having this means the registry change must be done on all deployments of the app and this makes no sense.

I'm not sure I'm following. How is it different to change `image.registry` across all values.yaml compared to changing `image.repository`?

**Comment by QuentinBisson** [comment]
I did a poor job explaining our setup.

We have a multi-level configuration tool used to deploy our apps accross multiple fleets of management clusters.

What we usually do is to configure `global.image.registry` (and `global.imageRegistry`to cover most cases) at the management cluster level so we configure it once and the value is applied to all our helm charts installed thanks to the global property. That way we can use the management cluster local registry.

If we were to use `image.repository` on all our management clusters instead, that means we would have to override it for the grafana agent we want to deploy. I would rather we do not go through this edge case.

What I would really need here is to have `global.image.registry` more than just `image.registry` but having `global.image.registry` also means we need `image.registry`. With that we could override the 2 container images (reloader included).

**Comment by rfratto** [comment]
Thanks for explaining your use case in more detail, I have a better understanding of it now.

I'm generally a little protective of how many new configuration points we add into values.yaml, since it's really easy for Helm charts to become bloated and hard to maintain and use. 

That being said, I think `image.registry` is innocent enough and doesn't add too much overhead. If there was a PR to add it, I'd help get it merged.

**Comment by QuentinBisson** [comment]
@rfratto here is the PR https://github.com/grafana/agent/pull/4127

**Comment by edwintye** [comment]
I saw your comment on #4127 about how you are not "feeling the pain". I actually want to know how you guys use the chart internally such that the current helm structure seems fine.

To elaborate a bit on my side, we have estate across aws/gcp and uses argocd. If the image we are pulling is available on the public ecr/gcr, then we use that, else there are a few choices which one is of interest here.  We do a deploy time override and use cache the image into our private image registry on a cloud provider level, i.e. if it is `docker.io` we simply replace that since there is absolutely zero point in going over the public internet.

Now there are some immediate questions that you may ask such as "Why not proxy your image pull through a registry so that the image is cached on the first download?".  Yes, we already do that at the cluster level, but that is still infra we have to manage (which means it can fail), and having the extra `image.registry` field allows us to be more exact in determining the correct download and cache path at each layer from the cloud provider -> account -> cluster. As much as this sounds like unnecessary micro optimization, once you have set up the correct pattern for *all the images* that you download, the megabytes quickly become gigabytes or even terabytes.

**Comment by rfratto** [comment]
> I actually want to know how you guys use the chart internally such that the current helm structure seems fine.

Grafana Labs currently deploys Helm charts via [Tanka](https://tanka.dev), where it would be very easy for us to apply consistent defaults to values.yaml files. The Helm charts are rendered to Kubernetes, where Flux deploys them for us. 

But we also don't take advantage of that capability; we use the publicly available images on docker.io. If we needed to use a different registry, we have a few options:

1. Rely on Tanka's ability to apply defaults to objects. 
2. Make sure that each installation of the Helm chart is passing a custom image. 

> We do a deploy time override and use cache the image into our private image registry on a cloud provider level

Can you help me understand why this is being applied at deploy time rather than as a prerequisite for updating an image? 

All this aside, I'm not going to block #4127; I'm still going to merge it after my two comments are addressed, I'm just still not understanding why the complexity on the deploying side should propagate all the way down to the Helm chart API.

**Comment by edwintye** [comment]
Thanks a lot for the explanation. A bit surprised that you guys are not using private registries but hey, if it works for you then it works right.

> Can you help me understand why this is being applied at deploy time rather than as a prerequisite for updating an image?

This is a rather complicated scenario so this is going to be a condensed version and hopefully it will still make sense. Following from above, we use argocd to manage our deployments.  When I said deploy time, we actually do nothing for non-prod environments. The images are updated via the argo image updater, which polls the `registry/repo/image` for a tag and updates our deployment when a new tag is available. Evidently this is going to be quite a few api requests and downloads when every image is checked this way so the two operation, poll and pull, goes through a different path.  For some registry this can be the same path, i.e. we can leverage the pull through cache functionality for public ecr.  However, dockerhub is one (and maybe only) edge case where we have a couple of additional tricks up our sleeves via private registries so to make sure every operates smoothly due to some of the well publicised constraints.
