### ISSUE TITLE
Bug: grafana agent mangles utf-16 windows log files

### ISSUE THREAD

**Issue by yosiasz** [grafana/agent#3935]
### What's wrong?

Describe the bug
In Windows SQL Server log files are saved with the UTF-16 encoding, this means that trying to scrape them as-is will result in a mangled output in Grafana using Grafana Agent. This issue surfaced in promtail a while back and it was fixed

https://github.com/grafana/loki/pull/6395

Original issue was

https://github.com/grafana/loki/issues/1119

### Steps to reproduce

To Reproduce
Steps to reproduce are here
https://community.grafana.com/t/need-help-specifying-log-path-for-mssql-log-files/87916/6

### System information

WIindows s

**Comment by tpaschalis** [comment]
Grafana Agent's static mode (YAML config) reuses Promtail's code and configuration. Have you tried using the `encoding `field under your logs' [scrape_configs](https://grafana.com/docs/agent/latest/static/configuration/logs-config/#logs_instance_config/) as described in Promtail [docs](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#scrape_configs)?

**Comment by mattdurham** [comment]
Closing this please reopen if problem persists.

**Comment by yosiasz** [comment]
> Grafana Agent's static mode (YAML config) reuses Promtail's code and configuration. Have you tried using the `encoding `field under your logs' [scrape_configs](https://grafana.com/docs/agent/latest/static/configuration/logs-config/#logs_instance_config/) as described in Promtail [docs](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#scrape_configs)?

I am not seeing this `encoding` in the config?
