### ISSUE TITLE
loki.source.file: allow tailing non-UTF8 encoded files

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#3938]
### Request

We should change `loki.source.file` to allow the files encoding to be set to something other than UTF-8. I'm not sure if this should be a target-specific option that can be defined via a label or a component-level option, although I'm leaning towards the latter.

### Use case

This is something that is supported on Promtail and should be brought over for feature-parity. Some applications output their logs in non-UTF8 encodings by default, and changing that might be challenging for end-users in restricted environments.

**Comment by gpinkos** [comment]
Thank you @tpaschalis   See [this thread](https://community.grafana.com/t/need-help-specifying-log-path-for-mssql-log-files/87916/3?u=grant2) for more support on the inability of Grafana Agent to read non UTF-8 encoded logs, while Promtail (with specification under `scrap configs:` with `encoding: utf-16` ) can read them fine.

**Comment by yosiasz** [comment]
https://github.com/grafana/agent/issues/3938

**Comment by tpaschalis** [comment]
@gpinkos @yosiasz the latest PR now allows the `loki.source.file` component to use a custom encoding!

It will be available in our next release, roughly available in six weeks, but in the meantime, you can test it by building from main or using our [dockerhub images](https://hub.docker.com/r/grafana/agent/tags) from main.
