### ISSUE TITLE
loki.source.file doesn't pick up the file if it's created after the agent starts

### ISSUE THREAD

**Issue by thampiotr** [grafana/agent#3954]
### What's wrong?

loki.source.file doesn't pick up the file if it's created after the agent starts

### Steps to reproduce

1. Use this config
```
loki.source.file "tail_file" {
	targets = [
		{__path__ = "./logs.txt", "job" = "time_and_date"},
	]
	forward_to = [
		loki.echo.print.receiver, 
	]
}

loki.echo "print" { }
```

2. Start the agent when the logs.txt file doesn't exist
3. Start writing to logs.txt and observe that agent doesn't pick the logs up

Expected outcome: Agent should pick up the logs.txt file after it's created and consume its logs.

### System information

macOS 13

### Software version

main-952bdfd

### Configuration

```text
See above
```

### Logs

```text
ts=2023-05-23T10:55:52.137795Z level=info msg="now listening for http traffic" addr=127.0.0.1:12345
ts=2023-05-23T10:55:52.137888Z level=info msg="running usage stats reporter"
ts=2023-05-23T10:55:52.137914Z level=info trace_id=8a7a89b6585f64b91479b2f5a030da45 msg="starting complete graph evaluation"
ts=2023-05-23T10:55:52.13808Z level=info trace_id=8a7a89b6585f64b91479b2f5a030da45 msg="finished node evaluation" node_id=loki.write.write_to_cloud duration=157.958µs
ts=2023-05-23T10:55:52.138094Z level=info trace_id=8a7a89b6585f64b91479b2f5a030da45 msg="finished node evaluation" node_id=loki.echo.print duration=5.75µs
ts=2023-05-23T10:55:52.138243Z component=loki.source.file.tail_file level=error msg="failed to tail file, stat failed" error="stat ./logs.txt: no such file or directory" filename=./logs.txt
ts=2023-05-23T10:55:52.138251Z level=info trace_id=8a7a89b6585f64b91479b2f5a030da45 msg="finished node evaluation" node_id=loki.source.file.tail_file duration=153.584µs
ts=2023-05-23T10:55:52.13826Z level=info trace_id=8a7a89b6585f64b91479b2f5a030da45 msg="finished node evaluation" node_id=tracing duration=5.417µs
ts=2023-05-23T10:55:52.138266Z level=info trace_id=8a7a89b6585f64b91479b2f5a030da45 msg="finished node evaluation" node_id=logging duration=3.125µs
ts=2023-05-23T10:55:52.138271Z level=info trace_id=8a7a89b6585f64b91479b2f5a030da45 msg="finished complete graph evaluation" duration=396.791µs
ts=2023-05-23T10:55:52.138283Z level=info msg="scheduling loaded components"
```
```

**Comment by sbhrule15** [comment]
@thampiotr more than happy to take this, but before I do, isn't this supposed to be handled by the discovery component?

<img width="683" alt="image" src="https://github.com/grafana/agent/assets/65102852/0306d04d-6569-4c17-87c2-bfbafc782ee2">
<img width="1432" alt="image" src="https://github.com/grafana/agent/assets/65102852/5d50d9fd-6b7d-40e0-86c8-c2552d8a98cb">

Tested that and works as expected - my assumption is that discovery is used to setup dynamic targets to send to the other components, rather than having the loki file component also both discovery and processing?

**Comment by thampiotr** [comment]
Hi @sbhrule15, thanks so much for taking a look and verifying that with `discovery.file` works. 

Indeed, it seems like this is the right way to solve the problem. We should probably document it as a good practice and make it clear [in our docs here](https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.file/) that users should use `discovery.file` instead of hard-coding file paths and correct the examples in that doc as well. 

If people keep running into this issue, we may consider other options, but for now I'm happy to only fix the docs.

**Comment by sbhrule15** [comment]
I'll get something up soon to fix the docs 👍
