### ISSUE TITLE
systemctl reload grafana-agent-flow failed

### ISSUE THREAD

**Issue by fqcprodigy** [grafana/agent#4003]
### What's wrong?

`systemctl reload grafana-agent-flow` this command failed with error:

_grafana-agent-flow.service: Failed to execute command: No such file or directory
 grafana-agent-flow.service: Failed at step EXEC spawning /usr/bin/kill: No such file or directory_

I have to manually create soft link: `ln -sf /bin/kill /usr/bin/kill` to resolve it.

### Steps to reproduce

1. Install grafana-agent-flow on Azure Ubuntu18.04
2. Update /etc/grafana-agent-flow.river
3. run  `systemctl reload grafana-agent-flow`

### System information

5.4.0-1107-azure

### Software version

v0.33.2-1

### Logs

```text
grafana-agent-flow.service: Failed to execute command: No such file or directory
grafana-agent-flow.service: Failed at step EXEC spawning /usr/bin/kill: No such file or directory
```

**Comment by rfratto** [comment]
Hi, thanks for the report. This is a known issue that will be fixed with the next release thanks to #3600. 

I'll close this since a fix bug is already in main and awaiting a release.
