### ISSUE TITLE
Unable to override User-Agent on http.remote component

### ISSUE THREAD

**Issue by jkroepke** [grafana/agent#4042]
### What's wrong?

For a better traceability, I would like to enrich the User-Agent http header with own values.

However the http user-agent header is always set to `GrafanaAgent/main-a82513e`. For `prometheus.remote_write`, can I override the User-Agent.

### Steps to reproduce

1. Create a config file with the content below
2. Start Agent

### System information

MacOS 13.4

### Software version

v0.33.0 + main

### Configuration

```text
remote.http "config_os" {
    url = "https://exmaple.com/" + constants.os + ".river"
    headers = {
        "User-Agent" = constants.hostname + " OS/" + constants.os,
    }
}

prometheus.remote_write "prometheus" {
    endpoint {
        url = "https://example.com/api/v1/write"
        headers = {
            "User-Agent" = argument.imds_resource_id.value + " OS/" + constants.os,
        }
    }
}
```

**Comment by hainenber** [comment]
Hi @rfratto, I'd like to work on this issue. Can it be assigned to me? Thank you.

**Comment by rfratto** [comment]
@hainenber Sure, it's all yours!
