### ISSUE TITLE
Errors from http.remote component are not logged

### ISSUE THREAD

**Issue by jkroepke** [grafana/agent#4084]
### What's wrong?

Any error from `http.remote` components are not logged. This is horrible, in combination with `module.string`, if the module has arguments.

Unlike Grafana Agent 0.33.2, the 0.34 version validate if arguments are present inside a Flow module.

If `http.remote` fail silently, an empty string will be passed to module.string which results in a fatal error. (see logs below).

Since the grafana agent will terminate directly, it's impossible to archive what the health status of the `remote.http` component. A debugging through logs is not possible because of the missing log entries (even with debug enabled) and the Web UI is not reachable, because the agent terminates instantly.

### Steps to reproduce

Run the agent with the configuration below

### System information

mac OS 

### Software version

version main-a82513e (branch: main, revision: a82513e7)

### Configuration

```text
remote.http "config" {
  url = "https://nonexists.com"
}

module.string "config" {
  content = remote.http.config.content
  arguments {
    anyvalue = "PROMETHEUS_PASSWORD"
  }
}

logging {
  level = "debug"
}
```

### Logs

```text
ts=2023-06-07T17:45:29.608557Z level=info msg="now listening for http traffic" addr=127.0.0.1:12345
ts=2023-06-07T17:45:29.608807Z level=info msg="running usage stats reporter"
ts=2023-06-07T17:45:29.609836Z level=info trace_id=eb9352bf7668a9120f8ee8f6dd57033d msg="starting complete graph evaluation"
ts=2023-06-07T17:45:29.610556Z level=info trace_id=eb9352bf7668a9120f8ee8f6dd57033d msg="finished node evaluation" node_id=logging duration=711.625µs
ts=2023-06-07T17:45:29.825396Z level=info trace_id=eb9352bf7668a9120f8ee8f6dd57033d msg="finished node evaluation" node_id=remote.http.config duration=214.833333ms
ts=2023-06-07T17:45:29.825858Z level=error trace_id=eb9352bf7668a9120f8ee8f6dd57033d msg="failed to evaluate config" node=module.string.config err="building component: -: Provided argument \"anyvalue\" is not defined in the module"
ts=2023-06-07T17:45:29.825897Z level=info trace_id=eb9352bf7668a9120f8ee8f6dd57033d msg="finished node evaluation" node_id=module.string.config duration=413.917µs
ts=2023-06-07T17:45:29.825927Z level=info trace_id=eb9352bf7668a9120f8ee8f6dd57033d msg="finished node evaluation" node_id=tracing duration=12.708µs
ts=2023-06-07T17:45:29.825942Z level=info trace_id=eb9352bf7668a9120f8ee8f6dd57033d msg="finished complete graph evaluation" duration=216.272958ms
Error: -: Provided argument "anyvalue" is not defined in the module

ts=2023-06-07T17:45:29.826284Z level=info msg="http server closed" addr=memory err="http: Server closed"
ts=2023-06-07T17:45:29.826308Z level=info msg="http server closed" addr=127.0.0.1:12345 err="http: Server closed"
ts=2023-06-07T17:45:29.826334Z level=debug msg="flow controller exiting"
ts=2023-06-07T17:45:29.826358Z level=error msg="failed to start reporter" err="context canceled"
```

**Comment by jkroepke** [comment]
An additional potential solution would be if there is a way to mark `remote.http` as required. If the remote content is not `fetchable`, throw an error like the same ways as module.string in that case.

**Comment by rfratto** [comment]
> An additional potential solution would be if there is a way to mark remote.http as required. If the remote content is not fetchable, throw an error like the same ways as module.string in that case.


Yeah, this is component best practices IMO: a component which retrieves external state should fail on construction if it fails to retrieve that state. This is what `local.file` does; the component will fail to build if its initial config points it at an invalid file. 

This is best practices because of exactly what you described; if it's hiding the error and fetching the HTTP response in the background, it propagates the error downstream and leads to confusing errors. 

It looks like `remote.http` isn't surfacing the error back to the user, and instead [ignores it](https://github.com/grafana/agent/blob/c736dbb1da985e7d97bd74dbfbcffcf8faebc110/component/remote/http/http.go#L245) if the request fails on component construction/update. 

I'm in favor of both changes here:

* `remote.http` should return an error on New/Update if the initial request fails. 
* `remote.http` should log errors if the request fails instead of only putting the error in the debug info.

**Comment by jkroepke** [comment]
Follow the best practice here would solve the issues here around `remote.http`.

What happens, if grafana is running and `remote.http` fails temporarily? Would this also stop the execution?

**Comment by jkroepke** [comment]
https://github.com/grafana/agent/pull/3539 seems like there was already a discussion about this.

Its important if `remote.http` fails after initial request, the component should pull continuously.

**Comment by rfratto** [comment]
Yes, if remote.http fails after the first load it will be unhealthy but other components referencing it will continue to use the last valid export from the previously successful poll.

**Comment by mattdurham** [comment]
We have had some discussion on `argument` requirements and I am thinking we should verify arguments from the standpoint of the caller and revert that behavior to v33 behavior.

**Comment by jkroepke** [comment]
@mattdurham I'm +1 for this strict behavior. It always prevents some mistakes, e.g. typos.

HCL has a similar behavior. If I define an argument, the argument should define OR the execution should fail.

**Comment by rfratto** [comment]
From a graph evaluation standpoint, it's unsafe for components to silently fail on first evaluation. This follows all the way through the DAG, including into modules. 

> The reason I am not specifically for it is that it prevents no-ops and removes the ability to module overload.

Is this something that's been discussed in a design document which outlines pros/cons? I'm concerned removing argument validation for modules is going to lead to frustration to users if they typo an optional argument passed to a module and things silently don't work without any feedback.

**Comment by mattdurham** [comment]
Its tangentially related, the enforcement of argument names should have been labelled a breaking change in v0.34. Release v0.33 accepts arguments that arent defined in the child. The discussion should be split off since it is unclear if it is a problem or not.
