### ISSUE TITLE
v0.34 Issue with windows_exporter incorrectly setting defaults

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#4104]
### What's wrong?

Defaults for some collectors (at least mssql) are not being applied correctly.

### Steps to reproduce

Add mssql as an enabled-collector but no specific mssql  sub-collectors. Normally the defaults would fill in several but currently it sets it to a blank string.

### Configuration

```text
server:
  log_level: debug
metrics:
  global:
    scrape_interval: 60s
    remote_write:
      - url: https://prometheus-us-central1.grafana.net/api/prom/push 
        basic_auth: 
          username: 12345
          password: "PASSWORD"
integrations:
  agent:  
    enabled: true
  windows_exporter:
    enabled: true
    enabled_collectors: "mssql,logical_disk"
```

**Comment by joeyj** [comment]
We've also had to roll back to v33.2 due to issues with `windows_exporter` I believe @jkroepke made the last round of large changes to this component: https://github.com/grafana/agent/pull/3603

**Comment by mattdurham** [comment]
We will have a patch forthcoming though sadly it might be Monday before that occurs.

**Comment by ptodev** [comment]
Just fyi, #4112 is also something that needs fixing in the windows exporter. But don't worry about it if you don't have time.
