### ISSUE TITLE
Non-stable version in `https://apt.grafana.com stable main` repository

### ISSUE THREAD

**Issue by DeadNews** [grafana/agent#4126]
### What's wrong?

Non-stable version in `https://apt.grafana.com stable main` repository.
Moreover, `grafana-agent-0.34.0-rc.1-1` is preferred over `grafana-agent-0.34.0-1`.

### Steps to reproduce

According to <https://apt.grafana.com>:

```sh
mkdir -p /etc/apt/keyrings/
wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg
echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | tee /etc/apt/sources.list.d/grafana.list
```

After [v0.34.0](https://github.com/grafana/agent/releases/tag/v0.34.0) release:

```sh
$ sudo apt update && sudo apt list --upgradable

'grafana-agent/stable 0.34.0-rc.1-1 amd64 [upgradable from: 0.33.2-1]'
```

`grafana-agent` versions in `https://apt.grafana.com stable main` repository:

```sh
$ grep grafana-agent-0 /var/lib/apt/lists/*grafana*_Packages | head -n 5

Filename: pool/main/g/grafana-agent/grafana-agent-0.34.0-rc.1-1.amd64.deb
Filename: pool/main/g/grafana-agent/grafana-agent-0.34.0-1.amd64.deb
Filename: pool/main/g/grafana-agent/grafana-agent-0.33.2-1.amd64.deb
Filename: pool/main/g/grafana-agent/grafana-agent-0.33.1-1.amd64.deb
Filename: pool/main/g/grafana-agent/grafana-agent-0.33.0-1.amd64.deb
```

### System information

Ubuntu 22.04

### Software version

Any

**Comment by rfratto** [comment]
Hi, thanks for reporting. I've reached out to the team which maintains the Grafana package repository so they can unpublish the -rc.1 version and make sure that release candidates don't get published to the stable stream again.

**Comment by rfratto** [comment]
This is resolved now. Thanks for reporting!
