### ISSUE TITLE
[Operator] Support GKE Copilot environment

### ISSUE THREAD

**Issue by shubhamranjan** [grafana/agent#4128]
### What's wrong?

While deploying grafana agent using grafana agent operator on a GKE autopilot cluster, the following errors occur on the log agent daemonset:

- container grafana-agent is privileged; not allowed in Autopilot
- hostPath volume data in container config-reloader is accessed in write mode; disallowed in Autopilot.
- hostPath volume dockerlogs used in container config-reloader uses path /var/lib/docker/containers which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].
- hostPath volume data in container grafana-agent is accessed in write mode; disallowed in Autopilot. 
- hostPath volume dockerlogs used in container grafana-agent uses path /var/lib/docker/containers which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].

While the first  error can be resolved easily by setting `securityContext.privileged` to `false`, the volume mounts cannot be overridden

### Steps to reproduce

- Deploy grafana agent along with LogsInstance. The log agent fails to come up and the operator logs will show the errors

### Logs

```text
level=error ts=2023-06-01T19:15:21.840889252Z controller=grafanaagent controllerGroup=monitoring.grafana.com controllerKind=GrafanaAgent GrafanaAgent=observability/observability-agent namespace=observability name=observability-agent reconcileID=db5b090f-c57c-4945-8f02-11c6bb547281 msg="error during reconciling" err="failed to reconcile statefulset governing service: failed to create daemonset: admission webhook \"gkepolicy.common-webhooks.networking.gke.io\" denied the request: GKE Warden rejected the request because it violates one or more constraints.\nViolations details: {\"[denied by autogke-disallow-privilege]\":[\"container grafana-agent is privileged; not allowed in Autopilot\"],\"[denied by autogke-no-write-mode-hostpath]\":[\"hostPath volume data in container config-reloader is accessed in write mode; disallowed in Autopilot.\",\"hostPath volume dockerlogs used in container config-reloader uses path /var/lib/docker/containers which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].\",\"hostPath volume data in container grafana-agent is accessed in write mode; disallowed in Autopilot.\",\"hostPath volume dockerlogs used in container grafana-agent uses path /var/lib/docker/containers which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/].\"]}\nRequested by user: 'system:serviceaccount:observability:grafana-probe', groups: 'system:serviceaccounts,system:serviceaccounts:observability,system:authenticated'."
```

**Comment by captncraig** [comment]
I do not think we have plans to update the Operator to support those settings. Our recommended way to install the agent in kubernetes in the future is going to be our [helm chart](https://github.com/grafana/agent/tree/main/operations/helm/charts/grafana-agent), which we hope will be easier to iterate on, and can be more flexible with things like volumes. I do not think it runs privileged by default, and you can customize any volumes as you see fit.
