### ISSUE TITLE
Support Profile for AWS features

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#413]
Add support for passing -profile=example into the agent when using with AWS.

**Comment by rfratto** [comment]
👍 This might already work if you pass `AWS_PROFILE` as an environment variable, but we'll need to validate.

**Comment by mattdurham** [comment]
Yes! https://docs.aws.amazon.com/sdk-for-go/api/aws/session/ looks like by setting a few ENV it will work.

**Comment by rfratto** [comment]
Profiles will be supported as part of the upstream PR (prometheus/prometheus#8509).

**Comment by rfratto** [comment]
This is available as of v0.13.0.
