### ISSUE TITLE
Flow agent dependencies with incompatible or missing licenses (loki, vic, percona-toolkit, and go-common)

### ISSUE THREAD

**Issue by luisgerhorst** [grafana/agent#4130]
### What's wrong?

While checking the licenses of the dependencies pulled when building `agent-flow`, I have discovered the following recursive dependencies which have a license incompatible to Apache 2.0, or no license:

```
github.com/hashicorp/go-discover@v0.0.0-20220105235006-b95dfa40aaed/provider/vsphere/vsphere_discover.go:22:2
  -> github.com/hashicorp/vic@v1.5.1-0.20190403131502-bbfe86ec9443
  Contains incompatible licenses
github.com/percona/mongodb_exporter@v0.31.2/exporter/topology_info.go:25:2
  -> github.com/percona/percona-toolkit@v0.0.0-20211210121818-b2860eee3152
  Incompatible license (GPLv2)
github.com/webdevops/azure-metrics-exporter@v0.0.0-20230502203721-b2bfd97b5313/metrics/insights.go:10:2
  -> github.com/webdevops/go-common@v0.0.0-20230502000651-d37d46be8ee7
  No license
```

Here are the licenses:
- https://github.com/hashicorp/vic/blob/master/LICENSE
- https://github.com/percona/percona-toolkit/blob/3.x/COPYING
- None in https://github.com/webdevops/go-common

Could you clarify whether / why not this affects the license under which the Flow agent sources are distributed?

### Steps to reproduce

Run `make agent-flow` and check the licenses of all pulled dependencies.

### Software version

45211095

### Configuration

```text
NA
```

### Logs

```text
NA
```

**Update 1:** Noticed that the parts of loki this project uses should be under Apache License 2.0 (https://github.com/grafana/loki/blob/main/LICENSING.md).

**Comment by luisgerhorst** [comment]
Regarding mongodb_exporter, there is a long-standing issue at https://github.com/percona/mongodb_exporter/issues/578

**Comment by mattdurham** [comment]
Thank you for the issue. Reviewed the licenses and go-common added a license and we removed the mongodb with the most recent release until the licensing issue is resolved. We believe the vic license is covered appropriately as is.

**Comment by luisgerhorst** [comment]
Reopened a part of this issue as https://github.com/grafana/agent/issues/5081
