### ISSUE TITLE
river: Add jsonpath function

### ISSUE THREAD

**Issue by jkroepke** [grafana/agent#4171]
### Request

Add a [`jsonpath`](https://goessner.net/articles/JsonPath/index.html#e2) function similar to json_encode.

### Use case

Azure supports fetch instance metadata tags through [IMDS](https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=linux#sample-3-get-vm-tags). Request tags give a JSON array back.

For example:

```json
[
  {
    "name": "Department",
    "value": "IT"
  },
  {
    "name": "ReferenceNumber",
    "value": "123456"
  },
  {
    "name": "TestStatus",
    "value": "Pending"
  }
]
```

I would like to pass some of the tag values to `external_label` property. To fetch `Department` in this case, I would like to use a JSONPath expression like `$.[?(@.name == "Department")].value`.

## Alternatives

A map or loop function could also archive this, e.g. `[for tag in remote.http.tags.content: tag.value if tag.key == "Department"]` (HCL syntax)

Since JSONPath seems like a complex full features solution, I'm also open to alternatives.

**Comment by rfratto** [comment]
I wouldn't be necessarily against it, but it does feel like a stopgap in place of more complex expressions via things like #2783. 

As long as it's a light dependency (and the function is named `json_path` to align with our naming conventions), maybe a stopgap is OK for now. 

@grafana/grafana-agent-core-maintainers what do y'all think?

**Comment by mattdurham** [comment]
I am totally fine with this. When dealing with json data this is likely preferable to conditional logic, I always think of this as regex for json =)
