### ISSUE TITLE
OTEL: Resource Detection Processor

### ISSUE THREAD

**Issue by gouthamve** [grafana/agent#4183]
### Request

The [resourcedetectionprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor) and [k8sattributesprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor) are good ways to enrich the signals with common metadata and we should make sure the Agent supports it.

### Use case

To help add the right metadata to the signals collected by the Agent. 

https://github.com/grafana/agent/issues/2909 related k8sattributeprocessor

**Comment by gouthamve** [comment]
This is slightly different from the Prometheus SD mechanism in that it produces attributes that are aligned to the defined [OpenTelemetry Semantic Conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/resource/semantic_conventions/k8s.md).

**Comment by richardqlam** [comment]
https://github.com/grafana/agent/issues/2909 related k8sattributeprocessor

**Comment by cyrille-leclerc** [comment]
Should GA on Feb 27th
