### ISSUE TITLE
Docs feedback: /docs/sources/flow/reference/components/otelcol.exporter.otlp.md

### ISSUE THREAD

**Issue by xorilog** [grafana/agent#4186]
There is an issue on the documentation for the `queue` and `retry` blocks where the actual river mapping is the following:
- [`queue`](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.exporter.otlp/#queue-block) => [`sending_queue`](https://github.com/grafana/agent/blob/v0.34.1/component/otelcol/exporter/otlp/otlp.go#L34)
- [`retry`](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.exporter.otlp/#retry-block) => [`retry_on_failure`](https://github.com/grafana/agent/blob/v0.34.1/component/otelcol/exporter/otlp/otlp.go#L35)

Do you prefer a PR on the documentation to use the coded value or on the code to use the documented value ?

**Comment by xorilog** [comment]
This seems to also impact the following: 
- [`otelcol.exporter.otlphttp`](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.exporter.otlphttp/)
- [`otelcol.exporter.jaeger`](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.exporter.jaeger/)

**Comment by rfratto** [comment]
Hi @xorilog! I think for now the documentation should be updated to match the code (`sending_queue`, `retry_on_failure`). It looks like #4192 is already on track to fix this, so I'll help get that merged so this is addressed!
