### ISSUE TITLE
Grafana Agent in Flow mode otelcol.exporter.otlphttp component ignores TracesEndpoint/ MetricsEndpoint/ LogsEndpoint

### ISSUE THREAD

**Issue by SimoneFalzone** [grafana/agent#4210]
### What's wrong?

Grafana Agent in Flow mode otelcol.exporter.otlphttp component ignores TracesEndpoint/ MetricsEndpoint/ LogsEndpoint.

This is because in [otlphttp.Convert()](https://github.com/grafana/agent/blob/d485da6dc2bf38c25c6ea2a544d94ac42e812ab6/component/otelcol/exporter/otlphttp/otlphttp.go#L61) the values aren't set. 

The change in the screenshot fixes this issue.

![image](https://github.com/grafana/agent/assets/34038878/3fd1ecf5-8a42-4a3e-9a48-d695a5968184)

### Steps to reproduce

Apply the following config:

otelcol.exporter.otlphttp "default" {

  traces_endpoint = "https://backendurl.com/otlp/v1/traces"

  client {
    endpoint = "https://backendurl.com"
    tls {
      insecure             = true
      insecure_skip_verify = true
    }
  }
}

Exporter will always append /v1/traces and tries to send the traces to https://backendurl.com/v1/traces, instead of using https://backendurl.com/otlp/v1/traces.

### System information

5.4.72-microsoft-standard-WSL2 (Ubuntu)

### Software version

Grafana Agent 0.34

### Configuration

```text
otelcol.exporter.otlphttp "default" {

  traces_endpoint = "https://backendurl.com/otlp/v1/traces"

  client {
    endpoint = "https://backendurl.com"
    tls {
      insecure             = true
      insecure_skip_verify = true
    }
  }
}
```

**Comment by rfratto** [comment]
Thanks for reporting! The fix you suggested in the screenshot looks good. Would you be interested in opening up that fix as a PR?

**Comment by SimoneFalzone** [comment]
If it only this small fix, yes. Because i am pretty busy right know and have no time to write additional tests etc.

**Comment by rfratto** [comment]
I don't think we need tests which are easily verified visually to be correct. Exactly what you showed (with a CHANGELOG entry) would be accepted as-is.

**Comment by SimoneFalzone** [comment]
Hello @rfratto,
i opened a PR [#4218 ](https://github.com/grafana/agent/pull/4218)
