### ISSUE TITLE
Install Script is tied to AMD64

### ISSUE THREAD

**Issue by cleanerx** [grafana/agent#423]
The cloud installer is hardcoded to AMD64 platforms.

RELEASE_URL="https://github.com/grafana/agent/releases/download/v${RELEASE_VERSION}"
DEB_URL="${RELEASE_URL}/grafana-agent-${RELEASE_VERSION}-1.amd64.deb"
RPM_URL="${RELEASE_URL}/grafana-agent-${RELEASE_VERSION}-1.amd64.rpm"

Are there ARM (for Raspberry PI4) versions available ?

**Comment by rfratto** [comment]
Hi, we'll have support for selecting your architecture in a week or so, support was just merged for it in #402 but hasn't been released yet. Until then, ARM deb/rpm packages are available at the [releases page](https://github.com/grafana/agent/releases/tag/v0.12.0). Hope this helps!
