### ISSUE TITLE
Support decoupled scraping in the cloudwatch exporter integration

### ISSUE THREAD

**Issue by dtrejod** [grafana/agent#4251]
### Request

The grafana-agent `cloudwatch_exporter` integration vendors the OSS YACE:
https://github.com/nerdswords/yet-another-cloudwatch-exporter

YACE supports a concept of decoupled-scraping. Decoupled-scraping is the default, and instructs YACE to spin up an async [go-routine](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/be9950213af29f00465867983cb2e897350f6063/cmd/yace/scraper.go#L37) that periodically (every 5m) calls `UpdateMetrics()` instead of calling this func every time a request comes into the sever handler. The implementation in grafana-agent makes it so `UpdateMetrics()` is [synchronous](https://github.com/grafana/agent/blob/92f9ee8cc8d16e6cfcd83c1b6e03a370eccc2495/pkg/integrations/cloudwatch_exporter/cloudwatch_exporter.go#L46) with the server handler. 

I'd like to see grafana-agent also support the decoupled-scraping technique used by YACE. 

### Use case

Decoupled-scraping ensures the number of requests that hit Cloudwatch APIs is not tied to the `scrape_interval` set in the grafana-agent. The number of API calls to cloudwatch APIs is linked to the billing calling these APIs too frequently.

**Comment by marctc** [comment]
cc @thepalbi

**Comment by dtrejod** [comment]
Closed by https://github.com/grafana/agent/pull/4914
