### ISSUE TITLE
cloudwatch_exporter not working

### ISSUE THREAD

**Issue by diegobelotti** [grafana/agent#4285]
### What's wrong?

Integration CW exporter doesn't work as documented, tried to update to v0.34.2 (branch: HEAD, revision: 32600dfc) without any change.

There is no way to export metrics from AWS for 1 minute period in static mode and no way to export metrics for 1 minute period in discovery mode (unless using a workaround).

1. static mode: when you try to get 1 period metric, for CPUUtilization Minimum and Maximum, nothing is pushed to mimir. If you configure one metric for 5m period and an other for 1m, the one with 1m stop getting data points after some minutes
2. discovery mode: if you try to get 1m metric, every data point for CPU is set to 0. Memory seems to be reported (aws_rds_freeable_memory_average).
3. discovery mode: all metrics set to 1m, only one set to 5m - WORKING

I'd like to get a working configuration also for 1 and 2 scenarios.

### Steps to reproduce

Use provided config sample with an RDS aurora cluster.

### System information

Linux 3.10.0-1160.88.1.el7.centos.plus.x86_64

### Software version

agent, version v0.34.2 (branch: HEAD, revision: 32600dfc)

### Configuration

```text
# case 1
  cloudwatch_exporter:
    enabled: true
    instance: "cw_exporter"
    scrape_interval: 1m
    fips_disabled: true
    sts_region: eu-west-1
    static:
      - name: myname
        regions:
          - eu-west-1
        namespace: AWS/RDS
        dimension:
          - name: DBClusterIdentifier
            value: mycluster
          - name: Role
            value: WRITER
        custom_tags:
          - key: account
            value: company
          - key: DBClusterIdentifier
            value: mycluster
        metrics:
          - name: CPUUtilization
            period: 1m
            statistics:
              - Average

# case 2
  cloudwatch_exporter:
    enabled: true
    instance: "cw_exporter"
    scrape_interval: 1m
    # Optional: Disable use of FIPS endpoints. Set 'true' when running outside of USA regions.
    fips_disabled: true
    sts_region: eu-west-1 # AWS region to use when calling STS (https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html) for retrieving account information.
    discovery:
     exported_tags:
       AWS/RDS:
        - name
        - AnsibleEnv
     jobs:
      - type: AWS/RDS
        regions:
          - eu-west-1
        search_tags:
          - key: AnsibleEnv
            value: prod
        custom_tags:
          - key: account
            value: myaccount
        metrics:
          - name: CPUUtilization
            period: 1m
            statistics:
              - Maximum
          - name: CPUUtilization
            period: 1m
            statistics:
              - Minimum
          - name: FreeableMemory
            period: 1m
            statistics:
              - Average


# case 3
  cloudwatch_exporter:
    enabled: true
    instance: "cw_exporter"
    scrape_interval: 1m
    # Optional: Disable use of FIPS endpoints. Set 'true' when running outside of USA regions.
    fips_disabled: true
    sts_region: eu-west-1 # AWS region to use when calling STS (https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html) for retrieving account information.
    discovery:
     exported_tags:
       AWS/RDS:
        - name
        - AnsibleEnv
     jobs:
      - type: AWS/RDS
        regions:
          - eu-west-1
        search_tags:
          - key: AnsibleEnv
            value: prod
        custom_tags:
          - key: account
            value: myaccount
        metrics:
          - name: CPUUtilization
            period: 1m
            statistics:
              - Maximum
          - name: CPUUtilization
            period: 5m
            statistics:
              - Minimum
          - name: FreeableMemory
            period: 1m
            statistics:
              - Average
```

**Comment by marctc** [comment]
cc @thepalbi @kgeckhart

**Comment by diegobelotti** [comment]
Let me know if I can help in any way. May be the issue is related to AWS API call to metrics that aren't in real time but there is a delay of 2 or 3 minutes.

**Comment by kgeckhart** [comment]
> Let me know if I can help in any way. May be the issue is related to AWS API call to metrics that aren't in real time but there is a delay of 2 or 3 minutes.

I think this is what you are running up against ATM which is why scenario 1 and 2 do not work but scenario 3 does. The way AWS API calls are made is based on https://grafana.com/docs/agent/latest/static/configuration/integrations/cloudwatch-exporter-config/#period. Length is going to be the longest period defined which for scenario 3 is 5 minutes so for that scenario metrics are aggregated with a 1 minute period for those with a 1 minute period but the exporter is going to look for the latest datapoint in the last 5 minutes because 1 metric has a 5 minute period. 

I believe @thepalbi is working on some changes to allow setting period and length independently but if not that is what's needed to solve this issue. A length of 5 minutes and a period of 1 minute for each of these metrics will allow for a 1 minute scrape interval that always gets the latest 1 minute data point in the past 5 minutes.
