### ISSUE TITLE
Pushing to loki.source.api does not honour the url format accepted by promtail and loki

### ISSUE THREAD

**Issue by prime23-gareth** [grafana/agent#4317]
### What's wrong?

Grafana Agent v0.34.3 using the loki.source.api component, expects the URL path to be `http://<server>:<port>/api/v1/push` unlike existing Promtail and Loki endpoints that accept the path `http://loki:3100/loki/api/v1/push` as defined here: https://grafana.com/docs/loki/latest/api/#push-log-entries-to-loki

This causes a 404 error to be reported in the Windows Event log:
`ts=2023-06-30T12:54:39.063912Z component=loki.source.api.loki_push_api level=debug msg="POST /loki/api/v1/push (404) 0s"`

### Steps to reproduce

- Install Grafana Agent on Windows and configure as described here: https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.api/
- Enable Grafana Agent debug logging.
- Send output from your .NET 6.0 application using Serilog and the Serilog Loki Sink to the Grafana Agent.
- No data will appear in Loki and there will be an error in the Windows Event Log.

### System information

Windows Server 2019 DataCenter Edition

### Software version

Grafana Agent 0.34.3

### Logs

```text
Windows Event Logs:

`ts=2023-06-30T12:54:39.063912Z component=loki.source.api.loki_push_api level=debug msg="POST /loki/api/v1/push (404) 0s"`
```

**Comment by prime23-gareth** [comment]
My guess is it is related to this code in p`ush_api_server.go` where those endpoints are defined:

```
func (s *PushAPIServer) Run() error {
	level.Info(s.logger).Log("msg", "starting push API server")

	err := s.server.MountAndRun(func(router *mux.Router) {
		router.Path("/api/v1/push").Methods("POST").Handler(http.HandlerFunc(s.handleLoki))
		router.Path("/api/v1/raw").Methods("POST").Handler(http.HandlerFunc(s.handlePlaintext))
		router.Path("/ready").Methods("GET").Handler(http.HandlerFunc(s.ready))
	})
	return err
}
```

It doesn't appear to support the /loki/api/v1/push endpoint.

**Comment by prime23-gareth** [comment]
I've raise a potential issue in the Grafana Loki Sink repository here for reference: https://github.com/serilog-contrib/serilog-sinks-grafana-loki/issues/187

**Comment by mattdurham** [comment]
This also causes issues with json requests and labels not being processed.

Given the below json push

```
curl -vvv -H "Content-Type: application/json" -XPOST -s "http//:localhost:8001/api/v1/push" --data-raw \
  '{"streams": [{ "stream": { "fooo": "barxx" }, "values": [ [ "1688569965000000000", "fizzbuzzsdfxxxxx" ] ] }]}'
```

This will NOT get parsed as the v1 since it is missing the loki in the path, it should be /loki/api/v1. This is checked via

github.com/grafana/loki/pkg/loghttp/push/push.go:103 which calls
github.com/grafana/loki/pkg/loghttp/versions.go

// GetVersion returns the loghttp version for a given path.
func GetVersion(uri string) Version {
	if strings.Contains(strings.ToLower(uri), "/loki/api/v1") {
		return VersionV1
	}

	return VersionLegacy
}

**Comment by rfratto** [comment]
> Easy way is to change the default path that loki.source.api component uses to /loki/api/v1/push - this would be a breaking change.

You could also make the base URL in loki.source.api configurable, that way you could set it to `/loki` for compatibility with existing clients. This would have to be documented though, since most clients already assume the base URL is `/loki`.

**Comment by tpaschalis** [comment]
I'm also in favor of making the URL configurable.

To solve both issues mentioned by @thampiotr (for clients _sending_ data to us, which assume the path must be /loki/api/v1/push and _our_ version detection code) we have to port over the `github.com/grafana/loki/pkg/loghttp/push` package we're using in `internal/lokipush` to match the detection logic whenever a different path is provided.

**Comment by mattdurham** [comment]
I have a PR where it handles both URLs and converts to the old path for passing to push package. This way it isnt a breaking change and handles the code paths appropriately.
