### ISSUE TITLE
[Flow Documentation] `loki.relabel` docs refers to metric rules rather than log lines rules

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/agent#4329]
### What's wrong?

[`loki.relabel` docs](https://grafana.com/docs/agent/latest/flow/reference/components/loki.relabel/) refers to metric rules rather than log lines rules making the documentation confusing.

`loki.relabel` cannot share he same "rule block" documentation fragment as `prometheus.relabel`.

https://grafana.com/docs/agent/latest/flow/reference/components/loki.relabel/

### Steps to reproduce

![image](https://github.com/grafana/agent/assets/459691/a5fe17ae-65da-48da-bb82-6e881f1486ec)

**Comment by GrafanaWriter** [comment]
@clayton-cornell - can you please review and move out of triage to either Backlog or In Progress?

**Comment by clayton-cornell** [comment]
@cyrille-leclerc FYI, this is fixed in next, 0.34 and 0.33
