### ISSUE TITLE
Support promtail's `drop_rate_limited_batches` in `loki.write`

### ISSUE THREAD

**Issue by thampiotr** [grafana/agent#4335]
### Request

`promtail` currently supports the following setting for Loki clients:
```
	// When enabled, Promtail will not retry batches that get a
	// 429 'Too Many Requests' response from the distributor. Helps
	// prevent HOL blocking in multitenant deployments.
	DropRateLimitedBatches bool `yaml:"drop_rate_limited_batches"`
```

This is not supported in `loki.write` component.

### Use case

Helps prevent HOL blocking in multitenant deployments.

**Comment by thampiotr** [comment]
Note: if this is added, we may need to update the config converters too if they're already merged.

**Comment by rfratto** [comment]
The prometheus.remote_write version of this is the inverse: an attribute to _opt-in_ to retrying HTTP 429s.

Should we add the Promtail field as-is or make it align with prometheus.remote_write and have it be an opt-in field instead?

**Comment by thampiotr** [comment]
I would be in favour of aligning with Prometheus, since it's a reasonable default. We can have `retry_on_http_429` added to `loki.write` [similar to this](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.remote_write/#queue_config-block).

**Comment by thampiotr** [comment]
Related issue: https://github.com/grafana/agent/issues/4441

**Comment by rfratto** [comment]
Makes sense to me 👍
