### ISSUE TITLE
Support configuring scheduled_task for windows_exporter

### ISSUE THREAD

**Issue by ntimo** [grafana/agent#4341]
### Request

Currently the Grafana Agent's (static mode) build in windows_exporter does not support the scheduled_task configuration (https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.scheduled_task.md) this could be helpful the use the batteries included approach of the Grafana Agent to monitor schedueld tasks. Therefore it should be possible to configure this.

### Use case

Monitoring scheduled tasks on windows can be important to make sure they work as intended, therefore it would be amazing if the Grafana Agent's windows_exporter would support this just like the upstream project does.

**Comment by jkroepke** [comment]
@ntimo could you please explain, why it is not supported?

https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.exporter.windows/#scheduled_task-block

**Comment by ntimo** [comment]
@jkroepke because I am using the static mode of the grafana agent and for the static mode this config option does not exist.

**Comment by jkroepke** [comment]
https://github.com/grafana/agent/blob/3d92001037b3a9915b1760a15683f3023a876b17/pkg/integrations/windows_exporter/config.go#L96

Seems like present, but not documented.

**Comment by duj4** [comment]
hi @ntimo , are you able to configure the scheduled_task for now? As in our env (GA 0.35.2), once scheduled_task is added to collector list, GA will go down for a while.

**Comment by rfratto** [comment]
Tagging as `type/docs` since the field exists but is lacking documentation in static mode.

**Comment by GrafanaWriter** [comment]
@clayton-cornell - assigning to you and moving to Backlog. Please remove yourself as assignee as appropriate.
