### ISSUE TITLE
Add logs limits support similar to promtail

### ISSUE THREAD

**Issue by thampiotr** [grafana/agent#4342]
### Request

Promtail has [limits configuration](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#limits_config) section which allows to configure several limits for logging pipeline. These do not appear to be implemented currently in Loki flow components.

* [readline_rate_enabled: <bool> | default = false]
* [readline_rate: <int> | default = 10000]
* [readline_burst: <int> | default = 10000]
* [readline_rate_drop: <bool> | default = true]
* [max_streams: <int> | default = 0]
* [max_line_size: <int> | default = 0]
* [max_line_size_truncate: <bool> | default = false]

This could be implemented via a new `loki.limit` component with all these features, except for `max_streams` which may need to be added to a different component.

Another option would be to extend existing components.

### Use case

If I want to protect Loki from excessive traffic/load and shed load on the agent side when there is a burst in traffic.

**Comment by rfratto** [comment]
Where in Promtail do the limits get applied? (i.e., is it by the client, or the scraper, or something else?)

**Comment by thampiotr** [comment]
The docs say those are global limits for instance of promtail:
> The optional limits_config block configures global limits for this instance of Promtail.

I was advised that we also have `loki.process` which can have `stage.limit` and `stage.drop` which, AFAICT, can support the limits like above.

The only difference is that they would be per `loki.process` component and not global to the process. I think that's fine and actually gives plenty of flexibility. 

I would be inclined to close this ticket, unless there are some other concerns?

**Comment by mattdurham** [comment]
No concerns, closing
