### ISSUE TITLE
`loki.source.api` does not handle json requests to `/api/v1` correctly

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#4348]
### What's wrong?

Loki looks at the request and to trigger V1 behavior looks at the path `/loki/api/v1` but we server it via `/api/v1`.

### Steps to reproduce

Create a river config like below
```

loki.source.api "listener" {
    http {
        listen_address = "0.0.0.0"
        listen_port = 8001
    }
    forward_to = [loki.write.endpoint.receiver]
}


loki.write "endpoint" {
    endpoint {
        url = "https://logs-prod-us-central1.grafana.net/loki/api/v1/push"
        basic_auth {
            username = USER
            password = "PASSWORD"
        }
    }
}
```

And then send 

```
curl -vvv -H "Content-Type: application/json" -XPOST -s "http//:localhost:8001/api/v1/push" --data-raw \
  '{"streams": [{ "stream": { "fooo": "barxx" }, "values": [ [ "1688569965000000000", "fizzbuzzsdfxxxxx" ] ] }]}'
```

This will NOT get parsed as the v1 since it is missing the `loki` in the path, it should be `/loki/api/v1`. This is checked via

`github.com/grafana/loki/pkg/loghttp/push/push.go:103` which calls
github.com/grafana/loki/pkg/loghttp/versions.go

```
// GetVersion returns the loghttp version for a given path.
func GetVersion(uri string) Version {
	if strings.Contains(strings.ToLower(uri), "/loki/api/v1") {
		return VersionV1
	}

	return VersionLegacy
}
```

**Comment by rfratto** [comment]
@mattdurham Is this a dupe of #4317?

**Comment by mattdurham** [comment]
Crap, yes closing as dupe of #4317

**Comment by mattdurham** [comment]
Its slightly different but the root is the same, but will add context to 4317
