### ISSUE TITLE
Empty regex causes metrics inside pods to be not scraped

### ISSUE THREAD

**Issue by flokli** [grafana/agent#436]
I deployed the agent according to https://github.com/grafana/agent/#getting-started, which essentially just uses `https://github.com/grafana/agent/blob/v0.12.0/production/kubernetes/agent.yaml` under the hood.

For some reason, the "empty regex" relabel_config at

https://github.com/grafana/agent/blob/e9bd098ffd09930015173008ffb254018e7333c4/production/kubernetes/agent.yaml#L51-L54

seems to be problematic - with it, I couldn't scrape pod workloads exporting their own metrics on a `/metrics` endpoint.

What's that line supposed to be doing in first place?

**Comment by rfratto** [comment]
Hi! It's [looking for a label named `name`](https://github.com/grafana/agent/blob/e9bd098ffd09930015173008ffb254018e7333c4/docs/getting-started.md#kubernetes-install-script). Do your pods have that?
