### ISSUE TITLE
kubernetes manifests: use secret and configmap for credentials/username/url

### ISSUE THREAD

**Issue by flokli** [grafana/agent#439]
https://github.com/grafana/agent#getting-started currently points to a bash script, which downloads a manifest file, runs envsubst on it. Afterwards, this is piped to `kubectl apply -f`.

This will interpolate username, password and URLs somewhere deep in the config file directly.
(It'll also interpolate the namespace name, but that's hardcoded by the shell script, so let's ignore this for now).

`grafana-agent` supports substituting from environment variables in the config file (if you add `-config.expand-env`) to the `args`.

It would be *way* more convenient if you could just ship raw manifests (so people can pull these in via whatever tooling they use), without having to run `envsubst`, and require another `ConfigMap` containing username and url, and a `Secret` resource containing the password.

The quickstart instructions could provide one-liners to create these resources.

**Comment by flokli** [comment]
From @rfratto at https://github.com/grafana/agent/discussions/437#discussioncomment-411086:

> I'm open to discussing #439, but just warning you that it's not a priority from our side since soon-ish we're going to abandon the bash script approach for something more customizable. (Also it was designed with the intent of having one command to copy-and-paste when going through the Grafana Cloud setup, but that's a discussion we can have over on the issue directly)

**Comment by flokli** [comment]
How are the files in https://github.com/grafana/agent/tree/main/production/kubernetes produced, and kept in sync with the tanka/jsonnet things?

**Comment by flokli** [comment]
Still relevant.

**Comment by rfratto** [comment]
(I'm doing a bug scrub today and came across this)

> How are the files in https://github.com/grafana/agent/tree/main/production/kubernetes produced, and kept in sync with the tanka/jsonnet things?

They're produced from [production/kubernetes/build](https://github.com/grafana/agent/tree/main/production/kubernetes/build/build.sh).
