### ISSUE TITLE
Grafana Agent still unable to install on FIPS-mode CentOS 9

### ISSUE THREAD

**Issue by andrewimeson** [grafana/agent#4419]
### What's wrong?

This was first reported in #4267, and an attempt to fix was made in #4268, but the release since that PR was merged still is not able to be installed on a FIPS-mode EL system.

### Steps to reproduce

```sh
# On a test CentOS 9 Stream box, enable FIPS mode (warning, irreversible)
fips-mode-setup --enable
shutdown -r now
```

And then with an `/etc/yum.repos.d/grafana.repo` with GPG checking turned on or off:

```ini
[grafana]
baseurl = https://rpm.grafana.com
enabled = 1
gpgcheck = 0
gpgkey = https://rpm.grafana.com/gpg.key
name = grafana
repo_gpgcheck = 0
sslcacert = /etc/pki/tls/certs/ca-bundle.crt
sslverify = 1
```

```sh-session
$ sudo dnf install grafana-agent-flow -y
Last metadata expiration check: 2:29:44 ago on Wed 12 Jul 2023 02:58:43 PM UTC.
Dependencies resolved.
=============================================================================================================================================================================
 Package                                          Architecture                         Version                                   Repository                             Size
=============================================================================================================================================================================
Installing:
 grafana-agent-flow                               x86_64                               0.34.3-1                                  grafana                                51 M

Transaction Summary
=============================================================================================================================================================================
Install  1 Package

Total download size: 51 M
Installed size: 177 M
Downloading Packages:
grafana-agent-flow-0.34.3-1.amd64.rpm                                                                                                         17 MB/s |  51 MB     00:03
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                         17 MB/s |  51 MB     00:03
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                     1/1
  Installing       : grafana-agent-flow-0.34.3-1.x86_64                                                                                                                  1/1
Error unpacking rpm package grafana-agent-flow-0.34.3-1.x86_64
  Verifying        : grafana-agent-flow-0.34.3-1.x86_64                                                                                                                  1/1

Failed:
  grafana-agent-flow-0.34.3-1.x86_64

Error: Transaction failed
```

### System information

CentOS 9 Stream kernel 5.14.0-333.el9.x86_64

### Software version

Grafana Flow Agent 0.34.3-1

**Comment by andrewimeson** [comment]
Here's a comparison of a signed package from the CentOS repos and the Grafana Agent Flow

```sh-session
$ rpm -v --checksig vim-enhanced-8.2.2637-20.el9.x86_64.rpm
vim-enhanced-8.2.2637-20.el9.x86_64.rpm:
    Header V3 RSA/SHA256 Signature, key ID 8483c65d: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V3 RSA/SHA256 Signature, key ID 8483c65d: OK

$ rpm -v --checksig grafana-agent-flow-0.34.3-1.amd64.rpm
grafana-agent-flow-0.34.3-1.amd64.rpm:
    Header V4 RSA/SHA512 Signature, key ID 2cf3c0c6: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
```

**Comment by andrewimeson** [comment]
Looking at other projects, it may also need `%_binary_filedigest_algorithm sha256` in the RPM macros.

**Comment by mattdurham** [comment]
Can you check against the boringcrypto suffixed images/binaries?

**Comment by andrewimeson** [comment]
I tried to reproduce this locally by creating a GPG key and building and signing an RPM with the `~/.rpmmacros` from this repository, but the result RPM installs fine for me on a FIPS-mode test machine with both `dnf localinstall` and `rpm -i`.

The error from trying to install grafana-agent-flow might be instructive

```sh-session
[root@fips-test ~]# rpm -i grafana-agent-flow-0.35.1-1.amd64.rpm
error: unpacking of archive failed on file /etc/grafana-agent-flow.river;64c165ff: cpio: Digest mismatch
error: grafana-agent-flow-0.35.1-1.x86_64: install failed
```

Interestingly, the `grafana` (not `grafana-agent[-flow]`) package installs with no issues.

**Comment by andrewimeson** [comment]
I think it is the lack of `%_binary_filedigest_algorithm`. My RPM environment must have a different default and that's why my attempt to reproduce the issue by copying the `.rpmmacros` failed.

```sh-session
[root@fips-test ~]# rpm -qp --qf "%{filedigestalgo}\n" grafana-agent-flow-0.35.1-1.amd64.rpm
(none)
[root@fips-test ~]# rpm -qp --qf "%{filedigestalgo}\n" grafana-10.0.3-1.x86_64.rpm
8
[root@fips-test ~]# rpm -qp --qf "%{filedigestalgo}\n" hello-world-1.0.0-1.el9.noarch.rpm
8
```

Setting `_binary_filedigest_algorithm` to `sha256` (indirectly, via FPM) is how Elastic Beats (https://github.com/elastic/beats/pull/27103) fixed this issue, so I'm going to submit a PR to do the same.

**Comment by rfratto** [comment]
The RPMs that get published are re-signed, which might be making your change a no-op. @julienduchesne knows the most about the RPM publish process, but he's on PTO until the 31st.

**Comment by andrewimeson** [comment]
@rfratto I think the GPG signing is completely separate from the file digest creation (you can have the latter without the former), but I can't say for sure.

I built the [build-image/Dockerfile](https://github.com/grafana/agent/blob/main/build-image/Dockerfile), setup the rpmmacros file, built my test package, and it's properly setting the file digest, so I remain confused.

**Comment by andrewimeson** [comment]
I take that back - `rpmsign` / `rpm --sign` is responsible for creating the digest, not just signing with GPG, so your theory seems like a good explanation.

I'll set this aside for a while and wait for Julien to take a look when he's back.

**Comment by julienduchesne** [comment]
Seems like the fix didn't work in #4268 since the digest is not OK either on the releases on this repo or on packages.grafana.net. Using @andrewimeson's command:

```console
julienduchesne@Juliens-MacBook-Pro ~ % rpm -qp --qf "%{filedigestalgo}\n" ~/Downloads/rpm_Packages_grafana-agent-0.34.3-1.amd64.rpm 
(none)
julienduchesne@Juliens-MacBook-Pro ~ % rpm -qp --qf "%{filedigestalgo}\n" ~/Downloads/rpm_Packages_grafana-agent-0.35.2-1.amd64.rpm 
(none)
julienduchesne@Juliens-MacBook-Pro ~ % rpm -qp --qf "%{filedigestalgo}\n" ~/Downloads/grafana-agent-0.35.2-1.amd64.rpm 
(none)
```

The first two files are from packages.grafana.net and the last one is from the repo's Github release. I've verified that there is no re-signing in our internal process uploading from Github releases -> packages.grafana.net so once the sig is fixed in the release process here: https://github.com/grafana/agent/blob/main/packaging/grafana-agent/rpm/gpg-sign.sh, then it should work

**Comment by rfratto** [comment]
@andrewimeson How did you try to test your fix? If you run `USE_CONTAINER=1 make dist-agent-flow-packages-amd64` locally, it'll place the RPM and DEB in `dist/`, replacing our build environment exactly, including shelling out to a Docker container with our build tools.

**Comment by andrewimeson** [comment]
I am having a hard time getting a build environment working with the `make` route.

This may be exceeding my ability to troubleshoot given my lack of knowledge on the interworking of the Grafana agent build system.
