### ISSUE TITLE
bump grafana-agent helm chart to v0.35.0

### ISSUE THREAD

**Issue by flokli** [grafana/agent#4510]
### Request

I can't use some of the features in v0.35, because the helm chart still deploys `v0.34.2`.

### Use case

Run the current release of grafana-agent with the helm chart.

**Comment by rfratto** [comment]
@mattdurham What's the status of #4505 so we update the Helm chart? Can we decouple changing the documentation and changing the Helm chart so we don't block people from upgrading?

**Comment by mattdurham** [comment]
Going to work on it today
