### ISSUE TITLE
node_exporter integration (diskstats)

### ISSUE THREAD

**Issue by hakuno** [grafana/agent#4517]
### What's wrong?

The path is wrong.
Maybe it doesn't set `--path.udev.data=/host/root/run/udev/data` properly with `integrations.node_exporter.rootfs_path`.
It reads `/run/udev/data` instead of `/host/root/run/udev/data`.

### Steps to reproduce

By using the Helm chart of Grafana Agent with static mode.
Enabled the `node_exporter` integration.
The volumes and their mounts are okay. Root, proc and sys are set on `agent.mounts.extra` and `controller.volumes.extra`.
But the node exporter doesn't know the correct path that should be read from `integrations.node_exporter.rootfs_path` as told.

### System information

GKE 1.25

### Software version

Grafana Agent v0.34.2

### Configuration

```text
integrations:
  node_exporter:
    enabled: true
    rootfs_path: /host/root
    sysfs_path: /host/sys
    procfs_path: /host/proc
```

### Logs

```text
ts=2023-07-19T16:18:05.136133134Z caller=diskstats_linux.go:264 level=error integration=node_exporter collector=diskstats msg="Failed to open directory, disabling udev device properties" path=/run/udev/data
```

**Comment by marctc** [comment]
I think this [PR](https://github.com/grafana/agent/pull/4481) solves your problem, no?

**Comment by hakuno** [comment]
> I think this [PR](https://github.com/grafana/agent/pull/4481) solves your problem, no?

@marctc Interesting. Yes, I think so.

At moment, my option is scraping from standalone Node Exporter deployment until then.
