### ISSUE TITLE
Issue with windows encoding and expand vars

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#4519]
### What's wrong?

If using an encoding that is not windows 1252 on a file (lets say UTF-16E) when the agent tries to expand vars it seems to write a UTF8 string into UTF16. This gives an error.

The simplest solution would be to either convert to UTF8 beforehand or return an error if the file is not utf8 or windows 1252. 

### Steps to reproduce

TBD

**Comment by rfratto** [comment]
Is this just for static mode?

**Comment by mattdurham** [comment]
Tested and it affects both

**Comment by mattdurham** [comment]
Possibly due to injecting the environment variables into a byte stream without converting to UTF8.

**Comment by mattdurham** [comment]
This might be able to be solved by using https://github.com/softlandia/cpd
