### ISSUE TITLE
Update k3d example to use k3d 4.x

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#452]
The `k3d` example still expects a version <3.0, and is easy to miss as a requirement. We should update the scripts to expect k3d 4.x. 

k3d 4.x automatically merges the cluster into your kube config for you, so we can also remove the merge script after this upgrade, and just leave the create script.

**Comment by hoenn** [comment]
@rfratto I think this closed by #510

**Comment by rfratto** [comment]
👍
