### ISSUE TITLE
Supporting custom DNS servers

### ISSUE THREAD

**Issue by jkroepke** [grafana/agent#4595]
### Request

It should be possible to define a custom DNS that is used across the whole agent.

### Use case

We are using Grafana Agent for VM based monitoring. On each machine, an agent is deployment.

DNS issues in enterprise environment are common and some special configuration at customer environment could break the connection to our endpoints. For example some machines requires to use the DNS servers of the Active Directory which is not compatible with Route53 private zones or Azure DNS private zones.

**Comment by rfratto** [comment]
This would be extremely challenging for us to pull off, since it would also require making sure that all of our upstream dependencies can be configured with custom DNS.

**Comment by jkroepke** [comment]
Before writing this issue, I read https://koraygocmen.medium.com/custom-dns-resolver-for-the-default-http-client-in-go-a1420db38a5d and think that its more a low hanging low fruit. However if its more complicated they we may have to throw away it.

**Comment by rfratto** [comment]
Right, in that case the issue is making sure all of our upstream dependencies respect `http.DefaultTransport` (Prometheus doesn't; it creates its own transport), so it's still a fairly large undertaking to achieve.

**Comment by jkroepke** [comment]
I guess then I will close that issue. Seems not worth enough.
