### ISSUE TITLE
Interoperability between local.file_match and discovery.file

### ISSUE THREAD

**Issue by djcode** [grafana/agent#4610]
### Background

Now that 0.35.0 has `discovery.file` and `local.file_match` it would be great if these could work together.
`local.file_match` is structured in a way to only really works for `loki.source.file`, but could also be used to collect files to be passed to `discovery.file`.
`local.file_match` expects a `path_targets` formatted like `[{"__path__" = DOUBLESTAR_PATH}]` where `discovery.file` expects `[FILE_PATH_1, FILE_PATH_2, ...]` making it incompatible to one another.

In my experimenting, I don't think this possible currently, but I'd love to be proven wrong!

### Proposal

There's a few solutions I can think of to address this.

1. Add an new exported field to `local.file_match` in the `discovery.file` format.
2. Make `discovery.file` support an array of objects with a `__path__` key.
3. A function to modify the contents of an array, similar to what Terraform can do commonly seen in for_each lines. This would be really powerful and have lots of other uses.
```
local.file_match "tmp" {
  path_targets = [{"__path__" = "/tmp/logs/**/*.log"}]
}

discovery.file "example" {
  files = [ for k,v in local.file_match.tmp.targets: v.__path__ ]
}
```

**Comment by rfratto** [comment]
> A function to modify the contents of an array, similar to what Terraform can do commonly seen in for_each lines. This would be really powerful and have lots of other uses.

I have a proposal for something similar to this with #2783, where this would be possible:

```
local.file_match "tmp" {
  path_targets = [{"__path__" = "/tmp/logs/**/*.log"}]
}

discovery.file "example" {
  files = map(
    func(target) => target.__path__,
    local.file_match.tmp.targets,
  )
}
```

**Comment by mattdurham** [comment]
We have accepted #2783 which implements similar functionality.
