### ISSUE TITLE
Flow: Add OpenTelemetry Collector components - Filter Processor

### ISSUE THREAD

**Issue by kago-dk** [grafana/agent#4628]
### Request

Please consider adding the https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor into Grafana Agent Flow so that we can filter spans from traces https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/filterprocessor/README.md#filter-spans-from-traces ?

### Use case

Filter spans from traces and easily migrate from Otel Collector.

**Comment by evenh** [comment]
I would love to see this in Flow mode as well, to remove health checks etc.

**Comment by hainenber** [comment]
Hi, please help assigning me to this 😄

**Comment by rfratto** [comment]
@hainenber done!
