### ISSUE TITLE
loki.source.kafka should use secret type for password

### ISSUE THREAD

**Issue by thampiotr** [grafana/agent#4636]
### What's wrong?

https://github.com/grafana/agent/blob/29131a6cfbe6af4939577a85940836103bf628fb/component/loki/source/kafka/kafka.go#L56 uses `string` for password

### Steps to reproduce

Set `loki.source.kafka` password in the args.
Go to Agent UI.
See the password leaked in the UI.

**Comment by harsiddhdave44** [comment]
@thampiotr I'd like to take this up. Can you please assign it to me?

**Comment by rfratto** [comment]
@harsiddhdave44 Done, it's all yours!
