### ISSUE TITLE
Improve remote write outage recovery by discarding too-old samples

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#4651]
During prolonged outages of a remote write endpoint, Grafana Agents will continue accumulating data and can potentially fall behind by a significant period of time.

Once an outage ends, catching up (if possible at all) could take hours, since the WAL contents are read and pushed to the remote_write endpoint in sequence.

Moreover, in cases where the remote_write endpoint has a configured timeframe as to how old data it can accept, most of this data will be discarded at the database layer, putting unnecessary load  on both the agent and the remote write backend.

An interesting idea that can generally help with recovering from outages would be to discard datapoints that we know cannot be accepted by the remote earlier on. A way to achieve this is the following Prometheus proposal, where some of the legwork has already been done for us.

https://github.com/prometheus/prometheus/issues/7912

**Comment by marctc** [comment]
Related: https://github.com/prometheus/prometheus/issues/7912

**Comment by tpaschalis** [comment]
I'm updating the description of the ticket to align with our current direction.

**Comment by marctc** [comment]
PR to upstream: https://github.com/prometheus/prometheus/pull/13002
