### ISSUE TITLE
Always use retry after header even if response code is not 429

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#4652]
### Request

Always use retry after header even if response code is not 429

### Use case

If the server isn't properly sending a 429 but is sending a retry header we should honor that, so that load shedding can occur.

**Comment by ptodev** [comment]
Is this for any HTTP status code, or just for 5xx ones?

**Comment by mattdurham** [comment]
Any status code, has long as it sends back a retry header.

**Comment by ptodev** [comment]
I have a couple of concerns if this has to apply for any status code:
* I'm not sure if it makes sense to retry status codes such as 1xx and 2xx.
* Given the context around why this issue was raised, I'm not sure if it's necessary to retry anything other than 429 and 5xx.

**Comment by mattdurham** [comment]
I think the underlying assumption it is easier to override the status code incorrectly than applying a header. So in the case where you have an internal system that is wrapped by a gateway and the internal system adds a header to retry but the gateway doesnt wrap the status code correctly.

**Comment by tpaschalis** [comment]
Closing this as completes; we have merged the Prometheus PR and brought it back to the Agent.
