### ISSUE TITLE
Ability to tail compressed files (like promtail does)

### ISSUE THREAD

**Issue by thampiotr** [grafana/agent#4669]
### Request

Promtail currently supports reading logs from compressed files:
```
# Defines decompression behavior for the given scrape target.
decompression:
  # Whether decompression should be tried or not.
  [enabled: <boolean> | default = false]

  # Initial delay to wait before starting the decompression.
  # Especially useful in scenarios where compressed files are found before the compression is finished.
  [initial_delay: <duration> | default = 0s]

  # Compression format. Supported formats are: 'gz', 'bz2' and 'z.
  [format: <string> | default = ""]
```

We should add the same functionality to `loki.source.file`.

### Use case

* I want to read logs from a compressed file
* I want to migrate from promtail to agent flow

**Comment by tpaschalis** [comment]
nit: `loki.source.file` currently _does_ support reading from compressed files. When we forklifted the component over, the Promtail didn't allow for these settings but simply looked for the files' suffix and treated them accordingly.

I agree that these new settings can be useful to users, so we should port them for completion's sake.

**Comment by thampiotr** [comment]
I see, thanks. I didn't see anything about compression in [loki.source.file documentation](https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.file/) - is it not documented?

**Comment by thampiotr** [comment]
I intend to switch the behaviour of compression to get in line with what promtail does, as per this comment: https://github.com/grafana/loki/pull/8994#pullrequestreview-1369428691 

In summary, in the new promtail version:
* compression is off by default - users need to enable it explicitly 
* when enabled, only the specified compression format is used
* it adds an initialDelay feature useful to avoid reading files that are not yet fully written

These changes were added to promtail after reports from users that autodetection would not always work (when file extension was not matching) and they could even get panics. 

It is a bit more rigid, but it's also simple and predictable, so I intend to switch to use this approach even if it's a breaking change.
