### ISSUE TITLE
debian package should not overwrite existing configuration file

### ISSUE THREAD

**Issue by tcurdt** [grafana/agent#468]
Installing and/or upgrading a package should not wipe out existing configuration files.
I assume it's missing a `conffile` entry.

https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html#conffile

**Comment by rfratto** [comment]
I'm not able to reproduce this with the Debian package. Can you share what commands you tried?

This is what I did:

```bash
# Elevate to a superuser to make the rest of this less verbose 
sudo su 

# Download and install Debian package
wget https://github.com/grafana/agent/releases/download/v0.13.0/grafana-agent-0.13.0-1.amd64.deb
apt install ./grafana-agent-0.13.0-1.amd64.deb

# Append a comment to the end of the file and see if it persists after a reinstall. 
echo "# test" >> /etc/grafana-agent.yaml
apt reinstall ./grafana-agent-0.13.0-1.amd64.deb 
grep "# test" /etc/grafana-agent.yaml

# Try completely uninstalling the package and installing it fresh to see if the changes 
# to the config file persist. 
apt uninstall grafana-agent
apt install ./grafana-agent-0.13.0-1.amd64.deb
grep "# test" /etc/grafana-agent.yaml 
```

Note that the [Grafana Cloud install script](https://github.com/grafana/agent/blob/main/production/grafanacloud-install.sh) will always overwrite `/etc/grafana-agent.yaml` for various internal reasons. That won't be the case forever, but it won't be addressed shortly. 

Until then, if you're running the install script and need to make changes, I would recommend creating your own configuration file and specifying it in `/etc/default/grafana-agent`, which is loaded as the EnvironmentFile for the service.

**Comment by tcurdt** [comment]
> Note that the Grafana Cloud install script will always overwrite /etc/grafana-agent.yaml for various internal reasons. That won't be the case forever, but it won't be addressed shortly.

Aaaah, OK. I didn't see a conffile entry and just blamed it on the package.
So it really is the curl installer. Sorry, my bad.

> Until then, if you're running the install script and need to make changes, I would recommend creating your own configuration file and specifying it in /etc/default/grafana-agent, which is loaded as the EnvironmentFile for the service.

So you suggest to change `CONFIG_FILE="/etc/grafana-agent.yaml"` in `/etc/default/grafana-agent` to get around this.
And `/etc/default/grafana-agent` won't be overwritten?

**Comment by rfratto** [comment]
> So you suggest to change CONFIG_FILE="/etc/grafana-agent.yaml" in /etc/default/grafana-agent to get around this.
And /etc/default/grafana-agent won't be overwritten?

Right, it won't get overwritten. I verified myself that changes to `/etc/default/grafana-agent` persist between (re-)installs.

**Comment by tcurdt** [comment]
I guess then it's safe to close this issue. Thanks!
