### ISSUE TITLE
WAL slowly fills forever on corrupt segment

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#47]
I noticed an agent with an infinitely growing WAL today. This was found in the logs:

```
level=warn ts=2020-04-21T21:26:44.741058582Z caller=instance.go:365 agent=prometheus instance=agent msg="could not truncate WAL" err="create checkpoint: read segments: corruption in segment /tmp/agent/data/agent/wal/00001087 at 131133: unexpected full record"
--
```

This is preventing truncation from running and required a full delete of the WAL.

**Comment by kirelagin** [comment]
We’ve got the same (with vanilla Prometheus, not Grafana Agent) after the server ran out of disk space.
