### ISSUE TITLE
Unable to stop the agent from writing old data

### ISSUE THREAD

**Issue by nicklan** [grafana/agent#476]
We basically want to prevent the agent from ever writing data that's more than a few minutes old. However, no matter what config we try, the old wals never seem to get cleaned up, and if we take down our remote-write endpoint, when it comes back the agents try and write lots of old data.

Testing is being done on `grafana/agent:latest`

I thought I could do this by setting the following configs:
```
prometheus:   
  configs:
    - name: agent
      wal_truncate_frequency: 4m
      min_wal_time: 2m
      max_wal_time: 3m
  wal_directory: [dir]
  wal_cleanup_age: 4m
  wal_cleanup_period: 3m
```

Now, when I prevent the agent from writing data for a while, I do see the wal being rolled over at 4 minute intervals:
```
[dir]/0a0119de6b4fd7a0fbe37119f4beca7c/wal# ls -lh
total 3.3M
-rw-r--r--. 1 root root 1.2M Mar 19 23:00 00000002
-rw-r--r--. 1 root root 1.2M Mar 19 23:04 00000003
-rw-r--r--. 1 root root 571K Mar 19 23:06 00000004
drwxr-xr-x. 2 root root   22 Mar 19 23:04 checkpoint.00000001
```

I also see the cleaner running regularly:
```
level=debug ts=2021-03-19T22:51:12.380575439Z caller=cleaner.go:194 agent=prometheus component=cleaner msg="active WAL" name=/[dir]/0a0119de6b4fd7a0fbe37119f4beca7c
level=debug ts=2021-03-19T22:54:12.380728926Z caller=cleaner.go:194 agent=prometheus component=cleaner msg="active WAL" name=/[dir]/0a0119de6b4fd7a0fbe37119f4beca7c
```

However, the old wals never appear to actually get deleted. They get checkpointed into a checkpoint directory at some point, but are still there. The logs for that are:
```
level=info ts=2021-03-19T23:04:13.391676777Z caller=checkpoint.go:95 agent=prometheus instance=0a0119de6b4fd7a0fbe37119f4beca7c msg="Creating checkpoint" from_segment=0 to_segment=1 mint=1616194873378
level=info ts=2021-03-19T23:04:13.876061028Z caller=wal.go:443 agent=prometheus instance=0a0119de6b4fd7a0fbe37119f4beca7c msg="WAL checkpoint complete" first=0 last=1 duration=497.068349ms
```

Is there any way to prevent old data from being sent?

**Comment by 56quarters** [comment]
> However, the old wals never appear to actually get deleted

FWIW, the cleaner only deletes "abandoned" WALs that correspond to prom instances the Agent isn't responsible for (for example if they got migrated to a different Agent). The log messages you cited indicate that the running Agent is still responsible for those WALs (even if they're older than `wal_cleanup_age`).

I'm not sure about the other things.

**Comment by nicklan** [comment]
Ahh. Thanks for the clarification. It seems then that those settings are irrelevant to what I'm trying to achieve. Hopefully someone who knows more can chime in with any possibility to prevent writing old data

**Comment by rfratto** [comment]
Hey there, sorry for the delay. I took a long weekend and then this got buried in a list of things to catch up on. 

The checkpoint directory is designed to not be deleted. It contains the identifiers for metrics that the Agent believes are still active (i.e., still receiving writes) and samples that haven't been written yet. It should always be fairly small, but I don't think there's a way to delete it. Note that the samples in the checkpoint aren't currently used by remote_write. 

I think what you're seeing likely isn't related to the WAL, but remote_write's retry functionality. By default (using the Prometheus [queue_config defaults](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write)), remote_write will queue up to 500,000 samples (capacity * max_shards) during an outage. These samples will continue to try to be delivered until the remote_write system recovers, and unfortunately, there's currently no way to set the maximum amount of times samples can be retried before being dropped. 

`min_wal_time` and `max_wal_time` are the right settings for keeping the WAL small, but if you want to minimize the amount of old data being sent, I'd recommend lowering the `capacity` and `max_shards` in the queue config, though keep in mind this will also lower your maximum throughput of metrics. Prometheus has a decent guide on how to [fine tune remote_write](https://prometheus.io/docs/practices/remote_write/) that you may find useful.

Hope this helps! Let me know if there's anything else I can help clear up.

**Comment by nicklan** [comment]
thanks! that at least clears up the situation. it would be great to have an explicit way to control this, but we'll mess with the remote_write settings for the time being thanks.
