### ISSUE TITLE
CPU consumption for grafana-agent-flow loki scraping

### ISSUE THREAD

**Issue by alxark** [grafana/agent#4777]
### What's wrong?

I'm using grafana-agent-flow to fetch logs from docker containers and upload them to loki. Grafana is running on host with just 2 docker containers and generates ~ 10 messages per second, but CPU usage looks to high (especially if you will compare it to promtail). Result for ps aux

```
grafana+ 1642768 82.3  4.2 1563584 83032 ?       Ssl  09:59 135:37 /usr/bin/grafana-agent-flow run --server.http.listen-addr=10.20.1.46:12345 --storage.path=/var/lib/grafana-agent-flow /etc/grafana-agent-flow.river
```

Promtail on host with same containers:
```
root        8871  9.5  0.0 6024040 55496 ?       Ssl  Apr13 16394:29 /usr/bin/promtail -config.file=/etc/promtail/config.yml
```

### Steps to reproduce

Tried same config file on 5 hosts in our system with different containers number - grafana-agent-flow consumes more CPU than promtail instance.

### System information

Linux 5.15.0-56-generic, Ubuntu 22.04.1 LTS

### Software version

v0.35.3

### Configuration

```text
logging {
    level = "warn"
}


// we scrape only containers with promtail=enabled label
discovery.docker "containers" {
    host = "unix:///var/run/docker.sock"
    filter {
        name   = "label"
        values = [ "promtail=enabled" ]
    }
}

discovery.relabel "docker" {
    targets = discovery.docker.containers.targets
}

loki.source.docker "default" {
    host       = "unix:///var/run/docker.sock"
    targets    = discovery.relabel.docker.output

    forward_to = [ loki.process.preprocess.receiver ]
}


loki.process "preprocess" {
    forward_to = [ loki.write.loki.receiver ]

    stage.metrics {
        metric.counter {
            name        = "log_lines_read"
            description = "total number of log lines"
            prefix      = "zm_"

            match_all         = true
            action            = "inc"
            max_idle_duration = "24h"
        }
    }

    stage.drop {
        older_than  = "1h"
        drop_counter_reason = "record is too old"
    }

    stage.drop {
        longer_than = "3KB"
        drop_counter_reason = "size is too big"
    }


    stage.metrics {
        metric.counter {
            name        = "log_lines_processed"
            description = "total number of log lines"
            prefix      = "zm_"

            match_all         = true
            action            = "inc"
            max_idle_duration = "24h"
        }
    }
}

loki.write "loki" {
    endpoint {
        url = "http://10.20.1.100:3100/loki/api/v1/push"
    }
}
```

**Comment by alxark** [comment]
120 seconds of pprof profiling added.

[cpu.pprof.zip](https://github.com/grafana/agent/files/12313093/cpu.pprof.zip)

**Comment by tpaschalis** [comment]
Thanks for the report Alex! It's the second time I'm hearing about this, so we'll try to see what's the cause; we share a lot of Promtail's code and I'd like to see what causes this difference.

One cause could be Promtail's [polling frequency](https://grafana.com/docs/loki/next/clients/promtail/configuration/#file_watch_config) that we still haven't ported over to Agent Flow, but is tracked on #3606.

Your config seems simple enough, but is there anything else unusual with your Docker containers that you think might be relevant? Like long-lived containers, lots of churned containers, or something else?

**Comment by meyersa** [comment]
I have a similar config and I'm noticing similar results, here's a 29 second pprof 

[profile29.gz](https://github.com/grafana/agent/files/12375398/profile29.gz)

I have about 10 containers on one core, all pretty small containers, but grafana agent will randomly jump in cpu to ~85% 

![image](https://github.com/grafana/agent/assets/88554476/89c32ce1-2294-4c71-b631-d6d78bd93981)

I know the core count is low but I have multiple other hosts in a similar configuration and their grafana agent is negligible

**Comment by tpaschalis** [comment]
I see an issue with excessive CPU usage when writing back to the positions file; I'll work on a fix.

**Comment by tpaschalis** [comment]
@alxark @meyersa thank you both for your reports, they were helpful in pinning down the culprit.

We've merged a PR that decreases the CPU _and_ memory usage of `loki.source.docker` by ~a factor of 10, and should be more efficient than Promtail now.

Our [Dockerhub repo](https://hub.docker.com/r/grafana/agent) contains new images from `main` that contain a fix; alternatively you can wait for our next release in late August!
