### ISSUE TITLE
Explore reducing Kubernetes SD load when using host_filter

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#48]
It appears that the overhead of Kubernetes SD increases across the agents as:

a) the number of nodes increase 
b) the number of pods increase

We noticed that a DaemonSet of 20 agents was using more CPU combined compared to a single instance of Prometheus that included more CPU-intensive tasks, such as TSDB, Recording Rules, and Alerts.

When the agents are running as a DaemonSet with host_filter, it would be more less CPU intensive if each agent only scraped pods on the node it's running on rather than pods across the entire cluster. 

I'm not sure how/if this can be done.

**Comment by rfratto** [comment]
We might be able to use https://github.com/prometheus/prometheus/pull/6096 here.

**Comment by posix4e** [comment]
What's left to do here?

**Comment by rfratto** [comment]
I haven't been able to put any time into this, unfortunately. I looked a little into it now and it seems like prometheus/prometheus/pull/6096 can definitely be used with field selectors.

It seems like a good approach would be to inject selectors into the `kubernetes_sd_configs` to filter based on the hostname. 

This field selector works with pods, but it might need to change for other role types:

```
kubectl get po --field-selector=spec.nodeName=my-node-hotsname
```
