### ISSUE TITLE
Installing agent problem: (unauthorized: incorrect username or password)

### ISSUE THREAD

**Issue by podguzovvasily** [grafana/agent#480]
Dear developers,
I have an issue with the installation of the agent. I see an error:
Error response from daemon: Get https://registry-1.docker.io/v2/grafana/agent/manifests/v0.13.0: unauthorized: incorrect username or password

For both methods:
docker pull grafana/agent:v0.13.0
docker-compose up -d

**Comment by rfratto** [comment]
Hi! I'm not able to reproduce this. Can you try `docker logout` and then pull the image again?
