### ISSUE TITLE
Possibility to adjust ScrapeInterval and ScrapeTimeout for prometheus.operator.servicemonitors

### ISSUE THREAD

**Issue by vtrtmnn** [grafana/agent#4806]
### Request

Currently the values for ScrapeInterval and ScrapeTimeout for the Prometheus Operator ServiceMonitor are set to the global default values. We would like to be able to adjust those values when deploying grafana-agent using the helm chart.

### Use case

We have recording rules defined, which are based on a time interval shorter than the ScrapeInterval of the ServiceMonitor. This leads to a situation, where we can't evaluate the rule.

**Comment by rfratto** [comment]
Hi, I'm not sure what ServiceMonitor or Helm chart you're referring to. I looked at our Helm charts, and none of them seem to provide a ServiceMonitor. 

If you have your own ServiceMonitor that you're looking to customize, you can already customize the scrape interval and scrape timeout via the `interval` and `scrapeTimeout` settings on the endpoint object.

**Comment by vtrtmnn** [comment]
Hi,
thanks for your reply and sorry for the inaccurate description of my problem.
We're running grafana-agent in flow mode and what we try to configure is the scrape interval and scrape timeout for the flow component _prometheus.operator.servicemonitors_ (analogous to the component _prometheus.scrape_ for example).

**Comment by captncraig** [comment]
There are `interval` and `scrapeTimeout`fields you can set in the ServiceMonitors and PodMonitors themselves: [PodMetricsEndpoint](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.PodMetricsEndpoint) and [Endpoint](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Endpoint) types have those fields. Setting them will change the interval and timeout on the generated scrape configs.

Are you looking for a more global setting for the entire component? There are a number of fields that are present on the `Prometheus` CRD, to globally enforce things like that, but we have not implemented them in the `prometheus.operator.*` components yet. They would likely be component level arguments.
