### ISSUE TITLE
Flow Prometheus Operator: insights into scrape jobs

### ISSUE THREAD

**Issue by akselleirv** [grafana/agent#4807]
### Request

The log collector is able to display the amount of logs per line produced per pod. I want a similar metric for the prometheus operator in flow mode.

### Use case

Need to understand the amount of active series and samples / sec produced per scrape job.

**Comment by rfratto** [comment]
👋 A few clarifying comments:

* Are you talking about the `prometheus.operator.*` Flow components, or something else?
* Are you looking for a new metric or something shown on the debug info page?

**Comment by akselleirv** [comment]
Hello @rfratto ,
Yes, I’m talking about the prometheus.operator.* components. Specially the servicemonitors.

Would prefer to have it as a metric due to debug UI does not scale across multiple clusters.

**Comment by captncraig** [comment]
I agree that would be really useful. Most of those metrics are hidden deep inside the prometheus ScrapeManager. There are metrics that report summarized versions of those stats, but they are a bit tricky to expose in the metrics registry last time I checked. I'll look into strategies we can do to find some visibility.

**Comment by akselleirv** [comment]
That would be great!

**Comment by captncraig** [comment]
I'm going to leave this open, because we do need to make sure / make decisions about those metrics.

**Comment by akselleirv** [comment]
The reason why I'm requesting this is that the company I'm working for is considering Grafana Cloud, however, currently the amount of series we store are way too many and would be too costly for us to consider Grafana Cloud. I have seen the [cardinality management dashboards](https://grafana.com/docs/grafana-cloud/account-management/billing-and-usage/control-prometheus-metrics-usage/cardinality-management/?pg=blog&plcmt=body-txt#analyze-metrics-usage-with-cardinality-management-dashboards) dashboard, but that is only unfortunately only for Grafana Cloud.

**Comment by captncraig** [comment]
I think there is not a lot we can do from the operator components to help with cardinality management. It isn't really any different than any other way to scrape metrics, like `prometheus.scrape`. 

There may be room for a discussion about cardinality management in general. If you have a proposal for a new component to summarize metrics or datapoints and things, please feel free to open another issue. It is a tricky subject, and there are a number of resources out there for it, but we don't have any concrete plans at present to add anything.

**Comment by akselleirv** [comment]
Hello again!

I found a repository which open sourced the cardinality management dashboards which provides the insights I need. So this feature is no longer needed from my side.

Link to repo: https://github.com/cerndb/grafana-mimir-cardinality-dashboards/tree/main
