### ISSUE TITLE
Agent stops abnormally, no such directory in temp WAL

### ISSUE THREAD

**Issue by nebbian** [grafana/agent#482]
I've recently installed the Grafana agent on around 90 machines (all Centos 7), and am seeing the same pattern in quite a few of them:

- After a few weeks, the agent starts to cause a high load.
- Retrieving the status of the agent shows multiple lines that mention "Repair corrupted WAL"
- Restarting the agent does not resolve the issue
- Stopping the agent, deleting /tmp/grafana-agent-wal, then starting the agent DOES resolve the issue
- Error messages all seem very similar, and mention the same error.

Sample error messages are below:
```
Mar 24 11:33:09 redacted.com.au grafana-agent[19006]: level=error ts=2021-03-24T00:33:09.803784713Z caller=manager.go:253 agent=prometheus msg="instance stopped abnormally, restarting after backoff period" err="failed to initialize instance: error creating WAL: repair corrupted WAL: cannot handle error: open WAL segment: 0: open /tmp/grafana-agent-wal/b611...ed5/wal/00000000: no such file or directory" backoff=5s instance=b611...ed5
Mar 24 11:33:16 redacted.com.au grafana-agent[19006]: level=error ts=2021-03-24T00:33:16.064321826Z caller=instance.go:276 agent=prometheus instance=b611...ed5 msg="failed to initialize instance" err="error creating WAL: repair corrupted WAL: cannot handle error: open WAL segment: 0: open /tmp/grafana-agent-wal/b611...ed5/wal/00000000: no such file or directory"
Mar 24 11:33:16 redacted.com.au grafana-agent[19006]: level=error ts=2021-03-24T00:33:16.064471931Z caller=manager.go:253 agent=prometheus msg="instance stopped abnormally, restarting after backoff period" err="failed to initialize instance: error creating WAL: repair corrupted WAL: cannot handle error: open WAL segment: 0: open /tmp/grafana-agent-wal/b611...ed5/wal/00000000: no such file or directory" backoff=5s instance=b611...ed5
Mar 24 11:33:22 redacted.com.au grafana-agent[19006]: level=error ts=2021-03-24T00:33:22.306146009Z caller=instance.go:276 agent=prometheus instance=b611...ed5 msg="failed to initialize instance" err="error creating WAL: repair corrupted WAL: cannot handle error: open WAL segment: 0: open /tmp/grafana-agent-wal/b611...ed5/wal/00000000: no such file or directory"
```

This can be resolved by the following sequence:

```
# du -sh /tmp/grafana-agent-wal
5.7M	/tmp/grafana-agent-wal
# rm -rf /tmp/grafana-agent-wal
# service grafana-agent start
Redirecting to /bin/systemctl start grafana-agent.service
# service grafana-agent status -l
Redirecting to /bin/systemctl status  -l grafana-agent.service
● grafana-agent.service - Monitoring system and forwarder
   Loaded: loaded (/usr/lib/systemd/system/grafana-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-03-24 11:35:05 AEDT; 4s ago
     Docs: https://github.com/grafana/agent/blob/master/docs/README.md
 Main PID: 19968 (grafana-agent)
    Tasks: 13
   CGroup: /system.slice/grafana-agent.service
           └─19968 /usr/bin/grafana-agent --config.file /etc/grafana-agent.yaml --log.level error
```

Has anyone else seen this issue?

**Comment by rfratto** [comment]
Hey, thanks for reporting this. What version of the Agent are you running? v0.13.0 introduced an increase to the frequency of WALs being cleaned up, which might help with this case.

Can you see any errors related to `checkpoint` in your logs? Looking at the code, it seems like this can happen when a checkpoint is missing.

**Comment by nebbian** [comment]
Hi rfratto, I'm running v0.120.0.

I can't find the logs, as when running this command: `kubectl -ndefault logs daemonset/grafana-agent | grep level=err` I just get `bash: kubectl: command not found`.

**Comment by rfratto** [comment]
If you don't want to upgrade to v0.13.0, you can reproduce the same change by setting `wal_truncate_frequency` to `60m` in your prometheus block ([docs](https://github.com/grafana/agent/blob/main/docs/configuration-reference.md#prometheus_instance_config)):

```yaml
prometheus:
  configs: 
  - name: default 
     wal_truncate_frequency: 60m 
     # ... 
```

`kubectl` is just if you're running the Agent on Kubernetes, which you don't seem to be doing here. Try `journalctl -u grafana-agent` instead.

**Comment by nebbian** [comment]
Hi rfratto,
Thanks for the ideas.  Setting the wal_truncate_frequency to 60m seems to fix the problem.

I couldn't see any references to checkpoint in the logs when using the journalctl command.

I hope this helps to diagnose the issue.  I'm happy now, feel free to close this issue if required.
