### ISSUE TITLE
No support for Kafka receiver as mentioned in the documentation

### ISSUE THREAD

**Issue by jithinchandranj** [grafana/agent#484]
As per the blog post mentioned here, [https://grafana.com/blog/2020/11/17/tracing-with-the-grafana-agent-and-grafana-tempo/](url), receivers allow the Grafana Agent to accept tracing data from a multitude of systems. We currently support receiving spans from Jaeger, Kafka, OpenCensus, OTLP, and Zipkin.

When integrated with the Kafka receiver config, error is shown on startup that the receiver is not supported. When checked the source code further, could see that the Kafka receiver is not added into the list of supported receivers.

**Comment by joe-elliott** [comment]
@mapno take a look when you get a chance.  _Should_ be relatively straightforward to add the kafka receiver.

Perhaps we want this in Tempo proper as well?
