### ISSUE TITLE
clustering: an early cluster change on operator components can cause a panic

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#4879]
### What's wrong?

When using the operator components, an early NotifyClusterChange call can lead to sending to an nil manager channel.

We should guard against this on the component level, but also maybe use the upcoming clustering Service implementation to send notifications only on components that are ready.

We've already identified in a previous TODO that we can rework the way that operator components are initialized to avoid having nil managers during the component's lifetime, or allow the component to fail early if the manager could not be created.

https://github.com/grafana/agent/blob/4340f7c67d8b5e3577fa87982ab106fe692dfd77/component/prometheus/operator/common/component.go#L86-L87

### Steps to reproduce

* Use operator components on an clustered agent deployment
* Be lucky enough for the cluster state to change before the manager is started
* See panic

### Logs

```text
goroutine 120 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc15e2e0a80, {0x0, 0x0, 0x67e3020?})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0xa29
panic({0x628dba0, 0xbe0e8f0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/grafana/agent/component/prometheus/operator/common.(*crdManager).ClusteringUpdated(...)
	/src/agent/component/prometheus/operator/common/crdmanager.go:145
github.com/grafana/agent/component/prometheus/operator/common.(*Component).NotifyClusterChange(0xc15e2e0c00?)
	/src/agent/component/prometheus/operator/common/component.go:108 +0x8a
github.com/grafana/agent/pkg/flow/internal/controller.NewLoader.func1({0x20?, 0x6373fe0?, 0x4a8201?})
	/src/agent/pkg/flow/internal/controller/loader.go:102 +0x437
github.com/grafana/ckit.FuncObserver.NotifyPeersChanged(0x0?, {0xc15e2ec060?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/grafana/ckit@v0.0.0-20230628095927-30fb40ef3315/observer.go:26 +0x2a
github.com/grafana/ckit.(*Node).notifyObservers(0xc000d87600, {0xc15e2ec060, 0x2, 0x2})
	/go/pkg/mod/github.com/grafana/ckit@v0.0.0-20230628095927-30fb40ef3315/node.go:541 +0x2e2
github.com/grafana/ckit.(*Node).run(0xc000d87600, {0x81bb228, 0xc000c480f0})
	/go/pkg/mod/github.com/grafana/ckit@v0.0.0-20230628095927-30fb40ef3315/node.go:278 +0xe7
created by github.com/grafana/ckit.(*Node).Start
	/go/pkg/mod/github.com/grafana/ckit@v0.0.0-20230628095927-30fb40ef3315/node.go:248 +0x18a
```

**Comment by rfratto** [comment]
It looks like this would've started with #4852, since before then the way cluster notifications were handled was exactly the same as a call to Update.
