### ISSUE TITLE
Grafana agent fails on IPv6 only cluster with clustering enabled.

### ISSUE THREAD

**Issue by ArbitraryCritter** [grafana/agent#4902]
### What's wrong?

We're running an IPv6 only Kubernetes (AWS EKS) cluster.

This basically means that only the Kubernetes nodes have IPv4 addresses, all pods only have IPv6 addresses. All outgoing traffic to IPv4 addresses is NAT'ed by the nodes to their IPv4 address using NAT64. (And DNS64)
When running grafana-agent in clustering mode, the code tries to detect what IP address is should advertise and this code seems to be unable to detect an IPv6 address, causing clustering mode to fail.

This caused deployment using the grafana k8s-monitoring helm chart to fail with these errors:

```
grafana-agent ts=2023-08-23T14:00:27.107335793Z level=info boringcryptoenabled=false
grafana-agent Error: building clusterer: determining advertise address: 2 errors occurred:
config-reloader 2023/08/23 14:00:25 Watching directory: "/etc/agent"
grafana-agent     * interface "eth0" has no suitable addresses
grafana-agent     * interface "en0": route ip+net: no such network interface
```

If I disable clustering everything works.
Most likely the reason is that there is only an IPv6 in the ip list.

Presumably, if I could predict the pod address, I could probably override the cluster address with "--cluster.advertise-address" and it might just work.

### Steps to reproduce

- Setup an IPv6 only kubernetes cluster (AWS provides this option more or less out of the box.)
- Install the k8s-monitoring helm chart with default configuration parameters (as provided by grafana-cloud).

### System information

Linux 5.15.117 x86_64

### Software version

v0.35.2

### Configuration

```text
agent:
  clustering:
    enabled: true
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "50m"
      memory: "512Mi"
```

### Logs

```text
grafana-agent ts=2023-08-23T14:00:27.107335793Z level=info boringcryptoenabled=false
grafana-agent Error: building clusterer: determining advertise address: 2 errors occurred:
config-reloader 2023/08/23 14:00:25 Watching directory: "/etc/agent"
grafana-agent     * interface "eth0" has no suitable addresses
grafana-agent     * interface "en0": route ip+net: no such network interface
```

**Comment by tpaschalis** [comment]
cc @wildum we've merged the changes on ckit, can we bump our dependency and close this one out?
