### ISSUE TITLE
Create a river go module

### ISSUE THREAD

**Issue by cyriltovena** [grafana/agent#4940]
### Request

Right now when we want to import `river` package we have to pull everything from Grafana Agent go.mod. And grafana agent dependencies are not easy to work with.

It would great to create a go submodule for the `river` package so that we can pull only this if we want to build tooling around.

### Use case

Recently added  river formatting test in Pyroscope and it forced me to pull the whole grafana agent code base.

**Comment by rfratto** [comment]
We're probably going to move River and Flow (with no components) out to its own repo within the next few months. How soon do you want this?

**Comment by cyriltovena** [comment]
Sounds good.

I found https://go.dev/doc/tutorial/workspaces less daunting on the developer workflow since you don't have to deal with multiple git repositories.
