### ISSUE TITLE
Document different topologies and recommendations

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#4951]
### Request

We're missing documentation for the different topologies that Grafana Agent may be deployed in:

* As a host daemon, where there is one Grafana Agent per machine.
* As a centralized service, where a smaller set of Grafana Agents collect telemetry data from other apps or machines. 
* As a sidecar to a Kubernetes container.

Note that the third use case is something we haven't typically recommended, but it may be worth documenting anyway.

Each of these should include recommendations about when to use which topology, and include common issues that users may run into, including how significantly large deployments of Grafana Agent (hundreds of thousands of agents all remote_writing) can lead to port exhaustion. 

### Use case

Help users better understand how to deploy and operate Grafana Agent in production.

**Comment by GrafanaWriter** [comment]
@clayton-cornell - FYI
