### ISSUE TITLE
clustering: improve alerting for growing cluster sizes

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#4991]
We should make sure our alerts scale properly with cluster size. For example, since the rate of outgoing and re-broadcasted messages is not scaling linearly with cluster size, alerts such as `ClusterLamportClockDrift` should also scale in the same way.

As a tangent, we can also alert on open transport streams, since they're only supposed to be short-lived streams for full push-pull syncs.

**Comment by thampiotr** [comment]
We have removed ClusterLamportClockDrift some time ago, as it was redundant and alerting on causes and not symptoms.
I'm still looking into tweaking some alerts as part of this item though.
