### ISSUE TITLE
prometheus.exporter.blackbox: issues with documentation and examples

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#5007]
I've had some issues with our current [documentation](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.exporter.blackbox/#examples) of the prometheus.exporter.blackbox component.

1) As a convention the first Usage section contains the minimum set of parameters required to run the component. In this case, at least _one_ target block is required, which doesn't exist. Maybe we can at least add a dummy `target` block and signify that there can be more, like we do for [prometheus.relabel](https://grafana.com/docs/agent/next/flow/reference/components/prometheus.relabel/#usage)
```
Error: /Users/tpaschalis/river-configs/clustering_scheduling.river:1:1: Failed to build component: decoding River: missing required block "target"

1 |   prometheus.exporter.blackbox "all" {
  |  _^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2 | | }
  | |_^
3 |
```

2) If I define a dummy `target` block, the component runs, but its endpoint reports `Unknown module "http_2xx"`, which is fair, but could use a better UX by erroring out early if neither `config` or `config_file` were passed.

3) The first example for "Collect metrics using a blackbox exporter config file ". Can we lead users where to find a valid `blackbox_modules.yml` file, maybe the one available on the [upstream repo](https://github.com/prometheus/blackbox_exporter/blob/master/example.yml)?

4) The second example for "Collect metrics using an embedded configuration" doesn't seem to work. Hitting the exporter's endpoint results in a cryptic message
```
$ curl localhost:12345/api/v0/component/prometheus.exporter.blackbox.example/metrics
Target parameter is missing
```

**Comment by GrafanaWriter** [comment]
@clayton-cornell - FYI

**Comment by marctc** [comment]
>     4. The second example for "Collect metrics using an embedded configuration" doesn't seem to work. Hitting the exporter's endpoint results in a cryptic message
> 
> 
> ```
> $ curl localhost:12345/api/v0/component/prometheus.exporter.blackbox.example/metrics
> Target parameter is missing
> ```

This is normal as this exporter is multi-target based so you always have to provide target. We could document that somewhere, but in this cases the snippet is to send the data to remote write.
