### ISSUE TITLE
module.git should not reload flow components every time it polls

### ISSUE THREAD

**Issue by erikbaranowski** [grafana/agent#5028]
### What's wrong?

module loaders commonly poll but they should not reload flow components unless a change is detected to the content of the module loader.

### Steps to reproduce

use module.git and observe that components are restarted without modification each time it polls.

https://github.com/grafana/agent/blob/2c12db25affbe919e1037005dbb938459b79fb0d/component/module/git/git.go#L231

**Comment by rfratto** [comment]
Should the module code in Flow ignore calls to LoadConfig if the config bytes are unchanged?

**Comment by mattdurham** [comment]
That would work as long as we assume all child modules are updating when appropriate. Which I think is a safe assumption.
