### ISSUE TITLE
0.36.0 build failure with undefined symbols

### ISSUE THREAD

**Issue by daurnimator** [grafana/agent#5037]
### What's wrong?

```
# github.com/pyroscope-io/godeltaprof/internal/pprof
../pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.1/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
../pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.1/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
```

### Steps to reproduce

`go build cmd/grafana-agent`

### System information

ArchLinux

### Software version

v0.36.0

**Comment by daurnimator** [comment]
Looks like this was already reported+fixed upstream: https://github.com/grafana/godeltaprof/issues/4
https://github.com/grafana/pyroscope-golang/issues/38

I guess you just need to bump the version used here?

**Comment by cyriltovena** [comment]
Correct let me take a look.
