### ISSUE TITLE
loki.source.kafka Example not working

### ISSUE THREAD

**Issue by FischlerA** [grafana/agent#5044]
### What's wrong?

The example provided in the docs for the loki.source.kafka does not work since the loki.relabel has an argument forward_to which is required.

### Steps to reproduce

- Use the example provided with the loki.source.kafka

### Software version

v0.35.4

**Comment by GrafanaWriter** [comment]
@clayton-cornell - FYI

**Comment by clayton-cornell** [comment]
Docs in question: https://grafana.com/docs/agent/latest/flow/reference/components/loki.relabel/
