### ISSUE TITLE
loki.source.kubernetes: add support for relabel_rules

### ISSUE THREAD

**Issue by flokli** [grafana/agent#5049]
### Request

Be able to specify `relabel_rules` for `loki.source.kubernetes`, to add labels / unhide private ones.

### Use case

I use `loki.source.FOO` and `discovery.kubernetes.FOO.targets` to scrape logs from Kubernetes.

I'd like to add some labels to the log streams, to end up producing a similar set of labels as in my previous grafana agent operator installation.

I tried to do an approach similar to how it's shown in the [systemd journal example](https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.journal/#example):

```hcl
discovery.kubernetes "pods" {
  role = "pod"
}

// Copy some useful labels from __meta over,
// so they end up as real fields in log entries.
loki.relabel "pods" {
  forward_to = []

  // namespace is trivial
  rule {
    source_labels = ["__meta_kubernetes_namespace"]
    target_label = "namespace"
  }
  
  // pod is the name of the pod
  rule {
    source_labels = ["__meta_kubernetes_pod_name"]
    target_label = "pod"
  }
  
  // container is the name of the container
  rule {
    source_labels = ["__meta_kubernetes_pod_container_name"]
    target_label = "container"
  }
  
  // app is the "app" label
  rule {
    source_labels = ["__meta_kubernetes_pod_label_app"]
    target_label = "app"
  }
  // name is the "app.kubernetes.io/name" label
  rule {
    source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
    target_label = "name"
  }
}

loki.source.kubernetes "pods" {
  targets    = discovery.kubernetes.pods.targets
  forward_to = [loki.write.push.receiver]
  relabel_rules = loki.relabel.pods.rules
}

loki.write "push" {
  endpoint {
    url = env("LOKI_URL")
  }
}
```

… and then noticed `relabel_rules` is not a field in `loki.source.kubernetes`?

I also tried "piping the output from `loki.source.kubernetes` through the `loki.relabel` resource, which I then configured to forward to `loki.write`, but it seems the labels are not there anymore at this stage.

**Comment by flokli** [comment]
Hmmh, I just stumbled over https://github.com/rfratto/agent-modules/blob/main/k8s_pods/module.river, suggesting it might be possible to do this already in the `discover.relabel` stage. This might work, even though it's not entirely obvious as to why there's no `relabel_rules` for `loki.source.kubernetes`.

Could some of these examples be moved/copied more into the official documentation? This seems quite helpful as a starter.

**Comment by flokli** [comment]
So, after some additional changes in that repo (https://github.com/rfratto/agent-modules/pull/1, https://github.com/rfratto/agent-modules/pull/2, https://github.com/rfratto/agent-modules/pull/3), I was able to use `discovery.relabel` to have the right labels appear next to the log entries sent to Loki.

I however feel strongly like these examples/recipes should live in the Grafana Agent Flow docs, not in a (personal) repository ;-)

**Comment by rfratto** [comment]
> I however feel strongly like these examples/recipes should live in the Grafana Agent Flow docs, not in a (personal) repository ;-)

They sure should :) 

github.com/grafana/agent-modules is actively being worked on for an opinionated home of modules. I haven't had time to port mine over to it yet, but @erikbaranowski (who helps maintaining that repo) definitely want them there.

Over time, you'll start to see recommendations to run modules from github.com/grafana/agent-modules in the Flow docs.
