### ISSUE TITLE
pkg/agentctl: FindCardinality, FindSamples do not invoke WAL.Close() hence leaks resources

### ISSUE THREAD

**Issue by odeke-em** [grafana/agent#506]
There is a missing defer WAL.Close() in FindCardinality and that’ll look like substantial resources will be leaked per https://github.com/grafana/agent/blob/e83883daf49e1f1bc076c5dc1cb326a7a43dc5fd/pkg/agentctl/cardinality.go#L18-L38

ditto for https://github.com/grafana/agent/blob/e83883daf49e1f1bc076c5dc1cb326a7a43dc5fd/pkg/agentctl/samples.go#L27-L35
given the code in (*WAL).Close

**Comment by rfratto** [comment]
Thanks for reporting! It's not clear to me how much this actually leaks since they're not being written to, but they should definitely be closed.

**Comment by odeke-em** [comment]
Thank you for the fix and quick turnaround, @rfratto.
