### ISSUE TITLE
grafana-agent forces nilToZero:true for YACE causing misfiring of BurstBalance monitors on AWS volume size changes

### ISSUE THREAD

**Issue by CVdV-au** [grafana/agent#5075]
### What's wrong?

YACE default for nilToZero is false - for good reason. AWS BurstBalance metrics stop being produced when a volume goes from less than 3TB more than 3TB, as BurstBalance is only relevant for smaller volumes sizes.

With grafana-agent as is, this means changing the volume size across this transition causes burst balance monitors to fire, as the burst balance appears to drops to zero (though in practise it is actually infinite).

The comment attached to nilToZero=true says "Avoid producing absence of values in metrics" - I'm not clear what the implications are if we flipped grafana-agent to having the same behaviour OOTB as YACE and producing NaN for this metric. Maybe this should actually be configurable?

### Steps to reproduce

Setup grafana to retrieve the metric aws_rds_burst_balance_average for a small volume (<3TB) - if volume is idle, will report 100.
Increase volume size to >3TB - metric will now report as 0.

... or just inspect the code.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using_cloudwatch_ebs.html notes that burst balance is not reporting "if the baseline performance of volume exceeds the maximum burst performance". Admittedly, this is only a problem on ye-olde world gp2 storage (as well as the now fairly obscure st1/sc1) but we rely on gp2 as gp3 is not yet available in non-public AWS which are our main targets.

### System information

N/A

### Software version

Latest

**Comment by tpaschalis** [comment]
I'm not sure what's the context around this parameter when we first introduced the cloudwatch exporter (cc @thepalbi in case he remembers), but I think it wouldn't hurt to make this configurable.

**Comment by berler** [comment]
I'm not sure if this is a similar issue, but when we look at EBS io/byte balance metrics for RDS many of our instances show an unexpected pattern of periodically bouncing back and forth between 100 and 0. In other words consecutive data points show `[..., 100, 100, 0, 100, 100, ...]`. (If your UI is set to a large time range grafana may be averaging multiple points so you don't notice the 0 values). When I go to the AWS console and look at the metrics for the same instances the EBS io/byte balances never dip below 99. I suspect that there can be cases where cloudwatch is missing several datapoints (or perhaps there is a delay in those points being available) so recording them as 0 is incorrect.
