### ISSUE TITLE
loki.kafka.source should provide the message offset

### ISSUE THREAD

**Issue by FischlerA** [grafana/agent#5079]
### Request

Currently the loki.source.kafka provides information about the partition of the message, but not the offset.
This information is crucial when working with any other tool against kafka and should be accessible through the loki.source.kafka.

So in my opinion there should be an internal label for the offset of the message, just like the partition.

### Use case

Some examples:
- Offset is required to interact through the kafka scripts with the message for example when using kafka-delete-records.sh
- Depending on the amount of messages published to a topic just using a timestamp is not enough

**Comment by hainenber** [comment]
hi @rfratto, I can work on this issue. Can you help assigning it to me? Thanks!

**Comment by FischlerA** [comment]
Thanks @rfratto for the quick work!

**Comment by rfratto** [comment]
Thank @hainenber, they were the one to implement it :)
