### ISSUE TITLE
Agent-specific User-Agent header for agent

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#51]
It would be useful to uniquely identify requests from `grafana/agent` incoming within the `remote_write` API implementation. One way to do this would be to set the `User-Agent` header to identify it as the Agent. 

Currently, Prometheus hard-codes the User-Agent header; a PR is needed upstream to allow for overriding this specific header or a mechanism to arbitrarily change headers (e.g., passing a custom http.Client).

**Comment by rfratto** [comment]
This issue came up in a discussion for passing a custom round tripper, which doesn't seem like it will be merged, but an [alternative](https://github.com/prometheus/common/pull/252#issuecomment-676668363) was proposed: 

> It turns out that your problem is very different and that 1. Prometheus should set its user agent 2. We should allow the name of the package to belong to the version package as well, then our user agent should take both from that package.

**Comment by roidelapluie** [comment]
we could also make the user agent a public constant,as noted by Brian

**Comment by rfratto** [comment]
I've opened an [upstream PR](https://github.com/prometheus/prometheus/pull/7832) to open the door for this.
