### ISSUE TITLE
Update HTTPClientConfig for new fields available in Prometheus configuration

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#5110]
Our current Prometheus dependency has introduced some extra proxy-related fields grouped under the [ProxyConfig](https://github.com/prometheus/common/blob/94bf9828e56d9670579b28a9f78237d3cd8d0395/config/http_config.go#L1178) struct.

We should include the new fields in the Validate and Convert methods of our HTTPClientConfig, and update the documentation of all components making use of HTTPClientConfig.

**Comment by wildum** [comment]
for now these fields are part of the unsupported diags in [ValidateHttpClientConfig](https://github.com/grafana/agent/blob/9c802a3eb898afa3dd7cddb4c99b4a1492c63f64/converter/internal/prometheusconvert/common.go#L31) because they are not supported in flow
