### ISSUE TITLE
Allow grafana-agent helm chart to use image digest instead of tag

### ISSUE THREAD

**Issue by alex-sentsiurou** [grafana/agent#5134]
### Request

Hi team, our company mandatory requirement is to use `digests` instead of `tags`. 

But grafana-agent helm chart accepts only tags:
https://github.com/grafana/agent/blob/498e414dff52b6fe97c73ae1e667dd4067bff124/operations/helm/charts/grafana-agent/templates/containers/_agent.yaml#L3C150-L3C150

Can it be implemented similar to bitnami charts? E.g.: https://github.com/bitnami/charts/blob/a26d06f91b80951dff888035e9436ca51d2f95cf/bitnami/nginx/values.yaml#L74C1-L78C13?

Thanks in advance!

### Use case

Tag mutability can cause security issues like bypassing image scanning checks. 
To get deterministic and repeatable deployments, use digests instead of tags.

**Comment by tpaschalis** [comment]
Thanks for opening the issue. A PR is on the way, and this will be available on the next Agent release.
