### ISSUE TITLE
Prometheus native histograms are not being scraped

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#5136]
It looks like the Agent does not scrape Prometheus' native histograms. We should be setting the EnableProtobufNegotiation; otherwise we only ever scrape the non-gRPC /metrics endpoint, so we never get the native histograms payload.

The Agent should be able to scrape both the HTTP and gRPC endpoints (in case the remote target supports it) and receive data from both histogram types at the same time.

**Comment by krajorama** [comment]
Note for the migration case where a metric defines both classic and native histograms buckets. E.g. [request_duration_seconds](https://github.com/grafana/dskit/blob/94fac3db9a1529f34a4243f6a3c12038cc53bf24/server/metrics.go#L40).

To not break all dashboards and alerts that refer to the classic histogram, agent should scrape both.

In Prometheus the migration is done this way:
0. User has some code instrumented with classic histogram.
1. User instruments the code with native histogram  _as well_.
2. User enables native histogram [feature](https://prometheus.io/docs/prometheus/latest/feature_flags/#native-histograms) in Prometheus. So gRPC is interrogated. 
3. User sets "scrape_classic_histograms" to true in [scrape config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) so both classic and native histogram series are generated.
4. User updates their dashboards and alerts.
5. User removes classic histogram instrumentation.

**Comment by rfratto** [comment]
As @krajorama said, we need to also support the `scrape_classic_histograms` field in the scrape config; not just setting `EnableProtobufNegotiation`.
