### ISSUE TITLE
Improve Logging on SNMP Exporter Component

### ISSUE THREAD

**Issue by nicolai-hornung-bl** [grafana/agent#5163]
### Request

The prometheus.exporter.snmp component is currently almost impossible to debug as there are no logs written even in debug mode (also stated on the official documentation). 

Please add better logging.

### Use case

I'm currently trying to transfer my running snmp_exporter config to grafana agent and getting a scrape failure with the only log entry available being "server returned HTTP status 400 Bad Request" on debug level. This should be way higher than debug and in debug actually useful information needs to be available. The agent.config is almost identical to the one provided in the documentation example and the snmp.yaml is verified to be working with the latest upstream release of snmp_exporter which makes this almost impossible to pin down.

**Comment by rfratto** [comment]
I've tagged this as upstream since it's likely these changes will likely need to be made in the upstream snmp_exporter. 

Can you briefly describe what debug information you'd like to see so we can make sure it's covered?

**Comment by nicolai-hornung-bl** [comment]
As always these problems fix themselves randomly. I was missing the "auth" value in the target block initially which is why the snmp_exporter was reporting a bad request to the grafana agent. And my change in adding this did not trigger the config reload properly. With the auth parameter snmp scraping works and the provided logging actually is more than adequate. So this was merely an issue between grafana agent and the embedded snmp_exporter.

This raises the following questions for me:
- Is the auth parameter always required since the recent change to snmp_exporter configuration? If yes then the Documentation needs to be updated to reflect this in both the example as well as parameter description.
- Can logging be improved on the communication between grafana agent and the embedded snmp_exporter? It would have been helpful to know my configuration was missing something instead of a solitary BAD_REQUEST on debug level especially as my config was analogous to the provided example. (For clarification: This was a misconfiguration in my config.river, not in the snmp.yaml)

**Comment by nicolai-hornung-bl** [comment]
Also on another note: The target.name parameter is listed as required in the docs and not used at all in the [examples](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.exporter.snmp/#target-block). When trying to add it (The metrics being scraped have the grafana agent machine for "instance") the agent says this attribute is not recognized.

This is my config:

```
prometheus.exporter.snmp "idracs" {
  config = local.file.snmp_config.content

  target "despesxhpc01" {
    name = "despesxhpc01"
    address = "despesxhpc01.rac"
    module = "dell_idrac"
    auth = "idrac-community"
  }
}
```


This is my version:
![image](https://github.com/grafana/agent/assets/95273217/7d6446d4-7ef5-46ac-89c1-2df335c5ffd6)


This is the output of the container logs:
![image](https://github.com/grafana/agent/assets/95273217/1ad66420-75a7-429b-bae6-290c3ebac7c1)
