### ISSUE TITLE
otelcol.processor.discovery causes lose of target data in input components

### ISSUE THREAD

**Issue by oferziss-armis** [grafana/agent#5164]
### What's wrong?

when using the `otelcol.processor.discovery` component, all components passed in the targets argument of the component lose their exported target data. 

so for example with this configuration:
```
discovery.docker "containers" {
  host = "unix:///tmp/docker.sock"
}
```
the UI will show that the discovery component has a number of containers with all of their metadata attributes. but once i change the config to this:
```
discovery.docker "containers" {
  host = "unix:///tmp/docker.sock"
}


otelcol.processor.discovery "traces_docker_attributes" {
	targets = discovery.docker.containers.targets

	output {
		traces = [
			...
		]
	}
}
```

when i reload the configuration the discovery components UI not shows me the exports section as `[{},{},{}]`. important to note the number of empty objects in the map matches the number of running containers but there is no data anymore.

### Steps to reproduce

running agent in flow mode at `0.36.1` with the following configs.
```
discovery.docker "containers" {
  host = "unix:///tmp/docker.sock"
}


otelcol.processor.discovery "traces_docker_attributes" {
	targets = discovery.docker.containers.targets

	output {
		traces = [
			...
		]
	}
}
```

tried the same with an agent runnig on the same version in a kubernetes cluster with:
```
discovery.kubernetes "pods" {
  role= "pod"
}


otelcol.processor.discovery "traces_pod_attributes" {
	targets = discovery.docker.pods.targets

	output {
		traces = [
			...
		]
	}
}

```

### System information

running the grafana agent container from docker hub for linux

### Software version

Grafana agent 0.36.1

### Configuration

```text
discovery.docker "containers" {
  host = "unix:///tmp/docker.sock"
}


otelcol.processor.discovery "traces_docker_attributes" {
	targets = discovery.docker.containers.targets

	output {
		traces = [
			...
		]
	}
}
```

### Logs

```text
only log line i could find that's relevant:
{"controller_id":"","duration":"196.955µs","level":"info","msg":"finished node evaluation","node_id":"discovery.docker.all_containers","trace_id":"4c7a9f4d3c40c39642d7ee408e0c6c08","ts":"2023-09-12T07:19:55.154350064Z"}
```

**Comment by oferziss-armis** [comment]
hi guys, any chance on getting a patch version out today with this?

**Comment by ptodev** [comment]
Unfortunately I don't think a patch release is likely to go out this week. I will ask the other developers if there are other changes which we should include in a patch, and we will probably release one next week.
