### ISSUE TITLE
Change the default component stability to "experimental" and make the "stage" label compulsory

### ISSUE THREAD

**Issue by ptodev** [grafana/agent#5207]
### Background

According to the [Agent stability guide](https://grafana.com/docs/agent/latest/stability/), the default stability of Flow components is "stable". In addition, the "stability" label is not required in a Flow component's documentation. If the label is missing, a stability of "stable" is implied.

When adding a new component, it is very easy to forget about adding a stability label. Thus, the component ends up being "stable" even if it shouldn't be.

### Proposal

This is a proposal for two changes:
* Changing the default stability to "experimental".
* Adding CI tests for the component docs to make sure a stability label is always present. The tests could be similar to the ones proposed in #5201.
* Making the "stage" label compulsory, even for stable components.

These changes would force developers to think about stability when adding new components, thereby making sure the stability labelling is accurate.

In addition, we could consider renaming the "stage" label to "stability". IMO people woulc expect it to be called "stability" given that the documentation page is called [Stability](https://grafana.com/docs/agent/latest/stability/) and not "Stage".

We may also consider making the value of the label a hyperlink to the corresponding section of the Stability doc (experimental/beta/stable).

**Comment by rfratto** [comment]
I'm not sure about this one. Do you have any examples of software where features are non-stable by default, if no explicit stability is mentioned? It feels that that is the opposite of how other projects do this. 

However, I am on board with making explicitly marking things as stable for better user comprehension.

**Comment by thampiotr** [comment]
If we add a test that requires stability label to be there, we don't need to have a default one, no?
In that case, let's do it :)

**Comment by thampiotr** [comment]
@ptodev would it be okay to close this one for now? This item sparked a fair amount of internal discussion and we have been sketching a plan how to handle it on a component-level and lower. We will likely use other issues to address these problems. The PR to explicitly specify component's stability level has been merged here: https://github.com/grafana/agent/pull/6523

**Comment by ptodev** [comment]
Thanks, @thampiotr, I agree!
