### ISSUE TITLE
Document resource requirements for Grafana Agent

### ISSUE THREAD

**Issue by clayton-cornell** [grafana/agent#5215]
The Grafana Agent documentation needs a new section that covers sizing/resource requirements for common deployment scenarios.

This information is critically important for Support Engineering and Sales as well as for any customer considering an Agent deployment.

**Comment by tpaschalis** [comment]
Do we think it's ok to close this issue after https://grafana.com/docs/agent/latest/flow/monitoring/agent-resource-usage/ was published? Or do you prefer to keep it around for future improvements? cc @thampiotr @clayton-cornell

**Comment by clayton-cornell** [comment]
@tpaschalis The new topic covers the intent of this issue. Closing.
