### ISSUE TITLE
Update all Otel Collector dependencies to at least v0.82.0

### ISSUE THREAD

**Issue by ptodev** [grafana/agent#5218]
### Request

This is required for people trying to use the spanmetrics connector with exemplar support.

As part of the upgrade, also take care of a [TODO in the loki exporter](https://github.com/grafana/agent/blob/v0.36.0/component/otelcol/exporter/loki/internal/convert/convert.go#L79-L81).

It is also a good opportunity to follow the guide written in #4343 for the first time and see if it's adequate.

### Use case

Keeping up to date with Otel.

**Comment by tpaschalis** [comment]
Closed as completed in #5290
