### ISSUE TITLE
Support defining Cortex Rules in Agent config

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#523]
Based on [this discussion](https://github.com/grafana/agent/discussions/456), I'd like it if the Agent could support recording and alerting rule definitions that are synced against the Cortex Ruler API.

**Comment by jpkrohling** [comment]
I'm removing myself from this task, as it's been for a while in my queue and I can't seem to even get started with it. I'll try to get a smaller issue first to get myself more comfortable with this codebase and might work on this again in the future. Sorry about that :-/

**Comment by sambacha** [comment]
Any update on this issue? This is a blocker to adopting grafana

**Comment by rfratto** [comment]
No updates for now, this isn't being actively worked on at the moment.

**Comment by rfratto** [comment]
This was implemented as a Grafana Agent Flow component in #2604. I'm going to close this as completed. 

At this time, there's no plan to backport this functionality into the static mode (i.e., the default mode the agent runs in).
