### ISSUE TITLE
Grafana agent operator rendering CloudWatch integration config with invalid integration config name

### ISSUE THREAD

**Issue by wltbenade** [grafana/agent#5318]
### What's wrong?

When applying an Integration CR for the CloudWatch exporter, the grafana agent config throws the error:
`line 1: field cloudwatch_exporter_configs not found in type integrations.SubsystemOptions`

The actual rendered config name should be `cloudwatch_exporter_config`; no 's'.

### Steps to reproduce

Apply Integration CR for CloudWatch exporter.

### System information

K3s kubernetes cluster v1.27.3+k3s1

### Software version

Grafana Agent v0.36.1/2

### Configuration

```text
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  name: integration-rds-postgres
  labels:
    agent: grafana-agent
spec:
  name: cloudwatch_exporter
  type:
    allNodes: false
    unique: true
  config:
    autoscrape:
      enable: true
      metrics_instance: monitoring-system/[REDACTED]-metrics
    sts_region: [REDACTED]
    fips_disabled: true
    discovery:
      jobs:
        - type: AWS/RDS
          roles:
            - roleArn: "[REDACTED]"
          regions:
            - [REDACTED]
          period: 300
          length: 300
          metrics:
            - name: CPUUtilization
              statistics: [Maximum]
            - name: DatabaseConnections
              statistics: [Sum]
            - name: FreeableMemory
              statistics: [Average]
            - name: FreeStorageSpace
              statistics: [Average]
            - name: ReadThroughput
              statistics: [Average]
            - name: WriteThroughput
              statistics: [Average]
            - name: ReadLatency
              statistics: [Maximum]
            - name: WriteLatency
              statistics: [Maximum]
            - name: ReadIOPS
              statistics: [Average]
            - name: WriteIOPS
              statistics: [Average]
```

### Logs

```text
From grafana-agent container in grafana-agent-integrations pod:
[TIMESTAMP] error loading config file /var/lib/grafana-agent/config/agent.yml: yaml: unmarshal errors:
  line 1: field cloudwatch_exporter_configs not found in type integrations.SubsystemOptions
```

**Comment by hainenber** [comment]
Because Integration CRs are [deployed](https://grafana.com/docs/agent/latest/operator/api/#integrationspec-a-namemonitoringgrafanacomv1alpha1integrationspeca) as `integration-next`, you'll need to remove the `exporter` suffix in `spec.name` path and now `cloudwatch_configs` is a [legitimate field](https://grafana.com/docs/agent/latest/static/configuration/integrations/integrations-next/#config-changes). Hope this helps!

**Comment by wltbenade** [comment]
Thanks, @hainenber! It's been accepted :)

And I JUST saw where this is documented: https://grafana.com/docs/agent/latest/operator/operator-integrations/#before-you-begin
