### ISSUE TITLE
Agent tailer backoff wait time always 0

### ISSUE THREAD

**Issue by anderssonw** [grafana/agent#5322]
### What's wrong?

When encountering containers which are not started, for example containers in `ImagePullBackoff` or `CreateContainerConfigError`, grafana-agent logs messages like these almost every second for every failing container:

```
ts=2023-09-28T07:33:52.129111985Z level=warn target=namespace/container_name:pod_id component=module.file.loki_config/loki.source.podlogs.default msg="tailer stopped; will retry" err="container \"container_name\" in pod \"pod_id\" is waiting to start: CreateContainerConfigError"
```

The log itself is not a problem, as it is expected. However, it seems that there is a bug in the code for producing exponential back-off times in `component/loki/source/kubernetes/kubetail/tailer.go`.

StartConfig:
```go
var retailBackoff = backoff.Config{
	MinBackoff: 0,
	MaxBackoff: time.Minute,
}
```

Creating the backoff at L#97:
```go
bo := backoff.New(ctx, retailBackoff)
```

When calculating `nextDelayMin` and `nextDelayMax` in the `backoff` package, they are set to the same value, 0.  This causes the calculation of the next delay of the backoff to be 0 as well:
```go
if b.nextDelayMin >= b.nextDelayMax {
     return b.nextDelayMin
}
```

Presumably, the MinBackoff has to be set to some other value than 0, or the `backoff` package should handle `nextDelayMax/Min == 0` in a different manner. 

### Steps to reproduce

Have a failing container which is being monitored by the grafana agent.

### System information

Darwin ARM64

### Software version

grafana-agent helm chart v0.21.0

### Logs

```text
ts=2023-09-28T07:33:52.129111985Z level=warn target=namespace/container_name:pod_id component=module.file.loki_config/loki.source.podlogs.default msg="tailer stopped; will retry" err="container \"container_name\" in pod \"pod_id\" is waiting to start: CreateContainerConfigError"
```

**Comment by tpaschalis** [comment]
Thanks for the report, this sounds like it could use a check on the upstream dskit library. In the meantime we can change the minBackoff we use on the Agent side, let me know if you'd like to open a PR for this!

Also, please consider avoiding vote-bombing issues in the future. 🙂 It won't help solve the issue faster, but pollutes a useful signal of how many different people have hit upon a specific issue. Thanks!

**Comment by anderssonw** [comment]
I agree that the upstream lib could benefit from catching this scenario. If 1 second as a minimum time is a fair back off I can make a PR for it just fine. Just wanted to make sure that y'all agreed that this is an error and not expected behaviour.

**Comment by tpaschalis** [comment]
@anderssonw yeah, sounds logical, go for it!
