### ISSUE TITLE
Docs feedback: /docs/sources/flow/setup/install/kubernetes.md

### ISSUE THREAD

**Issue by lionelmarksgrafana** [grafana/agent#5339]
Please provide examples on how to apply river config files.. without examples this is hard to successfully get the agent talking to Grafana Cloud

**Comment by tpaschalis** [comment]
Hey there @lionelmarksgrafana, thanks for the issue!

> Please provide examples on how to apply river config files

Could you please expand on what specific piece of documentation would make it easier to get you started, where do you think your gap is? Is it about _writing_ new configuration, deploying configuration, working examples of end-to-end pipelines?

We have a bunch of pages aimed for first-time users.
* [Install Grafana Agent in flow mode](https://grafana.com/docs/agent/latest/flow/setup/install/)
* [Configure Grafana Agent in flow mode](https://grafana.com/docs/agent/latest/flow/setup/configure/)
* [Get started with Grafana Agent in flow mode](https://grafana.com/docs/agent/latest/flow/getting-started/)
* [The run command](https://grafana.com/docs/agent/latest/flow/reference/cli/run/)

Also, each component also provides examples on how to make use of them; [here's](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.remote_write/#send-metrics-to-a-managed-service) how the prometheus.remote_write component can send data to Grafana Cloud.

**Comment by tpaschalis** [comment]
I'm closing this issue as we've been revamping our documentation to improve the experience of first-time users.

If you, or someone else would like to offer suggestions on how to improve our docs, please open a new issue and we'll be happy to assist.
