### ISSUE TITLE
Support specifying additional headers in the remote_write in Tempo config

### ISSUE THREAD

**Issue by alexbiehl** [grafana/agent#535]
`remote_write`s  for the Prometheus configuration support specification of additional headers that are passed to the remote writer. Unfortunately this doesn't apply for the `remote_write`s in Tempo's config.  

At work we have a requirement where this would come in very handy. I looked into the code and it seems to be pretty straightforward to add and I could provide a PR.

**Comment by rfratto** [comment]
Hey! I agree this would be great to have, and we're more than happy to accept a PR for it.
