### ISSUE TITLE
Request for converting grafana-agent configuration file in river mode using convert command

### ISSUE THREAD

**Issue by aryan-brane-1971** [grafana/agent#5375]
### Request

I want to request a feature as we know convert command in grafana flow mode only convert prometheus  configuration file and promtail file to river flow mode so when it possible to convert grafana agent configuration file to flow mode using convert command

### Use case

it will be beneficial if someone want to convert grafana agent static mode to grafana agent flow mode

**Comment by tpaschalis** [comment]
If I'm not mistaken this is now available on `main` after https://github.com/grafana/agent/commit/1520185d05d00f7a9a068f5ac02f6415b359e2d4 was merged, and will be available in our upcoming v0.37 release as well.

Feel free to try it out and report back with your feedback!

**Comment by rfratto** [comment]
Given v0.37 was released yesterday with this functionality, I'm going to close this as completed. Please feel free to open new issues if you find any problems, and reach out to us on Slack (link in the README) if you have questions!
