### ISSUE TITLE
Update Agent Kubernetes topics to use Helm chart

### ISSUE THREAD

**Issue by clayton-cornell** [grafana/agent#5380]
> It would be good for us to remove the production/kubernetes folder entirely, honestly. We don't maintain it anymore. I only see one remaining reference to it that uses a recent version: 
>
> https://grafana.com/docs/agent/latest/static/set-up/install/install-agent-kubernetes/ 
>
> This guide can be changed to use our Helm chart instead for static mode, with some opinionated values.yaml files.
>
> cc @clayton-cornell for a future goal

_Originally posted by @rfratto in https://github.com/grafana/agent/pull/5333#discussion_r1347710900_

**Comment by rfratto** [comment]
Once references to production/kubernetes are removed from our docs, we can remove both the production/kubernetes and production/tanka folders.

**Comment by tpaschalis** [comment]
I'm closing this issue as our production/ directory has been removed and instructions have been updated to use the Helm chart for static mode as well.
