### ISSUE TITLE
azure_exporter doesn't support multiple dimensions

### ISSUE THREAD

**Issue by mtrin** [grafana/agent#5411]
### What's wrong?

In a instance where we have to use a metric namespace with multiple dimension combinations, the only way to make it work seemed to be configuring one exporter per combination.
My use case is [applicationGateway](https://github.com/MicrosoftDocs/azure-reference-other/blob/main/azure-monitor-ref/supported-metrics/includes/Microsoft-Network-applicationgateways-metrics-include.md)

### Steps to reproduce

Attempt to configure everything in one exporter will fail with the described error.
It seems to be related to upstream version of the webdevops module and if I understand it right, just by using [this ](https://github.com/webdevops/azure-metrics-exporter/pull/53) version of the module `v0.0.0-20230721124911-34985800463f` would at least validate the dimensions by default and might resolve the problem. 
Is there anything that I'm missing?
I could not test this on the static version because I found it impossible to make it work accordingly to the docs using multiple instances.

### System information

Kubernetes

### Software version

v0.37.0-rc.0

### Configuration

```text
prometheus.exporter.azure "example" {
	subscriptions = ["<...>"]
	resource_type = "Microsoft.Network/applicationGateways"

	included_dimensions = ["BackendHttpSetting", "BackendPool", "BackendServer", "HttpStatusGroup"]
	metrics             = [
		"BackendResponseStatus",
		"Throughput",
	]
	timespan = "PT1M"
}

## workaround is to use two separate exporters for the above, then the error goes away. My case I'm having to use several exporters.
```

### Logs

```text
GET https://management.azure.com/subscriptions/<subscription>/resourceGroups/<rg>/providers/Microsoft.Network/applicationGateways/<agwname>/providers/Microsoft.Insights/metrics
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "error": {
    "additionalInfo": [
      {
        "type": "string",
        "info": "TraceId={<...>}"
      },
      {
        "type": "string",
        "info": "ExceptionType=Microsoft.Online.Metrics.MetricsMP.Utilities.RPRequestFormatException"
      }
    ],
    "code": "BadRequest",
    "message": "Metric: Throughput does not support requested dimension combination: backendhttpsetting,backendpool,backendserver,httpstatusgroup, supported ones are: , TraceId: {<...>}"
  }
}
```

**Comment by marctc** [comment]
cc @thepalbi

**Comment by thepalbi** [comment]
@kgeckhart might have a better idea on this

**Comment by kgeckhart** [comment]
This is indeed a limitation of the current exporter version. I started doing the upgrade here, https://github.com/grafana/agent/compare/kgeckhart/upgrade-azure-exporter?expand=1. I just need to test it out and should be able to PR it this week.

> I could not test this on the static version because I found it impossible to make it work accordingly to the docs using multiple instances.

@mtrin do you have any more info on what issues you had with this or are you happy using flow mode instead?

**Comment by mtrin** [comment]
@kgeckhart Thanks for looking into this
From memory, the documentation doesn't show a full example on how to make the exporter work with multiple instances for azure_exporter and I was just struggling on how the yaml structure should look like, the metrics wouldn't show up and I couldn't find logs to diagnose it.

Happy to use and test flow mode, as it seems it's where the agent is headed anyway? And it feels a lot more intuitive and easier to troubleshoot.

Happy to test it out when you have a build I can pull from.
Thanks!
