### ISSUE TITLE
-config.file required error when trying the use the new convert subcommand

### ISSUE THREAD

**Issue by mlcdf** [grafana/agent#5436]
Hello :)

### What's wrong?

Following this [blog post](https://grafana.com/blog/2023/10/10/grafana-agent-v0.37-feature-parity-between-static-and-flow-mode-easy-migration-configs-and-more/#migrate-from-static-to-flow-mode-with-one-command), I tried using the new `convert` subcommand and it didn't work.

```
$ ./grafana-agent-linux-amd64 --version                                                               
agent, version v0.37.1 (branch: HEAD, revision: d4b1fcc9)
  build user:       root@369bd067b59d
  build date:       2023-10-10T15:17:51Z
  go version:       go1.21.1
  platform:         linux/amd64
  tags:             netgo,builtinassets,promtail_journal_enabled
  
$ ./grafana-agent-linux-amd64 convert --format=static --output=flow.river static.yaml
2023/10/11 14:51:29 -config.file flag required
```

I checked the [v0.37 docs](https://grafana.com/docs/agent/v0.37/flow/getting-started/migrating-from-static/?pg=blog&plcmt=body-txt#convert-a-static-mode-configuration) which indicate a slightly different command:

```
$ AGENT_MODE=flow; ./grafana-agent-linux-amd64 convert --source agent.yml --output config.river
2023/10/11 14:54:26 -config.file flag required
```

I downloaded the grafana-agent-linux binary from GitHub release. What I am missing? Should have I download another binary?

I also tried submitting the `-config.file` flag but then the agent starts ;()

### Steps to reproduce

```
wget https://github.com/grafana/agent/releases/download/v0.37.1/grafana-agent-linux-amd64.zip
unzip grafana-agentctl-linux-amd64.zip
./grafana-agent-linux-amd64 convert --format=static --output=flow.river static.yaml
```

### System information

Ubuntu 20.04

### Software version

Grafana Agent v0.37.1

**Comment by mlcdf** [comment]
Oh, I feel like I should have downloaded the grafana-agent-flow binary? It's not clear in the blog post and there no single binary available for grafana-agent-flow (only distro packages).

**Comment by mlcdf** [comment]
Alright, I managed to make this work by downloading the `grafana-agent-flow` debian package and extracting the binary.

But 
```
// Using the flags from the blog post
./grafana-agent-flow convert --format=static --output=flow.river agent.yaml
Error: unknown flag: --format

./grafana-agent-flow convert  --output=flow.river agent.yaml 
Error: source-format is a required flag


./grafana-agent-flow convert --source-format=static --output=flow.river agent.yaml
// it worked !
```

**Comment by rfratto** [comment]
> $ AGENT_MODE=flow; ./grafana-agent-linux-amd64 convert --source agent.yml --output config.river
> 2023/10/11 14:54:26 -config.file flag required

I suspect the documentation is misleading here, or behaves differently in different shells.

Can you try removing the `;` after the environment variable? 

```
AGENT_MODE=flow ./grafana-agent-linux-amd64 convert --source agent.yml --output config.river
```

or 

```
export AGENT_MODE=flow 
./grafana-agent-linux-amd64 convert --source agent.yml --output config.river
```

**Comment by mlcdf** [comment]
Oooh right, good catch! I didn't the issue would come from this! Thanks @rfratto :)

```
./grafana-agent-linux-amd64 convert --source-format=static --output config.river2 agent.yaml
// it works !
```

There's no such thing as the `--format` flag [mentioned in the blog post tho](https://grafana.com/blog/2023/10/10/grafana-agent-v0.37-feature-parity-between-static-and-flow-mode-easy-migration-configs-and-more/#migrate-from-static-to-flow-mode-with-one-command).

```
Usage:
  ./grafana-agent-linux-amd64 convert [flags] [file]

Flags:
  -b, --bypass-errors          Enable bypassing errors when converting
  -h, --help                   help for convert
  -o, --output string          The filepath and filename where the output is written.
  -r, --report string          The filepath and filename where the report is written.
  -f, --source-format string   The format of the source file. Supported formats: "prometheus", "promtail", "static".
```

**Comment by rfratto** [comment]
Thanks for the heads up! 

cc @erikbaranowski for fixing the blog post :)

**Comment by rfratto** [comment]
Thanks for the heads up! 

cc @erikbaranowski / @wildum for fixing the blog post :)
