### ISSUE TITLE
broken Flow mode link on the main docs page

### ISSUE THREAD

**Issue by mlcdf** [grafana/agent#5437]
Hello,

The `Flow mode` link below is broken on the [latest docs](https://grafana.com/docs/agent/latest/):
![image](https://github.com/grafana/agent/assets/9364931/7223347d-2342-4f0b-b1e9-df878d3650f4)
https://github.com/grafana/agent/blob/08dd42a6fd91669015fdb8f80797461dad9c4f12/docs/sources/_index.md?plain=1#L26

It's weird, the same syntax `[Flow mode][]` is use later on the page, and it works. Maybe it's because it's inside that `admonition` thing.

**Comment by marctc** [comment]
related https://github.com/grafana/agent/pull/5412

**Comment by mlcdf** [comment]
Good catch! Sorry for the noise... (I checked the recent issues but forgot the PRs)
