### ISSUE TITLE
loki.write: Unable to define User-Agent in flow component

### ISSUE THREAD

**Issue by jkroepke** [grafana/agent#5446]
### What's wrong?

I'm not able to define User-Agent header for loki.write Component

### Steps to reproduce

1. Setup Agent with the config below

### System information

Linux

### Software version

v0.36.1

### Configuration

```text
loki.write "remote" {
    endpoint {
        name      = "opsstack"
        url       = "http://localhost:3100/loki/api/v1/push"
        headers   = {
            "User-Agent" = " os=" + constants.os,
        }
        tenant_id = "opsstack"
    }
}
```

### Logs

```text
{"component":"client","host":"localhost:3100","key":"User-Agent","level":"warn","msg":"custom header key already exists, skipping","ts":"2023-10-12T07:57:04.9857509Z"}
```

**Comment by tpaschalis** [comment]
Thanks for the report. This behavior was ported over from Promtail, my 2c is that can be changed and if the user passes in a custom header they'd know better.

**Comment by rfratto** [comment]
Interestingly, this is intended behavior in Prometheus, where they document:

```
# Custom HTTP headers to be sent along with each remote write request.
# Be aware that headers that are set by Prometheus itself can't be overwritten.
headers:
  [ <string>: <string> ... ]
```

The headers Prometheus doesn't allow overriding is:

* Content-Encoding
* Content-Type
* User-Agent
* X-Prometheus-Remote-Write-Version
* Retry-Attempt 

I can see why it's useful to have consistency here, especially consistency with how agents identify themselves to servers. 

Can you give a little more detail around your use case here?

(Given that this behavior is intentional I'm relabeling this as "enhancement")

**Comment by jkroepke** [comment]
Hm, there are different view in terms of consistency here.

Looking at the agent overall consistency, I'm able to define the User-Agent on `remote.http`, `module.http` and `prometheus.remote_write`

> The headers Prometheus doesn't allow overriding is:

At least for `prometheus.remote_write`, is this not true.

**Comment by jkroepke** [comment]
> The headers Prometheus doesn't allow overriding is:

Hi @rfratto 

today, I checked the source Code of Prometheus I would like to disagree here.

It's true, that Prometheus defines some headers by default:

https://github.com/prometheus/prometheus/blob/f997c72f294c0f18ca13fa06d51889af04135195/storage/remote/client.go#L206-L212

However, Prometheus uses a RoundTrip function of the Transport Client which allowed to overwrite the default header.

https://github.com/prometheus/prometheus/blob/f997c72f294c0f18ca13fa06d51889af04135195/storage/remote/client.go#L182-L187

On our production systems, we already define the `User-Agent` header from the Agent config which is working fine.

**Comment by rfratto** [comment]
@jkroepke While the code technically allows setting any header, Prometheus performs [validations](https://github.com/prometheus/prometheus/blob/f997c72f294c0f18ca13fa06d51889af04135195/config/config.go#L1082-L1092) against the config to prevent certain headers from being changed: 

* [authorization](https://github.com/prometheus/prometheus/blob/f997c72f294c0f18ca13fa06d51889af04135195/config/config.go#L1084-L1086) is explicitly rejected if set 
* There's also a list of [reserved headers](https://github.com/prometheus/prometheus/blob/f997c72f294c0f18ca13fa06d51889af04135195/config/config.go#L43-L65) which get rejected if set, including User-Agent.

**Comment by jkroepke** [comment]
Okay, thank you.
