### ISSUE TITLE
Is there a canonical implementation for remote-write sending with WAL?

### ISSUE THREAD

**Issue by idoqo** [grafana/agent#547]
Hi, we’re currently trying to add stateless mode to Thanos ruler, where it will be able to store rule evaluations to a write-ahead-log, which is later sent via remote_write (a more detailed proposal is at https://github.com/thanos-io/thanos/blob/main/docs/proposals/202005_scalable-rule-storage.md). 

I was wondering if there’s an existing implementation out there that is used by the community, seeing as the Grafana Agent is kind of similar.

**Comment by rfratto** [comment]
Hey there! The best answer here is Prometheus' remote_write itself: it tails from a WAL and will send metrics it reads. 

The missing piece implemented by the Grafana Agent is a WAL-only appender, which takes a lot of inspiration from the Prometheus TSDB appender but doesn't persist any samples outside of the WAL. That code is in [pkg/prom/wal](https://github.com/grafana/agent/tree/main/pkg/prom/wal) and will be a part of our contribution to the upcoming Prometheus Agent.

When we glue everything together, we create a fanout storage that fans out to the WAL-only appender and the remote storage appender (which basically does nothing). Then the remote storage tails the WAL and ships any metrics off to remote write. 

Does this make sense?

**Comment by bwplotka** [comment]
It does to me! It sounds like the best way is to start using agent's `pkg/prom/wal` and help you to review/work the contribution so all can be smoothly reused! 

Sorry for missing this, but `doesn't persist any samples outside of the WAL`, why is that? (Other than extra code and complexity). Is this the replay times risk?

**Comment by rfratto** [comment]
> Sorry for missing this, but `doesn't persist any samples outside of the WAL`, why is that? (Other than extra code and complexity). Is this the replay times risk?

Ah, that's just because a design goal of the Grafana Agent is to be a storageless Prometheus, acting essentially as a metrics forwarder from scrape targets to remote write. The WAL is the only component we need to do that.

**Comment by bwplotka** [comment]
Thanks. Someday I guess it would be nice to have a more stateful agent if one wants to rely on each sample to be delivered. Or is it this in practice not needed? 🤔
