### ISSUE TITLE
0.14.0-rc.2 performance regression

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#548]
I've received a report that 0.14.0-rc.2 seems to have some kind of performance regression. The amount of remote_write shards increased by 3x, followed by an increase of failed samples. 

More information here from anyone else who is running into this would be great.

Until I can reproduce/fix or understand more, I'd say this is a blocker for 0.14.0.

**Comment by amckinley** [comment]
Hey @rfratto, not sure if the initial report you heard was from us, but we can definitely reproduce this on demand by trying to run any 0.14 release against our production workload. 0.13 works fine.

**Comment by rfratto** [comment]
Fixed by #636.
