### ISSUE TITLE
request for adding tempo crd in grafana operator resources 

### ISSUE THREAD

**Issue by aryan-brane-1971** [grafana/agent#5512]
### Request

i am requesting you to add tempo crd file in grafana agent operator resources just like metrics and logs as given in this link
https://grafana.com/docs/agent/latest/operator/deploy-agent-operator-resources/

### Use case

beneficial to deploy tempo in grafana agent operator

**Comment by marctc** [comment]
Hey, thanks for reporting! I'm closing the ticket as it already discussed here https://github.com/grafana/agent/issues/1044
