### ISSUE TITLE
Grafana Agent Blackbox integration /metrics endpoint returning - Target parameter is missing

### ISSUE THREAD

**Issue by prajul-nambiar** [grafana/agent#5530]
### What's wrong?

While trying to use the blackbox integration built into Grafana agent, the `/integrations/blackbox/metrics` endpoint returns `Target parameter is missing`, while the logs shows the "Probe Succeeded"

![image](https://github.com/grafana/agent/assets/65483386/406b95f7-b61e-49f2-9268-8ce114447846)

### Steps to reproduce

1. Configure grafana agent integration as mentioned in the config
2. Reload the agent
3. Check end point  /integrations/blackbox/metrics

### System information

Windows Server 2019 x64

### Software version

Grafana Agent v 0.37.2

### Configuration

```text
server:
  log_level: debug
metrics:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 1m
  configs:
    - name: integrations
integrations:
  blackbox:
    enabled: true
    blackbox_targets:
      - name: "name"
        address: "http://localhost/app/Virtual.aspx"
        module: http_2xx
    blackbox_config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
```

### Logs

```text
integration=blackbox module=http_2xx target=http://localhost/app/Virtual.aspx level=debug msg="Beginning probe" probe=http timeout_seconds=5

integration=blackbox module=http_2xx target=http://localhost/app/Virtual.aspx level=debug msg="Resolving target address" target=localhost ip_protocol=ip6

integration=blackbox module=http_2xx target=http://localhost/app/Virtual.aspx level=debug msg="Resolved target address" target=localhost ip=::1

integration=blackbox module=http_2xx target=http://localhost/app/Virtual.aspx level=debug msg="Making HTTP request" url=http://[::1]/app/Virtual.aspx host=localhost

integration=blackbox module=http_2xx target=http://localhost/app/Virtual.aspx level=debug msg="Received HTTP response" status_code=200

integration=blackbox module=http_2xx target=http://localhost/app/Virtual.aspx level=debug msg="Response timings for roundtrip" roundtrip=0 start=2023-10-18T21:03:09.4636644+02:00 dnsDone=2023-10-18T21:03:09.4636644+02:00 connectDone=2023-10-18T21:03:09.4636644+02:00 gotConn=2023-10-18T21:03:09.4636644+02:00 responseStart=2023-10-18T21:03:09.4656608+02:00 tlsStart=0001-01-01T00:00:00Z tlsDone=0001-01-01T00:00:00Z end=2023-10-18T21:03:09.4667672+02:00

integration=blackbox module=http_2xx target=http://localhost/app/Virtual.aspx level=debug msg="Probe succeeded" duration_seconds=0.0070095
```

**Comment by marctc** [comment]
The log displaying the output of the probes configured in the agent config. The `/metrics` endpoint requires that you specify which module and target you want to see.

**Comment by prajul-nambiar** [comment]
@marctc , Thank you very much for that clarity. So if I have to extract/scrape metrics about targets defined on grafana agent config file using something like a prometheus, I would have to have the target and module defined in prometheus config too?

**Comment by marctc** [comment]
@prajul-nambiar I'm afraid so, yeah. I'm not sure if that's the best way to setup of agent+prometheus tho.

**Comment by prajul-nambiar** [comment]
Thanks @marctc for your inputs. Appreciate it.

**Comment by ObserveLite** [comment]
./grafana-agent -config.file=/etc/grafana-agent1.yaml
ts=2024-01-19T05:52:57.889148868Z caller=main.go:71 level=info boringcryptoenabled=false
ts=2024-01-19T05:52:57.889689774Z caller=server.go:190 level=info msg="server listening on addresses" http=127.0.0.1:12345 grpc=127.0.0.1:12346 http_tls_enabled=false grpc_tls_enabled=false
ts=2024-01-19T05:52:57.890280003Z caller=node.go:85 level=info agent=prometheus component=cluster msg="applying config"
ts=2024-01-19T05:52:57.890444843Z caller=remote.go:180 level=info agent=prometheus component=cluster msg="not watching the KV, none set"
ts=2024-01-19T05:52:57.891528946Z caller=zapadapter.go:78 level=info component=traces msg="Traces Logger Initialized"
ts=2024-01-19T05:52:57.892251576Z caller=manager.go:228 level=debug msg="Applying integrations config changes"
ts=2024-01-19T05:52:57.89373642Z caller=instance.go:301 level=debug agent=prometheus instance=243a344db344241f404868d04272fc76 msg="initializing instance" name=243a344db344241f404868d04272fc76
ts=2024-01-19T05:52:57.897076641Z caller=manager.go:225 level=debug msg="Integrations config is unchanged skipping apply"
ts=2024-01-19T05:52:57.897277574Z caller=reporter.go:103 level=info msg="running usage stats reporter"
ts=2024-01-19T05:52:57.902612801Z caller=wal.go:211 level=info agent=prometheus instance=243a344db344241f404868d04272fc76 msg="replaying WAL, this may take a while" dir=C:\ProgramData\grafana-agent-wal/243a344db344241f404868d04272fc76/wal
ts=2024-01-19T05:52:57.904443805Z caller=wal.go:260 level=info agent=prometheus instance=243a344db344241f404868d04272fc76 msg="WAL segment loaded" segment=0 maxSegment=1
ts=2024-01-19T05:52:57.904660245Z caller=wal.go:260 level=info agent=prometheus instance=243a344db344241f404868d04272fc76 msg="WAL segment loaded" segment=1 maxSegment=1
ts=2024-01-19T05:52:57.904775406Z caller=manager.go:289 level=debug agent=prometheus instance=243a344db344241f404868d04272fc76 component="discovery manager" msg="Starting provider" provider=static/0 subs=map[integrations/blackbox/name:{}]
ts=2024-01-19T05:52:57.906058965Z caller=manager.go:323 level=debug agent=prometheus instance=243a344db344241f404868d04272fc76 component="discovery manager" msg="Discoverer channel closed" provider=static/0
ts=2024-01-19T05:52:57.911709851Z caller=instance.go:384 level=debug agent=prometheus instance=243a344db344241f404868d04272fc76 msg="running instance" name=243a344db344241f404868d04272fc76
ts=2024-01-19T05:52:57.913662189Z caller=manager.go:198 level=info agent=prometheus msg="dynamically updated instance" instance=243a344db344241f404868d04272fc76
