### ISSUE TITLE
PodLog CRD in grafana-agent helm subchart incompatible with PodLog CRD in another part of the project

### ISSUE THREAD

**Issue by gregwhorley** [grafana/agent#5531]
### What's wrong?

A recent change to the `grafana-agent` Helm chart added a `crd` subchart that contains a PodLog CRD that is incompatible with the PodLog CRD located in `production/operator/crds`. The [change](https://github.com/grafana/agent/pull/5410) shows that a CRD with only `v1alpha2` version listed while [another copy of the CRD](https://github.com/grafana/agent/blob/f2b2456503338af3a5d00cbdf628042fe933189c/production/operator/crds/monitoring.grafana.com_podlogs.yaml) contains the `v1alpha1` version.

If a user sets `crds.create` to true for this Helm chart and then installs another Grafana product's Helm cart such as [mimir](https://github.com/grafana/mimir/blob/2c11a34ae4531a4c280f51ab9133c855dc523d0f/operations/helm/charts/mimir-distributed/templates/metamonitoring/pod-logs.yaml)  with a `PodLog` template that references api version `v1alpha1`, that install will fail.

### Steps to reproduce

- Install `grafana-agent` helm chart per these instructions https://artifacthub.io/packages/helm/grafana/grafana-agent#usage and override `crds.create` value to true
- Install `mimir-distributed` helm chart with meta monitoring enabled per these instructions https://grafana.com/docs/helm-charts/mimir-distributed/latest/get-started-helm-charts/#generate-some-metrics-for-testing
- Observe install failure for the `PodLog` resource because the CRD that was installed from the `grafana-agent` Helm chart is incompatible.

### System information

Linux 5.10.192-183.736.amzn2.x86_64

### Software version

Grafana Agent: 0.37.2 Helm chart version: grafana-agent-0.27.0

### Configuration

```text
grafana-agent values at default except for `crds.create` which should be set to true

mimir-distributed values for meta-monitoring described in https://grafana.com/docs/helm-charts/mimir-distributed/latest/get-started-helm-charts/#generate-some-metrics-for-testing
```

**Comment by rfratto** [comment]
Thanks for reporting. #5532 should fix this.
