### ISSUE TITLE
License may not be compliant in the future

### ISSUE THREAD

**Issue by roidelapluie** [grafana/agent#555]
This project includes

github.com/grafana/loki/pkg/distributor
(and maybe others)

Which are (or will be once vendoring is updated) licensed under AGPL. Therefore if the agent is not expliciltly relelased under AGPL, it will create a risk for the people who would depend on this code.

**Comment by roidelapluie** [comment]
The distributors links to

     "github.com/grafana/loki/pkg/ingester/client"
     "github.com/grafana/loki/pkg/logproto"
     "github.com/grafana/loki/pkg/logql"
     "github.com/grafana/loki/pkg/runtime"
     "github.com/grafana/loki/pkg/util"
     "github.com/grafana/loki/pkg/validation"

And I think that especially logql is a touchy one.

**Comment by rfratto** [comment]
Yeah, once we update the vendor we will make sure we don't import `pkg/distributor` at all. This is the full list of packages we explicitly import:

```
github.com/grafana/loki/pkg/distributor
github.com/grafana/loki/pkg/logproto
github.com/grafana/loki/pkg/promtail
github.com/grafana/loki/pkg/promtail/client
github.com/grafana/loki/pkg/promtail/config
github.com/grafana/loki/pkg/promtail/positions
github.com/grafana/loki/pkg/promtail/scrapeconfig
github.com/grafana/loki/pkg/promtail/server
github.com/grafana/loki/pkg/promtail/targets/file
``` 

Of those, `pkg/distributor` is the only one has been since changed to AGPLv3, and is only used for tests. We don't need it.

**Comment by rfratto** [comment]
Thanks for the heads up about this!

**Comment by roidelapluie** [comment]
Thanks. I will close this then.
