### ISSUE TITLE
Let the windows installer create the service with the -config.expand-env parameter

### ISSUE THREAD

**Issue by ToonTijtgat2** [grafana/agent#5554]
### Request

It would be nice if it's possible to run the windows installer of the grafana agent with a parameter to create the windows service with the -config.expand-env parameter

### Use case

installing grafana agent on windows

**Comment by erikbaranowski** [comment]
I should mention... this is a static mode specific feature request as flow mode makes use of a standard library function and does not require a CLI flag for this functionality: https://grafana.com/docs/agent/next/flow/reference/stdlib/env/

**Comment by erikbaranowski** [comment]
I have a draft PR https://github.com/grafana/agent/pull/5958 and built the windows installer locally. I plan to keep playing around in January as I experiment with testing the windows installer locally to confirm it is working as intended

**Comment by dmitrydonskih** [comment]
@erikbaranowski could you also check "silent" installer mode?
Nullsoft installer allows unattended install/unninstall with `/S` parameter. No need to say how useful it is.
Customizable options should be available in this mode also, by command-line parameters.
Thanks for your work!
