### ISSUE TITLE
Proposal: pushgateway integration

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#557]
The [Prometheus Pushgateway](https://github.com/prometheus/pushgateway) is a fairly common tool in the ecosystem. It'd be great to have it an an integration. 

The implementation of this would need to find a way to wire the Pushgateway API into the existing HTTP server or spin up a new server for the metrics.

**Comment by adeverteuil** [comment]
It seems redundant to me. We can already scrape custom metrics using the textfile collector from the node_exporter integration. Pushgateway is for collecting service scoped metrics from ephemeral jobs, so it needs to be hosted at a central location. I think hosting the Pushgateway as part of the Grafana Cloud stack is more natural.
https://github.com/grafana/support-escalations/issues/556

**Comment by adeverteuil** [comment]
@richardqlam mentioned this came from a customer request.
Probably this one: https://admin.grafana.com/orgs/paymentsense
Do we have the exact request from the customer? How did they describe their use-case? Would a cloud Pushgateway be equivalent or better for them?

**Comment by tpanum** [comment]
Any news on this? This is a critical feature for any job-orient stack.

**Comment by rfratto** [comment]
This isn't something we have prioritized at the moment, especially since there's a decent workaround (e.g., deploying the actual Pushgateway alongside the agent). Unless this suddenly gets prioritized, it's shaping up to be something we'd have to collaborate with an external contributor for it to get added natively into the agent as an integration.

**Comment by rfratto** [comment]
I'm going to close this for now. We don't have anything planned for a pushgateway integration, but if someone is interested in contributing this please reach out.
