### ISSUE TITLE
Update Postgres exporter to the latest version of Postgres exporter community

### ISSUE THREAD

**Issue by EdithChenLi** [grafana/agent#5610]
### Request

It's little confused that pg exporter integrated in the grafana agent(0.37.2), checked the integration pg exporter link not there anymore. It would be greate to update Postgres exporter to latest version of community

### Use case

The metrics in collector like postmaster/db_size is really needed to monitor the PG databases

**Comment by marctc** [comment]
Hey, we have a bunch of issues for that already:
https://github.com/grafana/agent/issues/4749
https://github.com/grafana/agent/issues/3419
The main issue is that we rely on a fork that is something hard to upgrade.
Unless there's anything specific that is not already mentioned in other tickets, I'm closing
