### ISSUE TITLE
Issue's with GrafanaAgent dashboards (metrics missing for flow mode)

### ISSUE THREAD

**Issue by paul-bormans** [grafana/agent#5612]
### What's wrong?

The GrafanaAgent dashboards (from https://github.com/grafana/jsonnet-libs/tree/master/grafana-agent-mixin) rely on certain metrics that appear to be missing when running G/A in flow mode.

At least following metrics are missing:
- prometheus_sd_discovered_targets
- agent_tcp_connections

It seems the dashboard is currently tuned for static mode; or flow mode isn't on-par with static mode.

### Steps to reproduce

Agent is running with following arguments (kind of default helm chart):
`  - args:
    - run
    - /etc/agent/config.river
    - --storage.path=/tmp/agent
    - --server.http.listen-addr=0.0.0.0:8888
    - --disable-reporting
    - --cluster.enabled=true
    - --cluster.join-addresses=grafana-agent-system-cluster
    env:
    - name: AGENT_MODE
      value: flow
`

Reviewing the dashboard; for instance the Grafana Agent Operational panel shows "No data"

### System information

Kubernetes

### Software version

grafana/agent:v0.37.2 and dashboard from https://github.com/grafana/jsonnet-libs.git commit 197b22d7a053fe6d03a40f26abda064d4b717620

**Comment by tpaschalis** [comment]
Yes, that's true; that set of dashboards is optimized for static mode.

The Flow mode equivalent mixin is available here, with more views focused on Flow concepts like graph evaluations, or clustering.

https://github.com/grafana/agent/tree/main/operations/agent-flow-mixin

Can you check if it fits your needs?

**Comment by paul-bormans** [comment]
They work out of the box; yet doesn't shows nof targets or scrape failures?

**Comment by rfratto** [comment]
I'm going to close this issue as we do have a mixin specific for Flow. The Flow mixin will improve over time; if you are looking for specific improvements, please open new issues for the improvements to the mixin that you would like to see.

**Comment by paul-bormans** [comment]
Agreed; in-fact i just pushed a PR to add panels :-).

**Comment by gonzalo-dibiase-webbeds** [comment]
@paul-bormans how did you generate the dashboards, cant find anywhere nor in the make file
