### ISSUE TITLE
Support resource_to_telemetry_conversion in otelcol.exporter.prometheus

### ISSUE THREAD

**Issue by ptodev** [grafana/agent#5631]
### Request

The OpenTelemetry [prometheus remotewrite exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusremotewriteexporter) supports a `resource_to_telemetry_conversion` config option which converts resource attributes to datapoint attributes. We need to add the same feature to `otelcol.exporter.prometheus`.

### Use case

`otelcol.processor.k8sattributes` attaches Kubernetes metadata as resource attributes. Those attributes need to be copied as data point attributes in order to not be lost when remote writing with `prometheus.remote_write`. This was recently [discussed](https://grafana.slack.com/archives/C01050C3D8F/p1697614064021499) in a community Slack. 

The only workaround so far is to use `otelcol.processor.transform`, but I believe this requires listing all attributes explicitly, which is inconvenient.

**Comment by hainenber** [comment]
Hello there, I'm working on this atm so can I be assigned? :D
