### ISSUE TITLE
Implement eventlogmessage from promtail in loki.process

### ISSUE THREAD

**Issue by nswright** [grafana/agent#5657]
### Request

The loki.process component should implement [eventlogmessage](https://grafana.com/docs/loki/latest/send-data/promtail/stages/eventlogmessage/) from promtail.

### Use case

This feature would greatly simplify querying windows event logs by attaching structured metadata using this stage. It would also speed up queries on windows event logs by eliminating the need to parse the message field.

**Comment by tpaschalis** [comment]
The loki.process component _does_ implement the [eventlogmessage stage](https://grafana.com/docs/agent/next/flow/reference/components/loki.process/#stageeventlogmessage-block) since v0.37

What version of the Agent are you running?

**Comment by tpaschalis** [comment]
I'm going to close this issue out, please feel free to re-open it if there was something different you had in mind. Thanks!
