### ISSUE TITLE
Pods in Kind: Integration resources Can I specify a custom image?

### ISSUE THREAD

**Issue by 1473371932** [grafana/agent#5675]
### Background

In internal environment，need to use custom image，but currently you can only use a custom image of an agent when creating a grafana agent，creating the kind: Integration resource，two containers in the Pod，config-reloader container how to specify a custom image？

> root@k8s-master:~# kubectl describe pods -n deepflow grafana-agent-integrations-ds-xghbv | grep -EA 1 "grafana-agent:|config-reloader:"
>   config-reloader:
>     Image:         quay.io/prometheus-operator/prometheus-config-reloader:v0.67.1
>   grafana-agent:
>     Image:         hub.deepflow.yunshan.net/public/grafana-agent:v0.36.2

### Proposal

Where to change the image of the config-reloader container？

**Comment by tpaschalis** [comment]
Since there is a way to specify the config reloader image, I'm closing this issue as completed.
