### ISSUE TITLE
Add otelcol.filter.processor flow component

### ISSUE THREAD

**Issue by mar4uk** [grafana/agent#5690]
### Request

The component [filterprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor) allows dropping spans, span events, metrics, datapoints, and logs

This component is useful to filter out unneeded telemetry data

### Use case

For example, we have metric `traces_spanmetrics_calls_total`, it has `span_kind` label with possible values: 
- SPAN_KIND_SERVER
- SPAN_KIND_CLIENT
- SPAN_KIND_INTERNAL
- SPAN_KIND_PUBLISHER
- SPAN_KIND_CONSUMER

But we are interested only in SPAN_KIND_SERVER and SPAN_KIND_CONSUMER values, all other values are not needed for us, but their presence increases cardinality.
To decrease cardinality (aka decrease price) we want to drop uninterested label values.

Filter processor can do it

**Comment by hainenber** [comment]
Greeting, this has been [implemented](https://github.com/grafana/agent/commit/481674a6f5b095451e253abd3573fdb8deb4fa28) already (I was the author :D) but this hasn't been released yet so stay tune!

**Comment by tpaschalis** [comment]
I'm going to close this issue as completed (thanks @hainenber 🙌). The component will be included in the next Agent release, around mid-November.

**Comment by mar4uk** [comment]
Great! Thank you!
