### ISSUE TITLE
snmp export: Support config property.

### ISSUE THREAD

**Issue by jkroepke** [grafana/agent#5734]
### Request

The [prometheus.exporter.snmp](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.exporter.snmp/) components only support config property and requires a local file to work properly. 

### Use case

This can be problematic, if the Agent relies only Remote Agent configuration (module.http). The Agent does not have the functionality to download and store files in a local file system which can be references on the component.

Same request exists for blackbox_exporter: 
ref: https://github.com/grafana/agent/pull/3550

**Comment by tpaschalis** [comment]
Did you mean to close this one out @jkroepke?

**Comment by jkroepke** [comment]
@tpaschalis Yes. I indicently looked on a outdated online documentation version. This feature is present on the current agent version
