### ISSUE TITLE
Windows Flow Installer 0.37.4 flagged by ESET.NOD32

### ISSUE THREAD

**Issue by PaulKlein** [grafana/agent#5763]
### What's wrong?

When I try to download the `grafana-agent-flow-installer.exe.zip` asset for the 0.37.4 release, my ESET antivirus flags it as `Generik.LMMXENY`

You can see the same when uploading to VirusTotal:
https://www.virustotal.com/gui/file/284e67ffac8ef1efe66073cb349067dc793e6d900cb4013e05ffd7a664bd9f81

Is this a false positive? No other anti-virus detects this as an issue but FYI about this.

Thanks

### Steps to reproduce

ESET flags + quarantines the .exe file as soon as I unzip the downloaded .zip file

### System information

Windows 11

### Software version

Grafana Agent Flow 0.37.4

**Comment by mattdurham** [comment]
Occasionally virus detection will detect our use of NSIS has something. When googling I couldn't find any hits for LMMXENY to see what the scanner is flagging. This appears to be a false positive unless you can get more details from your anti virus provider.

**Comment by PaulKlein** [comment]
Thanks Matt,
I have submitted the file to ESET as a potential false positive, hopefully they'll update their detection to resolve this.
I am using the previous release in the meantime.
Thanks

**Comment by PaulKlein** [comment]
I re-ran the virus total scan for 0.37.4, and while ESET now doesn't detect anything, a few other AV products do. Again these are all very vague detection results though, and probably also heuristics / false-positives.

The latest 0.38.1 release is also getting picked up but only by Jiangmin

 - 0.37.4: https://www.virustotal.com/gui/file/284e67ffac8ef1efe66073cb349067dc793e6d900cb4013e05ffd7a664bd9f81
 - 0.38.1: https://www.virustotal.com/gui/file/a81a67e5b54f375b7494ed1b7741f45d60e6977264f21b8f966acd6923109f61

Anyway just FYI about this - I'm happy to close if there's no concrete action needed here.
