### ISSUE TITLE
Consider making certain configuration options available via flag only

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#581]
The upcoming /-/reload support has made a lot of sacrifices to be implemented. Many components do not support dynamic configuration and need to be fully shut down and replaced to emulate a configuration change. 

I've not been happy with the code I've had to do this, and I'm concerned about its stability. The user experience of /-/reload is also challenging. Given these components aren't meant to be dynamically updated, the system can be left in an undefined state when providing an invalid config file. 

I suggest a breaking change of **removing all configuration options that should be static** from the config file and exposing them only via flags. 

This would trim down the config file to only consist of the following:

1. Prometheus instance configs
2. Loki instance configs 
3. Tempo instance configs 
4. Integrations

Loki, Tempo, and Integrations would still need to be fully shut down to be updated, but this is OK. The sources of trouble implementing reload was the HTTP server and scraping service. 

I'm on the fence about this. I considered it when initially implementing config reload, but opted for the current approach instead to try it out. Now, I think it'd be better to simplify the config file and code required to make reload work.

**Comment by 56quarters** [comment]
FWIW, this is what Prometheus does prometheus/prometheus#6188

Anything that isn't hot-reloadable goes into a CLI flag.

**Comment by rfratto** [comment]
Yep, following Prometheus' lead is a good reason to want to do this. 

I'm wary about breaking change fatigue (if such a thing exists). We've been making quite a few breaking changes lately, and although they've been small, it's been frequent. Maybe this isn't something we want to do immediately, but after a few months or so.

**Comment by kfp** [comment]
Consider making this consumable via environment variables instead of/in addition to command args. Command args are more buried in k8s land where env variables are first class.

**Comment by rfratto** [comment]
This is something that is going on in the background with the development of Flow. I'm going to close this as not planned.
