### ISSUE TITLE
Rename binary to grafana-agent-* ?

### ISSUE THREAD

**Issue by RichiH** [grafana/agent#582]
In particular with https://github.com/prometheus/prometheus/pull/8785 it would make sense to be more specific in naming with the binary, I think.

**Comment by rfratto** [comment]
I'm open to this. This isn't even something we're internally consistent with; the system packages install a grafana-agent while everything else is just called agent. 

I'd probably prefer not to rename the docker image though.

**Comment by RichiH** [comment]
The image itself has grafana in the path name, that seems fine.

**Comment by rfratto** [comment]
Hoping to make this change this week.
