### ISSUE TITLE
Provide agent_hostname default label for promtail

### ISSUE THREAD

**Issue by onsails** [grafana/agent#584]
All metrics from promtail configs come with `instance=127.0.0.1:9615` label which is pretty useful in case of multiple nodes.

There is `agent_hostname` label in `node_exporter` integration which can be relabeled to `instance` vial `metrics_relabel_configs`. In my opinion, it's logical to have the same `agent_hostname` label for the promtail module.

**Comment by langerma** [comment]
This is still an issue
