### ISSUE TITLE
Support remote_write name parameter

### ISSUE THREAD

**Issue by adeverteuil** [grafana/agent#589]
Prometheus [`remote_write` configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) support a `name` parameter. I tried setting it in the `integrations.prometheus_remote_write` items but the debug logs and the `prometheus_remote_storage_*` metrics still use the generated name.

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write

```
# Name of the remote write config, which if specified must be unique among remote write configs.
# The name will be used in metrics and logging in place of a generated value to help users distinguish between
# remote write configs.
[ name: <string> ]
```

Sample log line:
```
ts=2021-05-11T20:33:49.499168454Z caller=dedupe.go:112 agent=prometheus instance=26e5a509e2afa42d835a848e7bd24dc6 component=remote level=debug remote_name=26e5a5-9a9e41 url=https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push msg="runShard timer ticked, sending samples" samples=3 shard=0
```

**Comment by rfratto** [comment]
Hey, the default behavior of the Agent merges all remote_writes together, ignoring the name field. This was done as an optimization for the scraping service, where you may have 500 identical remote_writes (minus the name), but _don't_ want 500 remote WALs. You can avoid this by setting `prometheus.instance_mode` to `distinct` in the [config file](https://github.com/grafana/agent/blob/main/docs/configuration-reference.md#prometheus_config). 

I've been wanting to change this behavior for a while. I don't think it was the best idea to ignore the remote_write names by default, and I'm planning on exploring better approaches this week.

**Comment by adeverteuil** [comment]
Thank you, this can now be closed! I also found more info here: https://github.com/grafana/agent/blob/main/docs/operation-guide.md#instance-sharing
