### ISSUE TITLE
Agent instances in clustering / flow mode are running the exact same target resulting in out-of-order samples

### ISSUE THREAD

**Issue by paul-bormans** [grafana/agent#5926]
### What's wrong?

I have GrafanaAgent running as a deployment with 6 replicas; an envoy podmonitor is being served which discoveres a number of targets which are then divided over the instances in the cluster. Then however in logging I'm seeing issue's with metrics being send to mimir that are out-of-order and those series get rejected.

```
ts=2023-12-06T11:13:31.35153131Z caller=push.go:130 level=error user=system msg="push error" err="rpc error: code = Code(400) 
desc = failed pushing to ingester: user=system: 
the sample has been rejected because another sample with a more recent timestamp has already been ingested and out-of-order samples are not allowed (err-mimir-sample-out-of-order).
The affected sample has timestamp 2023-12-06T10:23:03.669Z and is from series 
{
__cluster__="dp-monitoring/grafana-agent", 
__name__="istio_agent_go_gc_duration_seconds", 
container="istio-proxy", 
instance="10.101.9.139:15020", 
job="dp-istio-egress/envoy-stats-monitor-dp-istio-egress", 
namespace="dp-istio-egress", 
platform="dev", 
pod="dp-istio-egressgateway-85fb54967c-gd5gl", 
pod_name="dp-istio-egressgateway-85fb54967c-gd5gl", 
quantile="0.75"
}
```

I checked the 6 instances and found 3 of them running the exact same target.
<img width="1205" alt="scrape-ooo-istio-egress-1-2-3" src="https://github.com/grafana/agent/assets/78035262/0223f20a-65ea-47c5-896a-49f10d1a55af">

I also checked the clustering state and found they all belong to the same cluster; no split brain.
Also these instances are running for some days already.

### Steps to reproduce

I tried to reproduce on a kind cluster, but no luck so far.
On cluster however, when I delete the podmonitor resource both targets are gone from the GA UI (correct), when I recreate the same podmonitor they actually reappear; I checked 2 instances and the same target pops up there.

As a second test I scaled the deployment from 6 to 5 and back to 6 instance. This should trigger a cluster-updated event to the operator/discovery module. I noticed the targets did indeed move around but I again found 3 instances scraping the same target?

### System information

GKE

### Software version

grafana/agent:v0.38.1

**Comment by tpaschalis** [comment]
Can you please share your config file after redacting any sensitive info? Have you enabled the [clustering block](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.operator.podmonitors/#clustering-beta) on your podmonitor (or prometheus.scrape) component?

**Comment by paul-bormans** [comment]
Please find those configs attached.
[agent.river.txt](https://github.com/grafana/agent/files/13600020/agent.river.txt)
[deployment.txt](https://github.com/grafana/agent/files/13600023/deployment.txt)

**Comment by tpaschalis** [comment]
Thanks for providing your config Paul!

You're right in that each Agent individually constructs its own ring and filters for targets in its ownership. 

There is no way to check for consistency today, eg. a hash of the current status, and there's also no random behaviour on how nodes define ownership as peers are sorted lexicographically.

> So having found multiple owners of a given target can only mean that the rings over the instances are not consistent?

Yes. My original suspicion was about whether it's a very dynamic environment where service discovery can't keep up and provides stale results to a subset of the nodes; do you think that could be the culprit here?

One thing I'm interested about: 

> I noticed the targets did indeed move around but I again found 3 instances scraping the same target?

When you say that, do you mean the _same target_ that was originally also shared between resources before you deleted and recreated the podmonitor?

**Comment by tpaschalis** [comment]
Thanks for providing your config @paul-bormans!

You're right in that each Agent individually constructs its own ring and filters for targets in its ownership. 

There is no way to check for consistency today, eg. a hash of the current status, and there's also no random behaviour on how nodes define ownership as peers are sorted lexicographically.

> So having found multiple owners of a given target can only mean that the rings over the instances are not consistent?

Yes. My original suspicion was about whether it's a very dynamic environment where service discovery can't keep up and provides stale results to a subset of the nodes; do you think that could be the culprit here?

One thing I'm interested about: 

> I noticed the targets did indeed move around but I again found 3 instances scraping the same target?

When you say that, do you mean the _same target_ that was originally also shared between resources before you deleted and recreated the podmonitor?

**Comment by tpaschalis** [comment]
In any case, I think it's possible we may have a bug here; either in the way that the crdManager generates the targets, how we filter them down, or the ckit code itself, will be taking a closer look.

Another culprit for example could be if the podmonitor actually generated multiple targets per pod (cc @captncraig for good measure)

**Comment by paul-bormans** [comment]
Hi @tpaschalis thanks for helping us out with this issue.
Let me first answer your questions:

1. Dynamic environment; no it's not, this is a +/- 25 nodes cluster with in total maybe 500 targets (about 50% envoy podmonitor, rest is service-monitor based). There are hardly any jobs; deployments are 99% static.
2. When I triggered "resharding" by scaling to 5 and back to 6, indeed I was observing / following a single target (a specific istio egressgateway pod). Before the resharding and after the resharding it was handled 3 times by different GA instances. They did partly move to different targets, from my notes:

```
Target to search:

url: "http://10.101.9.139:15020/stats/prometheus"
container = "istio-proxy",
instance  = "10.101.9.139:15020",
job       = "istio-egress/envoy-stats-monitor-istio-egress",
namespace = "istio-egress",
pod       = "istio-egressgateway-85fb54967c-gd5gl",
pod_name  = "istio-egressgateway-85fb54967c-gd5gl",

Before scaling:
X 10.101.12.118 => not scraping the target
+ 10.101.22.169 => this one scrapes successfully
+ 10.101.15.72 => also runs the same target ????
X 10.101.2.105 => only other targets
+ 10.101.20.152 => also the same target it seems
X 10.101.7.52 => 

Review 2774
obs doc in component repo + link to from confluence

After scaling:
X 10.101.12.118
? 10.101.22.169
+ 10.101.15.72
X 10.101.20.152
X 10.101.7.52
+ 10.101.2.130
```

As you can see the scaling termintated 2.105 (which didn't run the target) and instance 2.130 was added (that immediately owns the target as well). The questionmark at 22.169 is there because there wasn't a X or + in my notes, so I can't tell for sure.

Question:
Are we sure target ownership is dropped by a GA instance when the next server in the ring becomes another new server? How exactly are the (HTTP/2 based) ring updates synchronized with cluster-update events in the crdManager (who then should reevaluate it's targets?)

Paul

**Comment by paul-bormans** [comment]
A first code review of the cluster changed event doesn't reveal any issue's. crdManager does re-filter the discovered (cached) targets on each Clustering NotifyClusterChange even which actually comes right from ckit (Observer) and ckit only enqueues the callback right after the sharder is updated with the new last known set of peers.

I'm thinking of 2 paths to follow:
1) Search back logging of last week using the "peers changed" log statements to figure out of all instances knew eachother.
2) Add/enable logging in the Lookup to tell which servers (peers) are known/are used; this might reveal state inconsistencies between the sharder state and the wrapping Service (Cluster).

To be continued...

**Comment by paul-bormans** [comment]
I can already answer the first question; yes they did know all 6 instances of the cluster, see attached logs.
[20231211-grafana-agent-duplicate-targets-11-sorted.log](https://github.com/grafana/agent/files/13637972/20231211-grafana-agent-duplicate-targets-11-sorted.log)

**Comment by paul-bormans** [comment]
While running some tests for the second question (to tell which servers are known to the ring at the time of the lookup) I most probably found the issue and it's related to istio (podmonitor) i'm affraid (or actually good news).

Discovery finds 3 targets for a pod because of the istio-proxy container listing 3 ports but due to prometheus.io annotations the __address__ is replaced to the exact same value:

```
    - action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      sourceLabels:
      - __address__
      - __meta_kubernetes_pod_annotation_prometheus_io_port
      targetLabel: __address__
```

For the sharding only the initial address field is used so that explains why they end up on 3 different instances: 

`nonMetaLabelString {__address__=\"10.101.3.11:8443\"}`

Solution for now it to extend the podmonitor to drop non metrics ports.

I'm also thinking to setup a dashboard to easily find duplicate targets; but not sure yet if i manage.

**Comment by captncraig** [comment]
Ah, I wondered if it was something like that, but haven't encountered that with podmonitors yet. Is this podmonitor for a specific deployment, or are you trying to capture a variety of resources across your cluster with it?

With a PodMonitor, I'd always recommend setting the `port` field to the name of the port you want to scrape. That will insert a rule to drop all port names.

**Comment by paul-bormans** [comment]
The podmonitor is the default envoy one: [https://github.com/istio/istio/blob/master/samples/addons/extras/prometheus-operator.yaml#L2](https://github.com/istio/istio/blob/master/samples/addons/extras/prometheus-operator.yaml#L2), and actually for both the istio ingress and egress gateway resources there are multiple ports defined and so you run into this issue.

I would really want to develop a dashboard to detect duplicate targets; but for this I need to have additional metrics with the actual scrape targets (so not the discovered ones), and after the relabeling being applied.

Paul

**Comment by captncraig** [comment]
Yeah, I really don't love that PodMonitor. Anytime you add a rule like that to change the address, you should probably be adding keep or drop rules as well, or you will get duplicates like that. Why does that need to dynamically select ports at all instead of just using a hard coded port name. I assume the istio containers from their chart or whatever are fairly predictable.

**Comment by captncraig** [comment]
Do we agree that this issue is not a problem with Grafana Agent though? I believe you will get the same duplicate targets with Prometheus operator as well.

If you want to talk about detecting duplicates, that is probably a different issue. The scrape targets are availible via debug info, but clustering makes that difficult to take advantage of.

**Comment by paul-bormans** [comment]
@captncraig sorry for only commenting after 2 weeks :-(.

Yes, we agree this isn't a GrafanaAgent issue, this ticket can be closed.

Regarding the detection of duplicates, that is still a problem, the only metrics i could find are target-pools and not individual (active) scrape targets. Maybe these are not even made available through the scrape-manager... (as only in there the address renaming happens...).

It would be a separate ticket anyway.

Paul

**Comment by mattdurham** [comment]
Closing per the comment above.
