### ISSUE TITLE
Expose /probe endpoint of prometheus.exporter.blackbox

### ISSUE THREAD

**Issue by stevensdavid** [grafana/agent#5936]
### Request

I would like to be able to debug `prometheus.exporter.blackbox` failures using the `/probe`-endpoint that is provided by the base Prometheus blackbox exporter, as documented [here](https://github.com/prometheus/blackbox_exporter#checking-the-results).

### Use case

This would help when setting up new synthetic tests, and would also provide information regarding why probes fail when alerts are triggered.

**Comment by marctc** [comment]
Hey @stevensdavid, thanks for reporting. This is already in place: in Flow, you can browse `http://localhost:12345/api/v0/component/prometheus.exporter.blackbox.example/metrics?target=google.com&module=http_2xx`. Is that what are you looking for?

**Comment by stevensdavid** [comment]
Hi @marctc ! You're absolutely correct, everything seems to be exposed there. I wasn't aware of the `/api/v0/` path, thank you for the help!

**Comment by tmarshall98** [comment]
@marctc  Sorry for the necro, is this still possible in the Grafana Agent Operator on Integrations Next?

**Comment by marctc** [comment]
@tmarshall98 yes it is, but paths are different. It should be something like this: http://localhost:12345/integrations/blackbox_exporter/metrics?target=http://grafana.com&module=http_2xx. Please look at the docs for more details
