### ISSUE TITLE
Allow prometheus.exporter.blackbox to provide target name via a string instead of river identifier

### ISSUE THREAD

**Issue by erikbaranowski** [grafana/agent#5940]
### Request

The current implementation of `prometheus.exporter.blackbox` uses the target block label as the target name as documented [here](https://grafana.com/docs/agent/next/flow/reference/components/prometheus.exporter.blackbox/#target-block). For example,

```river
prometheus.exporter.blackbox "example" {
  config_file = "blackbox_modules.yml"

  target "grafana" {
    address = "http://grafana.com"
    module  = "http_2xx"
    labels = {
      "env": "dev",
    }
  }
}
```

Instead, use an argument inside the block for less restrictive naming. For example,

```river
prometheus.exporter.blackbox "example" {
  config_file = "blackbox_modules.yml"

  target {
    name     = "grafana"
    address = "http://grafana.com"
    module  = "http_2xx"
    labels = {
      "env": "dev",
    }
  }
}
```

### Use case

River identifiers are fairly restrictive. https://grafana.com/docs/agent/next/flow/config-language/syntax/#identifiers

This prevents someone from having an otherwise valid target name like `job-name` and is a stumbling block when converting from static mode to flow mode since static mode does not have this restriction.

**Comment by ptodev** [comment]
I am personally happy with this proposal:
* It is more in line with how other blocks work too, such as the [policy block](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.processor.tail_sampling/#policy-block) in the tail sampler.
* It is easier to document than using the block label.
* With a target, the value could come form a component such as `local.file`. I'm not sure if this is possible with labels.

I also agree with @tpaschalis that other components such as `prometheus.exporter.cloudwatch` and `prometheus.exporter.snmp` which use this pattern should be changed to use an argument instead.
