### ISSUE TITLE
[task doc] Installing agent using Ansible

### ISSUE THREAD

**Issue by thampiotr** [grafana/agent#5959]
Use format for [task docs](https://grafana.com/docs/writers-toolkit/structure/topic-types/task/) from writer's toolkit.

**Comment by ishanjainn** [comment]
hey folks, The Ansible doc in cloud docs has flow support -> https://grafana.com/docs/grafana-cloud/developer-resources/infrastructure-as-code/ansible/ansible-grafana-agent-linux/#install-grafana-agent-in-flow-mode-using-ansible

**Comment by thampiotr** [comment]
That looks like a simple-enough instruction. @captncraig do you think we should adopt this approach and wrap this task up?

**Comment by captncraig** [comment]
I'm going to merge this into my existing branch, and make it as streamlined as possible for flow. Running now to make sure it all works and I understand what it is doing.
