### ISSUE TITLE
[task doc] Installing agent using Terraform

### ISSUE THREAD

**Issue by thampiotr** [grafana/agent#5960]
Use format for [task docs](https://grafana.com/docs/writers-toolkit/structure/topic-types/task/) from writer's toolkit.

**Comment by jcreixell** [comment]
I personally think we should close this one, as terraform is typically used to provision cloud resources in combination with a config management tool that installs and configures the software.

@captncraig do you have opinions on this?

**Comment by thampiotr** [comment]
I agree.
