### ISSUE TITLE
OTEL Prometheus  label not working as expected

### ISSUE THREAD

**Issue by fede843** [grafana/agent#5986]
### What's wrong?

I am trying to get some manual defined OTEL resources as metric labels. I am using the brand new resource_to_telemetry_conversion feature.

The problem I cannot figure out, is that I am getting now all the OTEL platform labelling overhead too.

### Steps to reproduce

Spring up a java application. I am testing auto instrumentation, with the OTEL java jar agent, v1.32.0.
Once I  enable resource_to_telemetry_conversion I get this kind of labeling:

`jvm_gc_memory_allocated_bytes_total{container_id="839a3d228ef223b3fb1efd8ae5415018cc862c03dce28891ade8f8d0f93b91f3", datacenter="datacenter", env="prod", host_arch="amd64", host_name="bahia-local.domain.com", instance="bahia", job="eureka", os_description="Linux 6.5.8-1-default", os_type="linux", process_command_line="blahblah", process_executable_path="/layers/paketo-buildpacks_bellsoft-liberica/jre/bin/java", process_pid="1", process_runtime_description="BellSoft OpenJDK 64-Bit Server VM 25.372-b07", process_runtime_name="OpenJDK Runtime Environment", process_runtime_version="1.8.0_372-b07", service_name="eureka", telemetry_auto_version="1.32.0", telemetry_sdk_language="java", telemetry_sdk_name="opentelemetry", telemetry_sdk_version="1.32.0", key1="val1", key2="val2"}
`

before I was getting:

`jvm_gc_memory_allocated_bytes_total{datacenter="datacenter", env="prod", instance="bahia", job="eureka"}
`

What I want is:

`jvm_gc_memory_allocated_bytes_total{datacenter="datacenter", env="prod", instance="bahia", job="eureka", key1="val1", key2="val2"}
`

Am I missing something? I have played with all the include_* params from otelcol.exporter.prometheus but they seem to do nothing to help.

### System information

Docker 24.0.6-ce

### Software version

grafana/agent:main-bb1d64d

### Configuration

```text
river file

otelcol.exporter.prometheus "default" {
        forward_to           = [prometheus.remote_write.default.receiver]
        include_target_info  = false
        include_scope_info   = false
        include_scope_labels = false
        add_metric_suffixes  = true
        resource_to_telemetry_conversion = true
}

docker compose

  grafana-agent:
    image: grafana/agent:main-bb1d64d
    container_name: grafana-agent
    restart: always
    labels:
      observability_metrics_enabled: true
      observability_metrics_port: 12345
    environment:
      AGENT_MODE: flow
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--disable-reporting=true",
      "--storage.path=/data",
      "/rivers",
    ]
    volumes:
      - ./traces/agent:/rivers:ro
      - ./traces/data:/data
      - /var/log:/var/log/observability:ro # Host syslog
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "12345:12345"
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    hostname: grafana-agent
    networks:
      - mainnet

java related config

      -javaagent:/java-agents/opentelemetry-javaagent.jar
      -Dotel.exporter.otlp.endpoint=http://grafana-agent:4317
      -Dotel.service.name=api-gateway
      -Dotel.resource.attributes=key1='val1,key2=val2'
      -Dotel.traces.exporter=none
      -Dotel.metrics.exporter=otlp
      -Dotel.logs.exporter=none
```

**Comment by ptodev** [comment]
Hi! 👋  `resource_to_telemetry_conversion` will convert all resource attributes to labels, regardless of what the attributes are called. The ones that you want to exclude seem to be part of OTel's semantic conventions:
https://opentelemetry.io/docs/specs/semconv/resource/process/
https://opentelemetry.io/docs/specs/semconv/resource/

In order to copy only some attributes, you need to use a transform processor prior to `otelcol.exporter.prometheus`. Something like this:
```
otelcol.processor.transform "default" {
  error_mode = "ignore"

  metric_statements {
    context = "datapoint"

    statements = [
      `set(attributes["key1"], resource.attributes["key1"])`,
      `set(attributes["key2"], resource.attributes["key2"])`,
    ]
  }

  output {
    metrics = [otelcol.exporter.prometheus.default.input]
  }
}
```

I can see why this is confusing, so I'll update our documentation to clarify this. Most people probably want to use `otelcol.processor.transform` instead of `resource_to_telemetry_conversion`.

**Comment by fede843** [comment]
Sorry for the delay.
Beautiful. That did exactly what I was looking for.

This applies fine for my usage, but it adds a static component. You need beforehand those resource attributes in order to configure the transform block. That might be not suitable for all cases.

Thanks @ptodev !!

**Comment by fede843** [comment]
Not sure if you have updated already the docs. Will let the closing to you.
