### ISSUE TITLE
agent does not detect a failure to download the configuration

### ISSUE THREAD

**Issue by simonc6372** [grafana/agent#599]
When the Grafana cloud agent is installed via the https://raw.githubusercontent.com/grafana/agent/release/production/grafanacloud-install.sh script, there is no checking to make sure the configuration downloaded successfully in `retrieve_config` 

In some circumstances the download can fail, (such as running on non a shell where variable substation does not work in the same way), but this is not detected, and the user sees an ugly error. 

```--- Retrieving config and placing in /etc/grafana-agent.yaml
could not retrieve agent cloud config: failed to make request: Get "https://integrations-api.grafana.net/stacks/xxxxxx/agent_config": context deadline exceeded
Failed to retrieve config
--- Enabling and starting grafana-agent.service
```

**Comment by rfratto** [comment]
@rlankfo Can you take a look at this?
