### ISSUE TITLE
Grafana agent as Proxy not forwarding old data received from Grafana clients after a downtime to remote system

### ISSUE THREAD

**Issue by sakthiraam** [grafana/agent#6007]
### What's wrong?

We are using the prometheus.receive_http component  to receive telemetry data from fleet of grafana agents and then from the receive_http component we are remote writing it to our Prometheus setup we have today. 

As part of our system integration test we stopped the grafana agent which has the receive_http component and started it after 10 minutes. 

We started seeing log message like below. “Skipping resharding, last successful send was beyond threshold”. 

There is no blockage on getting the new data but only if we restart the agent the log lines stop printing but we had the data loss for that 10 min. 

We are using default values for the remote_write parameters.

Grafana Agent —> Grafana Agent (Proxy) —> Prometheus

Slack discussion Link - https://grafana.slack.com/archives/C01050C3D8F/p1702459830770639?thread_ts=1701912166.242259&cid=C01050C3D8F

### Steps to reproduce

1) Configure a Grafana client with prometheus.receive_http component  (referred as Grafana Proxy) and a exporter component to either Prometheus or Mimir

2) Configure a Grafana client with Node exporter pushing the metrics to the Grafana proxy

3) Stop the Grafana Proxy for sometime and start it.

4) On the destination system Prometheus or Mimir you will only see the new data and the data that was collected by the Grafana client when the Grafana Proxy was done are lost.

### System information

RHEL 8.x

### Software version

v0.37.2

**Comment by mattdurham** [comment]
This is expected behavior. The underlying prometheus code does not resend the samples in the wal when the agent restarts. This is similar to prometheus https://github.com/prometheus/prometheus/issues/13185

**Comment by mattdurham** [comment]
Going to re-open since there might be other reasons.

Does any of this go through a load balancer or other network device where the proxy IP will change?

**Comment by mattdurham** [comment]
Second deep dive, and the Agent will not replay the any records older than its start time. This means that proxying wont replay like expectation.

**Comment by sakthiraam** [comment]
Hi @mattdurham , Thanks for your analysis. Just quoting my initial comment here for better understanding. Below is the flow.

Grafana Agent (Client) —> Grafana Agent (Proxy) —> Prometheus

We have this wall replay issue only when Grafana Agent (Proxy) is down. Once the Grafana Agent (Proxy) is comes up the Grafana Agent (Client) is able to replay all the data in the WAL to Grafana Agent (Proxy) but the Proxy is not able to remote write it to Prometheus.

So are you saying when the Grafana Agent (Proxy) for any reason it goes down there will be data loss ?

We already implemented a reverse proxy solution and we tested by bringing down Prometheus for couple of hours and backfilling happened with no issues as the proxy is just relaying the HTTP 5xx error to Grafana Agent Client.

We will go with this approach. Thanks again for your analysis. Good day ahead!

**Comment by mattdurham** [comment]
Yes, the agent wal will reject any samples that are older than the start time of the agent. In the above case once the proxy is down only data with timestamps after it came back up will filter through. There are some issues to better handle this upstream with prometheus.
