### ISSUE TITLE
Please make Prometheus-Operator CRDs OPTIONAL to be able to have them deployed alongside during migration

### ISSUE THREAD

**Issue by hajdukda** [grafana/agent#6017]
### Request

From what I could check in helm chart itself, the CRDS are deployed always.
Which make it really difficult to migrate from one operator to another as version drift can cause a big issue (keeping them in sync), big overhead that is not rly needed.

The idea is to make prometheus-crds optional like in `k8s-monitoring` chart.

### Use case

This would be extremely useful during migration from one operator to another.
Im also open to other ideas.

**Comment by captncraig** [comment]
There is already a value for this in our [helm chart](https://github.com/grafana/agent/blob/main/operations/helm/charts/grafana-agent/values.yaml#L21):

```
crds:
  # -- Whether to install CRDs for monitoring.
  create: true
```

Set that to false and it will skip those.

**Comment by hajdukda** [comment]
Tho this one wont install "all" crds. Not only Prometheus but also Grafana ones :(
