### ISSUE TITLE
Tempo: Add a flat downsampling processor

### ISSUE THREAD

**Issue by joe-elliott** [grafana/agent#603]
Now that we have metrics generation in our agents it is quite possible that someone may want to send traces to the agent to generate metrics but then drop them before sending them to Grafana Cloud. This feature would let a user generate metrics on a very large number of traces before dropping them.

https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/probabilisticsamplerprocessor

cc @mapno

**Comment by mapno** [comment]
We can use the new probabilistic policy in the tail sampling processor https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3876
