### ISSUE TITLE
Feature parity - requesting config reload API on Grafana Agent to match with Prometheus reload API 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/agent#610]
It would be nice to have the config reload API on Grafana Agent match with Prometheus reload API, for ease of use / operability 
 
Grafana Agent:
`GET /-/reload` 

Prometheus:
`PUT  /-/reload`
`POST /-/reload`

**Comment by rfratto** [comment]
👍 we can add support for `POST`. This would be a small and easy PR, so contributions welcome from anyone that's reading this!

**Comment by tharun208** [comment]
@rfratto i like to work on this
