### ISSUE TITLE
Grafana Agent is display "404 page not found"

### ISSUE THREAD

**Issue by mohdsyahiran** [grafana/agent#6108]
<img width="281" alt="image" src="https://github.com/grafana/agent/assets/79651001/661431bb-7743-4cc2-b27c-07b354e1a4da">
<br><br>
<img width="365" alt="image" src="https://github.com/grafana/agent/assets/79651001/38bbf558-60e4-4076-a9d3-faa59f6af762">

Anybody know why this are happen? I include the configuration file that I do. I'm using Grafana Agent + Grafana Loki
[grafana.zip](https://github.com/grafana/agent/files/13898067/grafana.zip)

**Comment by tpaschalis** [comment]
I'm renaming the issue since reading the attached manifest it looks like you're working with static mode.

Also, as pointed out, the endpoint to use is `/-/config` instead so I'm closing this issue.
