### ISSUE TITLE
otelcol.receiver.otlp http endpoint not working properly.

### ISSUE THREAD

**Issue by hcshy** [grafana/agent#6166]
### What's wrong?

When starting Grafana Agent on kubernetes with the otelcol.receiver.otlp component no endpoint is shown to be listening on the running pods. 

I'm not sure if there is any extra configuration needed in the basic values.yaml or in the river file.

### Steps to reproduce

1. Helm install the agent with values.yaml and the agent.river file (in this case upgrade).

![image](https://github.com/grafana/agent/assets/127315762/4904df90-bad0-479a-b811-6adb352f3d41)

2. Try to make a post request to the otelcol.receiver.otlp endpoint.

![image](https://github.com/grafana/agent/assets/127315762/cc0bbc0a-6cc9-471a-818b-380503b0b844)

4. Check the debug http page and logs of the Grafana Agent.

![image](https://github.com/grafana/agent/assets/127315762/27be19c4-c395-4ea6-acf9-db636ad0f9e5)

logs:
![image](https://github.com/grafana/agent/assets/127315762/9e95383e-39d4-4415-b98c-17403babea6c)

### System information

Kubernetes

### Software version

Grafana Agent v0.39.0

### Configuration

```text
otelcol.receiver.otlp "example" {
  http {
    endpoint = "0.0.0.0:4318"
  }

  output {
    metrics = [otelcol.processor.batch.example.input]
    logs    = [otelcol.processor.batch.example.input]
    traces  = [otelcol.processor.batch.example.input]
  }
}

otelcol.processor.batch "example" {
  output {
    metrics = [otelcol.exporter.otlp.default.input]
    logs    = [otelcol.exporter.otlp.default.input]
    traces  = [otelcol.exporter.otlp.default.input]
  }
}

otelcol.exporter.otlp "default" {
  client {
    endpoint = "tempo-prod-08-prod-eu-west-3.grafana.net:443"
    auth = otelcol.auth.basic.grafana_cloud_tempo.handler
  }
}

otelcol.auth.basic "grafana_cloud_tempo" {
username = "removed"
password = env("removed")
}
```

**Comment by mattdurham** [comment]
Did you expose the port in your chart via `extraPorts`?

**Comment by hcshy** [comment]
> Did you expose the port in your chart via `extraPorts`?

Thanks for the quick reply! Yes I did expose the ports. I think the endpoint is actually reachable as sending POST requests result in a 200 status code. Not sure why it does not show on logs and gives "partial success" back in response.

**Comment by mattdurham** [comment]
Is the issue that your not seeing signals flow through?

**Comment by hcshy** [comment]
The current issue is there is no way to see what's going on with the posted json data. At this moment nothing shows up on Tempo on Grafana Cloud.

**Comment by clementduveau** [comment]
@mattdurham I can confirm they are not receiving traces in their Grafana Cloud Traces backend. My main concern is why the OTEL endpoint doesn't appear in the Agent UI while it's effectively present in their YAML ?

**Comment by mattdurham** [comment]
We don't display default arguments in the UI and `0.0.0.0:4318` is equivalent to the default. Many of our pages become overwhelming if we display all the default fields.

**Comment by hcshy** [comment]
The reason for the partial success response on the POST request has to do with the json payload as described in:

> > Did you expose the port in your chart via `extraPorts`?
> 
> Thanks for the quick reply! Yes I did expose the ports. I think the endpoint is actually reachable as sending POST requests result in a 200 status code. Not sure why it does not show on logs and gives "partial success" back in response.
> 
> For example a Grafana Agent on Ubuntu writes logs which at least lets me know the http server starts:
> 
> ![image](https://private-user-images.githubusercontent.com/127315762/297099246-f58852fd-881e-4792-839f-c43604ee76c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MjczMTIsIm5iZiI6MTcwNTQyNzAxMiwicGF0aCI6Ii8xMjczMTU3NjIvMjk3MDk5MjQ2LWY1ODg1MmZkLTg4MWUtNDc5Mi04MzlmLWM0MzYwNGVlNzZjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxNzQzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTBkYzIyZmMyZmNlZDQyZTFjMmEyN2E2MzA0ZTViYjhjZTM1ZTIzYWE2ZWIwZjJjZGRjOWE1ODRmNDJlNGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AOD5rzCiuXfe6yW4_Bdojxuu3fIP2qG2i5pJAWzrl-E)
> 
> Posting a test trace to the receiver on the linux machine also results in a "partial success". Maybe this "partial success" has something to do with the data of the test trace JSON?
> 
> [EDIT]
> 
> So based on the following documentation of open-telemetry:
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/ac639af144fbb3875af921d5ba30ad04417564de/specification/protocol/otlp.md#full-success
> 
> ![image](https://private-user-images.githubusercontent.com/127315762/297103474-3c6020a9-13d7-4eff-8004-3d7467bda3df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MjczMTIsIm5iZiI6MTcwNTQyNzAxMiwicGF0aCI6Ii8xMjczMTU3NjIvMjk3MTAzNDc0LTNjNjAyMGE5LTEzZDctNGVmZi04MDA0LTNkNzQ2N2JkYTNkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxNzQzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2FiOGMwMmFiNWRlYzAxNWQzOGVjYzhlNzRmMTljYTlkNjcxZTVkOGY1OWY5NjZjZGQwMTQ3MTUxNDNiMDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YQCLxVbV9eQ5LPpLR9m3oJm5Pro_CNPpOTkb7SYjsr0)
> 
> The receiver endpoint is at least available since POST requests result in the partial success status.

By enabling de logging block in the river file I can now see some logs on debug level which point me to a failure of the exporter and authentication block:

![image](https://github.com/grafana/agent/assets/127315762/b121682e-a7bc-4220-881c-1d80a2d32c31)

I've tried a few sources and methods / refreshed the API keys with no success!

https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.exporter.otlp/#send-data-to-a-managed-service

https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.auth.basic/

`otelcol.receiver.otlp "example" {
   http {
    endpoint = "0.0.0.0:4318"
  }

  output {
    metrics = [otelcol.processor.batch.example.input]
    logs    = [otelcol.processor.batch.example.input]
    traces  = [otelcol.processor.batch.example.input]
  }
}

otelcol.processor.batch "example" {
  output {
    metrics = [otelcol.exporter.otlp.default.input]
    logs    = [otelcol.exporter.otlp.default.input]
    traces  = [otelcol.exporter.otlp.default.input]
  }
}

otelcol.exporter.otlp "default" {
  client {
    endpoint = "tempo-prod-08-prod-eu-west-3.grafana.net:443"
    auth = otelcol.auth.basic.tempo.handler
  }
}

otelcol.auth.basic "tempo" {
username = "removed"
password = env("removed")
}

logging {
  level  = "debug"
  format = "logfmt"
}
`

**Comment by clementduveau** [comment]
No bug but docs need updates.

https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.exporter.otlp/#send-data-to-a-managed-service shows an endpoint like `https://tempo-xxx.grafana.net/tempo` but a correct value would be `tempo-prod-08-prod-eu-west-3.grafana.net:443` (no protocol, add the port)

**Comment by mattdurham** [comment]
Good catch, will get that changed up.
