### ISSUE TITLE
401 Error otelcol.exporter.otlp

### ISSUE THREAD

**Issue by hcshy** [grafana/agent#6173]
### What's wrong?

The otelcol.exporter.otlp component is returning a 401 error when trying to send a trace to Grafana Cloud using basic authentication (otelcol.auth.basic). 

### Steps to reproduce

1. Create a new Cloud Access Policy with all rights to test (Read, Write and Delete).
2. Helm install Grafana Agent using the default values.yaml and extra ports 4318 for the otelcol.receiver.otlp component. 
3. Curl a POST request to send a trace from a different pod to the host:4318 endpoint.
4. Kubectl log grafana-agent for logs.

### System information

Kubernetes

### Software version

Grafana Agent v0.39.0

### Configuration

```text
otelcol.receiver.otlp "example" {
   http {
    endpoint = "0.0.0.0:4318"
  }

  output {
    metrics = [otelcol.processor.batch.example.input]
    logs    = [otelcol.processor.batch.example.input]
    traces  = [otelcol.processor.batch.example.input]
  }
}

otelcol.processor.batch "example" {
  output {
    metrics = [otelcol.exporter.otlp.default.input]
    logs    = [otelcol.exporter.otlp.default.input]
    traces  = [otelcol.exporter.otlp.default.input]
  }
}

otelcol.exporter.otlp "default" {
  client {
    endpoint = "tempo-prod-08-prod-eu-west-3.grafana.net:443"
    auth = otelcol.auth.basic.tempo.handler
  }
}

otelcol.auth.basic "tempo" {
username = "717821"
password = env("removed")
}

logging {
  level  = "debug"
  format = "logfmt"
}
```

### Logs

```text
ts=2024-01-17T09:36:43.903728276Z level=error msg="Exporting failed. The error is not retryable. Dropping data." component=otelcol.exporter.otlp.default error="Permanent error: rpc error: code = Unauthenticated desc = unexpected HTTP status code received from server: 401 (Unauthorized); transport: received unexpected content-type \"application/json\"" dropped_items=1
```

**Comment by hcshy** [comment]
Solution:

in the "otelcol.auth.basic" block 

```
otelcol.auth.basic "tempo" {
username = "717821"
password = env("removed")
}
```

instead of using:
`password = env("API_TOKEN")`

use:
`password = "API_TOKEN"`

**Comment by clementduveau** [comment]
Debugged. It was a River env expansion problem on the user end. We can close this.
