### ISSUE TITLE
Investigate running as Local Service/Network Service and shifting to start type: Delayed Automatic

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#621]
Currently, Grafana Agent runs as Local System, which is administrator-level rights. This is not the preferred path if it can be helped. It is possible that windows_exporter will require but need to test what rights windows_exporter requires.

Also, Automatic Delayed Start is preferable, over automatic.

**Comment by rfratto** [comment]
Reopening. Can you prioritize this so it gets fized?
