### ISSUE TITLE
Agent Ignorig  data - CPU and Network

### ISSUE THREAD

**Issue by SanthoshKumar18245** [grafana/agent#6237]
### Discussed in https://github.com/grafana/agent/discussions/6228

<div type='discussions-op-text'>

<sup>Originally posted by **SanthoshKumar18245** January 24, 2024</sup>
i am configuring the grafana agent to scrape the metrics which is prometheus node_exporter can do... but i am getting some Errors

my config file,,,

server:
  log_level: debug

metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 60s
    remote_write:
      - url: http://127.0.0.1:9009/api/v1/push
        headers:
          X-Scope-OrgID: monitoring
integrations:
  node_exporter:
    enabled: true
    rootfs_path: /root
    sysfs_path: /sys
    procfs_path: /proc
    udev_data_path: /run/udev/data
    enable_collectors:
      - cpu
      - diskstats
      - filesystem
      - loadavg
      - netdev

<img width="936" alt="image" src="https://github.com/grafana/agent/assets/133011171/686a9a18-fe04-4409-89f4-190a7b2d8320">

</div>

**Comment by tpaschalis** [comment]
You can look at the default values for the node_exporter integrations configuration: https://grafana.com/docs/agent/latest/static/configuration/integrations/node-exporter-config/

All volumes that match the `filesystem_mount_points_exclude` or `filesystem_fs_types_exclude` will be excluded; this is expected and the debug-level logs are there just to show what's being used and what not. You can use the relevant YAML fields to fine-tune what is being monitored.

This shouldn't affect anything else around the agent or the node_exporter integration though.

**Comment by SanthoshKumar18245** [comment]
@tpaschalis  i have used the yaml file in the documentation but i can't able to monitor the cpu and network related metrics like the prometheus node_exporter does .. i added the collectors for collecting the metrics but it shows some are not present and ignoring ..idk the agent suppose to do like the exporters right ?

can you give me the configuration file for collecting the metrics .. because the documentation is not for beginners.. i can't understand most of them 

server:
log_level: debug

metrics:
   wal_directory: /tmp/agent
   global:
      scrape_interval: 60s
   remote_write:
      - url: http://127.0.0.1:9009/api/v1/push
       headers:
           X-Scope-OrgID: monitoring
integrations:
  node_exporter:
    enabled: true
    rootfs_path: /root
    sysfs_path: /sys
    procfs_path: /proc
    udev_data_path: /run/udev/data
    
    
  add anything if necessary and thank you for your biggest help and response....

**Comment by tpaschalis** [comment]
Configuration looks OK to me. For some metrics, you may have to run the agent with elevated privileges to be fetched properly.

Since the original report doesn't seem to be a bug with the node_exporter integration producing errors, but rather configuration around which mounts to expose data for, I'm closing this issue.
