### ISSUE TITLE
AWS SigV4 failed because signature failed.

### ISSUE THREAD

**Issue by Nebulazhang** [grafana/agent#6264]
### What's wrong?

When I use AWS Managed Prometheus, chart version 0.31.1, the sigv4 failed because 
``
{"ts":"2024-01-29T03:12:20.177146993Z","level":"error","msg":"non-recoverable error","component":"prometheus.remote_write.default","subcomponent":"rw","remote_name":"b6d5a7","url":"https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/ws-xxxxxxx-/api/v1/remote_write","count":1057,"exemplarCount":0,"err":"server returned HTTP status 403 Forbidden: {\"message\":\"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\\n\\nThe Canonical String for this request should have been\\n'POST\\n/workspaces/ws-aaa67b6a-7507-4936-ba88-ada6bb028476/api/v1/remote_write\\n\\ncontent-encoding:snappy\\ncontent-type:application/x-protobuf\\nhost:aps-workspaces.ap-southeast-1.amazonaws.com\\nx-agent-id:\\nx-amz-date:20240129T031220Z\\nx-amz-security-token:my-token"}
``

### Steps to reproduce

Using the grafana-agent chart version 0.31.1
AWS Prometheus and creating a role/policy
Using ServiceAccount and adding the annotation: `eks.amazonaws.com/role-arn` on the ServiceAccount

### Configuration

```text
prometheus.remote_write "default" {
	endpoint {
		url = "https://aps-workspaces.${AWS_REGION}.amazonaws.com/workspaces/${WORKSPACE_ID}/api/v1/remote_write"

		sigv4 {
			region = "${AWS_REGION}"
		}
	}
}
```

### Logs

```text
{"ts":"2024-01-29T03:12:20.177146993Z","level":"error","msg":"non-recoverable error","component":"prometheus.remote_write.default","subcomponent":"rw","remote_name":"b6d5a7","url":"https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/ws-xxxxxxx-/api/v1/remote_write","count":1057,"exemplarCount":0,"err":"server returned HTTP status 403 Forbidden: {\"message\":\"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\\n\\nThe Canonical String for this request should have been\\n'POST\\n/workspaces/ws-aaa67b6a-7507-4936-ba88-ada6bb028476/api/v1/remote_write\\n\\ncontent-encoding:snappy\\ncontent-type:application/x-protobuf\\nhost:aps-workspaces.ap-southeast-1.amazonaws.com\\nx-agent-id:\\nx-amz-date:20240129T031220Z\\nx-amz-security-token:my-token"}
```

**Comment by Nebulazhang** [comment]
As @wjf3121 mentioned, this issue maybe because this PR (https://github.com/grafana/agent/pull/5774)

**Comment by Nebulazhang** [comment]
Related PR: https://github.com/grafana/agent/pull/5999

Image: main-1cbeff4, works
Image: main-b1dd499. **NOT** work

**Comment by Nebulazhang** [comment]
@captncraig Hi, captncraig, can you help me?

**Comment by captncraig** [comment]
Interesting. If that bisect is correct, it means they are being pretty picky about headers sent from the agent. Looking into it.

**Comment by captncraig** [comment]
Yes, I believe this is an issue with the prometheus write client code. Custom headers are injected after the signature is calculated from the other request data. 

https://github.com/prometheus/prometheus/blob/main/storage/remote/client.go#L158.

Will discuss ways to mitigate tomorrow.

**Comment by captncraig** [comment]
@Nebulazhang Are you able to test `main-62530fb`? If that works for you, I can publish a patch release tomorrow.

**Comment by wjf3121** [comment]
Hi @captncraig , thank you so much for promptly addressing the issue. I can confirm `main-62530fb` works without this issue anymore.
