### ISSUE TITLE
500 error from cloud-config with no further information

### ISSUE THREAD

**Issue by bigpresh** [grafana/agent#629]
I have used the install script to install the Grafana Cloud Agent, but the config file /etc/grafana-agent.yaml is empty.

Looking at the script, I see that it fetches the config by calling `grafana-agentctl cloud-config` so I'm trying to do the same.

I'm running:

`grafana-agentctl cloud-config -u 'xxx' -p 'xxxx'`

It exits with only:

`could not retrieve agent cloud config: unexpected status code 500`

I don't think it's a problem with the credentials being supplied, as if I e.g. change the API key being passed as the `-p` argument, I then get a 401 error.

The lack of additional detail in the response is somewhat related to #360 - it's possible that there's something in the response which would tell me what was wrong, but the response I get from cloud-config gives me nothing to go on.

**Comment by rfratto** [comment]
Hi there! We try to keep this repository focused on open source issues rather than anything related to Grafana Cloud specifically. Could you create a support ticket so they can assist you further?

**Comment by bigpresh** [comment]
Well, my point was more that the tool could report the error more helpfully, which does sound like a useful improvement to me; the actual problem causing the 500 error would be something to talk to support about, indeed.
