### ISSUE TITLE
Solidify component names and lifecycle

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#6307]
Given the accepted and published [RFC #008](https://github.com/grafana/agent/blob/main/docs/rfcs/0008-backwards-compatibility.md) around backwards compatibility in Grafana Agent, we should solidify our around component names and deprecations. As we're paving the road for a v1.0 release and since no breaking changes will be made for at least a year:

* Do we want to rename any existing components?
* Do we want to set up any conventions around future component naming?
* Do we want to deprecate any stable functionality/components? (eg. prometheus.exporter.vsphere since otelcol.receiver.vcenter _also_ exists)

**Comment by mattdurham** [comment]
Since we have an easy way to alias components this should not be a blocker and we have removed prometheus.exporter.vsphere. We also agreed to review naming/how long aliases need to stick around when we get closer to v2.
