### ISSUE TITLE
Graduate clustering to stable

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#6309]
As we're gearing up for a v1.0 release, we should graduate clustering to a Stable feature.

We've been extensively and successfully dogfooding clustering during these past six months with X00M active metrics series workloads.

To mark the feature as Stable, we should:
```[tasklist]
### Tasks
- [x] Polish meta-monitoring and alerting from our recent experience running clustering within Grafana https://github.com/grafana/agent/issues/4991
- [x] Bring the maintainers team up to speed on this feature
```

**Comment by roobalimsab** [comment]
Hi,

I see that clustering is available for GA. Can we close this?
