### ISSUE TITLE
Document a migration path from Static mode to Flow for loki.source.file

### ISSUE THREAD

**Issue by ptodev** [grafana/agent#6323]
### Request

Similarly to Static mode, [loki.source.file](https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.file/) uses a "positions file" which tells it the latest logs that it ingested from a given file. This is useful in case of Agent restart, so that the Agent doesn't re-send all the logs from the log file to the database. Instead, the Agent can just resume where it left off before the restart.

Ideally, users should be able to stop their "static" agent and then start a new "flow" agent with an identical Flow config. However, this is not possible at the moment:
1. The location of the position file in Flow is not very configurable. It is not possible to easily point Flow to the Static mode's position file (unless a symlink is used, or unless Static mode points to the Agent Flow data directory)
1. The format of Flow's position file is not the same as Static mode's. Even if we add a feature to configure a custom path for a position file, Flow wouldn't be able to read a Static mode position file.

@tpaschalis suggested several workarounds:
* Use the `tail_from_end` argument.
* In case the logs have structured timestamps, use` loki.process` to drop logs older than X hours/days

Instead of stopping the static agent, it might be preferable to run both static and flow mode in parallel?
@tpaschalis suggested sending identical logs to Loki and letting Loki deduplicate them.
We need to clarify if this will work for all types of logs?

Alternatively, can we make it possible for Static mode to emit a 2nd positions file which is Flow compatible? Then a Flow agent could reuse it?

### Use case

Making migrating to Flow easier.

**Comment by ptodev** [comment]
`loki.source.kubernetes_events` also uses a positions file. I am not sure if there is a need for it to go in scope for this migration path doc as well.

**Comment by JStickler** [comment]
Maybe I'm missing something obvious, but I don't see any **_documentation_** for how users can migrate from static to flow mode provided in PR #6812.  I think this issue should still be open.

**Comment by mattdurham** [comment]
Using the legacy_positions_file which is automatically set if using the config converter.

**Comment by JStickler** [comment]
@mattdurham  Thanks, I was following this issue assuming it would result in a new doc topic.  But the topic for using the converter has already been written.  I think I found the topic I need to link to.  Closing again!  Sorry for the back and forth.

**Comment by mattdurham** [comment]
No worries, I should have linked the other issues so it would have been clearer.
