### ISSUE TITLE
Grafana Agent on Windows don't send part of  logs

### ISSUE THREAD

**Issue by PsySuck** [grafana/agent#6344]
### What's wrong?

Agent works on domain controllers and parse a lot of events in security logs.
For example: 
Filter for logs
<img width="544" alt="Screenshot 2024-02-09 at 15 11 26" src="https://github.com/grafana/agent/assets/87027160/534188d6-a0c1-4f99-9c7e-97beefdfb3df">
Result in event viewer
<img width="640" alt="Screenshot 2024-02-09 at 15 10 37" src="https://github.com/grafana/agent/assets/87027160/3b392576-d749-476c-b349-7d4289717316">
Result in loki
<img width="1726" alt="Screenshot 2024-02-09 at 15 15 41" src="https://github.com/grafana/agent/assets/87027160/74db044f-a53f-4415-bc38-de64bcdc614c">

I don't see any error.

### Steps to reproduce

Install agent to domain controllers.
Enable various audit event.
Run Agent.

### System information

Windows server 2019

### Software version

agent, version v0.39.2 (branch: HEAD, revision: deae3f86)

### Configuration

```text
########################################################
      - job_name: ad
        windows_events:
          bookmark_path: "C:\\Program Files\\Grafana Agent\\bookmarks\\ad_bookmark.xml"
          use_incoming_timestamp: true
          eventlog_name: "Security"
          # Filter for logs
          xpath_query: '*'
          poll_interval: 1s
        
        relabel_configs:
          - source_labels: ['channel']
            target_label: 'log_type'
            
        pipeline_stages:
          - template:
              source: computer
              template: '{{ ToLower .Value }}'
              
          - regex:
              source: computer
              expression: "^(?P<hostname>\\S+?)\\."

          - template:
              source: hostname
              template: '{{ ToLower .Value }}'
          
          - template:
              source: log_type
              template: '{{ ToLower .Value }}'
      
          - json:
              expressions:
                event_id:
                event_data:
                
          - template:
              source: filter
              template: 'notfiltered'
              
          - labels:
              event_id:
              hostname:
              log_type:

          - match:
              selector: '{event_id = "4625"}'
              stages:
              - regex:
                  source: event_data
                  expression: "Name='SubjectUserName'>(?P<subjectusername>.+?)<.+Name='TargetUserName'>(?P<targetusername>.+?)<.+Name='FailureReason'>(?P<failurereason>.+?)<.+Name='LogonType'>(?P<logontype>.+?)<.+Name='WorkstationName'>(?P<workstationname>.+?)<.+Name='IpAddress'>(?P<ipaddress>.+?)<.+" 
              - regex:
                  source:
                  expression: "Failure Reason:....(?P<failurereasontext>.+?)\\."
              
              - template:
                  source: filter
                  template: 'filtered'
              

                  
              - pack:
                  labels:
                    - subjectusername
                    - targetusername
                    - failurereason
                    - logontype
                    - workstationname
                    - ipaddress
                    - failurereasontext
                    
              - template:
                  source: service
                  template: 'ad'
                    
              - labels:
                  service:     

          - match:
              selector: '{event_id = "4624"}'
              stages:
              - regex:
                  source: event_data
                  expression: "Name='SubjectUserName'>(?P<subjectusername>.+?)<.+Name='TargetUserName'>(?P<targetusername>.+?)<.+Name='LogonType'>(?P<logontype>.+?)<.+Name='WorkstationName'>(?P<workstationname>.+?)<.+Name='IpAddress'>(?P<ipaddress>.+?)<.+"
              
              - template:
                  source: filter
                  template: 'filtered'
                  
              - labels:
                  service: ad
                  
              - pack:
                  labels:
                    - subjectusername
                    - targetusername
                    - logontype
                    - workstationname
                    - ipaddress
                    
              - template:
                  source: service
                  template: 'ad'
                    
              - labels:
                  service:
            
          - match:
              selector: '{event_id = "4740"}'
              stages:
              - regex:
                  source: event_data
                  expression: "Name='TargetUserName'>(?P<targetusername>.+?)<.+Name='TargetDomainName'>(?P<targetdomainname>.+?)<"
              
              - template:
                  source: filter
                  template: 'filtered'
              
                  
              - pack:
                  labels:
                    - targetusername
                    - targetdomainname
                    
              - template:
                  source: service
                  template: 'ad'
                    
              - labels:
                  service:
          #NPS          
          - match:
              selector: '{event_id =~ "627(2|3)"}'
              stages:
              - regex:
                  source: event_data
                  expression: "Name='SubjectUserName'>(?P<subjectusername>.+?)<.+Name='CallingStationID'>(?P<callingstationid>.+?)<.+Name='ClientIPAddress'>(?P<clientipaddress>.+?)<.+Name='NetworkPolicyName'>(?P<networkpolicyname>.+?)<"
            
              - regex:
                  source: event_data
                  expression: "Name='ClientName'>(?P<clientname>.+?)<.+"
              - match:
                  selector: '{event_id ="6272"}'
                  stages:
                  - template:
                      source: status
                      template: 'Network Policy Server granted access to a user'
                
              - match:
                  selector: '{event_id="6273"}'
                  stages:
                  - regex:
                      source: event_data
                      expression: "Name='Reason'>(?P<reason>.+?)<"
              
                  - template:
                      source: status
                      template: 'Network Policy Server denied access to a user'
                  
              - template:
                  source: filter
                  template: 'filtered'
                  

                    
              - pack:
                  labels:
                    - event_id
                    - clientipaddress
                    - networkpolicyname
                    - subjectusername
                    - callingstationid
                    - clientname
                    - clientipaddress
                    - reason
                    - status
                    
              - template:
                  source: service
                  template: 'nps'
                    
              - labels:
                  service:
                    
          #kerberos
          - match:
              selector: '{event_id =~ "47(68|69|70|71|72|73)"}'
              stages:
              - template:
                  source: filter
                  template: 'filtered'
              
              - pack:
                  labels:
                    - event_id
                    
              - template:
                  source: service
                  template: 'kerberos'
                    
              - labels:
                  service:
           
          
          
          - labels:
              filter:
          #other logs to ad service    
          - match:
              selector: '{filter = "notfiltered"}'
              stages:
              - template:
                  source: service
                  template: 'ad'
                    
              - labels:
                  service:
           
          - labelallow:
              - event_id
              - service
              - log_type
              - hostname
########################################################
```

**Comment by ptodev** [comment]
Hello, thank you for submitting a bug report! Did the Agent run successfully with this configuration on the domain controller before? Or did it stop sending logs only recently?

In addition, are you sure that the `pipeline_stages` are correct? It might be worth simplifying them a bit to see if any logs are getting through.

Finally, it might be worth taking a look at `localhost:12345/metrics`, but I'm not sure if there are (useful) metrics for windows events.

**Comment by PsySuck** [comment]
Hello.
Sometimes events appear in loki. I selected the query from the label selector.
This configuration works great, I just recently found that some events are missing.

**Comment by ptodev** [comment]
It seems like this issue, along with #4092 and #4082 might be caused by too many messages coming in from the event log. Would it be possible to limit the number of incoming messages by filtering some of them out via `xpath_query`? Another thing to consider is running multiple agents, each consuming a different type of windows event log?

**Comment by PsySuck** [comment]
Hello.
Actually usually i use filter and xpath_query. But I just discovered this problem using filters.
Multiple agents are not a good idea. I used fluentd before and migrated from it precisely because I had to create several agents.
How can this problem be diagnosed?
Are there any known limits on the number of logs?

**Comment by ptodev** [comment]
> How can this problem be diagnosed?

If you are using the Flow mode, you could use [loki.echo](https://grafana.com/docs/agent/latest/flow/reference/components/loki.echo/) after the loki processing stage so that you can see the logs coming out. You could also add an extra processing stage so that you only echo logs from 4662. This would help in knowing whether the problem is due to the writing to Loki, due to reading from the Event Log, or due to processing.

> Are there any known limits on the number of logs?

I am personally not aware of any.

**Comment by PsySuck** [comment]
I'm using static mode.
Maybe this will can be used https://grafana.com/docs/loki/latest/send-data/promtail/stages/metrics/ ?

**Comment by ptodev** [comment]
Yes, I think you could use the `metrics` stage in this case. It would be useful to have a counter metric for the log lines which you believe are missing. If the counter is bigger than 0, then this would indicate that the Agent receives those log lines and processes them, but somehow isn't sending them.

By the way, the OTel Collector has a [windows events receiver ](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/windowseventlogreceiver/README.md)and a [loki exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md). The events receiver is labeled as "alpha", so it must be still experimental. If you are interested, you could try it out and see if you get the same issues as in #6344, #4092 and #4082. If you find the OTel component to be more stable, we could add it as an `otelcol` [Flow component](https://grafana.com/docs/agent/latest/flow/reference/components/).

**Comment by PsySuck** [comment]
I switched to grafana agent flow. I converted config.
Performance leaves much to be desired.
There are a lot of events. But the agent seems unable to cope. I don't see any problems on the Loki side.

**Comment by PsySuck** [comment]
After various tests, unfortunately, I came to the conclusion that the problem is in the performance of virtualization and storage.
Thanks, I closed the bug.
