### ISSUE TITLE
Rename prometheus.exporter.agent to prometheus.exporter.self

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#6354]
### Request

Rename prometheus.exporter.agent to prometheus.exporter.self. This would be a breaking change and would have to be documented as soon.

### Use case

prometheus.exporter.agent is potentially ambiguous, as it could be mistaken as an exporter for Prometheus Agent. The "agent" term is something we're also moving internally away from; prometheus.exporter.self better represents what the purpose of the component is (an exporter for the process' own metrics).

**Comment by hainenber** [comment]
I'd like to own up this one as I was introducing this back then :D
