### ISSUE TITLE
Upgrade OpenTelemetry to at least  versions v1.23.1/v0.94.1

### ISSUE THREAD

**Issue by marctc** [grafana/agent#6389]
We plan to integrate https://github.com/grafana/beyla in the Agent. The problem is that depends on version OpenTelemetry that are incompatible with Agent. If this helpful at all, [this is](https://github.com/grafana/agent/compare/add_beyla_component) what I had to comment and delete to make it work. The main problem might that we have a custom fork.

**Comment by ptodev** [comment]
I plan to start working on this on March 11th. I'll try to update the Agent to whatever is the latest OTel version at that time.

**Comment by ptodev** [comment]
We need to make sure to include the `proxy_url` config argument which was [added recently](https://github.com/open-telemetry/opentelemetry-collector/pull/8339), but is still [not documented](https://github.com/open-telemetry/opentelemetry-collector/issues/9314).
