### ISSUE TITLE
Unable to install Grafana Agent Operator CRD - metadata.annotations too long

### ISSUE THREAD

**Issue by debugger24** [grafana/agent#6392]
### What's wrong?

When installing grafana agent operator CRD, it crashes saying metadata.annotations is too long, it also impact other dependent helm charts like Loki.

### Steps to reproduce

1. Download CRD from https://github.com/grafana/helm-charts/blob/main/charts/agent-operator/crds/monitoring.grafana.com_grafanaagents.yaml
2. Run `kubectl apply -f monitoring.grafana.com_grafanaagents.yaml`

We will get error `The CustomResourceDefinition "grafanaagents.monitoring.grafana.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

### System information

Linux pi1 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64

### Software version

Grafana Agent Operator helm chart 0.3.15 (App version: 0.39.1)

**Comment by tpaschalis** [comment]
Thanks for opening an issue Rahul.

This was fixed as part of https://github.com/grafana/agent/pull/6258 and will be available on the next release in late February. I'm closing the issue as completed.

**Comment by debugger24** [comment]
Ah nice, thanks.
