### ISSUE TITLE
loki.source.journal return Code(429)

### ISSUE THREAD

**Issue by JustNZ** [grafana/agent#6394]
### What's wrong?

loki.source.journal returns the following error message:

`level=warn ts=2024-02-20T11:02:47.108477136Z caller=grpc_logging.go:57 method=/logproto.Pusher/Push duration=68.217µs err="rpc error: code = Code(429) desc = Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased, user: 'swiftlog_itops'" msg=gRPC`

grafana-agent version: 0.39.0-1
mode: flow

### Steps to reproduce

1. Run agent in flow mode
2. create loki.source.journal component and forward it directly to loki.write
3. see error in grafana-agent log

### System information

RHEL7/8

### Software version

v0.39.0-1

### Configuration

```text
loki.source.journal "read"  {
  forward_to    = [loki.write.local.receiver]
  relabel_rules = loki.relabel.journal.rules
  labels        = {
    component = "journal",
    scope = "system",
    filename = "/var/log/messages",
  }
}

loki.write "local" {
  endpoint {
    url = "https://endpoint/loki/api/v1/push"
    tenant_id = "sample"
  }
  external_labels = {
    "swift_instance" = "sample",
    "swift_stage" = "sample",
    "swift_host" = "sample",
    "swift_type" = "sample",
  }
}
```

### Logs

```text
level=warn ts=2024-02-20T11:02:47.108477136Z caller=grpc_logging.go:57 method=/logproto.Pusher/Push duration=68.217µs err="rpc error: code = Code(429) desc = Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased, user: 'swiftlog_itops'" msg=gRPC
```

**Comment by tpaschalis** [comment]
It doesn't sound like this is a bug with Grafana Agent or the loki.source.journal component, do you have any other hints that might point to this?

It sounds like in your case you're hitting limits with the Loki instance you're sending to (maybe a Grafana Cloud free tier?). Some tips:

1) You can first pass logs through a `loki.process` component to decrease the number of unique labels (streams) you're using
2) You can fan out logs to a loki.echo component to understand what your log lines and labels look like
3) You can hit the agent's root `/metrics` endpoint to see the cardinality of your metrics and gauge impact of any changes you're testing.

**Comment by JustNZ** [comment]
My Loki is a 3 Server Cluster on a onPremis Infra where I already increased the limits to an maximum value for me.
The first two points sound good and I will definetly test those - thanks
The third one is also already implemented and on the metrics I was not really able to spot anything bad.


```
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  per_stream_rate_limit: 512M
  per_stream_rate_limit_burst: 1024M
  cardinality_limit: 200000
  ingestion_rate_mb: 10000
  ingestion_burst_size_mb: 1000
  max_streams_per_user: 100000
  max_entries_limit_per_query: 1000000
  max_label_value_length: 20480
  max_label_name_length: 10240
  max_label_names_per_series: 300
```

**Comment by JustNZ** [comment]
Okay so it seems to be an issue with the `loki.source.journal`
Since I enabled it my logs are full of this error message.

```
loki.source.journal "read"  {
  forward_to    = [loki.write.local.receiver]
  relabel_rules = loki.relabel.journal.rules
  labels        = {
    component = "journal",
    scope = "system",
    filename = "/var/log/messages",
  }
}

loki.relabel "journal" {
  forward_to = []

  rule {
    source_labels = ["__journal__systemd_unit"]
    target_label  = "unit"
  }
}
```

**Comment by JustNZ** [comment]
It seems that there is more discovery from my end required - I will close this issue for now and will maybe open a new one as soon as I can say what the exact issue is
