### ISSUE TITLE
Add support for converting OpenTelemetry Collector components

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#6419]
grafana/agent#6379 introduced a framework for converting OpenTelemetry Collector components, with initial support for converting `otlpreceiver` and `otlpexporter`. There are many more components we need to support conversions for. The following lists track OpenTelemetry Collector components used in both static mode or exclusively used in Flow mode. (Flow mode also uses the components from static mode).

> **NOTE**: Some components may not make sense to convert, but are left in this list for completion. Such components can be ignored and checked off.
>
> Components which do not have a direct Flow component, or are used as an implementation detail in static mode, may be ignored and revisited later during work on converting the tracing subsystem for static mode.

```[tasklist]
### General
- [ ] https://github.com/grafana/agent/issues/6697
- [ ] https://github.com/grafana/agent/issues/6698
```

```[tasklist]
### Components used in static mode
- [ ] https://github.com/grafana/agent/issues/6420
- [ ] https://github.com/grafana/agent/issues/6421
- [ ] https://github.com/grafana/agent/issues/6422
- [ ] https://github.com/grafana/agent/issues/6423
- [ ] https://github.com/grafana/agent/issues/6424
- [ ] https://github.com/grafana/agent/issues/6425
- [ ] https://github.com/grafana/agent/issues/6428
- [ ] https://github.com/grafana/agent/issues/6429
- [ ] https://github.com/grafana/agent/issues/6437
- [ ] https://github.com/grafana/agent/issues/6432
- [ ] https://github.com/grafana/agent/issues/6433
- [x] Support converting `otlpreceiver`
- [x] Support converting `otlpexporter`
- [ ] https://github.com/grafana/agent/issues/6430
- [ ] https://github.com/grafana/agent/issues/6431
- [ ] https://github.com/grafana/agent/issues/6434
- [ ] https://github.com/grafana/agent/issues/6426
- [ ] https://github.com/grafana/agent/issues/6427
- [ ] https://github.com/grafana/agent/issues/6435
- [ ] https://github.com/grafana/agent/issues/6436
- [ ] https://github.com/grafana/agent/issues/6438
- [ ] https://github.com/grafana/agent/issues/6718
```

```[tasklist]
### Components used exclusively in flow mode
- [ ] https://github.com/grafana/agent/issues/6439
- [ ] https://github.com/grafana/agent/issues/6440
- [ ] https://github.com/grafana/agent/issues/6441
- [ ] https://github.com/grafana/agent/issues/6442
- [ ] https://github.com/grafana/agent/issues/6443
- [ ] https://github.com/grafana/agent/issues/6444
- [ ] https://github.com/grafana/agent/issues/6445
- [ ] https://github.com/grafana/agent/issues/6451
- [ ] https://github.com/grafana/agent/issues/6452
- [ ] https://github.com/grafana/agent/issues/6453
- [ ] https://github.com/grafana/agent/issues/6454
- [ ] https://github.com/grafana/agent/issues/6455
- [ ] https://github.com/grafana/agent/issues/6456
- [ ] https://github.com/grafana/agent/issues/6458
- [ ] https://github.com/grafana/agent/issues/6459
- [ ] https://github.com/grafana/agent/issues/6448
```

**Comment by rfratto** [comment]
Connectors and extensions may need tweaks to the conversion framework before they're implemented; the low hanging fruits right now are converting receivers/processors/exporters.

**Comment by tpaschalis** [comment]
Seems like we removed lokiexporter from the list but didn't close the issue, was there any reason behind this or was it unintentional? (I've opened a PR to convert it either way) cc @rfratto

**Comment by rfratto** [comment]
> Seems like we removed lokiexporter from the list but didn't close the issue, was there any reason behind this or was it unintentional? (I've opened a PR to convert it either way) cc @rfratto

I think this was a bug with the task list; I've only removed duplicate issues from the list, but the eventual consistency of it threw me off and I ended up removing the same item twice, which might've accidentally removed other things. I'll add it back, thanks for the heads up 👍
