### ISSUE TITLE
import.file: support importing folders as a single module

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#6460]
#5547 mentions that import.file should support importing folders, but it currently only supports importing single files. import.file should be updated to support folders.

IMO, this should _not_ include folder support in local.file, as that would require much more thinking beyond the use case of what we need for import.file.

Related to #6461, which is the same issue but for import.git.

**Comment by wildum** [comment]
I'm trying the following approach: the import source file manages as many file components as there are river files in the folder. The content of all the files is concatenated into one string passed to the import config node.
This way the import node is updated when the content of one of the files in the folder changes.
I'm also watching the folder for added/removed files.
