### ISSUE TITLE
Sync defaults in otelcol.receiver.opencensus

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#6489]
This file notes that our defaults for otelcol.receiver.opencensus have desynced with upstream (or in this case, I'm not sure it was ever correct).

https://github.com/grafana/agent/blob/c58709a9625b361200183e3dff083a25e4e8ef3b/converter/internal/otelcolconvert/testdata/opencensus.yaml#L6-L8

Changing a listening port like this _would_ be a breaking change, but given how 4317 is used by another receiver by default, I think it's justifiable in this case; we should change our default for otelcol.receiver.opencensus to align with the upstream opencensusreceiver component.

**Comment by hainenber** [comment]
Consider that OpenCensus has merged into OpenTelemetry and is [encouraging people to migrate](https://opencensus.io/) to the latter in addition to the OpenTelemetry folks's [effort](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29867) as well

I wonder if we should continue with the component to conserve engineering powers 🤖 (my 2c ofc)

**Comment by rfratto** [comment]
This one makes me worried because we're so close to releasing 1.0, so if we're going to make breaking changes it really needs to be now. Even with encouraging people to migrate, it can sometimes take organizations a really long time to move off of old tooling, so in this case I think it's better to make sure we're aligned with upstream going into 1.0. 

I spent a few minutes to fix this and opened #6682 so we can move on :)
