### ISSUE TITLE
dropequal and keepequal are messed up

### ISSUE THREAD

**Issue by 532910** [grafana/agent#6497]
### What's wrong?

keepequal drops equal labels
dropqual keeps equal labels

This:
```
rule {
     action = "keepequal"
     source_labels = ["__name__"]
     target_label = "__drop"
}       
```
drops this:
`test{"__drop"="test"}`
and leaves this:
`test2{"__drop"="test"}`

This:
```
rule {
     action = "dropequal"
     source_labels = ["__name__"]
     target_label = "__drop"
}       
```
keeps this:
`test{"__drop"="test"}`

and drops this:
`test2{"__drop"="test"}`

### Steps to reproduce

see above

### Software version

grafana-agent-flow 0.39.2-1

**Comment by tpaschalis** [comment]
Hey there @532910 , thank you for the report!

Can you share more on how you've hit this bug? The code for relabeling hasn't been changed for nearly 2 years now in upstream Prometheus (or our side). 

I've tested with a simple configuration like the following and the UI shows targets being filtered as expected.

```
discovery.relabel "keepequal" {
  targets = [
    { "input" = "foo", "target" = "foo" },
    { "input" = "foo", "target" = "bar" },
  ]

  rule {
    action        = "keepequal"
    source_labels = ["input"]
    target_label  = "target"
  }
}

discovery.relabel "dropequal" {
  targets = [
    { "input" = "foo", "target" = "foo" },
    { "input" = "foo", "target" = "bar" },
  ]

  rule {
    action        = "dropequal"
    source_labels = ["input"]
    target_label  = "target"
  }
}
```

![image](https://github.com/grafana/agent/assets/17771679/8d49c9f1-192d-4c77-844d-d24074fa5074)
![image](https://github.com/grafana/agent/assets/17771679/9d1f7ad8-be33-4c51-9adb-61c4362e492b)

**Comment by 532910** [comment]
it was my fault, I was trying to change double underscore scrapped labels using `discovery.relabel`, when `prometheus.relabel` should have been used.
