### ISSUE TITLE
Sync defaults in otelcol.processor.k8sattributes

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#6499]
The upstream processor introduces some default excludes that we don't have set up in otelcol.processor.k8sattributes

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ee728f70e403a4f3347a30be5fc2944ab17ce8e4/processor/k8sattributesprocessor/factory.go#L21

**Comment by ptodev** [comment]
Do we need to have those excludes? They are not documented in the otel [readme](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md). It also seems sort of arbitrary to exclude pods with those names - I personally don't know what the reasoning for their exclusion is.

**Comment by hainenber** [comment]
It may have something to the historical usage of Jaeger's tracing platform and the processor's author was trying to exclude span data coming from now deprecated `jaeger-agent` and `jaeger-collector`

I still think it's fairly crucial if Agent user still having historical Jaeger components running in their K8s cluster.
