### ISSUE TITLE
Loki kubernetes rules refactor follow-up

### ISSUE THREAD

**Issue by wildum** [grafana/agent#6545]
The component `loki.rules.kubernetes` introduced by https://github.com/grafana/agent/pull/3936 has a lot of copied logic from the `mimir.rules.kubernetes` component (if the mimir implementation had bugs then those were ported to the loki implementation) 

We should avoid redundancy as much as possible to keep the code manageable. 

I suggest to put the common logic in the common kubernetes pkg.

**Comment by hainenber** [comment]
I can tackle this one :D

**Comment by wildum** [comment]
Thanks! Don't hesitate to reach out if you have any questions :)
