### ISSUE TITLE
bug: clustering fails to switch to a member

### ISSUE THREAD

**Issue by db-wally007** [grafana/agent#6554]
### What's wrong?

Hello,

please correct me if I'm wrong but I was expecting "clustering" to failover to the member if and when one of the scraped targets is down.

### Steps to reproduce

For example, I have `grafana-agent1` and `grafana-agent2` containers.

They are both in a cluster and prometheus scrape is configured with clustering enabled.

```json
prometheus.scrape "veeam_2m" {
	targets         = discovery.relabel.veeam_2m.output
	forward_to      = [prometheus.relabel.veeam_2m.receiver]
	job_name        = "veeam-2m"
	scrape_interval = "2m0s"
        clustering {
          enabled = true
    }
}
```

When cluster starts, `grafana-agent1` begins to scrape this target. All good so far.

Now when `grafana-agent1` loses connectivity to the target but it is still part of the cluster with `grafana-agent2` - the target is marked as "down" on `grafana-agent1` but it never fails over to `grafana-agent2` to attempt connecting to the target.

Is this expected ?

**Comment by tpaschalis** [comment]
Hey there @db-wally007. Yeah, this is expected behavior; distribution of targets happens when the _cluster_ state changes (eg. a new node joins, a node leaves, or is detected to have gone away), not when the target status itself changes.

So one of the core assumptions of clustering is that all members have the same network access (eg. to service discovery APIs) so that they can have the same view about the available targets. Is there a reason in your setup why a target would be unavailable from `grafana-agent1`, but `grafana-agent2`  would be able to successfully scrape it?

**Comment by db-wally007** [comment]
> Is there a reason in your setup why a target would be unavailable from `grafana-agent1`, but `grafana-agent2` would be able to successfully scrape it?

Hi - thanks for taking the time. 
I feel like I misunderstood the clustering concept (at least partially)....

We dont run Kubernetes but we have a couple of independent podman host. Lets call them `podman1` and `podman2`.
Containers and pods are automatically deployed by Ansible Automation Platform.

`podman1` runs the following pod:
`monitoring_pod` exposes port 12354 (only)

`monitoring pod` has the following containers
`grafana-agent1` -> 0.0.0.0:12345
`veeam_exporter` -> 0.0.0.0:80
`vmware_exporter` -> 0.0.0.0:81
and so on ....

`podman2` runs the following pod:
`monitoring_pod` exposes port 12354 (only)

`monitoring pod` has the following containers
`grafana-agent2` -> 0.0.0.0:12345
`veeam_exporter` -> 0.0.0.0:80
`vmware_exporter` -> 0.0.0.0:81
and so on ....

Config of both `grafana-agent1/2` containers is identical and with clustering enabled - the target (in this example `vmware_exporter`) is scraped only once by the cluster. This works great.

This way we have not only `grafana-agent` HA but also individual exporters HA. The overhead of running multiple exporters is negligible - since only one of them will be scraped by grafana-agent cluster.
It also adds a bit of security, none of the exporters have ports exposed outside of the pod (only grafana-agent port is exposed for clustering - which will hopefully support mTLS soon-ish :-))

This morning `vmware_exporter` crashed on `podman1` host - but it was still running on `podman2` but `grafna-agent2` never got the signal to start scraping it. 
So I began to realize, my plan of having secure HA exporters will be limited to grafana integrations only - the external exporter will not be used if one of them crashes.

`
