### ISSUE TITLE
grafana-agent-flow add binary file release

### ISSUE THREAD

**Issue by Jack-Kingdom** [grafana/agent#6577]
### Request

we can find agent static binnary file in release, but not found for flow mode binary file. We can add it.

### Use case

add grafana-agent-flow binary release file for smooth upgrade

**Comment by mattdurham** [comment]
Any static mode version can be made flow mode with setting `AGENT_MODE=flow`

**Comment by Jack-Kingdom** [comment]
Oh, my bad, thank you for your remind.
