### ISSUE TITLE
Autologging: span attributes as log labels

### ISSUE THREAD

**Issue by mapno** [grafana/agent#661]
Automatic logging searches for a given set of span attributes and logs them as key-value pairs. This allows for automatically building a mechanism for trace discovery, in which traces can be searched with LogQL. However, most of the search requires parsing the log line (e.g. `logfmt`), which involves extra overhead compared to using log labels.

We should consider allowing to use labels for this attributes. Labels are passed to the log [entry](https://github.com/grafana/agent/blob/main/pkg/tempo/automaticloggingprocessor/automaticloggingprocessor.go#L226-L228).

**Comment by eamonryan** [comment]
This would help a ton with Grafana jumping from Metrics -> Logs in split pane view, as it relies on common labels between the two to automatically build a Loki query when you open a split!
