### ISSUE TITLE
Support custom CAs in tracing remote_write

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#662]
The [tracing remote_write](https://github.com/grafana/agent/blob/main/docs/configuration-reference.md#tempo_instance_config) configs do not allow you to specify a custom CA. This may be a problem if you're using an internal-only ingress and a self-hosted Tempo. Without this, users are forced to configure `insecure_skip_verify` to use the ingress.

Ideally we'd support this in the same way Prometheus does, some subset of [tls_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config).

cc @mapno

**Comment by cloudcafetech** [comment]
@rfratto 

Will it support for others (Log & Monitoring) agent?
