### ISSUE TITLE
Add support for OTLP HTTP trace exporting

### ISSUE THREAD

**Issue by mapno** [grafana/agent#663]
Currently, the Grafana Agent only support forwarding traces with the OTLP gRPC [exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter). It's possible to add support for a HTTP exporter, so we want to gather feedback on what uses cases might require HTTP and when gRPC is not an option or not ideal.

**Comment by joe-elliott** [comment]
I am fine with adding this as long as it's clearly documented that it does not work with Grafana Cloud. There are some on prem Grafana Agent users and I recognize this feature could allow them to use Tempo.

**Comment by kalali** [comment]
We can benefit from this implementation as our environment does not support http2 in some network hops and we are aiming to replace jaeger with tempo (Using Grafana Agent as shipper).

**Comment by Matthevv-k4y** [comment]
Thank you for opening this issue and putting a fix for it so quickly. Our env is openshift which does not support http2 for ingress/routes and shipping the traces using grpc is no possible. I will try this as soon as it is being released.
