### ISSUE TITLE
Update prometheus postgres exporter

### ISSUE THREAD

**Issue by thampiotr** [grafana/agent#6645]
### Request

The prometheus postgres exporter is on a forked version that hasn't been updated in over 2 years.
There have been [bugfixes such as these](https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.13.2) that we don't have. This blocks some users. We need to update the postgres exporter to new version.

### Use case

Export metrics from postgres using an embedded exporter.

**Comment by hainenber** [comment]
I see this as an opportunity to rid of the forked version.

We can refactor the codebase to use the upstream as `postgres_exporter` has been "library-ized" using the [`collector`](https://github.com/prometheus-community/postgres_exporter/tree/master/collector) package, evidenced by this [closed PR](https://github.com/prometheus-community/postgres_exporter/pull/562).

Please help assigning if possible :D

**Comment by bradleypettit** [comment]
Yeah I noticed the deprecations too... IMO the most impactful will be the custom queries support. I looked through this request to not deprecate - https://github.com/prometheus-community/postgres_exporter/issues/909 - and noted this comment

> That is what deprecation means. It is a warning that sometime in the future it may be removed. The queries.yaml is still supported. It has not been removed. We understand that people are still using it. We have not yet announced what version it will be removed in.

Maybe we can have a lower priority enhancement to add the more generic [sql_exporter](https://github.com/burningalchemist/sql_exporter) to our agent, so that our customers have a migration option once it does get removed from postgres_exporter.

**Comment by thampiotr** [comment]
@hainenber it appears that the `collector` package [dropped support for multiple datasources](https://github.com/prometheus-community/postgres_exporter/blob/b070e4534960fd42bd31f8d3f0198a820c6c1660/cmd/postgres_exporter/main.go#L129-L133), recommending to use instead multi-target pattern, which itself is BETA. 

So we could either have a simple update from upstream with a breaking change to `prometheus.exporter.postgres` where the agent also drops the multiple datasources support, or we could fork their latest and add back the multiple datasources support. I'm going to discuss with the team how to do this. 

Not for the posteriority: any user that is missing some specific metrics, there is a workaround, where you can use the `custom_queries_config_path` argument as [documented here](https://grafana.com/docs/agent/next/flow/reference/components/prometheus.exporter.postgres/). You can then use a file [like this](https://github.com/prometheus-community/postgres_exporter/blob/v0.11.1/queries.yaml) to define the missing metrics and their queries.
