### ISSUE TITLE
some wrong tags in the repo

### ISSUE THREAD

**Issue by chenrui333** [grafana/agent#6654]
👋 looks like there are some wrong tags got pushed into the repo recently, notably, 1.2.99 and 1.3.191, any idea? Can we also remove them? Thanks!

- https://github.com/grafana/agent/releases/tag/v1.2.99
- https://github.com/grafana/agent/releases/tag/v1.3.191

![image](https://github.com/grafana/agent/assets/1580956/20d70d6d-4896-4b1a-93b8-d36afe646e3d)

![image](https://github.com/grafana/agent/assets/1580956/0f81d9b0-37be-4748-954e-b77509c9a0dd)

cc @tpaschalis

**Comment by rfratto** [comment]
@tpaschalis When you take a look at this tomorrow, we'll probably want to also [retract](https://go.dev/ref/mod#go-mod-file-retract) these tags from go.mod

**Comment by tpaschalis** [comment]
Thanks for the heads-up @chenrui333 , taking a look!

**Comment by tpaschalis** [comment]
Running `git tag --sort=-version:refname` gives me these three invalid tags from up top, plus an invalid tag that has no `v` prefix.
```
v1.3.191
v1.2.99-rc1
v1.2.99
...
0.14.0-rc.3
```

I've removed all three tags and will look into the retract directive.
