### ISSUE TITLE
remotecfg in Grafana Agent Flow for Windows error: failed to read from cache err="open C:\\ProgramData\\Grafana Agent Flow\\data\\remotecfg\\7ff0f6c4: Cannot find specified file"

### ISSUE THREAD

**Issue by outofsight** [grafana/agent#6672]
### What's wrong?

Error while starting Grafana Agent in Windows (service and also normal process, UAC Elevated).
No detailed log to better understand the issue.

### Steps to reproduce

Try to start Grafana Agent in Windows, as normal process, UAC elevated, with the following `config.river`.

### System information

Windows 11

### Software version

Grafana Agent v0.40

### Configuration

```text
logging { level = "debug" }

remotecfg {
	url = "https://grafana-agent-config.portal.mydomain.tld"
	id             = constants.hostname
	metadata       = {"cluster" = "dev", "namespace" = "otlp-dev"}
	poll_frequency = "5m"
}
```

### Logs

```text
ts=2024-03-13T13:50:54.6807161Z level=error msg="failed to read from cache" service=remotecfg err="open C:\\ProgramData\\Grafana Agent Flow\\data\\remotecfg\\7ff0f6c4: Cannot find file specified."
ts=2024-03-13T13:55:54.6594486Z level=error msg="failed to fetch remote configuration from the API" service=remotecfg err="invalid_argument: unmarshal message: unmarshal into *agentv1.GetConfigResponse: proto:\u00a0cannot parse invalid wire-format data"
```

**Comment by tpaschalis** [comment]
Hey there @outofsight, thanks for opening an issue!

How are you trying to use the [remotecfg](https://grafana.com/docs/agent/next/flow/reference/config-blocks/remotecfg/) block? And what does your https://grafana-agent-config.portal.mydomain.tld return?

The Agent expects the endpoint to return responses that align with [the API reference](https://github.com/grafana/agent-remote-config), in Protobuf format. Logs indicate that's not the case here.

If you're looking for something more of raw string files, you may be also interested in looking at [Modules](https://grafana.com/docs/agent/next/flow/concepts/modules/) and the `import.http` or `import.git` blocks

**Comment by outofsight** [comment]
Thanks for reply @tpaschalis.

I later understood `remotecfg` endpoind is not supposed to return a full `config.river` in a form of simple text.

But from what I understand, even `import.http` can't be used the way I would like, i.e. getting the full agent configuration from an http(s) endpoint.

There is a simple way to achive this?

**Comment by tpaschalis** [comment]
> There is a simple way to achive this?

Yes, there is. You have to include a top-level component in your module that kick-starts the pipeline, and then just call to it from all agents.

This entrypoint component may or may not have any arguments depending on whether you need customizations.

So in your module you define `declare "start"` which contains the entire pipeline and then in your actual config file you

```
import.http "helpers" {
...
}
...

helpers.start "default" {
...
}
```

**Comment by outofsight** [comment]
Thanks for the input, I think I made it working, more or less.

Seems `import.http` doesn't support (yet) `basic_auth`, so for now I had to resort to `headers`.

**Comment by tpaschalis** [comment]
Good to hear! I'm closing this issue since there's no bug here.
