### ISSUE TITLE
Add support for remote write exporter in scraping service mode

### ISSUE THREAD

**Issue by mapno** [grafana/agent#669]
The remote write exporter is not supported in the Agent's scraping service mode as it [requires](https://github.com/grafana/agent/blob/main/pkg/tempo/remotewriteexporter/exporter.go#L80) a `ManagedInstance`, and they don't exist in that mode. We should find a way to pass an instance to the exporter in that mode.

**Comment by rfratto** [comment]
This will be resolved by the implementation of #875.

**Comment by rfratto** [comment]
I'm going to close this for now; it's really uncommon to create a scraping service deployment which also accepts traces. If someone runs into this in the future, please open a new issue.
