### ISSUE TITLE
Make remote write exporter compliant with prometheus

### ISSUE THREAD

**Issue by mapno** [grafana/agent#670]
We should add [compliance](https://github.com/prometheus/compliance) checks for prometheus in the remote write exporter

**Comment by rfratto** [comment]
I don't think there _are_ compliance tests for this: the existing compliance tests are based on how a Prometheus-compatible scraper will send Prometheus-compatible metrics over remote_write. I think since we're generating metrics based on spans, it falls under a different set of rules.

**Comment by rfratto** [comment]
I'm going to close this for now, but I agree that compliance is important and if we determine that there are test suites to run, we should definitely use them.
