### ISSUE TITLE
Excludes logs

### ISSUE THREAD

**Issue by cloudcafetech** [grafana/agent#672]
Using logging agent, is it possible to excludes pod logs from certain namespaces (default & kube-system)?

**Comment by mapno** [comment]
> Using logging agent, is it possible to excludes pod logs from certain namespaces (default & kube-system)?

Yes. If you're using the `kubernetes_sd_config` to discover targets, you should be able to select only the resources you want to tail. For further manipulation, you can use [`relabel_configs`](https://github.com/grafana/loki/blob/main/docs/sources/clients/promtail/configuration.md#relabel_configs) to inspect and drop logs.

**Comment by cloudcafetech** [comment]
Any examples or pointer?
