### ISSUE TITLE
🔥 incident: [firing:1] Mythical Application - High Latency (Cision)

### ISSUE THREAD

**Issue by matryer** [grafana/agent#6776]
See [`[firing:1] Mythical Application - High Latency (Cision)`](https://sedemo.grafana.net/a/grafana-incident-app/incidents/1258) on **Grafana Incident**.

Created by [Grafana Incident](https://sedemo.grafana.net/a/grafana-incident-app) (1.45.0)

**Comment by rfratto** [comment]
Seems like this was set up by mistake. Closing.
