### ISSUE TITLE
🔥 incident: Mythical Beast Service Violation Impacting Endpoint: payment

### ISSUE THREAD

**Issue by matryer** [grafana/agent#6777]
See [`Mythical Beast Service Violation Impacting Endpoint: payment`](https://sedemo.grafana.net/a/grafana-incident-app/incidents/1259) on **Grafana Incident**.

Created by [Grafana Incident](https://sedemo.grafana.net/a/grafana-incident-app) (1.45.0)

**Comment by rfratto** [comment]
Seems like this was set up by mistake. Closing.
