### ISSUE TITLE
🔥 incident: [DRILL] StatusPage test

### ISSUE THREAD

**Issue by matryer** [grafana/agent#6779]
See [`StatusPage test`](https://sedemo.grafana.net/a/grafana-incident-app/incidents/1260) on **Grafana Incident**.
⚠️ This incident is a drill

Created by [Grafana Incident](https://sedemo.grafana.net/a/grafana-incident-app) (1.45.0)

**Comment by rfratto** [comment]
Seems like this was set up by mistake. Closing.
