### ISSUE TITLE
release note hasnt been published for v0.40

### ISSUE THREAD

**Issue by christopherzli** [grafana/agent#6828]
### What's wrong?

https://grafana.com/docs/agent/v0.40/static/release-notes/

### Steps to reproduce

https://grafana.com/docs/agent/v0.40/static/release-notes/

### Software version

grafana agent 0.40

**Comment by hainenber** [comment]
There's a published [`release note`](https://grafana.com/docs/agent/v0.40/flow/release-notes/) for Flow mode, fyi

It seems there were no breaking changes in the last 2 major release regarding Static mode and hence nothing over there.

**Comment by tpaschalis** [comment]
Seconding @hainenber 's point. You can find more detailed release notes on the [GitHub releases page](https://github.com/grafana/agent/releases); these docs page is mostly about breaking changes, so I'll close this issue out.
