### ISSUE TITLE
Grafana-agent- flow fails to install using Brew on MacOS 14.5

### ISSUE THREAD

**Issue by teekwan** [grafana/agent#6958]
### What's wrong?

When running brew install grafana-agent-flow I get this eventually:
`~ % brew install grafana-agent-flow
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> Fetching grafana/grafana/grafana-agent-flow
==> Downloading https://github.com/grafana/agent/archive/refs/tags/v0.41.1.tar.gz
Already downloaded: /Users/softwarerimactechnology/Library/Caches/Homebrew/downloads/c6c1b968717b175570e5e6f32e8ddd4245aff9f0439fefec0ef880b19f007d8a--agent-0.41.1.tar.gz
==> Installing grafana-agent-flow from grafana/grafana
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ dir_chdir0 - web/ui`

Tried to reinstall Brew but no luck. :(

Thanks!

### Steps to reproduce

brew tap grfana/grafana
brew install grafana-agent-flow

### System information

MacOS 14.5

### Software version

0.41.1

**Comment by rfratto** [comment]
Thanks for reporting, I just fixed this. You'll need to run a `brew update` before trying to reinstall. Let me know if it still doesn't work after that!

**Comment by teekwan** [comment]
Thanks, but `brew update` still makes it fetch 0.41.1 and fail the same way 🤷‍♂️
