### ISSUE TITLE
Prometheus native histograms are NOT scraped in static mode

### ISSUE THREAD

**Issue by Reimirno** [grafana/agent#7056]
### What's wrong?

A similar issue for flow mode has been raised in https://github.com/grafana/agent/issues/5136 and fixed in https://github.com/grafana/agent/pull/5335

However, it seems that for static mode agent there is still no way to configure EnableProtobufNegotiation on prometheus.

This is needed for agent to be able to scrape native histogram. You need this turned on for prometheus to be able to send correct header and request protobuf. See src [here](https://github.com/grafana/prometheus/blob/cmp_header_order/scrape/scrape.go#L463).

### Steps to reproduce

no such option in `static/config/config.go`

**Comment by Reimirno** [comment]
I have a small PR to fix this - Can someone take a look? #7057 
Thank you :)

**Comment by ptodev** [comment]
Hello! Apologies, we no longer add new features to static mode. Please look into [migrating to Alloy](https://grafana.com/docs/alloy/latest/set-up/migrate/from-static/) instead.
