### ISSUE TITLE
grafana-agent/agent-loki.yaml doesn't support CRI log format

### ISSUE THREAD

**Issue by flokli** [grafana/agent#717]
I deployed `agent-loki.yaml` inside a k3s cluster.

k3s uses containerd, and its log format (CRI log format, as per https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md) is different than the docker one, which `agent-loki.yaml` seems to expect: https://github.com/k3s-io/k3s/issues/356#issuecomment-485080611

This causes log lines to be ingrested incorrectly (they're prefixed by timestamp and stdout/err), and causes parsing errors further down the line.

promtail seems to support CRI log format since https://github.com/grafana/loki/pull/365, but I'm not sure if/how that can be used in here.

**Comment by rfratto** [comment]
Hi there, you can change the `docker` stage from [`agent-loki.yaml`](https://github.com/grafana/agent/blob/dc8d7435ac7d12e3ae81e351c1c1a3e324b3c9f1/production/kubernetes/agent-loki.yaml#L20) with `cri`: 

```yaml
pipeline_stages:
  - cri: {}
```

It appears in a few places, so you'll have to replace them all.

**Comment by flokli** [comment]
Thanks, I'll give this a try!

Is there any plans to autodiscover this, or expose this configurability during installation time?

**Comment by flokli** [comment]
I can verify this fixed things for me. Thanks a lot!

**Comment by rfratto** [comment]
> Is there any plans to autodiscover this, or expose this configurability during installation time?

Autodiscovery might be a bit difficult, but we'll make sure to make it something that can be easily changed when we improve our installation instructions.

**Comment by flokli** [comment]
With https://github.com/grafana/agent/pull/749 merged, I wanted to send a PR to grafana/website to add a note on the `pipeline_stage`, and changing `docker` to `cri` in case of running containerd, but realized it's not public :-/

Are there plans to open-source it, or could you add a paragraph there?

**Comment by rfratto** [comment]
> Are there plans to open-source it, or could you add a paragraph there?
I'm not aware of any plans to open source grafana/website, though the inability for people to contribute has been a problem a few times.

cc @hjet @matthewhelmke to update the guide.

**Comment by hjet** [comment]
Thanks for flagging this, @flokli! Will add a brief note to the Agent/K8s logs quickstart guide.

**Comment by flokli** [comment]
@hjet has the note been added?

**Comment by hjet** [comment]
Thanks for the reminder, I'll make the PR today

**Comment by hjet** [comment]
@flokli the changes are live [here](https://grafana.com/docs/grafana-cloud/quickstart/agent-k8s/k8s_agent_logs/)

Thanks again for flagging this and following up!

Is there anything else required here, or can we close this issue?

**Comment by flokli** [comment]
Yes, this looks good. Thanks for adding it - feel free to close this issue.

**Comment by rfratto** [comment]
Thanks Hanif!
