### ISSUE TITLE
Large portion of links from grafana.com documentation are broken

### ISSUE THREAD

**Issue by quinndiggity** [grafana/agent#724]
Not sure if the structure of the repo was changed without regard to the documentation, but a significant amount of links on https://grafana.com/docs/ to this repo are broken with 404's; almost all the initial documentation pieces users see, one example of which being https://grafana.com/docs/grafana-cloud/how-do-i/agent/

Pretty poor experience when 90% of the links in the formal documentation are broken.

**Comment by rfratto** [comment]
Thanks for pointing this out. We've been re-organizing the docs this week to prepare for embedding the project docs on grafana.com/docs. I'll go through the broken links in the morning and fix everything. 

> Pretty poor experience when 90% of the links in the formal documentation are broken.

This is unnecessary.

**Comment by rfratto** [comment]
The links were updated on Thursday.

**Comment by quinndiggity** [comment]
> The links were updated on Thursday.

Thanks 👍🏻 

> This is unnecessary.

Personally, I was able to track down the information I needed; this was only reported so it would be fixed to avoid other+new users experiencing the same frustration. The reason for pointing out the poor experience is in hopes that changes that affect documentation and links may be considered in the future prior to making said changes.
