### ISSUE TITLE
don't require network access for running tests

### ISSUE THREAD

**Issue by flokli** [grafana/agent#731]
When trying to build `grafana-agent` in a sandbox with no network access, I realized the unit tests try to download things from a GCP bucket:

```
=== RUN   TestEnqueueRequestForSelector
    selector_eventhandler_test.go:48:
                Error Trace:    selector_eventhandler_test.go:170
                                                        selector_eventhandler_test.go:48
                Error:          Received unexpected error:
                                Get "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-1.19.2-linux-amd64.tar.gz": dial tcp: lookup storage.googleapis.com on [::1]:53: read udp [::1]:52238->[::1]:53: read: connection refused
                Test:           TestEnqueueRequestForSelector
                Messages:       failed to download dependencies for envtest
--- FAIL: TestEnqueueRequestForSelector (0.00s)
FAIL
FAIL    github.com/grafana/agent/pkg/operator   0.051s
FAIL
```

Can you ship these tools in the repo (maybe via git-lfs), or just require them to be in $PATH?

And make these kind of tests opt-in, or skip if the tools can't be downloaded?

**Comment by flokli** [comment]
For now I skipped that test in https://github.com/NixOS/nixpkgs/pull/129890, but it'd be nice if there would be no need to patch things to have it build with sandbox enabled.

**Comment by rfratto** [comment]
I wouldn't mind git-lfs as long as it didn't change the workflow of cloning/pulling the repository (I haven't used it before, so I'm not sure). The idea of having the test download the binary was to make sure there was no extra steps needed just to run this one test.

I'd accept a PR to add a build tag that excludes this test from normal test runs. Then `make test` could deliberately run tests with that build tag.

**Comment by flokli** [comment]
I went with the flag route - PR is up at https://github.com/grafana/agent/pull/776.
