### ISSUE TITLE
WAL watcher runs even when Prometheus not in use

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#735]
The WAL watcher will run even when Prometheus is not in use. This will lead to errors if it defaults to reading a non-empty directory (ie `/`): 

```
ts=2021-07-12T15:59:58.668240754Z level=warn agent=prometheus component=cleaner msg="unable to find segment mtime of WAL" name=sys err="unable to open WAL: open sys/wal: no such file or directory"
```

Either the WAL watcher should be disabled if no Prometheus configs are present, or it should default to an empty directory, or that warning-level log should be a debug-level log.

**Comment by 56quarters** [comment]
I think not running it if there are no Prometheus configs present makes the most sense. I assume the reverse should also apply, the cleaner should start running if the Agent becomes responsible for Prometheus configs?

**Comment by rfratto** [comment]
Not running if there are no configs can get a little confusing, I guess. If you go from 10 to 0 configs should the WAL watcher run?
Maybe it should only run if `prometheus.wal-directory` is set?

**Comment by 56quarters** [comment]
That makes sense to me :+1:

**Comment by yeya24** [comment]
I can take this one if no one is working on this. IIUC, the task is to check the wal directory flag here https://github.com/grafana/agent/blob/main/pkg/prom/agent.go#L224?

**Comment by rfratto** [comment]
@yeya24 Please do :) 

Yeah, that's the right place, though you'd have to be careful about references to it throughout the rest of that code if it's possible to be nil.
