### ISSUE TITLE
RELEASE_VERSION in grafanacloud-install.sh out of date

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#736]
https://github.com/grafana/agent/blob/b1e5ec5140e018b906cfeeb1110402be8691d532/production/grafanacloud-install.sh#L50

**Comment by rfratto** [comment]
I missed this because I was searching for v0.15.0 when doing the upgrade. We should look for other stale references to 0.15.0, but hopefully this is the only one.

**Comment by flokli** [comment]
This has been fixed in 997675b53a8e1685ee34f00a6dcc18e8ffa852f8 and can be closed.

**Comment by rfratto** [comment]
Thanks!
