### ISSUE TITLE
deb package: add grafana-agent to adm and systemd-journal groups

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#737]
From #524:

> Figured out the reason. The default UID/GID for grafana-agent does not have access to systemd-journal group used by Ubuntu 20.10.
> 
> To solve this:
> ```
> usermod -a -G adm grafana-agent
> usermod -a -G systemd-journal grafana-agent
> ```

_Originally posted by @zanglang in https://github.com/grafana/agent/issues/524#issuecomment-818592323_

**Comment by MurzNN** [comment]
Also will be good to find some way to log some error, if grafana-agent have no permissions to read journal files, because now even with debug level there are no log records, that can show this problem.
