### ISSUE TITLE
include_exporter_metrics is documented on all integrations but is only valid for redis and node exporters

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#751]
Remove references to include_exporter_metrics on everything except redis and node exporters in documentation

**Comment by mateuszdrab** [comment]
Can this be reopened? The https://grafana.com/docs/agent/latest/configuration/integrations/windows-exporter-config/#windows_exporter_config integration still documents the `include_exporter_metrics` setting but this prevents the agent from starting.

**Comment by mateuszdrab** [comment]
Thank you @mattdurham
