### ISSUE TITLE
v0.3's strict YAML parsing uncovered a typo in agent.yaml

### ISSUE THREAD

**Issue by jgraettinger** [grafana/agent#77]
https://github.com/grafana/agent/blob/3cbb06b56291f6a96631b584042386fc0dcef0a4/production/kubernetes/agent.yaml#L171

Should be `metric_relabel_configs` instead, I believe?

**Comment by rfratto** [comment]
Yep, you're totally right. #71 fixed part of this but we didn't update the Kubernetes YAML to include the change. I'll open a PR to fix this and do a release tomorrow to include the fix.

**Comment by rfratto** [comment]
Hi @jgraettinger, I just released v0.3.1 that includes the fix for this. Thanks again!
