### ISSUE TITLE
operator: failed to reconcile statefulset for shard

### ISSUE THREAD

**Issue by flokli** [grafana/agent#788]
I deployed grafana-agent-operator according to the quickstart docs (but with v0.18.0), then deployed a `GrafanaAgent` resource.
I didn't deploy the `PrometheusInstance` resource yet.

I didn't see the `grafana-agent-config` updating, so I looked in the operator logs, and saw the following:

```
level=error ts=2021-08-03T13:00:27.469101643Z component=controller.grafanaagent name=grafana-agent namespace=grafana-agent msg="error during reconciling" err="failed to reconcile statefulset for shard: failed to update statefulset: StatefulSet.apps \"grafana-agent\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"  
```

**Comment by rfratto** [comment]
Thanks for reporting. I'll try to take a look at this later on in the week. 

Did you already have a StatefulSet called `grafana-agent` that you manually created?

**Comment by flokli** [comment]
I was manually bringing up the operator resources and walking through the quickstart.

It's possible that I previously had a `grafana-agent` `StatefulSet` (from the old `agent.yaml`), and terraform didn't delete that quick enough before the operator tried to create it - but it feels a bit unlikely - there were multiple `terraform appiy` invocations in between, in which it should have been removed already. I can't say 100% for sure though.

I eventually got it working by randomly killing pods (and possibly also deleting a `grafana-agent` `StatefulSet`), so can't provide a failing reproducer anymore.

**Comment by rfratto** [comment]
Heads up: I _think_ this may be resolved in 0.19.0 when we added logging support. We changed some of the behavior for how resources are discovered (to have it match Kubernetes' default behavior of resource selectors) and made the update mechanism more reliable when a change to a CRD results in an incompatible change to a StatefulSet.

I'll try to reproduce and fix if I come across something, but please let me know if you happen to stumble on this again.

**Comment by flokli** [comment]
@rfratto where you able to reproduce this?

**Comment by rfratto** [comment]
I haven't been able to give this any attention yet, but I'm spending time this week building e2e tests for the operator. I should be able to add a test for checking this and seeing if I can trigger it. 

Have you come across this lately?

**Comment by flokli** [comment]
Nope, this was a one-time fluke, and I wasn't able to reproduce. Happy to close this once those e2e tests landed :-)
