### ISSUE TITLE
Potential inefficiency retrieving configurations from consul in scraping service mode

### ISSUE THREAD

**Issue by mattmendick** [grafana/agent#789]
Per an offline conversation with @mattdurham and @jdbaldry, there may be an inefficiency in how the agent's scraping service mode is retrieving scraping configs from consul. Currently it seems that the agent will perform one request to obtain the list of keys only, and then iterates over each of the keys to retrieve the value. As the agent has more and more configurations loaded, this will increase load on consul linearly to a breaking point of consul being unable to handle the requests.

Relevant code in consul's api code: https://github.com/hashicorp/consul/blob/main/api/kv.go#L85

This would be more efficient if we are able to do a single call to request the keys and values from consul so that all the configs are retrieved with a single call (or at least fewer than the n number of configurations that exist).

**Comment by mattdurham** [comment]
Specifically, the Key-Value Pairs are transformed into an array of keys, then the values are retrieved later. This loss of information happens in the imported cortex consul client https://github.com/cortexproject/cortex/blob/master/pkg/ring/kv/consul/client.go#L337
