### ISSUE TITLE
[SC] ControlService FAILED 1062

### ISSUE THREAD

**Issue by megaman18** [grafana/agent#794]
im trying to run grafana agent on windows but after editing the agent-config.yaml with my proper config if i stop the process and run it again it wont start
sc stop "Grafana Agent" 
and then
sc start "Grafana Agent"
results in not starting the process and keeps saying  [SC] ControlService FAILED 1062 the service has not been started

**Comment by rfratto** [comment]
Hey @megaman18, were you able to figure this out? I'd like to add troubleshooting info to the docs to help anyone else that might come across this.

**Comment by megaman18** [comment]
Yes i ran the service commands manually in an terminal windows and everything ran perfect
