### ISSUE TITLE
remote_write config stanzas ignore password_file

### ISSUE THREAD

**Issue by jgraettinger** [grafana/agent#81]
Per [docs](https://github.com/grafana/agent/blob/master/docs/configuration-reference.md#remote_write), it looks like one should be able to use `password_file` in a `remote_write` configuration (as in prometheus; desirable cause it plays well with K8s secrets, etc).

[Best I can tell though](https://github.com/grafana/agent/blob/master/pkg/prometheus/instance/remote_write.go#L105), a `password_file` value appears to be checked for / validated, but never makes it into the actual runtime configuration used? (I was led to this by 401 Unauthorized errors which I _believe_ are attributable to this.)

**Comment by rfratto** [comment]
Hi! This was another bug unfortunately introduced by v0.3.0; if you're not using the scraping service mode, you might want to roll back to v0.2.0 until we can do a new release that includes the fix for this (#82)

**Comment by jgraettinger** [comment]
Understood, thanks!
