### ISSUE TITLE
Enhancement request to add metric on scrape-service watcher config

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#839]
We have a metric on reshard but nothing on config. Definitely in the nice to have category.

**Comment by rfratto** [comment]
@mattdurham think you could add a small enhancement for this? Or is the new metric in the modal manager in v0.18.4 enough to close this?

**Comment by rfratto** [comment]
I think the new metric added to the ModalManager are equivalent to this now and this can be closed.
