### ISSUE TITLE
Scraping service: reshard timeout misapplied to cluster-wide reshard

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#857]
https://github.com/grafana/agent/blob/95f4504792f7e52e41e37f6e73fe2b10b43ab171/pkg/metrics/cluster/node.go#L176-L186

The timeout for reshard is being applied to the reshard of the entire cluster, which:

- Runs in parallel across the other nodes, with jitter of 500ms 
- Then runs locally 

This means that if any of the other nodes in the cluster time out, the local reshard will never get to run. I propose changing the gRPC reshard to schedule a background refresh and return immediately.

**Comment by mattdurham** [comment]
Agreed on the background refresh. On the returning immediately and spawning a background routine.  I think has more limited benefit. The transfer out requires a return of error for the flushtransferer interface, which requires a wait.
