### ISSUE TITLE
Load configuration files via URL

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#869]
Today, the agent's base config file may only be retrieved from disk. An exception to this rule is the scraping service, where a KV store must be used to pull scrape configs. The KV store was built to target huge deployments of the Agent, but is still being forced on smaller users of the scraping serivice, as it is the only available option. An alternative approach to allow remote configuration of both clustered and non-clustered agents could allow the agent to be far more generally useful. 

I suggest we allow users to specify a config file via URL, perhaps through using [go-fsimpl](https://github.com/hairyhenderson/go-fsimpl). This would allow users to receive configs from a storage bucket, an HTTP endpoint, a file, or more. 

Once implemented, you can imagine that other file fields in the agent could also be extended to support URLs. One example may be #868, where the combination of this issue and conf.d support could fully supplant the config management API with something that has no external dependencies. That is out of scope for this issue, but is something I'd like to work towards.

Credit to @mattdurham for the idea of URL-based config files.

**Comment by rlankfo** [comment]
This request was initially implemented for HTTP/HTTPS URLs in https://github.com/grafana/agent/pull/1143
