### ISSUE TITLE
Handle target being dropped in Tempo relabel config

### ISSUE THREAD

**Issue by mapno** [grafana/agent#904]
The Agent uses Prometheus' SD in Tempo to relabel spans via `relabel_configs`. This is commonly used to add metadata about the source, such as kubernetes labels.

Relabel configs allow to drop targets. When dropping a label set, [`relabel.Process`](https://github.com/grafana/agent/blob/main/pkg/tempo/promsdprocessor/prom_sd_processor.go#L188) returns an empty label set. This is an issue because then the Agent will warn that it failed to find the `__address__` label ([source code](https://github.com/grafana/agent/blob/main/pkg/tempo/promsdprocessor/prom_sd_processor.go#L196-L200)).

The Agent should differentiate between the address being missing and dropping a label set.

**Comment by snOm3ad** [comment]
Hello! I'd like to get assigned this issue this would be my first contribution to this project. Is there a message the agent should send if the label set gets dropped or should it just move to the next iteration?

**Comment by james-callahan** [comment]
> Is there a message the agent should send if the label set gets dropped or should it just move to the next iteration?

If there *is* a message, it would need to be at debug log level (rather than the warning level we have today)

**Comment by mapno** [comment]
Hi @snOm3ad, sorry for not seeing your comment until now, it was outside my working hours (eu timezone). While @james-callahan already opened a PR, please consider keeping an eye for other open issues. We're very excited about external contributions and would love to see you contribute.

Are you interested in a particular part of the Agent? We can find a suitable good first issue and ping you next.

**Comment by snOm3ad** [comment]
@mapno No problem! I'm currently not sufficiently familiar with Agent to ask for something specific, however, I will take a look around the repository looking for other issues!

**Comment by james-callahan** [comment]
Fixed via https://github.com/grafana/agent/commit/b350d2daa72d19ba5d957edfac53d825b8dc358f
