### ISSUE TITLE
Metrics scraping: UserAgent reports "Prometheus/v0.x"

### ISSUE THREAD

**Issue by bboreham** [grafana/agent#910]
I noticed in logs `User-Agent: Prometheus/v0.17.0` (using Grafana Agent 0.17.0).
IMO it should say `GrafanaAgent` not `Prometheus`.

From what I see in the code, Grafana Agent sets its own name for Prometheus remote storage and for logs, but not for scraping.

**Comment by rfratto** [comment]
Thanks, nice catch. I opened a PR upstream (prometheus/prometheus#9333) to allow us to customize the UserAgent header.
