### ISSUE TITLE
Agent Config Via Flags

### ISSUE THREAD

**Issue by midnightconman** [grafana/agent#926]
I would like the ability to run the grafana agent in a kubernetes environment without the need for a configmap... one way to accomplish this would be to allow config yaml (or json) to be submitted via flags. Here is an example of this in another application:

- thanos (tracing config and config file): `--tracing.config` or `--tracing.config-file` - https://github.com/thanos-io/thanos/blob/main/docs/components/store.md

```
- |-
  --tracing.confg=config:
    "access_token": "hidden"
    "collector":
      "host": "secret.us-west-2.elb.amazonaws.com"
      "port": 80
      "scheme": "http"
    "service_name": "thanos-store"
    "tags": "app=thanos-store"
  "type": "LIGHTSTEP"
```

**Comment by rfratto** [comment]
Thanks, I'm definitely open to supporting this. The agent's config file can get quite long though, and the only thing I would be worried about is some kind of length limit for command line arguments. Do you know if something like that might exist?

**Comment by midnightconman** [comment]
Excellent 😸 

I think the two limits are:
- Per arg limit (MAX_ARG_STRLEN) which has a static setting of `131072`
- Whole command line length limit (ARG_MAX) which on my system is `2097152`

True, line length would be a concern and for _very_ large configs this could be a problem... in that case we could easily switch to a configmap if the config size was larger than the field supports.

This approach is also used widely in jsonnet (tanka) to reduce the need for an extra operational item (a configmap). At 130K per line we should be able to have a reasonably complex config and not have to worry about this limit, right?

**Comment by rfratto** [comment]
Thanks for the information! Definitely 130K is generous enough to not really worry about it here for the most general cases. 

This isn't likely something any of the maintainers will have time to work on soon though. Anyone reading this that's interested in contributing should definitely feel free to do so :)
