### ISSUE TITLE
Add config to remove default labels from spanmetrics

### ISSUE THREAD

**Issue by mapno** [grafana/agent#960]
Spanmetrics should have a config option to remove labels from the default ones. This will probably mean a change upstream to the [spanmetrics processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanmetricsprocessor) and a change in the custom remote write exporter.

Default labels are

```
- Service name
- Operation
- Span kind
- Status code
```

**Comment by rfratto** [comment]
Would Prometheus relabel rules fly here?

**Comment by mapno** [comment]
That would be a viable option when using the spanmetrics processor, but I'd like to have a config that works for both and requires a bit less configuration that relabelling config.
