### ISSUE TITLE
Grafana Agent Operator should play nicely with Vertical Pod Autoscaler

### ISSUE THREAD

**Issue by thejosephstevens** [grafana/agent#991]
Certain single-point, high cardinality metric sources like kube-state-metrics and apiserver are difficult to handle with the existing sharding solutions available in grafana-agent because in practice, all shards of the agent must be sufficiently large to handle the largest data source, resulting in poor distribution of memory utilization across shards. This can be mitigated to some extent by launching multiple GrafanaAgent resources of different sizes, and creating a manual sharding across those GrafanaAgent pools by labeling ServiceMonitor and PodMonitor targets (this currently requires deploying GrafanaAgent resources in different namespaces due to a bug [here](https://github.com/grafana/agent/issues/964), but is doable).

The remaining issue is that you still need to provision the GrafanaAgent for peak scale, which can mean a very large GrafanaAgent pool has to sit idle while the cluster is quite small, only seeing high utilization when the cluster scales up (both kube-state-metrics and apiserver scale in cardinality with pod/node count). What would be great is to use the [Vertical Pod Autoscaler](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) to scale the Agent resources up and down with the cluster.

At the moment, it appears that the Grafana Agent Operator will fight with the VPA as it sees resources get out of sync, leading to a thrashing problem. It looks like this may be solvable with the [VPA admission plugin](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/README.md), but that may not be a viable solution in all cases.

I will see if I can get this working with the VPA and Admission Plugin in each cloud and report back if it works so this request can be closed.

**Comment by rfratto** [comment]
@thejosephstevens I'll close this, but please feel free to ask for it to be reopened if this becomes a problem again :)
